### ISSUE TITLE
L.Browser.touch is incorrectly being set when on desktop (Chrome)

### ISSUE THREAD

**Issue by jcarenza** [Leaflet/Leaflet#5266] opened 2017-01-18 20:14 UTC
It appears that recent updates to Chrome (on Mac, at least) have changed their implementation of `window.PointerEvent`. This causes the current version of Leaflet (1.0.2) to misdiagnose the browser as a touch device and adds the `leaflet-touch` class.

This line seems to be the culprit: 
```javascript
pointer = window.PointerEvent || msPointer
```
...it can be found here: https://github.com/Leaflet/Leaflet/blob/v1.0.2/src/core/Browser.js#L33

The problem is that `window.PointerEvent` is a function, which will always return 'truthy'.

### How to reproduce

- Browser: Mac OSX El Capitan (10.11.6), Chrome Version 55.0.2883.95 (64-bit)
- Go to www.leafletjs.com and look at the demo example...the Zoom In/Out buttons are enlarged, due to the `leaflet-touch` class being applied to the leaflet map container.

**Comment by rigoneri** [comment] 2017-01-18 20:29
I can reproduce this as well...

**Comment by IvanSanchez** [comment] 2017-01-19 08:33
Duplicate of https://github.com/Leaflet/Leaflet/issues/3944. There is no way to know if the browser is running on a computer with a touchscreen or not, it's only possible to know if the browser *supports* touch/pointer events or not. See also http://www.stucox.com/blog/you-cant-detect-a-touchscreen/

**Closed by IvanSanchez** 2017-01-19 08:33 UTC
