### ISSUE TITLE
Funny: Microsoft keyboard mute button results in zoom-out

### ISSUE THREAD

**Issue by hanselsen** [Leaflet/Leaflet#7503] opened 2021-03-10 14:59 UTC
**Steps to reproduce**
- Go to [leafletjs.com](https://leafletjs.com)
- Click the map so that it focusses
- Press the mute button on your keyboard

**Expected behavior**
Nothing happens

**Current behavior**
The map zooms out one level

**Environment**
- Leaflet version: latest
- Browser (with version): Non-Firefox
- OS/Platform (with version): Win10

**Additional context**
IE, Edge and Chrome are showing this issue

**Comment by hanselsen** [comment] 2021-03-11 12:32
![tmp_1615465755000](https://user-images.githubusercontent.com/1150323/110787715-fcd81d80-826d-11eb-8310-26b44c05c1cf.jpg)

TYG. I don't see any weird stuff. Do you?

**Comment by IvanSanchez** [comment] 2021-03-11 15:47
Well, `AudioVolumeMute` having keycode 173 **is** weird and shouldn't happen. And we cannot really get rid of it, since Firefox triggers that keyode with the minus key. See https://github.com/Leaflet/Leaflet/commit/eed2c8a12b073f95e41c2180b17e8db6e56a9bff , https://github.com/Leaflet/Leaflet/issues/869#issuecomment-11439849

Closing as a duplicate of #3362/#3367 for now. We might want to revisit #3367 and reconsider browser support if this is really nagging.

**Closed by IvanSanchez** 2021-03-11 15:47 UTC
Labels: bug, compatibility, needs more info
