### ISSUE TITLE
 Problems with map.locate() 

### ISSUE THREAD

**Issue by abdosalah2030** [Leaflet/Leaflet#7119] opened 2020-04-29 04:45 UTC
i am try open 
https://leafletjs.com/examples/mobile/
to see how map.locate({setView: true, maxZoom: 16});
its not work for me in sudan .

i am get this erorr 

Geolocation error: Unknown error acquiring position.

**Comment by IvanSanchez** [comment] 2020-04-29 13:11
Duplicate of https://github.com/Leaflet/Leaflet/issues/7087 . As I said there, use [`navigator.geolocation`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation) directly. If you're unable to get a geolocation with that API, then it isn't Leaflet's fault.

**Closed by IvanSanchez** 2020-04-29 13:11 UTC
