### ISSUE TITLE
rotate to map

### ISSUE THREAD

**Issue by gislayer** [Leaflet/Leaflet#6005] opened 2018-01-16 12:51 UTC
I searched a little but did not get a complete result. I guess there is no such method. it is possible for the open layers canvas but generaly i'm using leaflet. I will use navigation to make sure that the direction of travel is in the same direction. if you write such a plugin i would like to watch. I've changed the angle of the map div inline rotate, but this is probably not the right one. what are your thoughts on this matter ?

**Comment by IvanSanchez** [comment] 2018-01-16 12:53
Duplicate of #268. See discussion there.

**Closed by IvanSanchez** 2018-01-16 12:53 UTC

**Comment by gislayer** [comment] 2018-01-16 13:15
i have been read 2 mounth ago but I wanted to bring it to the agenda

**Comment by IvanSanchez** [comment] 2018-01-16 13:41
Opening a new bug won't help. If you want this to get done, the best way is to try and debug the `rotate` branches mentioned in #268.
