### ISSUE TITLE
On latest Firefox scroll wheel zooms map two zoom levels

### ISSUE THREAD

**Issue by paulatthehug** [Leaflet/Leaflet#8125] opened 2022-04-07 20:57 UTC
**Steps to reproduce**

- go to any leaflet map (e.g. the default one in the plunker or any of the examples in the documentation) using Firefox 99.0
- use the scroll wheel to zoom
- the map jumps two zoom levels each time instead of one.

**Environment**
- Leaflet version: 1.7.1 (also 1.8.0-beta.1)
- Browser: Firefox 99.0 (64 bit)
- OS/Platform (with version): Linux (Ubuntu 18.04) or Windows 10

This appears to be the only browser exhibiting this behaviour. It was also present in Firefox 98.0.2 but wasn't in the last update we did before that so this is new.

**Comment by paulatthehug** [comment] 2022-04-07 21:07
BTW I'm raising this on Leaflet rather than on Mozilla as our other apps, using <whisper>OpenLayers</whisper> are not exhibiting this behaviour so it seems to be related to the way Leaflet is servicing scroll wheel events from Firefox.

**Comment by IvanSanchez** [comment] 2022-04-07 21:21
Can confirm.

We need to double-check the `getWheelDelta` behaviour at https://github.com/Leaflet/Leaflet/blob/7847cc6913c296fb7e409e086a57366237c42728/src/dom/DomEvent.js#L252-L266

**Comment by Malvoz** [comment] 2022-04-10 09:48
Related / potentially duplicate of https://github.com/Leaflet/Leaflet/issues/7403.

**Comment by paulatthehug** [comment] 2022-04-11 10:11
If anyone wants a quick and dirty fix for now then this (where `mapObj` is your map):

`mapObj.on('zoomstart',  function(evt) { evt.target.options.wheelPxPerZoomLevel = 120; });`

seems to make the problem go away without breaking anything else.

Tested on Win10/Edge, Win10/Firefox, Linux/Chrome, Linux/Firefox, Linux/Waterfox, MacOS/Safari, ChromeOS/Chrome

**Comment by jinchun-wang** [comment] 2022-04-14 14:46
We have the same issue.

Can we check the zoomDelta in the following method of leaflet.js?

	_performZoom: function () {
		...

        if (!delta) { return; }

        // Fix the issue - https://github.com/Leaflet/Leaflet/issues/7403
        if (Math.abs(delta) > map.options.zoomDelta) {
            delta = delta > 0 ? map.options.zoomDelta : -map.options.zoomDelta;
        }

  		if (map.options.scrollWheelZoom === 'center') {
  			map.setZoom(zoom + delta);
  		} else {
  			map.setZoomAround(this._lastMousePos, zoom + delta);
  		}
  	}

**Comment by Falke-Design** [comment] 2022-04-15 07:11
I closing this because of duplicate of #7403

**Closed by Falke-Design** 2022-04-15 07:11 UTC
Labels: bug, compatibility
