### ISSUE TITLE
How do I synchronize gifs in chrome?

### ISSUE THREAD

**Issue by frowenz** [Leaflet/Leaflet#8308] opened 2022-06-21 21:41 UTC
Hi. I am working on a map where the tiles are composed of gifs that need to be in sync. When a user zooms in to a new layer and then moves around, the gifs in new tiles will load in out of sync. 

The weird thing is this does not happen on Safari only on Chrome. Is there any fix for Chrome?

**Comment by Falke-Design** [comment] 2022-06-22 05:16
Can you please share a demo?

**Comment by jonkoops** [comment] 2022-06-22 09:02
Please provide a minimal reproducible example of your code or otherwise we cannot help you. Closing this issue due to lack of information, feel free to open a new one with enough details for us to reproduce.

**Closed by jonkoops** 2022-06-22 09:02 UTC
Labels: needs more info
