### ISSUE TITLE
Strange behavior of circle added to layerGroup

### ISSUE THREAD

**Issue by kirvt** [Leaflet/Leaflet#5653] opened 2017-07-22 13:46 UTC
I have a layergroup with few polygons. When I add circle to this layergroup I get errors while zooming map:

Uncaught TypeError: Cannot read property '0' of null
    at e._projectLatlngs (leaflet.js:7)
    at e._projectLatlngs (leaflet.js:7)
    at e._projectLatlngs (leaflet.js:7)
    at e._project (leaflet.js:7)
    at e._onZoomEnd (leaflet.js:7)
    at e.fire (leaflet.js:5)
    at e._moveEnd (leaflet.js:6)
    at e.<anonymous> (leaflet.js:6)

## How to reproduce
- Leaflet 1.0.3
- Browser (with version) I'm using:  Chrome 59.0.3071.115 same in IE
- Windows 10

## Minimal example reproducing the issue
```
let zones_layer = L.layerGroup();
zones_layer.addLayer(L.polygon(pointsarr, { color: 'red' }));
...
zones_layer.addLayer(L.circle([points[1], points[2]], { radius: (points[0]) }));
zones_layer.addTo(mmap);
```

**Comment by ghybs** [comment] 2017-07-22 19:06
Hi,

As requested in the issue template, please can you share an actual reproduction example?
I cannot reproduce what you describe:
http://playground-leaflet.rhcloud.com/buma/1/edit?html,output

From the short error reports you share, it might be that your coordinates are `null`.
Also consider debugging using `leaflet-src.js` instead of the minified version `leaflet.js`.

**Comment by perliedman** [comment] 2017-08-03 12:51
Closing for now, we'll consider re-opening if we get more info that would indicate this is actually a Leaflet issue.

**Closed by perliedman** 2017-08-03 12:51 UTC
