### ISSUE TITLE
Enabling inertia on mobile causes leaflet to twitch back when dragging

### ISSUE THREAD

**Issue by ormajollila** [Leaflet/Leaflet#4913] opened 2016-09-14 16:24 UTC
Hi,

If I have inertia enabled, on chrome (52.0.2743.116 desktop and 52.0.2743.98 mobile), leaflet begins to twitch back to the drag starting point at some point. When I disable inertia I have no such problem. See the videos below for better explanation.

Enabled:
![inertia_enabled](https://cloud.githubusercontent.com/assets/9079351/18520288/e0aa08dc-7aaf-11e6-9e64-60a567603825.gif)
Disabled:
![inertia_disabled](https://cloud.githubusercontent.com/assets/9079351/18520289/e0ad2b5c-7aaf-11e6-94ff-b91b7fd40183.gif)

I'm using 1.0.0-rc3.

On 0.7.7 dragging works (but I had some other problems which is why I moved to 1.0.0).

**Comment by sharpchi** [comment] 2016-09-15 13:56
I was having a similar issue with 0.7.7, which you say works! In the end I tracked it down to another javascript plugin (https://github.com/peachananr/panorama_viewer) that was also tracking touch events. When I removed that, the twitching stopped. Could that be your issue?

**Comment by IvanSanchez** [comment] 2016-09-15 13:57
@ormajollila 
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by jwoyame** [comment] 2016-09-15 20:29
Like @sharpchi indicated it is probably a conflict with other JS. See #4588 where someone else had the very same issue, caused by a conflict with AngularJS. A file used by Angular called zone.js was breaking the browser's animation functions. The problem would only occur when animations are being used, as in your case.

**Comment by ormajollila** [comment] 2016-09-17 16:11
@IvanSanchez @jwoyame The project uses angular 2 so I guess zone.js could be the culprit.

**Comment by IvanSanchez** [comment] 2016-09-17 16:20
Culprit seems to be an angularjs component/library, so I'm gonna close this one. Reopen if the bug is reproducible without angular or without zone.js.

**Closed by IvanSanchez** 2016-09-17 16:20 UTC
Labels: needs more info
