### ISSUE TITLE
Map center moves after zooming

### ISSUE THREAD

**Issue by bleuroi** [Leaflet/Leaflet#5512] opened 2017-05-15 07:16 UTC
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome, Firefox (latest)
- OS/Platform (with version) I'm using: Mac 10.11.6

## What behaviour I'm expecting and which behaviour I'm seeing

I expect the center coordinates stay the same even after zooming. When you zoom-out to the lowest level and then zoom-in to the highest, the gap between the original center and the new center is sometimes fatally big. This can be quite problematic if you want to provide the center-oriented feature. Or is this how it's supposed to be?
I already read though pre-reported issues like #426 but couldn't draw a conclusion from them.

## Minimal example reproducing the issue

I made a simple jsfiddle case using the leaflet tutorial source code to make my point.

https://jsfiddle.net/bleuroi/7t3j6t29/

Step 1: Drag the map to move its center to any point.
Step 2: Zoom-out with the zoom control button. (Just make sure you don't use mousewheel for zooming)
 You'll see the coordinates displayed below the map change when zooming.

**Comment by perliedman** [comment] 2017-05-18 11:02
Hi and thanks for reporting.

This does indeed an unintuitive behavior.

This could be a nice start for diving into the Leaflet code base and fix something. Help welcome!

**Comment by ghybs** [comment] 2017-05-20 19:48
Hi,

Besides #426, is not it a duplicate of #3737 and #3879?

In #3737, some solution started to be proposed, but it looks like it was not pushed to "bullet-proof" state unfortunately…

**Comment by perliedman** [comment] 2017-05-21 10:35
@ghybs well spotted! This does indeed look like a duplicate of #3737, so I'm closing this.

**Closed by perliedman** 2017-05-21 10:35 UTC
Labels: bug, help wanted

**Comment by Objedname** [comment] 2019-04-03 11:27
I'm facing save issues in 1.4.0 even on tutorial page. Just try to pan something in the center. Zoom out and zoom in by +- buttons ... map moves a bit, error gets worse more you zoom.

**Comment by CoWayger** [comment] 2019-04-03 11:28
I'm facing same issues in 1.4.0 even on tutorial page. Just try to pan something in the center. Zoom out and zoom in by +- buttons ... map moves a bit, error gets worse more you zoom.

**Comment by cgirvine** [comment] 2022-02-15 16:21
Ditto in version 1.71. This is not a duplicate of #3737 as that one uses a mouse. This issue occurs when clicking the zoom buttons.

**Comment by ndavidson-manticore** [comment] 2022-10-12 00:02
I am still seeing this same issue in version 1.9.2
Is there any estimate on when this issue will be fixed?
