### ISSUE TITLE
Maps View Bug 

### ISSUE THREAD

**Issue by 3ma-TristanVK** [Leaflet/Leaflet#6989] opened 2020-02-06 11:13 UTC
Hello,
I have been using your plugin on cordova applications for just over 6 months.
I noticed today that the card had bugs:
Some part of it does not have a border for countries like Switzerland in zoom 7 the bottoms borders are not displayed like the attached photo.
My leaflet ini : 
mymap = L.map('mapid').setView([46.773495, 8.200047], 7);
           
    L.tileLayer('https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}{r}.png', {
        maxZoom: 18,
        minZoom : 6
    }).addTo(mymap);

- [ Yes ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [  No ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova)
- [ Yes ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Take Leaflet for cordova 
- Go to :  lat 46.773495  long 8.200047 7 
- and see on bottom of Swiss

**Environment**
- Leaflet version: 1.5.1
- Browser  :Android, ios and google chrome
- OS/Platform : Ios 13.3 Android 8.0.0

**Additional context**
i see it too here : https://maps.wikimedia.org/#9/46.7154/8.4924

![sreenBug](https://user-images.githubusercontent.com/58327942/73932016-ae718600-48d9-11ea-9501-3d2ff6f3dfb3.jpg)

Thanks a lot 
Tristan

**Comment by IvanSanchez** [comment] 2020-02-06 12:34
That's a (probably transient) problem with the way the tile server renders some tiles. 

Since it's a backend problem and not a Leaflet bug, closing as duplicate of #6925, #3896, #4661, #4332, #4819, #5056, and #6284.

**Closed by IvanSanchez** 2020-02-06 12:34 UTC
