### ISSUE TITLE
Problem with drawing a circle

### ISSUE THREAD

**Issue by mseslija** [Leaflet/Leaflet#3500] opened 2015-05-28 09:31 UTC
Hi,

I'm using leafletjs in combination with Leaflet.draw plugin to draw objects on map. Everything is working fine except circle. Sometimes it looks like circle radius is 0. Can anyone tell me why circle cannot be drawn on whole map area equally?
Here is example of my problem http://jsfiddle.net/mseslija/84a592gs/3/

Regards,
Marko

**Comment by IvanSanchez** [comment] 2015-05-28 09:59
Duplicate of Leaflet/Leaflet.draw#405

**Closed by IvanSanchez** 2015-05-28 09:59 UTC
