### ISSUE TITLE
Popups don't open in Safari

### ISSUE THREAD

**Issue by davidcurrie** [Leaflet/Leaflet#7555] opened 2021-04-22 11:26 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- In Safari on macOS, browse to LeafletJS.com
- Close the popup on the marker in the example
- Click on the marker

**Expected behavior**
- The popup reopens as it does on Chrome

**Current behavior**
- The popup remains closed

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Safari 14.0.3
- OS/Platform (with version): macOS 11.2.3

**Additional context**

**Minimal example reproducing the issue**

https://plnkr.co/edit/TP5SZ0D7fwIF2kAe

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by johnd0e** [comment] 2021-04-22 11:27
Duplicate of #7255

**Closed by johnd0e** 2021-04-22 11:27 UTC

**Comment by johnd0e** [comment] 2021-04-22 11:29
Build latest Leaflet from `master`, or use `{tap: false}` option when creating map.

**Comment by davidcurrie** [comment] 2021-04-22 11:33
Thanks, @johnd0e - made the mistake of only searching open issues and that one didn't jump out at me
