### ISSUE TITLE
MouseEvent.mozPressure is deprecated

### ISSUE THREAD

**Issue by cesarombredane** [Leaflet/Leaflet#7990] opened 2022-02-09 15:25 UTC
# Leaflet trigger ```MouseEvent.mozPressure``` is deprecated" warning

- this issue has been reported on [react-leaflet](https://github.com/PaulLeCam/react-leaflet)
   link : [react-leaflet issue](https://github.com/PaulLeCam/react-leaflet/issues/604)

I use leaflet with OSM but i think it trigger with all.
I use Mozilla 96.0.3

The warning tell to use ```PointerEvent.pressure``` instead
![image](https://user-images.githubusercontent.com/37673873/153232241-1e761d87-289c-4c96-9c3a-0286919d0496.png)
(sorry Mozilla is in french)

I hope it is possible to update this. it seem pretty easy to do

**Comment by IvanSanchez** [comment] 2022-02-09 15:37
Duplicate of #7078 / #3943

**Closed by IvanSanchez** 2022-02-09 15:37 UTC
