### ISSUE TITLE
Add custom data to marker

### ISSUE THREAD

**Issue by Etienne-M** [Leaflet/Leaflet#8309] opened 2022-06-21 22:10 UTC
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Say I have a list of domain objects, each with coordinates. I can display them on a map using Markers fine. I can also attach a popup to each individual `Marker`s to give information about the domain object it represents. That works well.

Now, if I want to add clustering and I am using `Leaflet.markercluster`, I can't really display a popup to give information about the aggregated domain objects. From my cluster, I can get the list of markers, but that isn't very useful, because it is just a set of coordinates. And since clusters are computed, I can't really attach popups knowing ahead of time the domain objects it will represent.

### Suggested solution

A simple option for custom data and a getter would fix this issue. It would be possible to create the markers with the custom data being their identifier, and from the cluster, I would get the list of markers _with the id of the underlying domain object_.

### Alternatives considered

It would also be possible to leverage the existing options for accessibility, like `title` or `label`. But that would be a bad practice in my opinion, the id would most likely be gibberish that is not intended for consumption by humans.

**Comment by Malvoz** [comment] 2022-07-01 11:12
This is essentially a duplicate of https://github.com/Leaflet/Leaflet/issues/4225 (how to use [`data-*` attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) with markers). But leaving this open for discussion for now, as it seems to be a common question on SO:
- [How to pass data with marker in leaflet js](https://stackoverflow.com/questions/17423261/how-to-pass-data-with-marker-in-leaflet-js) (nearly 40k views!)
- [Add data attribute to leaflet.js marker element](https://stackoverflow.com/questions/37782930/add-data-attribute-to-leaflet-js-marker-element)

**Comment by jonkoops** [comment] 2022-07-17 17:29
Perhaps this is something that could be improved with better documentation on our side? Perhaps this could be a part of [the examples](https://leafletjs.com/examples.html)?

**Comment by jonkoops** [comment] 2022-07-24 15:32
I'm closing this issue as it's a question which has been answered. If anyone feels up to writing a guide for this feel free to open up a PR.

**Closed by jonkoops** 2022-07-24 15:32 UTC
Labels: feature, needs discussion
