### ISSUE TITLE
Leaflet duplicate markers on Mobile browser for same coordinates! 

### ISSUE THREAD

**Issue by i-sourabh** [Leaflet/Leaflet#5257] opened 2017-01-16 09:46 UTC
I am using Leaflet for web/mobile browser view and markers coming on web browser are fine , have defined 3 icons and only 3 icons are coming on map. But on mobile browser it changes to 6 different colours . Following is the output coming on web browser and mobile browser:

![11](https://cloud.githubusercontent.com/assets/9436345/21977999/a02325c2-dbfe-11e6-8105-393848941cab.png)

On Mobile browser Marker duplicates are coming automatically as below:

![111](https://cloud.githubusercontent.com/assets/9436345/21978003/a836a84c-dbfe-11e6-8b2f-388905b02535.png)

Following are the libraries I am using for both in the following order:

`  <link rel="icon" href="./img/logo1n.png" type="image/x-icon">
    <meta name="description" content="DHIS 2">
    <meta name="keywords" content="DHIS 2">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="lib/js/jquerymin.js"></script>
    <script src="//dhis2-cdn.org/v221/ext/ext-all.js"></script>
    <link rel="stylesheet" href="lib/css/bootstrapmin.css" integrity="" crossorigin="anonymous" />
    <link rel="stylesheet"  href="lib/css/bootstrapthememin.css" integrity="" crossorigin="anonymous" />
    <script src="lib/js/bootstrapmin.js"  ></script>
    <script src="lib/js/bootstrapselectmin.js" ></script>
    <link rel="stylesheet" href="lib/css/bootstrap-selectmin.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    
    <link rel="stylesheet" href="lib/css/w3.css">
    <link rel="stylesheet" href="lib/css/style.css">

    <link rel="stylesheet" href="lib/font-awesome.css">
    <link rel="stylesheet" href="lib/leaflet.css" />
    <script src="lib/leaflet.js"></script>
    <script src="lib/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="lib/ionicons.min.css">
    <link rel="stylesheet" href="lib/leaflet.awesome-markers.css">`

**Comment by IvanSanchez** [comment] 2017-01-16 09:47
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by i-sourabh** [comment] 2017-01-16 09:57
Hi @IvanSanchez  not able to put the working code here as it is dynamic and coming from server api. however I am using it like below: 

var marker = L.marker([longitude[i], latitude[i]], {icon: blueMarker}).bindPopup(name[i]+","+" </br><strong>Contact:</strong>"+  mobile[i]+ "</br><strong>Schemes:</strong>"+hfschemes[i]+"</br><strong>Availabilities: </strong>"+availspecialiti[i]+"</br>GoTo List View for more details").openPopup();
                    markers.addLayer(marker);
                    map1.addLayer(markers);

**Comment by IvanSanchez** [comment] 2017-01-16 10:00
The problem might be due to the CSS and/or the background images used for the markers, and/or the hi-res screen settings. Without a **complete** example, it's impossible to know what might be wrong.

**Comment by i-sourabh** [comment] 2017-01-16 10:08
Here is the complete code:

Libraries:

`
    <link rel="stylesheet" href="lib/font-awesome.css">
    <link rel="stylesheet" href="lib/leaflet.css" />
    <script src="lib/leaflet.js"></script>
    <script src="lib/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="lib/ionicons.min.css">
    <link rel="stylesheet" href="lib/leaflet.awesome-markers.css">`

`var redMarker = L.AwesomeMarkers.icon({
    icon: 'coffee',
    markerColor: 'red'
});

var blueMarker = L.AwesomeMarkers.icon({
    icon: 'coffee',
    markerColor: 'blue'
});

var map1 =L.map('map1').setView([31.1471, 75.3412], 10);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map1);`


` var map =L.map('map').setView([31.1471, 75.3412], 8);

        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);



        L.marker([31.23911142,76.49470665], {icon: blueMarker}).addTo(map).bindPopup('Anandpur Sahib SDH').openPopup();
        L.marker([31.55747995,75.26604862], {icon: blueMarker}).addTo(map).bindPopup('Baba Bakala SDH').openPopup();
        L.marker([30.0667157,74.65523599], {icon: blueMarker}).addTo(map).bindPopup('Badal SDH').openPopup();

        L.marker([31.0759360441769,76.2937775969546], {icon: blueMarker}).addTo(map).bindPopup('Balachaur SDH').openPopup();
        L.marker([30.37550547,75.54520121], {icon: blueMarker}).addTo(map).bindPopup('Barnala DH').openPopup();
        L.marker([31.80871582,75.21504738], {icon: blueMarker}).addTo(map).bindPopup('Batala SDH').openPopup();
        L.marker([30.195269,74.948875], {icon: blueMarker}).addTo(map).bindPopup('Bathinda DH').openPopup();
        L.marker([31.80801415,75.66609161], {icon: blueMarker}).addTo(map).bindPopup('Dasuya SDH').openPopup();
        L.marker([30.58493912,76.84537522], {icon: blueMarker}).addTo(map).bindPopup('Dera Bassi SDH').openPopup();
        L.marker([30.36701341,75.86064861], {icon: blueMarker}).addTo(map).bindPopup('Dhuri SDH').openPopup();`

**Comment by IvanSanchez** [comment] 2017-01-16 10:29
Cannot reproduce using https://playground-leaflet.rhcloud.com/moxu/edit?html,output and a browser emulating a hi-res display, and Chrome beta in a HTC hero one (with hi-res display).

Cannot reproduce → closing.

**Closed by IvanSanchez** 2017-01-16 10:29 UTC
Labels: needs more info

**Comment by waterfall49** [comment] 2020-03-25 22:06
check this one. you can create layergroup and clear it
https://www.youtube.com/watch?v=gEmOFsglk34&t=26s
