### ISSUE TITLE
Incorrect calculation of visible tiles on decimal value zooms

### ISSUE THREAD

**Issue by alecabdia** [Leaflet/Leaflet#3273] opened 2015-03-03 14:45 UTC
When I set zoom with decimal values the map doesn't load properly. When I drag over the map, in the edges of map, the tiles aren't load if the new margin is minor than the tile width. Only when the margin is enough, is when the load occurs. In version 0.7.3 worked decimal values but not in version 0.8. The link http://jsfiddle.net/alecabdia/dzdz59ce/ is an example of what happens.

**Comment by mourner** [comment] 2015-03-04 10:12
Does it only affect WMS layers?

**Comment by mourner** [comment] 2015-03-04 11:27
OK I see what you mean now. I'll look into it.

**Comment by Jakobud** [comment] 2015-03-05 17:39
Wow I didn't know you could do fractional zooming. I hope this get fixed.

Also I'm not sure if this is related or not, but for example if you open up http://leafletjs.com and open up your console and say `map.setZoom(8.5)` you will get errors because it's trying to load tiles with URLs like `http://a.tile.openstreetmap.org/8.5/180/120.png`. Obviously that doesn't exist because of the 8.5 zoom value. It would be ideal if Leaflet knew to load the next highest zoom level if it's fractional.

Also it would be fantastic to be able to do fractional zooming with the zoom controls.

**Comment by mourner** [comment] 2015-03-05 17:53
It all works in master right now. :) There's just some small bug that makes it not load some tiles along the boundary in some cases.

**Comment by Jakobud** [comment] 2015-03-05 18:15
That is a really cool, undocumented feature. I was considering having to come up with a custom CRS and create new tiles and fractional zoom levels to do this. Really cool.

Can you setup the zoom controls to zoom on fractions? If not I will will look into adding that as an option.

**Comment by mourner** [comment] 2015-03-05 18:17
Not yet. There are still some issues left to fix too... And docs are in the works, see #3098. Also check out the new `flyTo` method — it works thanks to fractional zoom and it's pretty awesome.

**Comment by Jakobud** [comment] 2015-03-05 18:37
Okay, I'll go ahead and add fractional zooming as an option for the controls. Right now, when you create a map, you can have the option `zoomControl: true/false` as an option. If I was to add to option to the zoom control so you could specify a zoom amount (default: 1), where would be the right place to do that? Upon map instantiation? A map option of `zoomControlAmount: 0.5` or something like that? That is kind of a weird way to do it but you don't ever actually directly create the Zoom Control when instantiating the map. What do you think?

Also, ya `flyTo` is definitely really cool. There almost needs to be some kind of page on leafletjs.com that is like a "Kitchen Sink" kind of page with a map and tons of buttons for all the different functions so that people can play with it to see all the things it can do. Otherwise new functions like `flyTo` are just going to be sitting in the API doc pages and could be easily missed by a lot of developers.

**Comment by Jakobud** [comment] 2015-03-05 21:55
@mourner take a look at #3285 that I just added. If you look at the debug/zoom-factor.html I added to that PR, you can very clearly see the bug with the tile loading. I don't know if that will help you figure out the issue but it's there if you need it.

**Comment by IvanSanchez** [comment] 2015-05-13 09:12
> A map option of zoomControlAmount: 0.5 or something like that?

Hhhhhhmmmm.

We already have [keyboard zoom offset](http://leafletjs.com/reference.html#map-keyboardzoomoffset), so perhaps the right way to implement this is having options for keyboard zoom, wheelscroll zoom and buttons zoom.

> some kind of page on leafletjs.com that is like a "Kitchen Sink" kind of page with a map and tons of buttons for all the different functions

You might want to have a look at `debug/map/zoompan.html` in master.

**Comment by IvanSanchez** [comment] 2015-06-08 10:38
@alecabdia It would be great if you could check that #3518 makes the visible tiles work as expected. I've done a few tests but it'd be great to have a second set of eyes before merging that code.

**Comment by Eschon** [comment] 2015-06-09 11:08
I just tried out your PR and it seems to work for me. I can't reproduce the bug.
But now it sometimes shows borders between the tiles in Safari 8.0.6.

![screen shot 2015-06-09 at 13 02 11](https://cloud.githubusercontent.com/assets/11647830/8056452/8a54993a-0ea8-11e5-801e-1f6451a2adca.png)


It also breaks some other parts of my code that worked on the master branch before  and I'm not sure why. I'll take a closer look when I have the time.

**Comment by mourner** [comment] 2015-06-09 11:13
@Eschon the gaps between tiles in Safari is unfortunately something I don't know how to avoid. Removing them makes Safari extremely laggy. See https://github.com/Leaflet/Leaflet/commit/3ccbe5bca0dcf7d7d01371c327e3e42173e8313a

**Comment by Eschon** [comment] 2015-06-09 11:30
@mourner Yeah I guess it's better to choose performance in that case.

Also I just checked and my code breaking has nothing to do with the changes in this PR. 
I haven't tested the changes in master over the last few weeks so something else that was changed is responsible for my problems. I'll look around a bit more but I don't think that it is something that should be fixed in Leaflet.

**Closed** 2015-06-09 11:32 UTC
Labels: bug, in progress, needs review

**Comment by mourner** [comment] 2015-06-09 11:33
@Eschon there was a big change in #3278 which changes the way some events (e.g. `viewreset`) work, maybe that's the source. Let me know.

**Comment by Eschon** [comment] 2015-06-09 11:57
@mourner Yeah I figured most of it out already. One problem was that I was using `viewreset`.
Now I just need to get the zoom animation for my custom layer to work again.

**Comment by mourner** [comment] 2015-06-09 12:01
@Eschon for most custom layers, the only necessary change is to update the layer on `zoom` event in addition to `viewreset`. Should be easy.

**Comment by Eschon** [comment] 2015-06-09 12:45
@mourner everything works again for me. The problem was that I was using the scale property of the event that was passed to the animateZoom function. I switched to using getZoomScale and now it works.
