### ISSUE TITLE
[website doc issue] non working link in plugins page

### ISSUE THREAD

**Issue by solsticedhiver** [Leaflet/Leaflet#6333] opened 2018-09-06 15:32 UTC
On https://leafletjs.com/plugins.html, all the in-page links after "Clustering/decluttering" (included) are non functionnal.

It is easy to see tthat the page is generated from some markdown code because one can see on the page something like

`</table> ### Overlay animations These plugins animate markers or some geometries. See also [geometries with time or elevation](#geometryinteraction-time).`

and below some headers are not headers and not links because they are like

`### Clustering/Decluttering When you are displaying a lot of data, these plugins will make your map look cleaner.`

**Comment by mgred** [comment] 2018-09-07 12:01
@solsticedhiver This is caused by an additional `<tr>` tag in the list of Markers & Renderers.

**Comment by IvanSanchez** [comment] 2018-09-07 12:04
Fixed by #6334. @mgred, thanks for fixing this!

**Closed** 2018-09-07 12:04 UTC
