### ISSUE TITLE
L.Circle: circles with same radius have different sizes with L.CRS.Simple

### ISSUE THREAD

**Issue by giacomoburattini** [Leaflet/Leaflet#5854] opened 2017-10-19 16:36 UTC
## How to reproduce

- Leaflet version: 1.2.0
- Draw circles on the map (Please take a look at the JSFiddle: https://jsfiddle.net/wL9zgz1n/5/

## Circles have different sizes even if they have the same radius
After a quick look at the code it seems that the problem is the rounding applied by the latLngToLayerPoint function here https://github.com/Leaflet/Leaflet/blob/703ae02aa8cbd0b87be5b01e77754b83ad732267/src/layer/vector/Circle.js#L97 which produces different radius values depending on the circle coordinates.

**Comment by danydev** [comment] 2017-10-20 10:42
seems to be the same issue described here https://github.com/Leaflet/Leaflet/issues/4582

**Comment by perliedman** [comment] 2017-10-20 10:45
@danydev well spotted, I'm closing as duplicate of #4582.

**Comment by danydev** [comment] 2017-10-20 10:57
After deeper inspection, I'm not sure it's the same exact issue. By looking at the pull request in #4582 I see that the fix is in the code branch for `L.CRS.Earth.distance` while this bug refers to the `L.CRS.Simple`, so even if we finalize the proposed fix, we'll not fix this one.

**Comment by giacomoburattini** [comment] 2017-10-20 11:02
This issue refers to `L.CRS.Simple` so the fix proposed in #4582 won't fix this one.

**Comment by perliedman** [comment] 2017-10-20 12:34
Ok, lets instead say this is then a duplicate of #4745 and fixed by #4808, which removes the rounding in latLngToLayerPoint :smile:.

**Closed by perliedman** 2017-10-20 12:34 UTC
