### ISSUE TITLE
Box zoom causes popups to not respond to click events

### ISSUE THREAD

**Issue by mrollans** [Leaflet/Leaflet#3284] opened 2015-03-05 19:18 UTC
Zooming in on a map using the box zoom (shift + drag) causes popups to not respond to click events.  There is a JSFiddle that demonstrates this issue at the following link.

http://jsfiddle.net/3LLtqLsq/2/

1.  Open the JSFiddle link
2.  Click on some of the objects that have been added to the map, notice popups work for these objects.
3.  Zoom into the map using box zoom (shift + drag)
4.  Click the objects on the map, popups are no longer displayed

The issue appears to be related to this bit of code in `_draggableMoved: function (obj)` at line 2179 in the leaflet-src.js. 

```javascript
return (obj.dragging && obj.dragging.moved()) || (this.boxZoom && this.boxZoom.moved());
```
It seems that after box zoom is used, `(this.boxZoom && this.boxZoom.moved()` always evalutes to true and the DOM event is not fired.

I think the fix may be to add `this._moved = false` to `BoxZoom._onMouseUp()` around line 7620, but there may be more to it than that.

**Comment by jfirebaugh** [comment] 2015-03-05 19:24
Duplicate of #3026.

**Closed by jfirebaugh** 2015-03-05 19:24 UTC
