### ISSUE TITLE
Marker Shadow is not shown with custom icons, on v. 1.0.1

### ISSUE THREAD

**Issue by git-webmaster** [Leaflet/Leaflet#5083] opened 2016-11-09 21:56 UTC
- [yes] I'm reporting a bug, not asking for help
- [yes] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [yes] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [yes] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: Leaflet 1.0.1+ffcfcc1
- Browser (with version) I'm using: All Major Browsers
- OS/Platform (with version) I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing

I am using this code to set icons options:

```
    var mobile_zoom_factor = 1.3; L.Icon.Default.imagePath = '{{ settings.img_folder }}/leaflet/';
    mainIcon = L.icon({
      iconUrl: L.Icon.Default.imagePath + 'marker-icon.png',
      iconSize:     [24*mobile_zoom_factor, 32*mobile_zoom_factor], 
      iconAnchor:   [12*mobile_zoom_factor, 32*mobile_zoom_factor], 
      popupAnchor:  [0, -32*mobile_zoom_factor], 
      shadowUrl: L.Icon.Default.imagePath + 'marker-shadow.png',
      shadowRetinaUrl: L.Icon.Default.imagePath + 'marker-shadow.png',
      shadowSize:   [41*mobile_zoom_factor, 41*mobile_zoom_factor], 
      shadowAnchor: [14*mobile_zoom_factor, 41*mobile_zoom_factor]
    });
```

Then i add marker to the map:

```
var marker = new L.Marker(new L.LatLng(this.geox, this.geoy), {icon: mainIcon}).bindPopup(popup);
```

And with Leaflet v.1.0.1 there is no shadow (it exists in DOM, but shadow image is not visible. I tried to change z-index of the img, shadow-pane - but seems like this is not the nature of the problem).

When i change leaflet.js to v 0.7.7, marker shadow become visible (i change nothing but that).

Please check.

**Comment by IvanSanchez** [comment] 2016-11-10 09:00
@git-webmaster Please check if this is reproducible after the changes in https://github.com/Leaflet/Leaflet/pull/5046

**Comment by IvanSanchez** [comment] 2016-11-10 09:02
Wait, you're using rev ffcfcc1 ? That change should be there then.

Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by stuporglue** [comment] 2017-01-12 22:07
I was experiencing this in ffcfcc1 too, but just upgraded to the 1.0.2 release which no longer exhibits this behavior.

**Comment by Cagdas88** [comment] 2017-06-02 10:08
I have the same issue. Its only working on the basic icon. Not on custom icons.

**Comment by perliedman** [comment] 2017-06-02 10:18
@Cagdas88 can you provide a running example that reproduces this, for example on http://playground-leaflet.rhcloud.com/ ?

**Comment by Cagdas88** [comment] 2017-06-09 11:37
OK here i set up with a blank icon and with its shadow url... 
BTW on playground-leaflet is the latest version of leaflet 1.0.0. but it shows that it not work with the shadows too....

Im using the 1.0.3 version. 

http://playground-leaflet.rhcloud.com/caqi/edit?html,output

**Comment by perliedman** [comment] 2017-06-09 12:55
@Cagdas88 from what I can tell, you're using `DivIcon`, and even though it inherits from `Icon` it does not have exactly the same functionality. Among other things, it does not have builtin shadow support; as [the documentation notes](http://leafletjs.com/reference-1.0.3.html#divicon):

> Inherits from Icon but ignores the iconUrl and shadow options.

. If you need a shadow in a `DivIcon`, you need to add it yourself.

**Comment by Cagdas88** [comment] 2017-06-09 12:59
this is my compleate divIcon:

                        L.divIcon({
                            iconSize: [35, 45],
                            iconAnchor:   [17, 42],
                            popupAnchor: [1, -32],
                            shadowAnchor: [10, 12],
                            shadowSize: [36, 16],
                            shadowRetinaUrl: 'assets/img/markers/markers-shadow@2.png',
                            shadowUrl: 'assets/img/markers/markers-shadow.png',
                            html: '<img src="assets/img/markers/colors/red.png" >' +
                            '<i class=" fa fa-cafe icon-white" ></i> '
                        })

This does not work for me..

**Comment by perliedman** [comment] 2017-06-09 13:00
@Cagdas88 as mentioned in my comment above, `DivIcon` does not support shadows.

**Comment by Cagdas88** [comment] 2017-06-09 13:04
ok. why are the options than available for the divicon?
In a past project does this work. The reason why im using the divIcon is because the html option.

What you mean exactly with "If you need a shadow in a DivIcon, you need to add it yourself". how i add them?

**Comment by perliedman** [comment] 2017-06-09 13:14
@Cagdas88 again, as mentioned above, the docs clearly state that the shadow options are ignored.

Since you can create any HTML inside the `div`, you have plenty of options how to create a shadow. Exactly how is outside the scope for this issue tracker, this is more of a general HTML question than specific to Leaflet.

**Comment by git-webmaster** [comment] 2017-06-09 13:14
Hi.
Just got a notification about this.

Actually, i was not using **DivIcon**. I was using this code:

```
L.Icon.Default.imagePath = 'some-path';

                    var mainIcon = L.icon({

                        iconUrl: L.Icon.Default.imagePath + 'marker-icon.png',
                        shadowUrl: L.Icon.Default.imagePath + 'marker-shadow.png',

                        iconSize:     [24, 32],
                        shadowSize:   [41, 41],
                        iconAnchor:   [12, 32],
                        shadowAnchor: [14, 41],
                        popupAnchor:  [0, -32]
                    });

var this_org_mark = L.marker([x, y], {icon: mainIcon}).addTo(leaflet_map);

this_org_mark.bindPopup("lorem ipsum");
```

Sorry for the outlink, but here is an live example of what's discussed here:

https://unilocal.net/united-states/new-york/martin-cohen-and-company-attorney-at-law (source code line 1021)

Just activate the map, and see that there is no shadow - but it must be there according the code above.
I have just tried last release version of leaflet in local environment - and see no changes.

I will try to reproduce this in sandbox little bit later.

**Comment by perliedman** [comment] 2017-06-09 13:17
@git-webmaster yes, my reply was to @Cagdas88, the thread has been a bit side tracked. As far as I can tell, the issue you've reported is still valid.

**Comment by perliedman** [comment] 2017-11-16 18:22
Revisiting this, from looking at your example, I notice Chrome devtools says your shadow image is 0x41 pixels when displayed, although the natural size is 41x41 pixels. This is a bit perplexing, since the element's `style` has `width: 41px`.

However, borrowed your icon configuration and set up a minimal example using the same images as well as the configuration code from your sample above: https://plnkr.co/edit/HBs6K6rddLbqRDLa3Ssi?p=preview

In this example, the shadow works as expected for me, and is shown as 41x41 pixel. So, it looks to me like there is something going on on your page that causes the browser to draw the shadow with the wrong size.

I'm going to close this as we don't have a minimal example reproducing this, but I'm happy to reopen if we can reproduce it with code we can see.

**Closed by perliedman** 2017-11-16 18:22 UTC
Labels: needs investigation
