### ISSUE TITLE
Map.fitBounds prevent map auto-adjust

### ISSUE THREAD

**Issue by mclapa** [Leaflet/Leaflet#3406] opened 2015-04-27 21:16 UTC
When using fitbounds on a map object

http://leafletjs.com/reference.html#map-events

the map may be re-adjusted automatically to fit these points in including shifting the map, zooming it out, etc.

This is a problem as everytime the map adjusts, zooms out, etc it will trigger a moveend event (messing up a whole stack of events I'm watching)

I've narrowed it down to the math that calculates the centre, and with it dividing / 2, it incorrectly rounds the values and causes the map to zoom out. This is a very edge case but causes serious problems (sometimes causes the map to crash) as for every moveend it causes an infinite function call on my code.

Anyhow can we have a function similar to fitbounds that actually sets the bounds of the map where the points provided are the corners of the map, not necessarily contained WITHIN the map

Currently I have a lot of hacks to accommodate this but works only 90% of the time.

Thanks

**Comment by IvanSanchez** [comment] 2015-04-27 21:25
> ...it causes an infinite function call **on my code**.

So you're saying it's not a bug on Leaflet's code but on your code, right?

> Anyhow can we have a function similar to fitbounds that actually sets the bounds of the map where the points provided are the corners of the map, not necessarily contained WITHIN the map

No, because of the aspect ratio. If you provide a squashed bbox to fit the bounds to, should the map squash everything?

If what you're really asking for is "provide a bbox, then have the pan-zoom itself so that the bbox touches either the top and bottom sides or the left and right sides of the map", then this is a duplicate of #3030.

**Comment by mclapa** [comment] 2015-04-27 21:40
Hi

Your second paragraph is exactly what I'm looking for.

Essentially

- Provide the bounds of the box
- Are the bounds provided the perfect coordinates for all the map tiles? [Good]
- Are the bounds provided not the perfect coordinates and require pan / zoom?
-- Don't pan/zoom, but rather serve the map tiles and clip them so that the provided map-container holds the desired map coordinates. 

Essentially what is happening is this, so maybe you can point me in the right direction

- User pans around the map
- Save coordinates of corners of map
- User refreshes the page
- Try to re-align the map AS the user left it based on the last corners
[ The problem is above. When I try to re-align the map based on the box's corner coordinates, the map shifts, zooms out, etc to accommodate the coordinates]

I realize the ideal solution would be to use the center of the map but I have some backend logic that fetches locations based on the corners of the map so relying on the center of the map is a problem

Thank you!

**Comment by IvanSanchez** [comment] 2015-04-27 21:53
> Your second paragraph is exactly what I'm looking for.

Then I'm closing this as a duplicate of #3030. 

> When I try to re-align the map based on the box's corner coordinates, the map shifts, zooms out, etc to accommodate the coordinates.

I haven't looked at your code, but hint: try to use `.once()` instead of `on()` to react on the zoom change when running `.fitBounds()`; this way you can zoom out one level without triggering another event handler.

**Closed by IvanSanchez** 2015-04-27 21:53 UTC
