### ISSUE TITLE
noWrap is broken on certain mapbox styles 

### ISSUE THREAD

**Issue by aparij** [Leaflet/Leaflet#5938] opened 2017-11-24 21:53 UTC
- Leaflet version I'm using: 1.2

## What behaviour I'm expecting and which behaviour I'm seeing
`noWrap`  should not display extra tiles, but it does on right side only.
So for basic way of loading Mapbox tiles it works , while with styles it doesn't ? 
Is it because there is no png in the end of api call so it's a different format ?

Broken url way:
`https://api.mapbox.com/styles/v1/mapbox/streets-v10/tiles/256/{z}/{x}/{y}?access_token=`
Working url way:
`https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=`

## Minimal example reproducing the issue
Broken - http://jsbin.com/bizecogumi/1/edit?html,js,console,output
Good - http://jsbin.com/pebogay/1/edit?html,js,console,output

**Comment by ghybs** [comment] 2017-11-25 02:45
Duplicate of https://github.com/Leaflet/Leaflet/issues/5154.

In short:
- `noWrap` tells Leaflet not to use the CRS wrapping feature. If coordinates (here longitude) no longer wrap, they extend infinitely, therefore the Tile Layer tries to access new tiles: 0/1/0, 0/-1/0, etc.
- In a normal tiles scheme, only tile 0/0/0 is available, so those extra requests should result in 404 errors. In that case, these extra requests may remain unnoticed.
- For some reason, some Tile Servers (like Mapbox for certain styles in this case) still return an image for those extra coordinates. At that point, the issue becomes visible, as "imaginary" tiles are displayed.

Solution: use `noWrap` with [`bounds`](http://leafletjs.com/reference.html#gridlayer-bounds) option on your Tile Layer.

**Closed by ghybs** 2017-11-25 02:45 UTC
