### ISSUE TITLE
WMS load event trigger before loading the actual WMS tiles

### ISSUE THREAD

**Issue by iamtekson** [Leaflet/Leaflet#8987] opened 2023-06-15 22:31 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

According to documentation, the `load` event on `wms` should trigger after loading all the visible tiles but it trigger before loading the tiles. I have tested it with following code,

```js
 var layer = L.tileLayer
      .wms("https://www.fao.org/fishery/geoserver/wms", {
        layers: "UN_intbnd_layergroup",
        format: "image/png",
        transparent: true,
      })
      .addTo(map);

    layer.once("load", function () {
      console.log("loaded");
      alert("loaded tiles");
    });
```

In my case, the wms was not loaded. screenshot as below,

<img width="1258" alt="Screenshot 2023-06-15 at 4 26 00 PM" src="https://github.com/Leaflet/Leaflet/assets/39838116/5ac70d67-1535-4240-954c-e75b05edea6e">

### Expected behavior

The load event should fire after loading the full `wms` tiles.

### Current behavior

Sometimes it loads before loading the single tiles, sometimes it loaded after loading few tiles only. 

### Minimal example reproducing the issue

https://jsfiddle.net/iamtekson/0u1nb8kd/3/

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Chrome latest
- OS/Platform (with version): Mac

**Comment by IvanSanchez** [comment] 2023-06-15 22:52
If you change your `alert` statement with a `debugger` one (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger ), you'll see that the tiles are actually loaded but not yet *faded in*. 

Duplicate of https://github.com/Leaflet/Leaflet/issues/7234

**Closed by IvanSanchez** 2023-06-15 22:52 UTC
Labels: bug, needs triage

**Comment by iamtekson** [comment] 2023-06-16 00:22
Great! I was not aware about the fading in/out effect. Thanks for the quick response!
