### ISSUE TITLE
No pointerdown or mousedown events on Android Chrome > 55 and L.DomEvent.on

### ISSUE THREAD

**Issue by alexshk** [Leaflet/Leaflet#5556] opened 2017-06-11 09:18 UTC
No **pointerdown** or **mousedown** events on **Android Chrome > 55**.
Also I think this issue in Leaflet.Path.Drag is actually Leaflet bug: https://github.com/w8r/Leaflet.Path.Drag/issues/29

## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome 58.0.3029.83
- OS/Platform (with version) I'm using: Android 7
- open: http://leaflet-polyline-events.surge.sh
- try to move blue triangle

## What behaviour I'm expecting and which behaviour I'm seeing

Expecting: mousedown or pointerdown events displayed on lower part of the screen.
Have: nothing.

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Repo for example above here: https://github.com/alexshk/leaflet-test-android-chrome

Thanks

**Comment by perliedman** [comment] 2017-06-12 06:59
Hi!

We've had quite a few issues related to change with pointer events from Chrome 55 and up, so I'm not surprised to see something like this.

However, I was unable to reproduce this on my Nexus 5X with Android 7.1.2 / Chrome 58. Clicking the triangle results in (synthetic) mouse up / down / click events in the bottom of the screen. I'm not able to drag the polygon, though.

**Comment by alexshk** [comment] 2017-06-12 07:04
Hi

Thanks, but I was checking for pointerdown/mousedown events, sorry for bad dscription. Clicks are fine, check please if you have such events while trying to drag blue triangle (no actual dragging functionality here, just checking for event firing). Thanks

**Comment by perliedman** [comment] 2017-06-12 07:45
@alexshk this is what it looks like clicking the polygon on my Nexus 5X:

![image](https://user-images.githubusercontent.com/1246614/27023637-b7b08e82-4f53-11e7-86c5-545948375656.png)

So, as you can see there's `mousedown` as well as `mouseup` and `click`. This is not what you're seeing?

**Comment by alexshk** [comment] 2017-06-12 07:54
@perliedman if I tap on triangle, then yes -- I see the same. But I want to drag blue triangle. Check with desktop browsers and you'll see result I need.

**Comment by perliedman** [comment] 2017-06-12 08:02
Alright, now I finally see the issue. Will have to look closer.

**Comment by perliedman** [comment] 2017-06-12 08:03
BTW, this is reproducible in Chrome devtools on desktop with device emulation enabled.

**Comment by IvanSanchez** [comment] 2017-06-12 08:33
This might be a good time to revive the `pointerify` branch.

**Comment by alexshk** [comment] 2017-06-12 09:06
Disabling L.Browser.pointer for Android Chrome seems to be working: http://leaflet-polyline-events.surge.sh/index-pointer.html
Commit: https://github.com/alexshk/Leaflet/commit/2e55b7b796419832f07249b0cb651a3ca653f743

**Comment by data-ux** [comment] 2017-06-12 09:45
I have tested the following and can confirm that the bug is reproducible on both:

Android 4.4.2, Chrome 58
Android 6.0.1, Chrome 55

**Comment by joakimgunst** [comment] 2017-11-28 14:56
The fix by @alexshk seems to be working. Any updates on whether or when it will be fixed in Leaflet?

**Comment by Damorck** [comment] 2018-03-20 13:47
As asked above, when will this be fixed?  The issue can still be produced on Android 6, Chrome 68, Leaflet v. 1.3. ?

**Comment by johnd0e** [comment] 2020-03-21 13:41
Test page updated for latest leaflet: https://gist.githack.com/johnd0e/219609663cf734ddf6c04ecf27adedb8/raw/issue-5556.html

**Comment by johnd0e** [comment] 2020-03-24 10:01
Ok, I've found solution.
https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L1327-L1328

Here we need to add 'pointerdown pointerup '.

But I'm not sure: should we just add these 2 events, or make whole list customizable?

**Comment by johnd0e** [comment] 2020-03-24 12:02
According to [docs](https://leafletjs.com/reference-1.6.0.html#map-event), we have limited list of supported events.
`touch*` and `pointer*` events are not implemented.

So current behavior is valid, thus I am closing this issue.

@alexshk @nikkon226 @data-ux @joakimgunst @Damorck
Feel free to request support for additional events (in separate issue), describing your use cases.

**Closed by johnd0e** 2020-03-24 12:02 UTC
