### ISSUE TITLE
Only leaflet.js file is version Leaflet 1.7.1 others are 1.6.0

### ISSUE THREAD

**Issue by WebOSM** [Leaflet/Leaflet#7289] opened 2020-09-23 23:58 UTC
I have downloaded the latest version 1.7.1 from https://leafletjs.com/download.html

The zip file has a 1.7.1 version leaflet.js
All other files are 1.6.0.
I use the leaflet-src.esm.js file so i was suprised to find out it is version 1.6.0

Was there a mistake made when making the zip file or are the version variables and comments not updated?

**Comment by IvanSanchez** [comment] 2020-09-24 10:28
Duplicate of #7258

**Closed by IvanSanchez** 2020-09-24 10:28 UTC
