### ISSUE TITLE
Overlapping Polygon in MultiPolygons are displayed as having holes in version 1.0 onwards

### ISSUE THREAD

**Issue by devdattaT** [Leaflet/Leaflet#6173] opened 2018-05-29 05:26 UTC
## How to reproduce
If you have a GeoJSON with a Multipolygon, where the Polygons overlap, Leaflet shows the overlaping part as a hole. This was introduced in version 1.0 onwards and the issue is reproducible with 1.3.1 as well

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Google Chrome  66.0.3359.181 
- OS/Platform (with version) I'm using:Windows 10 Home

## What behaviour I'm expecting and which behaviour I'm seeing
![image](https://user-images.githubusercontent.com/4159622/40639530-0f488a42-632f-11e8-96e0-3f80e8ee6f3c.png)

This should appear as:
![image](https://user-images.githubusercontent.com/4159622/40639550-235c980c-632f-11e8-94b5-8da0803ce673.png)

## Minimal example reproducing the issue
 An Application with Leaflet 1.3.1 which shows the issue:
https://jsfiddle.net/Devdattat/yz4mqmvk/

The same code with version 0.7.7
https://jsfiddle.net/Devdattat/dped8usb/

**Comment by jbccollins** [comment] 2018-06-26 13:52
I suspect this is because Leaflet 1.X changed the MultiPolygon GeoJSON type to render as `L.Polygon` whereas in Leaflet 0.7.X it was rendered as `L.MultiPolygon`

1.X Render: https://github.com/Leaflet/Leaflet/blob/master/src/layer/GeoJSON.js#L197
0.7.X Render: https://github.com/Leaflet/Leaflet/blob/0.7/src/layer/GeoJSON.js#L113

**Comment by perliedman** [comment] 2018-10-26 15:29
If I understand correctly, this is because Leaflet now renders a `MultiPolygon` as a single polygon, treating the polygons inside it as holes; this works fine as long as they don't overlap, but when they do the result is like the overlap was an actual hole.

The correct solution would be to treat this as multiple polygon layers, but how to best achieve that needs to some investigation.

**Comment by AaronAsAChimp** [comment] 2020-01-06 18:56
This seems to be a duplicate of issue #3763.

**Comment by IvanSanchez** [comment] 2021-03-04 13:24
So I'm reading the OGC's [Simple Feature Access specification](https://www.ogc.org/standards/sfa) (again), to remind myself about the formal definitions of `Polygon`s and `MultiPolygon`s. Let me quote page 31:

> 6.1.14 MultiPolygon
> A MultiPolygon is a MultiSurface whose elements are Polygons.
> The assertions for MultiPolygons are as follows.
> a) The interiors of 2 Polygons that are elements of a MultiPolygon may not intersect.

Heck, it even comes with pretty pictures: 
![imagen](https://user-images.githubusercontent.com/1125786/109970085-f2a9a280-7cf4-11eb-973f-33f640279e21.png)

So, `MultiPolygon`s which have overlapping members are not valid `MultiPolygon`s. As such, I think Leaflet has no obligation to handle that invalid case.

See also https://github.com/Leaflet/Leaflet/issues/3763#issuecomment-133398821

**Closed by IvanSanchez** 2021-03-04 13:24 UTC
Labels: bug
