### ISSUE TITLE
this.map is undefined

### ISSUE THREAD

**Issue by purpen** [Leaflet/Leaflet#8315] opened 2022-06-29 03:51 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `leaflet@1.8.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/leaflet/src/layer/Tooltip.js b/node_modules/leaflet/src/layer/Tooltip.js
index 1025bca..9c0a906 100644
--- a/node_modules/leaflet/src/layer/Tooltip.js
+++ b/node_modules/leaflet/src/layer/Tooltip.js
@@ -169,8 +169,10 @@ export var Tooltip = DivOverlay.extend({
 	},
 
 	_updatePosition: function () {
-		var pos = this._map.latLngToLayerPoint(this._latlng);
-		this._setPosition(pos);
+		if (this._map) {
+			var pos = this._map.latLngToLayerPoint(this._latlng);
+			this._setPosition(pos);
+		}
 	},
 
 	setOpacity: function (opacity) {
@@ -182,8 +184,10 @@ export var Tooltip = DivOverlay.extend({
 	},
 
 	_animateZoom: function (e) {
-		var pos = this._map._latLngToNewLayerPoint(this._latlng, e.zoom, e.center);
-		this._setPosition(pos);
+		if (this._map) {
+			var pos = this._map._latLngToNewLayerPoint(this._latlng, e.zoom, e.center);
+			this._setPosition(pos);
+		}
 	},
 
 	_getAnchor: function () {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jonkoops** [comment] 2022-07-17 17:25
Closing this due to a lack of a reproducible example.

**Closed by jonkoops** 2022-07-17 17:25 UTC
Labels: bug, needs triage

**Comment by fschoenfeldt** [comment] 2023-02-28 14:23
although no example is given, I also use this fix to prevent errors when zooming after clicking a location marker:

https://salesforce.stackexchange.com/a/378048

**Comment by jonkoops** [comment] 2023-03-01 08:59
Feel free to file a new issue that can be reproduced, if there is already a known fix then feel free to open up a PR as well.
