### ISSUE TITLE
Leflet Map Rotate

### ISSUE THREAD

**Issue by pravinmitta** [Leaflet/Leaflet#6811] opened 2019-09-20 06:39 UTC
Hi Team,

i want to rotate my leaflet map in mobile device after placing the overlay on top of the map.And i've used Hammerjs to rotate. I'm not able to rotate with the below code

    var div = document.getElementById('map');
    var element = new Hammer.Manager(div);
    var Rotate = new Hammer.Rotate();

	// add the recognizers
	element.add(Rotate);
 
  element.on('rotate',function(e){
    // alert('rotate event');
    let rotation = Math.round(e.rotation);
    element.style.transform = 'rotate('+rotation+'deg)';
  })

**Comment by IvanSanchez** [comment] 2019-09-20 10:36
Duplicate of #268

**Closed by IvanSanchez** 2019-09-20 10:36 UTC

**Comment by pravinmitta** [comment] 2019-09-20 12:37
How we can rotate in mobile with pinching and zooming
