### ISSUE TITLE
polygon frame

### ISSUE THREAD

**Issue by maksimmoiseenko** [Leaflet/Leaflet#8970] opened 2023-05-24 08:22 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [ ] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

<img width="481" alt="Снимок экрана 2023-05-22 в 10 08 06" src="https://github.com/Leaflet/Leaflet/assets/61709217/ec59c93f-5b4a-4e54-b985-442f11e1ec3c">

### Expected behavior

**Hello, is it new update of leaflet or is it our bug? this blue-white frame around polygon**
<img width="481" alt="Снимок экрана 2023-05-22 в 10 08 06" src="https://github.com/Leaflet/Leaflet/assets/61709217/ec59c93f-5b4a-4e54-b985-442f11e1ec3c">

### Current behavior

Hello, is it new update of leaflet or is it our bug? this blue-white frame around polygon
<img width="481" alt="Снимок экрана 2023-05-22 в 10 08 06" src="https://github.com/Leaflet/Leaflet/assets/61709217/ec59c93f-5b4a-4e54-b985-442f11e1ec3c">

### Minimal example reproducing the issue

https://github.com/Leaflet/Leaflet/assets/61709217/ec59c93f-5b4a-4e54-b985-442f11e1ec3c

### Environment

- Leaflet version: 1.9.0
- Browser (with version): Chrome
- OS/Platform (with version): MacOS, Windows

**Comment by IvanSanchez** [comment] 2023-05-24 08:47
Duplicate of https://github.com/Leaflet/Leaflet/issues/8659

**Closed by IvanSanchez** 2023-05-24 08:47 UTC
Labels: bug, needs triage
