### ISSUE TITLE
Safari swipe back gesture causes one-finger zoom on map

### ISSUE THREAD

**Issue by sebojanko** [Leaflet/Leaflet#7521] opened 2021-03-22 08:59 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Open https://leafletjs.com/
- Click any link on the page, wait for it to load
- Go back with the arrow button
- Go forward by swiping to the left, starting from the right side of the screen, near the edge
- Go back again using the arrow button
- Try to interact with the map

**Expected behavior**
After going back and forth, the map should continue to accept one finger for panning and two for zooming.

**Current behavior**
The map is being zoomed by just one-finger touch events, and two-finger touch events don't do anything. Zooming in and out with the plus and minus buttons works as expected. After refreshing the page, the map works as expected.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Safari
- OS/Platform (with version): iPhone 7, iOS 14.4 and 14.4.1 (just a security update, https://support.apple.com/en-us/HT211808#1441)

**Comment by sebojanko** [comment] 2021-03-23 09:46
### Update

After spending a few hours trying to enable iPhone USB debugging on Linux, I finally succeeded!
I wanted to print the map events that fire after creating the already described behavior.
Here are the results:
**One finger click on map:**
```
zoomstart
movestart
move
zoomend
moveend
```
**One finger drag on map:**
```
zoomstart
movestart
zoom
move
zoom
move
zoom
move
...
zoom
move
zoomend
moveend
```
**Two fingers click/drag/whatever on map:**
```
no events
```

Listeners were created for the following events:
```
click
zoomlevelschange
resize
unload
viewreset
load
zoomstart
movestart
zoom
move
zoomend
moveend
```

This was not tested on https://leafletjs.com/, but on my app which uses react-leaflet. Since the same bug was reproduced on https://leafletjs.com/ I'm pretty certain react-leaflet is not at fault. Also, the creator says the library has no specific iOS code in it:  https://github.com/PaulLeCam/react-leaflet/issues/657


If you need additional info regarding some other outputs, I will gladly provide them to you.

**Comment by johnd0e** [comment] 2021-03-23 10:25
You can try #7084, or #7059, or #7029

**Comment by sebojanko** [comment] 2021-03-23 13:16
> You can try #7084, or #7059, or #7029

I tried the test links and the sample map in #7029 and it looks like everything works! I used gestures multiple times to move between pages and the map did not break once.

Do you know when this PR could get merged into master?

**Comment by johnd0e** [comment] 2021-03-23 14:01
> Do you know when this PR could get merged into master?

Unfortunately I don't know. One of maintainers has to approve it, but nobody seems interested yet to look.

Have you tried other 2 mentioned PRs?
#7026 also can be related.

**Comment by sebojanko** [comment] 2021-03-24 07:32
> Have you tried other 2 mentioned PRs?
> #7026 also can be related.

The other ones don't have a map I can try right away and getting it all together just for testing is not feasible for me now.
I wasn't able to replicate the mentioned bug in the map found in #7026.

Thanks!

**Comment by johnd0e** [comment] 2021-03-24 07:48
Ok, this seems a duplicate of #7255.

**Closed** 2021-03-24 07:48 UTC
