### ISSUE TITLE
Calling panBy() while already panning results in blurry tiles (Chrome)

### ISSUE THREAD

**Issue by RLRR** [Leaflet/Leaflet#3913] opened 2015-10-09 11:14 UTC
JSFiddle: http://jsfiddle.net/0x66297q/

Tiles become blurry after panning animation and stay like that even if you drag/zoom the map.

This reproduces in Chrome with current master.

**Comment by IvanSanchez** [comment] 2015-10-09 11:22
Duplicate of #3697

**Closed by IvanSanchez** 2015-10-09 11:22 UTC
