### ISSUE TITLE
2029 E Yesler Way, Seattle WA is an invalid address

### ISSUE THREAD

**Issue by pushkin33** [Leaflet/Leaflet#7569] opened 2021-05-13 00:33 UTC
I noticed on a Leaflet map for Seattle Washington that my building in our complex, at 2001 E Yesler Way, is marked 2029 E Yesler Way. That is in error, all four buildings in the complex are under the address 2001 E Yesler Way. I have lived here since 2003 and have often confronted very confused deliverypeople trying to locate 2029 E Yesler Way. Perhaps it was the address of an earlier structure that was torn down, but I assure you that it is 2001 E Yesler Way, same as all the others in the complex. For years I wondered where people were getting this address. Now I know. I stumbled across your map on a website. I hope there is some way to change this. Thank you.

**Comment by IvanSanchez** [comment] 2021-05-13 00:42
Duplicate of #3896 (and #7004, #6989, #6925, #4661, #4332, #4819, #5056, #6284, and #7288).

**Closed by IvanSanchez** 2021-05-13 00:42 UTC
