### ISSUE TITLE
Map.openTooltip is not considering options.interactive unlike Layer.openTooltip 

### ISSUE THREAD

**Issue by autumnharmony** [Leaflet/Leaflet#5974] opened 2017-12-20 11:06 UTC
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome Version 63.0.3239.84 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: Windows 7
- add tooltip by using Map.openTooltip
https://jsfiddle.net/lostboy/vcfz4kow/2/

## What behaviour I'm expecting and which behaviour I'm seeing
I'm expecting that Map.openTooltip will consider options, passed as third argument
## Minimal example reproducing the issue
https://jsfiddle.net/lostboy/vcfz4kow/2/

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by cherniavskii** [comment] 2017-12-21 12:37
Hi and thanks for finding Leaflet useful.
There are few ways to open a tooltip on the map:
1. Call [`openTooltip` with a `Tooltip` instance](http://leafletjs.com/reference-1.2.0.html#map-opentooltip).
2. Call [`openTooltip` with it's content, position and options](http://leafletjs.com/reference-1.2.0.html#map-opentooltip), which creates a `Tooltip` instance under the hood.

If first argument isn't a `Tooltip` instance - then instance is created using provided arguments (with tooltip options). See [implementation](https://github.com/Leaflet/Leaflet/blob/master/src/layer/Tooltip.js#L208).

In your case, tooltip options never reach a `Tooltip` instance itself, since you already provide a `Tooltip` instance and it's not created under the hood.

Please follow documentation to use `openTootlip` properly :)

**Comment by autumnharmony** [comment] 2017-12-21 14:08
next block of code will not be executed in case of Map.openTooltip 
https://github.com/Leaflet/Leaflet/blob/master/src/layer/Tooltip.js#L344 anyway

So i can't create interactive not bound tooltip (workaround is to add css class by hand)
https://jsfiddle.net/lostboy/vcfz4kow/2/

**Comment by cherniavskii** [comment] 2017-12-21 14:24
Can't you create tooltip first with `interactive` option and then call `map.openTooltip(tooltip)`?

**Comment by autumnharmony** [comment] 2017-12-22 10:22
please change jsfiddle to prove your suggestion

**Comment by ghybs** [comment] 2017-12-24 04:05
Hi @autumnharmony,

Thank you for insisting there is an inconsistency in Tooltip behaviour, depending on it is opened as bound to a Layer or directly on a map!
Pointing out the relevant code piece helps indeed.

IMHO, contributing to the Community is about (trying to) help each other, not winning a point over others.
Unfortunately, miscommunication always happens, even with the best initial intentions.
Sticking to the technical details helps preventing it, while keeping a constructive attitude helps mitigating, avoiding conflict escalation.

## How to reproduce
- Leaflet version I'm using: 1.2
- Open a tooltip directly on map (`map.openTooltip()`) with `interactive: true` option (whether it is passed to `L.tooltip` factory or as 3rd argument to `map.openTooltip` when the 1st argument is not a Tooltip instance).


## What behaviour I'm expecting and which behaviour I'm seeing
The tooltip should get the `'leaflet-clickable'` class, with the `pointer` mouse cursor and listen to feature events.
But none of that happens if the tooltip has been opened directly on map (`map.openTooltip()`), whereas it correctly becomes interactive if it is opened from a Layer (`someLayer.bindTooltip(content, options).openTooltip()`).

This piece of code only executes in the latter situation:
https://github.com/Leaflet/Leaflet/blob/1ac320ba232cb85b73ac81f3d82780c9d07f0d4e/src/layer/Tooltip.js#L342-L347

By moving it into [`L.Tooltip.onAdd`](https://github.com/Leaflet/Leaflet/blob/v1.2.0/src/layer/Tooltip.js#L70-L87) hook, it gets executed in all situations: https://jsfiddle.net/vcfz4kow/5/

Everyone please enjoy the festive season! :confetti_ball: :christmas_tree: :santa:

**Comment by cherniavskii** [comment] 2017-12-29 15:33
Hi @ghybs, thanks for your clarification

**Comment by johnd0e** [comment] 2021-03-28 17:57
> The tooltip should [...] listen to feature events.

Not quite true, atm tooltip itself does not listen to any event.
But with `interactive` option - it delegates events to feature it is bound to.
 
> By moving it into [`L.Tooltip.onAdd`](https://github.com/Leaflet/Leaflet/blob/v1.2.0/src/layer/Tooltip.js#L70-L87) hook, it gets executed in all situations: https://jsfiddle.net/vcfz4kow/5/

This will brake mentioned case, check yourself
```
marker.on('click', console.log);
```
Should be changed to `this._source.addInteractiveTarget(...`

**Closed** 2021-11-01 08:24 UTC
Labels: bug
