### ISSUE TITLE
Request to Correct Western Sahara (SADR) Representation as Part of Morocco

### ISSUE THREAD

**Issue by ouarrho** [Leaflet/Leaflet#9461] opened 2024-09-04 10:32 UTC
Dear Leaflet Maintainers,

I’ve noticed that the map data used in Leaflet currently displays Western Sahara (also referred to as the Sahrawi Arab Democratic Republic, SADR) as a separate country. However, this region is internationally recognized by several countries as part of Morocco.

I kindly request that you consider updating the map data to represent Western Sahara as part of Morocco, reflecting the reality that it is not a recognized independent country in the context of Moroccan sovereignty. This correction would help ensure that the map data used in Leaflet aligns with this perspective.

Thank you for your consideration, and I’m happy to provide any further information or assistance if needed.

**Comment by IvanSanchez** [comment] 2024-09-04 10:57
Duplicate of https://github.com/Leaflet/Leaflet/issues/5056 (and a bunch of others).

If this is about the representation of WS **in OpenStreetMap**, then do read https://wiki.openstreetmap.org/wiki/Western_Sahara, https://wiki.openstreetmap.org/wiki/Disputed_territories, and https://wiki.openstreetmap.org/wiki/Data_Working_Group

**Closed by IvanSanchez** 2024-09-04 10:57 UTC
