### ISSUE TITLE
Zooming lost the center position

### ISSUE THREAD

**Issue by DavidGSola** [Leaflet/Leaflet#3879] opened 2015-09-30 10:28 UTC
When you zoom using any method (Gesture, Scroll or Control) the map loses the center position. 

Steps:

1. On the Leaflet example of the webpage zoom to the maximum level using the control:
![bugleafletzoom_1](https://cloud.githubusercontent.com/assets/9080930/10190469/1112209c-676d-11e5-8181-5d2e421791b0.PNG)

2. Zoom out (using control) around 9-10 levels:
![bugleafletzoom_2](https://cloud.githubusercontent.com/assets/9080930/10190468/11121ce6-676d-11e5-9016-041da0d27414.PNG)

3. Zoom in again (using control) to the maximum level:
![bugleafletzoom_3](https://cloud.githubusercontent.com/assets/9080930/10190470/1116865a-676d-11e5-856d-dede981c68fb.PNG)

As you can see, if I zoom in/out, the map moves autonomously losing the center position (more or less the marker).

**Comment by IvanSanchez** [comment] 2015-09-30 10:43
Duplicate of #3737

**Closed by IvanSanchez** 2015-09-30 10:43 UTC
