### ISSUE TITLE
Custom markers not showing in map tiles in SAFARI (Windows)

### ISSUE THREAD

**Issue by dhrubo001** [Leaflet/Leaflet#5533] opened 2017-05-26 08:20 UTC
Hello friends,
I ave implemented leaflet.js in one of my ongoing projects.It's working fine CHROME,OPERA,FIREFOX
But when opened in safari the images are not at all showing.
Please check the screenshots below.
CHROME
---------------
![chrome](https://cloud.githubusercontent.com/assets/7116995/26485858/45456254-4216-11e7-9c7a-bb01902e243a.png)
The custom markers has numbering on it....and markercluster is also implemented.It's working fine in CHROME.

OPERA
---------
![opera](https://cloud.githubusercontent.com/assets/7116995/26486501/00fd8a60-4219-11e7-8f19-d80131ce7e1d.png)
This is also fine

SAFARI (WINDOWS)
---------------------------
In safari the masterclustering is ok,
![safari](https://cloud.githubusercontent.com/assets/7116995/26486618/7e090480-4219-11e7-8d19-89a75d8215ea.png)

But when zooming to get the markers, it's is all messing up, check the below image only the numbers are showing,
![safari](https://cloud.githubusercontent.com/assets/7116995/26486672/b9b60668-4219-11e7-8cc0-3cacaa88bb43.png)

This is  the problem i am facing, what might be the reason...

Thanks in advance

**Comment by IvanSanchez** [comment] 2017-05-26 08:27
I think this is not a bug in Leaflet, but rather in the CSS used for the cluster markers. You'll need to show that, and try displaying a single cluster marker in a standalone webpage, and debug that.

Also, what version of Safari are you using? AFAIK the latest version of Safari you can run on Win is 6.0, from 2012.

**Comment by dhrubo001** [comment] 2017-05-26 08:31
My safari version is 5.1.7.... but yes i also think it a case of css....anything else you want to suggest

**Comment by IvanSanchez** [comment] 2017-05-26 08:35
No, I don't really have any further suggestions.

I'm closing this one, as it looks like the problem is in the user-defined CSS.

**Closed by IvanSanchez** 2017-05-26 08:35 UTC

**Comment by dhrubo001** [comment] 2017-05-26 08:46
ok thanks i have sorted, the problem out...it's a css one..thank you
