### ISSUE TITLE
Position delta compared to Google Earth

### ISSUE THREAD

**Issue by neilyoung** [Leaflet/Leaflet#7004] opened 2020-02-24 12:44 UTC
**Steps to reproduce**
- Use leaflet with OpenStreetMap tile layer
- Click on the map and log the coordinate
- Use Google Earth and place a marker at coordinate

**Expected behavior**
I would expect that there would not a notable difference in display. This is mostly the case, but in this particular case (as shown in the plunker), there is a delta.

**Current behavior**
The delta is 5-6 meters. Also map rotation seems to be a little different (if you for instance place an image on this object, there will be a slight rotation difference compared to the GE image overlay)

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): Chrome, Firefox
- OS/Platform (with version): macOS Catalina

**Additional context**

**Minimal example reproducing the issue**

https://plnkr.co/edit/YTiyw9ea2Ta2xstoUiyH?p=preview

Point the mouse to the corner of the building as shown in the GE screenshot and compare the coordinates.

![image](https://user-images.githubusercontent.com/731020/75152911-6b514880-570a-11ea-928f-c2d467882bf0.png)

The coordinate shown by leaflet is lat: 52.5857376651135, lng: 13.286971449851992. Sticking a marker in GE at this coordinate gives a visible impression of the offset.

![image](https://user-images.githubusercontent.com/731020/75153235-31347680-570b-11ea-9dd4-3761faae61df.png)

The delta is 6.41 m.

I watch this problem with several structures. But not with all. Doing the same in the center of Berlin for instance does not show any difference (e.g. at  52.519606/ 13.406852)

Not sure, if leaflet is to address...

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment] 2020-02-24 13:12
Issue with a data provider, not Leaflet itself. Duplicate of #6989 (and #6925, #3896, #4661, #4332, #4819, #5056, and #6284).

Not really a data issue, but a (common) artifact of [orthorectification](https://en.wikipedia.org/wiki/Orthophoto). The *apparent* position of the top of the building depends on the relative angle that the plane was when taking the pic.

![imagen](https://user-images.githubusercontent.com/1125786/75154992-4ca18080-570f-11ea-860c-0a04046f85fd.png)

See https://wiki.openstreetmap.org/wiki/Using_Imagery as well if you wanna enter the rabbit whole of aerial imagery offset.

**Closed by IvanSanchez** 2020-02-24 13:12 UTC

**Comment by neilyoung** [comment] 2020-02-24 15:08
Thanks. That makes sense.
