### ISSUE TITLE
Leaflet 1.7.1: Popup not opening in Safari Desktop / iOS

### ISSUE THREAD

**Issue by mcguffin** [Leaflet/Leaflet#7430] opened 2021-01-25 11:07 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
 - Open https://leafletjs.com in Safari (14.0.2)
 - Close the pretty CSS3 popup
 - Click on the marker

**Expected behavior**
The popup should reopen

**Current behavior**
nothing happens.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Safari 14.0.2
- OS/Platform (with version): macOS 10.15.7

**Additional context**
The Issue has been reported for Safari on iOS too: https://github.com/mcguffin/acf-openstreetmap-field/issues/65

**Minimal example reproducing the issue**

https://leafletjs.com
Alternatively: https://plnkr.co/edit/IE70Iy2c62i6E28l

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by johnd0e** [comment] 2021-01-25 11:10
Closed as duplicate of #7330.

**Closed by johnd0e** 2021-01-25 11:10 UTC
