### ISSUE TITLE
unloadInvisibleTiles regression on master

### ISSUE THREAD

**Issue by bcamper** [Leaflet/Leaflet#3025] opened 2014-11-14 19:00 UTC
It looks like the `unloadInvisibleTiles` option has a regression on master. In this example, I still get `tileunload` events & DOM removals when `unloadInvisibleTiles` is set to false. On 0.7.3, I don't get these events.

```
        var map = L.map('map').setView([40.70531887544228, -74.00976419448853], 16);
        var layer = L.tileLayer(
                'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                { unloadInvisibleTiles: false })
            .addTo(map);

        layer.on('tileunload', function(event) {
            console.log('tileunload event for ', event.tile);
        });
```

It looks like these calls are coming from `_deferRemove`, called via `_pruneTiles`, which doesn't seem to have any checks for this flag.

**Comment by yohanboniface** [comment] 2015-10-12 12:11
Hi @bcamper can you check if the issue is still in latest master? If yes, can you setup a quick test case to demonstrate the issue (http://playground-leaflet.rhcloud.com/ may help) ? Thanks :)

**Comment by mourner** [comment] 2016-02-12 14:42
No test case or further comments -> closing

**Closed by mourner** 2016-02-12 14:42 UTC
Labels: needs more info
