### ISSUE TITLE
shift+drag map zoom not working on safari

### ISSUE THREAD

**Issue by dieterdreist** [Leaflet/Leaflet#7278] opened 2020-09-16 14:12 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- hold shift and drag over map

**Expected behavior**

zoom window

**Current behavior**

nothing happens

**Environment**
- Leaflet version: I believe it is 1.7 (e.g. on OSM.org and on leafletjs.com frontpage map) 
- Browser (with version): Safari Version 13.1.2 (15609.3.5.1.3)
- OS/Platform (with version): macOS 10.15.6

**Additional context**

**Minimal example reproducing the issue**

See https://leafletjs.com/
or https://osm.org/
- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment] 2020-09-16 16:17
Possible duplicate of #7255. Please try reproducing with a fresh build from the `master` branch, as explained in https://github.com/Leaflet/Leaflet/issues/7255#issuecomment-689562115

**Comment by dieterdreist** [comment] 2020-09-16 17:09
It works here on Safari as expected: https://plnkr.co/edit/v4GzrCYSxpIO1aOo?preview

**Comment by dieterdreist** [comment] 2020-09-16 17:12
actually, I just noticed it behaves a bit odd, because it does not zoom to the rectangle but adds some padding to it (on all sides). Bug or Feature?

**Comment by IvanSanchez** [comment] 2020-09-17 08:25
> actually, I just noticed it behaves a bit odd, because it does not zoom to the rectangle but adds some padding to it (on all sides). Bug or Feature?

Feature. Changing the map's `zoomSnap` option to `0` should give you the desired behaviour.

**Comment by IvanSanchez** [comment] 2020-09-17 08:25
> With the master branch It works on Safari as expected: https://plnkr.co/edit/v4GzrCYSxpIO1aOo?preview

Closing as duplicate of #7255

**Closed by IvanSanchez** 2020-09-17 08:25 UTC
Labels: bug, compatibility
