### ISSUE TITLE
no dragging under chrome devtools' mobile emulation

### ISSUE THREAD

**Issue by oallouch** [Leaflet/Leaflet#3519] opened 2015-06-08 13:01 UTC
Hi,

I'm very new to leaflet, but, to make it work under Chrome's emulation, I had to add, before loading the library:

var doc = document.documentElement;
doc.ontouchstart = doc.ontouchstart || function() {};

This way it detects the touch capability of the Browser, done in line 544 of leaflet v0.7.3:

// IE10+ (We simulate these into touch* events in L.DomEvent and L.DomEvent.Pointer) or WebKit, etc.
if (pointer || (startName in doc)) {
	return true;
}

thx

**Comment by IvanSanchez** [comment] 2015-06-08 13:03
Duplicate of #3466

**Closed by IvanSanchez** 2015-06-08 13:03 UTC
