### ISSUE TITLE
dragend event on marker fails when setIcon is used to change the icon color

### ISSUE THREAD

**Issue by andrewhodel** [Leaflet/Leaflet#7668] opened 2021-09-13 15:03 UTC
I've provided a simple example on the plunker leaflet site, I hope it allows you to understand how the `setIcon()` marker function is ending the drag event.

**Expected behavior**

The drag event should not be interrupted.

**Current behavior**

The drag event is being interrupted.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome 93.0.4577.63
- OS/Platform (with version): OS X M1 11.52

**Additional context**

**Minimal example reproducing the issue**

https://plnkr.co/edit/ygpLak9qAAGSv6lp?preview

<details>
<summary>Source code for the "plunk" in the event it is modified</summary>

```js
var map = new L.Map('leaflet', {
	layers: [
		new L.TileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
			attribution:
				'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
		}),
	],
	center: [0, 0],
	zoom: 0,
});

var svg_icon = get_svg_icon();

var icon = new L.icon({
	iconUrl: svg_icon.url,
	iconSize: svg_icon.iconSize,
	iconAnchor: svg_icon.anchor,
});

var opts = { title: 'test', draggable: true, icon: icon };

var marker = new L.Marker([0, 0], opts).addTo(map);

marker._icon.classList.add('randomclass');

marker.addEventListener('dragend', function (marker) {
	console.log('dragend event fired', marker);
});

function get_svg_icon(c) {
	// needs to return url, iconSize, anchor, z_index
	var icon = {};

	icon.z_index = 99;

	var svg = '';
	var svg_path =
		'm-22.5,0.45313c0,-6.07735 9.62155,-11 21.5,-11c11.87845,0 21.5,4.92265 21.5,11c0,6.07735 -9.62155,11 -21.5,11c-11.87845,0 -21.5,-4.92265 -21.5,-11z';
	var fillColor = c;
	var strokeColor = 'white';
	var strokeWidth = 2;
	// set the offset of the point on the image
	icon.anchor = [0, 0];

	var scale = 1.5;

	if (true) {
		icon.anchor = [13.5, 23];

		svg_path =
			'M 12,2 C 8.1340068,2 5,5.1340068 5,9 c 0,5.25 7,13 7,13 0,0 7,-7.75 7,-13 0,-3.8659932 -3.134007,-7 -7,-7 z';
		svg =
			"<svg xmlns='http://www.w3.org/2000/svg'><path transform='translate(" +
			strokeWidth +
			' ' +
			strokeWidth +
			') scale(' +
			scale +
			")' d='" +
			svg_path +
			"' fill='" +
			fillColor +
			"' stroke-width='" +
			strokeWidth +
			"' stroke='" +
			strokeColor +
			"'/></svg>";
	}

	icon.iconSize = [46, 24];

	var sc = 0;
	while (sc < icon.anchor.length) {
		// apply scale to anchor and iconSize
		icon.anchor[sc] = icon.anchor[sc] * scale;
		icon.iconSize[sc] = icon.iconSize[sc] * scale;
		sc++;
	}

	icon.url = 'data:image/svg+xml,' + encodeURIComponent(svg);

	return icon;
}

var current_color = 'red';

// here we change the marker color by using a new icon, every second and this forces the dragend event to fail and not fire, a solution is to use the drag event but this still makes it a pain to drag around
setInterval(
	function () {
		if (current_color == 'blue') {
			current_color = 'red';
		} else {
			current_color = 'blue';
		}

		var svg_icon = get_svg_icon(current_color);

		var icon = new L.icon({
			iconUrl: svg_icon.url,
			iconSize: svg_icon.iconSize,
			iconAnchor: svg_icon.anchor,
		});

		this.marker.setIcon(icon);
	}.bind({ marker: marker }),
	1000
);
```

</details>

**Comment by andrewhodel** [comment] 2021-09-13 15:04
Drag the marker on the plunker example slowly for more than one second, you will see that the use of `marker.setIcon()` in the loop that flashes the marker color forces the drag event to end.

**Comment by Malvoz** [comment] 2022-04-08 00:19
Related / potentially duplicate of #6226.

**Comment by Falke-Design** [comment] 2022-04-08 04:37
Duplicate of #4484

**Closed by Falke-Design** 2022-04-08 04:37 UTC
