### ISSUE TITLE
Map tile layer floats on the surface

### ISSUE THREAD

**Issue by ZhaoXingPeng** [Leaflet/Leaflet#8695] opened 2022-12-04 07:54 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. 
Create a container to store the contents of the map. 
two。. 
Other components are being written inside this container
It looks like this: 
< div id= "container" >. 
< div > component 1 < / div >. 
< div > component 2 < / div >. 
< div > component 3 < / div >. 
< div > component 4 < / div >. 
< / div >. 
Ideally, all components except the map can float on the map container, the map can be clicked and dragged in a small area in the center of the screen, and the background of the other components is transparent. You can see the map, but you can't operate it.

3. 
The problems I encountered: 
The map floats above all the components, covering all the components. 
The details are shown in the following figure
![image](https://user-images.githubusercontent.com/77369958/205480124-b051e188-8c44-42bc-9377-7add086f01d6.png)
4. 
In terms of solutions: 
You have tried to change the level using panes. 
As follows. 
/ / create pane and put offline map at the bottom. 
That.offMap.createPane ('labels'). 
/ / put the offline map at the bottom. 
That.offMap.getPane ('labels'). Style.zIndex =-50. 
/ / set the display level. 
Var layer = L.tileLayer ('URL' 
{. 
MaxZoom: 11. 
MinZoom: 8. 
AutoZIndex: false. 
Pane: 'labels' 
});

It still hasn't been solved effectively.

### Expected behavior

I hope there is a boss who can help me solve this problem, so that the map appears at the bottom and does not float at the top and block other components.
![image](https://user-images.githubusercontent.com/77369958/205480149-ccffdc3c-ec1c-4a56-aea2-1ab55b17e65d.png)

### Current behavior

![image](https://user-images.githubusercontent.com/77369958/205480157-e5c79504-e91f-4ed7-867e-5b759eb48d39.png)

### Environment

- Leaflet version: 1.9.3
- Browser (with version): Microsoft Edge version 107.0.1418.62 
- OS/Platform (with version): windows

**Comment by IvanSanchez** [comment] 2022-12-04 11:48
Duplicate of #3690. Set a stacking context for the map container.

**Closed by IvanSanchez** 2022-12-04 11:48 UTC
Labels: bug, needs triage
