### ISSUE TITLE
Jammu And Kashmir not shown as part of India

### ISSUE THREAD

**Issue by AviRns** [Leaflet/Leaflet#5056] opened 2016-10-26 10:36 UTC
Hi,

when i see the map of J&K as in other maps like google where J&K is shown as part of india but in Leaflet whole J&K is not shown as part of india, rather it mentions Azad Kashmir.

Can you fix it.

Thanks And regards
Avinash

**Comment by IvanSanchez** [comment] 2016-10-26 10:37
Duplicate of #3896, #4661, #4332, #4819.

Leaflet is just a map display library. Look for the data provider.

**Closed by IvanSanchez** 2016-10-26 10:37 UTC

**Comment by IvanSanchez** [comment] 2016-10-26 10:53
@AviRns BTW, You should also see http://frab.fossgis-konferenz.de/en/foss4g-2016/public/events/1242 and its recording at http://ftp5.gwdg.de/pub/misc/openstreetmap/FOSS4G-2016/foss4g-2016-1242-when_politics_meet_maps_there_is_no_right-hd.webm

**Comment by akbu2498** [comment] 2018-05-22 10:28
@AviRns, were you able to solve this? If yes, let me know how to go about it. I am using leaflet for rendering mapbox.
