### ISSUE TITLE
Flickering while zooming on some Android WebView with custom CSS-filter

### ISSUE THREAD

**Issue by andreandersson** [Leaflet/Leaflet#8630] opened 2022-10-30 12:40 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Set a custom `CSS-filter` on `img`. For example: `img { filter: invert(1); }`
2. Create an Android-app which opens the map in a WebView
3. Pinch zoom

### Expected behavior

While pinch-zooming some strange flickering can be seen; and it seems like a "none-styled map" is overlayed above the map. The issue is easier to see if you have `zoomSnap` 0.0001 or something similar.

### Current behavior

The map should be pinch zoomed correctly

### Minimal example reproducing the issue

https://github.com/andreandersson/leaflet-bug/tree/main

### Environment

NOTE: This does not seem to be the case with most WebViews, but only some phones... We have been able to see it on Pixel 6 and 7 Pro. See video in the repo linked in the example reproducing the issue.

- Leaflet version: 1.9.2
- Browser (with version): Android System WebView 106.0.5249.126
- OS/Platform (with version): Android 13 (seen in 12 as well)

**Comment by jonkoops** [comment] 2022-10-31 16:45
Android WebView is not a supported browser, as we cannot reasonably reproduce any issues in it. The fact that this only occurs on a sub-set of phones as well makes if even more problematic to reproduce.

I have not been able to reproduce this in either Chrome (107.0.5304.87) or Firefox (105.0.2) by running the provided code in a regular browser.

Since the Android WebView is based on Chrome, this issue might be fixed by a future update. Either way, this is a quirk in the browser, not Leaflet.

**Closed by jonkoops** 2022-10-31 16:45 UTC
Labels: bug, needs triage

**Comment by Malvoz** [comment] 2022-10-31 16:58
@andreandersson You can file WebView bugs at https://bugs.chromium.org/p/chromium/issues/entry?template=Webview+Bugs.

**Comment by andreandersson** [comment] 2022-11-06 12:22
Created a bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1380149&start=0
Started questioning if this is an WebView bug as well, or if it is related to the Pixel 6/Pixel 7 more specifically. Not my speciality, but perhaps it could be some hardware accelerated CSS-things affecting it all. Say drivers for the Tensor-chips or something similar... Just mentioning my thought :)

**Anyway, if anyone needs a workaround so... for future reference:**
Instead of applying the filter on the `img-tag` set it to the parent `.leaflet-tile-container`. This will give you a quite ugly looking map (depending on your filter)... However; that is something which can also be worked around. Leaflet has the following CSS `.leaflet-tile { filter: inherit; visibility: hidden; }` which we need to override and set `filter: initial` to. The CSS you will end up with is:

```css
.leaflet-tile-container {
  filter: invert(1);
}

.leaflet-tile {
  filter: initial !important;
}
```

**And back to something we might want to do in the Leaflet codebase:**
The `filter: inherit` on `.leaflet-tile` was added as a fix for IE6-9 here: https://github.com/Leaflet/Leaflet/issues/451

Since `filter` in Internet Explorer 6-9 and `filter` in Edge (and most other browsers) is completely different; shouldn't we ensure that the IE-filter is actually only targeting IE by changing it to `ms-filter: inherit`? See https://learn.microsoft.com/en-us/previous-versions/ms530752(v=vs.85)
See https://learn.microsoft.com/en-us/previous-versions/ms530752(v=vs.85)

**Comment by jonkoops** [comment] 2022-11-09 16:32
We don't support those older versions of Internet Explorer any longer, so perhaps we can simply remove the `filter` from the CSS entirely?

**Comment by andreandersson** [comment] 2022-11-09 16:55
What browsers are supported today? Im all in for removing code :)

**Comment by jonkoops** [comment] 2022-11-10 16:34
For 2.0 we're aiming for latest Chrome (and Chromium derivatives), Firefox, Safari. Basically all the 'evergreen' targets.
