### ISSUE TITLE
Wrong version leaflet-src.js 1.6 in 1.7.1 download

### ISSUE THREAD

**Issue by aanndd** [Leaflet/Leaflet#7301] opened 2020-10-04 08:16 UTC
File leaflet-src.js have version 1.6 in the 1.7.1 download.

**Comment by aanndd** [comment] 2020-10-04 08:24
In the version downloaded from:
https://leafletjs.com/download.html

**Comment by IvanSanchez** [comment] 2020-10-04 09:45
Duplicate of #7258

**Closed by IvanSanchez** 2020-10-04 09:45 UTC
