### ISSUE TITLE
[Suggestion] Please make HTTPS download links

### ISSUE THREAD

**Issue by ZondLV** [Leaflet/Leaflet#4408] opened 2016-04-11 07:42 UTC
I am unable to load Leaflet in JSFiddle, because download links are HTTP. It would be great if there were HTTPS download links for JS and CSS files.

**Comment by snkashis** [comment] 2016-04-11 19:39
Duplicate of https://github.com/Leaflet/Leaflet/issues/1824.

**Closed by snkashis** 2016-04-11 19:39 UTC
