### ISSUE TITLE
Stale version numbers in leaflet-src*.js

### ISSUE THREAD

**Issue by dmullis** [Leaflet/Leaflet#7514] opened 2021-03-16 18:37 UTC
**Description**
File leaflet.js  in downloaded .zip distro contains "1.7.1", but leaflet-src.esm.js and leaflet-src.js contain "1.6.0""

**Steps to reproduce**
Download and unpack .zip file, `cd` into unpacked directory. Then:
```
$ grep --only-matching -E '1[.][67][.].*' **' *
...
leaflet-src.esm.js:1.6.0+Detached: bd88f73e8ddb90eb945a28bc1de9eb07f7386118.bd88f73, a JS library for interactive maps. http://leafletjs.com
leaflet-src.esm.js:1.6.0";
leaflet-src.js:1.6.0+Detached: bd88f73e8ddb90eb945a28bc1de9eb07f7386118.bd88f73, a JS library for interactive maps. http://leafletjs.com
leaflet-src.js:1.6.0";
leaflet.js:1.7.1, a JS library for interactive maps. http://leafletjs.com
leaflet.js:1.7.1",t.Control=Xi,t.control=Yi,t.Browser=Bt,t.Evented=E,t.Mixin=ne,t.Util=C,t.Class=S,t.Handler=ie,t.extend=h,t.b
...
```

Verified (and first discovered) by loading from HTML with 
`  <script src="./lib/leaflet-src.js"> </script>`
then typing into Firefox Debug Console:
`>> L.version`
`"1.6.0"`

**Environment**
- Leaflet version: 1.7.1 -- http://cdn.leafletjs.com/leaflet/v1.7.1/leaflet.zip

**Additional**
Code contents of leaflet-src*.js however appear correct, as containing a [post-1.6.0 change](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md):
```
grep --only-matching -E --with-filename 'featureGroup.*' *-src*.js
```

**Comment by johnd0e** [comment] 2021-03-16 19:08
Duplicate of #7258.

**Closed by johnd0e** 2021-03-16 19:08 UTC
