### ISSUE TITLE
Add double quotes for CSS / filter to prevent warnings in Safari debugger

### ISSUE THREAD

**Issue by robertharm** [Leaflet/Leaflet#5353] opened 2017-02-21 22:33 UTC
A user of our plugin reported at https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/issues/24#note_23896582 that the following CSS is producing "Unexpected CSS token" warnings in Safari debugger:

```
.leaflet-oldie .leaflet-popup-tip {
	width: 24px;
	margin: 0 auto;
	-ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)";
	**filter: progid:DXImageTransform.Microsoft.Matrix(M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678);**
	}
.leaflet-oldie .leaflet-popup-tip-container {
	margin-top: -1px;
	}
```

We fixed this by adding double quotes which according to our research is the suggested fix for those kind of warnings: `filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678);"`

Perhaps this change should also be added to the leaflet repo.

**Comment by IvanSanchez** [comment] 2017-02-22 09:00
Duplicate of #5066, #4977, #4122.

**Closed by IvanSanchez** 2017-02-22 09:00 UTC

**Comment by ahmad-ben** [comment] 2024-02-27 17:38
Always add a **" "** double quote to the filter value in the correspondent path.
In my case:
<img width="786" alt="Screenshot 2024-02-27 173448" src="https://github.com/Leaflet/Leaflet/assets/114083017/60b6ffe4-fb0a-41e6-b15b-01807c02d3b9">
The path is **./node_modules/leaflet/dist/leaflet.css:538:15**
So i went to  **./node_modules/leaflet/dist/leaflet.css** and search for **filter property**:
<img width="896" alt="Screenshot 2024-02-27 173635" src="https://github.com/Leaflet/Leaflet/assets/114083017/8a8e75fe-ff94-437c-96b5-2ac51c85bf4f">
Then added the double quote:
<img width="905" alt="Screenshot 2024-02-27 173650" src="https://github.com/Leaflet/Leaflet/assets/114083017/0a679dd9-a408-40b8-98c0-82fd3723824a">
