### ISSUE TITLE
Leaflet mobile example - geolocation not working

### ISSUE THREAD

**Issue by bplmp** [Leaflet/Leaflet#4801] opened 2016-08-06 15:08 UTC
When opening the [Leaflet mobile example](http://leafletjs.com/examples/mobile-example.html) I get the following error: "Geolocation error: only secure origins are allowed" and a link to this page https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features.

**Comment by IvanSanchez** [comment] 2016-08-06 15:10
Duplicate of #4565

**Closed by IvanSanchez** 2016-08-06 15:10 UTC
