### ISSUE TITLE
Control.Layers not adding scrollbar when setting collapsed to false

### ISSUE THREAD

**Issue by tgelz** [Leaflet/Leaflet#5328] opened 2017-02-13 06:09 UTC
Using Leaflet 1.0.3, I noticed that no scrollbar (leaflet-control-layers-scrollbar class) is added to the layer list when creating the control with `collapsed: false` and the list is exceeding the map height. When using `collapsed: true` instead, the scrollbar is added correctly.

https://jsfiddle.net/nwenkfq5/

**Comment by IvanSanchez** [comment] 2017-02-13 09:00
Duplicate of https://github.com/Leaflet/Leaflet/issues/5277 , already fixed in the master branch.

**Comment by ghybs** [comment] 2017-02-14 05:03
Hi,

Seems like the dev version on S3 still has this bug:
https://playground-leaflet.rhcloud.com/bohu/1/edit?html,output
(forked from the playground from #5277)
(Chromium 53, FF 51)

It sounds different from #5277, where the issue was scroll event affecting the map under the Layers Control, but the scroll bar was correctly displayed (and Layers Control was scrollable, even though scrolling also made the map zoom).

Here the Layers Control is not scrollable at all, if its `collapsed` option is set to `false`.

**Comment by IvanSanchez** [comment] 2017-02-14 08:41
Hah, I would swear I tested for that when I had a look at #5277. My fault.

**Comment by ghybs** [comment] 2017-02-14 12:18
Looks like this bug is present even before version 0.7.3:
https://playground-leaflet.rhcloud.com/keka/1/edit?html,output

The "tricky" part is that the `expand` computation happens before the Control ever reached the DOM, therefore its height has never been computed by the browser.
It is necessary then to hook a new `expand` *after* the Control has been actually inserted into the DOM:
https://playground-leaflet.rhcloud.com/dilow/1/edit?html,output

Furthermore, the same issue can happen when dynamically adding base layers / overlays while the Layers Control is already on the map / in the DOM.
It is therefore necessary to also hook a new `expand` after each `_addLayer`:
https://playground-leaflet.rhcloud.com/lofi/1/edit?html,output (click on "Add overlays" button on bottom)

When `collapsed` option is `true`, and Layers Control is expanded (i.e. mouse has entered the control), the issue when dynamically adding layers does not happen because the entire form is updated, and mouse *re-enters* the control, triggering an `expand`.

**Comment by ghybs** [comment] 2017-02-21 14:45
@tgelz: this should be fixed in `master` now.

**Closed** 2017-07-09 15:08 UTC
