### ISSUE TITLE
Leaflet 1.7.1 + Ionic React / Capacitor: no double click on generated iOS app

### ISSUE THREAD

**Issue by jedilor** [Leaflet/Leaflet#7419] opened 2021-01-21 10:03 UTC
Hello

I am using Ionic React / Capacitor with Leaflet 1.7.1 to build iOS and Android apps, but the double click is not working on the generated iOS app.
The map does not zoom in and the `dblclick` events are not triggered.

Here is the Browser object in iOS:
**"ie":false,
"ielt9":false,
"edge":false,
"webkit":true,
"android":false,
"android23":false,
"androidStock":false,
"opera":false,
"chrome":false,
"gecko":false,
"safari":false,
"phantom":false,
"opera12":false,
"win":false,
"ie3d":false,
"webkit3d":true,
"gecko3d":false,
"any3d":true,
"mobile":true,
"mobileWebkit":true,
"mobileWebkit3d":true,
"msPointer":false,
"pointer":true,
"touch":true,
"mobileOpera":false,
"mobileGecko":false,
"retina":true,
"passiveEvents":true,
"canvas":true,
"svg":true,
"vml":false}**

and the navigator.userAgent:
**Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148**

I looked at the code and the function `browserFiresNativeDblClick` (in DomEvent.js) returns true, indicating a native double click support.
But it doesn't work as expected. Do you have any idea?

Just for testing, I locally and temporary changed browserFiresNativeDblClick to always return false and it starts working successfully on the iOS device.

I also precise it is working fine in the generated Android app.

Thanks.

**Comment by IvanSanchez** [comment] 2021-01-21 10:12
Most likely a duplicate of https://github.com/Leaflet/Leaflet/issues/7255 , so the workaround of disabling the `tap` handler (as seen in the comments of #7255) should help. Otherwise, you're getting the "we don't do bugs if there's a framework in betwen" boilerplate.

**Comment by IvanSanchez** [comment] 2021-01-21 10:12
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Closed by IvanSanchez** 2021-01-21 10:12 UTC

**Comment by johnd0e** [comment] 2021-01-21 10:42
@jedilor
You could try #7027

**Comment by jedilor** [comment] 2021-01-21 11:17
@johnd0e
I tried #7027 and I confirm this is working!

**Comment by johnd0e** [comment] 2021-01-21 11:25
Please also try alternative @IvanSanchez's suggestion: https://github.com/Leaflet/Leaflet/issues/7419#issuecomment-764528261

**Comment by jedilor** [comment] 2021-01-21 11:27
@johnd0e 
I tried @IvanSanchez's suggestion, setting `tap=false`, but it didn't work.

**Comment by johnd0e** [comment] 2021-01-21 11:30
Ok. then vote for #7027.
I hope @IvanSanchez or @morner will find time to review and merge it.

**Comment by johnd0e** [comment] 2021-01-21 11:37
@jedilor
> I tried @IvanSanchez's suggestion, setting `tap=false`, but it didn't work.

Please also show your exact code (that part with `tap` option), to make sure that you tried proper option.

**Comment by jedilor** [comment] 2021-01-21 12:01
This is written in React Leaflet, but here is an extract of the code:
```
      <Map
            crs={this.mapCrs}
            className={"lk-leaflet-container"}
            ref={this.mapRef}
            attributionControl={false}
            tap={false}
            zoomControl={false}
            minZoom={0}
            maxZoom={6}
            zoomSnap={0}
            bounceAtZoomLimits={true}
      >
                   TileLayer or ImageOverlay are used inside
      </Map>
```

**Comment by johnd0e** [comment] 2021-01-21 12:19
Ok, that means that you really need #7027.
