### ISSUE TITLE
PolyLine is displayed with an offset In the old browser

### ISSUE THREAD

**Issue by alik-datsko** [Leaflet/Leaflet#5299] opened 2017-02-02 11:09 UTC
In the old browser, I see the PolyLine shift relative to the Markers.
Here everything is correct -
http://playground-leaflet.rhcloud.com/towe/

However, when I run the program 1C (with built-in simple browser like IE8)
PolyLine is displayed with an offset
When I zooming map offset increases.
Please tell me where to look.

![polyline_offset](https://cloud.githubusercontent.com/assets/20067371/22547123/359c8328-e951-11e6-8de5-c7f11dc9354b.JPG)

**Comment by IvanSanchez** [comment] 2017-02-02 11:54
That demo is using Leaflet 1.0.0-rc3, which is quite old. Is this bug reproducible with Leaflet 1.0.3?

**Comment by alik-datsko** [comment] 2017-02-02 12:01
Yes, I chose the wrong library in playground for demonstration.
In my maps I use Leaflet 1.0.3 of course

**Comment by IvanSanchez** [comment] 2017-02-02 14:11
I can not reproduce the bug in a IE8 virtual machine.

Which exact browser are you using?

**Comment by alik-datsko** [comment] 2017-02-02 14:40
The trouble is that it's programm-built-in browser. Maybe it IE7.
I'm afraid you will not be able to reproduce it on its side.
I was hoping that maybe you have met with a similar past.

**Comment by IvanSanchez** [comment] 2017-02-02 14:58
Do you know what browser engine does it use? What's the user-agent string?

**Comment by DenisCarriere** [comment] 2017-02-27 21:42
Having the same PolyLine shift behavior.
Here's the GeoJSON:
https://gist.github.com/anonymous/e678f8809fe5d7f5d8d486a56ffd7ad0

The shift happens in both GeoJSON.io & GitHub.

According to [GeoJSON.io `package.json`](https://github.com/mapbox/geojson.io/blob/gh-pages/package.json), the versions are:

- mapbox.js 2.2.2
  - leaflet 1.0.2

However, when I test it in QGIS everything lines up perfectly.

**GeoJSON.io (Scale 1km)**

![image](https://cloud.githubusercontent.com/assets/550895/23380405/a68f2214-fd08-11e6-911a-4bf22f7e7eb2.png)

**Github's Gist**

![image](https://cloud.githubusercontent.com/assets/550895/23380444/ce24ef98-fd08-11e6-8ad5-aa7ec0654969.png)


**QGIS (Scale 1:50)**

![image](https://cloud.githubusercontent.com/assets/550895/23380364/7a7e6cde-fd08-11e6-982c-6ed912eae22b.png)

CC: @IvanSanchez @alik-datsko

**Comment by perliedman** [comment] 2017-06-29 21:07
@DenisCarriere I think what you're showing is a different problem, and not an issue in Leaflet.

What appears to be going on is that you have one very long line going from A to B, and then you have a point X (position of the marker in your screenshot) which appears to be a point on the great circle from A to B.

The straight line from A to B, drawn in Spherical Mercator will not hit all intermediate points on a great circle from A to B, so it's natural to see this type of difference.

As to why you're not seeing this in QGIS, I can only guess: perhaps another projection, or perhaps QGIS draws the actual great circle?

It's hard to say this 100%, since I don't know how your data was constructed, but drawing 1000 km straight lines in spherical mercator quite often gives unexpected results.

Also: closing this issue - the original issue is about a problem only in some old IE version, and it looks like we can't get enough info to do anything about it.

@DenisCarriere if you feel this is still a Leaflet issue, I'm happy to continue this discussion in a new issue if you open it!

**Closed by perliedman** 2017-06-29 21:07 UTC
Labels: needs more info

**Comment by DenisCarriere** [comment] 2017-06-30 12:06
👍 @perliedman Makes sense, this is a Mercator projection related issue and not a Leaflet issue. Large GeoJSON can visually represent unexpected results.
