### ISSUE TITLE
Calling openPopup() on a layerGroup fails

### ISSUE THREAD

**Issue by anrikun** [Leaflet/Leaflet#5414] opened 2017-03-27 13:37 UTC
## How to reproduce
- Leaflet version I'm using: latest dev
- Browser (with version) I'm using: Firefox 52
- OS/Platform (with version) I'm using: Win 7 64
- add a GeoJSON layer containing a point and a polygon
- bind a popup
- call openPopup()

## What behaviour I'm expecting and which behaviour I'm seeing
Popup should open at the center of the layer.
Instead, error in console: TypeError: layer.getLatLng is not a function

## Minimal example reproducing the issue
http://playground-leaflet.rhcloud.com/bosi/1/edit?html,console,output

**Comment by IvanSanchez** [comment] 2017-03-27 13:46
An even simpler way to reproduce (as per http://playground-leaflet.rhcloud.com/vope/edit?html,output ) is:

```
    var group = L.layerGroup();
    var marker = new L.Marker(myCenter).addTo(group);
    group.addLayer(marker);
    group.addTo(map);

    group.bindPopup("<p>Lorem ipsum</p>");
    group.openPopup();
```

The behaviour of `openPopup()` is not defined when triggering it on a `L.LayerGroup` (or `L.FeatureGroup`, or `L.GeoJson` for that matter). While it might seem obvious to pass it through to a layer inside, that is only appropriate for groups with just one member layer.

Not sure what should be the behaviour on this case.

**Comment by gggauravgandhi** [comment] 2017-03-30 10:17
Can you have a popup on a group ? Will below code is what you wanted to achieve ?
```
    var group = L.layerGroup();
    var marker = new L.Marker(selectionObject.leaflet_event.latlng).addTo(group);
    group.addLayer(marker);
    group.addTo(coreObject.mapObject.map);

    marker.bindPopup("<p>Lorem ipsum</p>");
    marker.openPopup();
```

**Comment by Falke-Design** [comment] 2020-10-26 17:07
The current behavior of L.FeatureGroup is that the popup is opened on the last layer of the group. 
https://github.com/Leaflet/Leaflet/blob/bc918d4bdc2ba189807bc207c77080fb41ecc196/src/layer/DivOverlay.js#L168

This would also work for LayerGroups.

But don't forgot, after closing the popup, it can't reopened by clicking on the layer, it must be opened over the LayerGroup. This works with FeatureGroups.



@IvanSanchez you said:
> Not sure what should be the behaviour on this case.

I think it is clear now, because how FeatureGroups are working.

**Comment by johnd0e** [comment] 2021-04-04 14:46
As already said, `openPopup` behavior is not defined for `LayerGroup`.
Looking in code you may find that these cases are handled:
- either you specify latlng
- or layer has getCenter() or `getLatLng()` or `getBounds()` (you can `include` them even in `LayerGroup` btw)
- or layer is FeatureGroup (and that it's first member is used as source)

> This would also work for LayerGroups.

Well yes, this part of code will work for `LayerGroup` too.
But there is a little sense to allow this without all other functionality that you can see in `FeatureGroup`.

**Closed by johnd0e** 2021-04-04 14:46 UTC
Labels: needs discussion
