### ISSUE TITLE
Zoom level must be between 0-20

### ISSUE THREAD

**Issue by tssobe** [Leaflet/Leaflet#6549] opened 2019-03-11 09:24 UTC
Hey,
I am using leaflet among side with mapbox.
Once calling to mapbox with styles : https://{s}.api.mapbox.com/styles/v1 ...
the response is "Zoom level must be between 0-20" (with zoom level 24).
Any idea how can I solve it?
Thanks

**Comment by IvanSanchez** [comment] 2019-03-11 10:03
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by tssobe** [comment] 2019-03-11 11:56
i have the following code:
    this.leafletLayers = [
      tileLayer(`https://{s}.api.mapbox.com/styles/v1/shlomir/${this.environment.mapId}/tiles/256/{z}/{x}/{y}@2x?access_token=...`, {
        maxZoom: 24,
        minZoom: ZOOM_MIN,
        attribution: '...',
        subdomains: 'ab'
      }),
      tileLayer(`https://{s}.api.mapbox.com/styles/v1/shlomir/cjk7x5aktgraz2smu3nkuainl/tiles/256/{z}/{x}/{y}@2x?access_token=..`, {
        maxZoom: 24,
        minZoom: ZOOM_MIN,
        attribution: '...',
        subdomains: 'ab'
      }),
    ];

    this.leafletOptions = {
      layers: this.leafletLayers[0],
      zoomControl: false,
      zoom: this.zoom,
      doubleClickZoom: false,
      center: this.center,
    };

**Comment by IvanSanchez** [comment] 2019-03-11 12:47
Duplicate of https://github.com/Asymmetrik/ngx-leaflet/issues/212

**Comment by IvanSanchez** [comment] 2019-03-11 12:47
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Closed by IvanSanchez** 2019-03-11 12:47 UTC
Labels: needs more info
