### ISSUE TITLE
Leaflet.PixiOverlay doesn't work with 1.9.1 version of leaflet

### ISSUE THREAD

**Issue by mitow7821** [Leaflet/Leaflet#8485] opened 2022-09-27 08:49 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

This library doesn't work after last update:
https://github.com/manubb/Leaflet.PixiOverlay#usage

### Expected behavior

Library should work as in 1.8 leaflet.

### Current behavior

![image](https://user-images.githubusercontent.com/34492112/191918385-52d639b2-017b-4dfa-b3b5-75af0a21ae4b.png)

### Environment

- Leaflet version: 1.9.1
- Browser (with version): Chrome 105.0.5195.127
- OS/Platform (with version): Windows 10

**Comment by Falke-Design** [comment] 2022-09-27 09:01
Thank you for reporting, we are already working on this.

Duplicate of #8451

**Comment by jonkoops** [comment] 2022-09-27 09:47
Duplicate of #8451

**Closed by jonkoops** 2022-09-27 09:47 UTC
Labels: bug, needs triage
