### ISSUE TITLE
Tiles blurred after panning

### ISSUE THREAD

**Issue by gopi-ar** [Leaflet/Leaflet#6329] opened 2018-09-05 03:44 UTC
## How to reproduce

- Leaflet version I'm using: This is visible on the latest Leaflet version in the demo page at https://leafletjs.com/
- Browser (with version) I'm using: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: Mac OS 10.13.3
- step 1 - load leafletjs.com, the tiles in the demo map appear sharp.
- step 2 - move the map around a bit, tiles now appear blurred.

I'm using an external monitor which isn't retina, so it's not a Retina / 512px tile issue. Also, since it loads correctly the first time it can't be a monitor issue.

Screenshot after loading the page:
![leaflet_-_a_javascript_library_for_interactive_maps](https://user-images.githubusercontent.com/3132453/45069781-d3ae0380-b0eb-11e8-940c-cf98acc0386c.png)

Screenshot after panning the map a bit:
![leaflet_-_a_javascript_library_for_interactive_maps__after_pan_-2](https://user-images.githubusercontent.com/3132453/45069790-e6283d00-b0eb-11e8-9b75-a6a9b8e2454f.png)

Strangely enough even the text in the popup appears blurred.

**Comment by IvanSanchez** [comment] 2018-09-05 10:56
Duplicate of https://github.com/Leaflet/Leaflet/issues/6069

**Closed by IvanSanchez** 2018-09-05 10:56 UTC
