### ISSUE TITLE
Two-finger zooming gets unusably slow with many markers

### ISSUE THREAD

**Issue by php4fan** [Leaflet/Leaflet#8032] opened 2022-03-03 23:58 UTC
I have a map with a few hundreds markers, maybe a couple thousands, of which usually, in a typical usage scenario, only a few dozens are within the viewport at any given time.

When I use two fingers to zoom in and out and move around, the animation gets terribly sluggish.

I have the exact same map with the exact same markers in Google Maps and it's blazingly fast (on the same device, obviously), so it's clearly not impossible to display and move and scale that many icons in real time efficiently.

Ok I can see what happens.

In Leaflet, while I zoom in and out with two fingers, all the markers are constantly redrawn at every slightest movement. I can see  that because the markers wiggle around all the time (effect of the rounding of their position) and they maintain their size. Obviously that's very CPU-intensive when there are a lots of markers. In ontrast, Google Maps scales and translates the whole image as if it was a pre-rendered image (the markers get smaller or bigger) until a certain threshold where it redraws everything.

It would be reasonable to be able to choose, because Leaflet's behavior can be viable if you have very few markers, and in that case might be preferrable. But when you have a fair amount of markers it becomes unusable.

I have looked at the documented options and I haven't found anything that seems to address this (besides completely hiding the markers while zooming).

**Comment by php4fan** [comment] 2022-03-04 00:02
> (besides completely hiding the markers while zooming).

LOL not even that. I have just tried `markerZoomAnimation: false` but that only hides the markers during the animation when you RELEASE the two fingers. That's useful when zooming with the zoom control, but completely useless for pinch zoom.

**Comment by IvanSanchez** [comment] 2022-03-04 00:12
Duplicate of #6314

**Closed by IvanSanchez** 2022-03-04 00:12 UTC

**Comment by siikamiika** [comment] 2022-05-08 12:04
I mostly solved this issue on pretty slow hardware with ~2000 total markers by

1. Creating  `L.marker` instances for each marker in advance but not adding them to the map with `marker.addTo(map)` yet
2. Binding a function to `L.map` `moveend` event that
    1. removes all markers with `marker.remove()`
    2. checks if the zoom level is large enough to sufficiently limit the amount of visible markers
    3. queries the map bounds with `map.getBounds()`
    4. for each marker checks if the marker is within the bounds before adding it to the map with `marker.addTo(map)`

Future improvement could be to show aggregate markers when zoom is far away
