### ISSUE TITLE
IE8 error SCRIPT5007: Unable to get property 'replace' of undefined or null reference

### ISSUE THREAD

**Issue by huazhikui** [Leaflet/Leaflet#5683] opened 2017-08-03 02:16 UTC
## How to reproduce

- Leaflet version I'm using: Leaflet 1.1.0
- Browser (with version) I'm using: IE8
- OS/Platform (with version) I'm using: window 10

## What behaviour I'm expecting and which behaviour I'm seeing
IE8 error SCRIPT5007: Unable to get property 'replace' of undefined or null reference
## Minimal example reproducing the issue
```js
var overlayLayers = {

}
L.control.layers(baseLayers, overlayLayers).addTo(map);
```
### fix
leaflet-src.js, line 174:
```js
function template(str, data) {
	if(!str) return;
        ....
}
```

**Comment by perliedman** [comment] 2017-08-03 13:31
Hi!

From you very short example code, it looks like you have identified the layers control as the source of this error, but looking at the code for the layers control, it does not call the `template` function you refer to.

I suspect the problem is really somewhere else, but it's not possible to investigate without a proper, fully running example that reproduces the issue, so I need to ask you to expand the sample code. Ideally, put it on http://playground-leaflet.rhcloud.com/ or a similar service.

**Comment by perliedman** [comment] 2017-08-08 15:11
Closing for now, happy to re-open when we get more information on the issue!

**Closed by perliedman** 2017-08-08 15:11 UTC
Labels: needs more info

**Comment by Pictor13** [comment] 2019-03-13 13:54
You didn't write where `baseLayers` comes from and what's inside there. You probably didn't initialise them correctly.

However... the solution is to provide an actually defined string as argument to `tileLayer()` (or other way you initialise layers).
Otherwise the template function will try to use it and replace vars on `undefined`, throwing that error.
