### ISSUE TITLE
Tiles not shown when zooming out of minzoom

### ISSUE THREAD

**Issue by mcastril** [Leaflet/Leaflet#3977] opened 2015-10-30 10:07 UTC
I have seen similar issues to this but not the same.

I have experimented this problem only on mobile devices, not in a desktop browser.

- Set minzoom
- Pinch out, zoomstart fires
- zoomend is not fired

Appart of this, sometimes the tiles dissappear and then don't refresh again.

This is a problem for me because I use a custom overlay and make it hide when zoom starts, and then redraw when zoom ends. In this case the layer never reappears.

I have tried to set bounceAtZoomLimits to false but the result is more or less the same, with the only difference that it does not animate the bounce. Some times the zoom does not perform, but if you insist on pinching out the map it then jumps to another position and my layer and tiles disappear.

**Comment by IvanSanchez** [comment] 2015-10-30 10:34
What leaflet version? Which mobile browser(s)?

**Comment by mcastril** [comment] 2015-10-30 10:36
Leaflet 0.7.5
Google Chrome on Android 5.0 Lollipop

**Comment by mcastril** [comment] 2015-10-30 11:17
Ok I have done more testing and it seems that the zoomend it is fired. The only problem that remains there is that in many ocassions the tiles disappear and don't appear again after you do another different zoom in.

It happens both in Google Chrome and Phonegap.

**Comment by mourner** [comment] 2016-09-27 14:17
Closing because we just released 1.0 and minor issues in 0.7.x are unlikely to be fixed. Let's reopen if the issue is still relevant in 1.0.

**Closed by mourner** 2016-09-27 14:17 UTC
Labels: 0.7.x, bug, mobile, needs investigation
