### ISSUE TITLE
MapQuest basemaps now require AppKey

### ISSUE THREAD

**Issue by tomkralidis** [Leaflet/Leaflet#4724] opened 2016-07-12 10:42 UTC
As reported in https://github.com/ckan/ckanext-spatial/issues/157, MapQuest tiles now require an AppKey.  It would be valuable to ensure any documentation/examples are updated accordingly.

**Comment by IvanSanchez** [comment] 2016-07-12 10:48
Duplicate of #4723. The current leaflet website and documentation don't mention MapQuest, except a link to the plugin they provide.

Nothing do be done here.

**Closed by IvanSanchez** 2016-07-12 10:48 UTC
