### ISSUE TITLE
Mouse wheel scrolling results in 2 step zoom

### ISSUE THREAD

**Issue by zdila** [Leaflet/Leaflet#7403] opened 2021-01-10 19:27 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- setup 4k (UHD) monitor on your system (in Xfce settings / Apperance / set Window scaling to 2x)
- open Chrome and go to https://leafletjs.com/examples/quick-start/
- move scroll wheel just a single step

**Expected behavior**

Zoom should be changed by value of 1

**Current behavior**

Zoom is changed by value of 2

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Google Chrome 87.0.4280.141
- OS/Platform (with version): Debial Bullseye Linux, Xfce 4.16

**Additional context**

- window.devicePixelRatio is 1.875
- no problem in Firefox (where window.devicePixelRatio is 1.2)
- zooming page to 50% (where Chrome then reports devicePixelRatio to be 0.9375) doesn't help
- see also https://github.com/Leaflet/Leaflet/issues/4538#issuecomment-720090197
- also reproducible in MS Edge 89.0.752.1 

**Minimal example reproducing the issue**

https://leafletjs.com/examples/quick-start/example-basic.html

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by jeffreykog** [comment] 2021-01-16 22:36
I'm experiencing this issue as well on https://antennekaart.nl/kaart/4g. On that page you can see the actual zoom level in the URL. When scrolling (zooming) in chrome on a 4k monitor you see these levels increment/decrement with 2 instead of 1. Zooming by double clicking or using the zoom controls zooms by a single level.

I expect this issue to be related to an event getting triggered twice by the browser, and being handled twice by Leaflet. That assumption will have to be confirmed

**Comment by zdila** [comment] 2021-01-26 13:20
This patch fixes the issue for me:
```diff
diff --git a/src/dom/DomEvent.js b/src/dom/DomEvent.js
index a79ddffd..f3887357 100644
--- a/src/dom/DomEvent.js
+++ b/src/dom/DomEvent.js
@@ -232,7 +232,7 @@ export function getMousePosition(e, container) {
 // Chrome on Win scrolls double the pixels as in other platforms (see #4538),
 // and Firefox scrolls device pixels, not CSS pixels
 var wheelPxFactor =
-       (Browser.win && Browser.chrome) ? 2 * window.devicePixelRatio :
+       ((Browser.win || navigator.platform.indexOf('Linux') === 0) && Browser.chrome) ? 2 * window.devicePixelRatio :^M
        Browser.gecko ? window.devicePixelRatio : 1;
 
 // @function getWheelDelta(ev: DOMEvent): Number
```

**Comment by jeffreykog** [comment] 2021-02-22 16:17
@zdila Perhaps you (or I, if you don't have time) could make a pull request for this patch. I verified it and it fixes it in my case as well. I prefer to rely on npm packages and not my own custom patched packes.

**Comment by zdila** [comment] 2021-09-30 16:46
After upgrading to FF 92 on Linut is started to behavw like Chrome on Windows.

So now I am patching leaflet using webpack string-replace-loader like this:
```javascript
{
  enforce: 'pre',
  test: /\bnode_modules\/leaflet\/dist\/leaflet-src\.js/,
  loader: 'string-replace-loader',
  options: {
    search: '(win && chrome) ? 2 * window.devicePixelRatio :',
    replace:
      "(win && chrome || navigator.platform.indexOf('Linux') === 0) ? 2 * window.devicePixelRatio :",
    strict: true,
  },
}
```

**Comment by zdila** [comment] 2021-12-22 22:10
I think you should target this in the milestone 1.8. It is pretty annoying that all the leaflet-based maps all over the internet zooms in step of two if you have 4k display, at least on Linux. Observable on osm.org or umap.openstreetmap.fr.

**Comment by zdila** [comment] 2022-02-15 17:41
Meanwhile zooming by scroll wheel causes www.osm.org to be in steps of 3 on my Firefox at Linux PC with non-hidpi display. On my friend's windows PC (also non-hidpi) FF scrolls by 2.

**Comment by KommX** [comment] 2022-02-23 07:20
To document my (slightly different) case from #8016:
I can observe this issue on

- Windows 10 21H1
- Firefox 97.0.1
- screen resolution 2560*1440

It works fine in Chrome for me.

**Comment by jinchun-wang** [comment] 2022-04-15 06:57
We also have the issue on firefox with the fix.

It's really fixed if I add a check in the following file

Leaflet/src/map/handler/Map.ScrollWheelZoom.js

 _performZoom: function () {
    ...
    if (!delta) { return; }
	
	// Check if delta is bigger than zoomDelta for firefox
    var zoomDelta = map.options.zoomDelta;
    if (Math.abs(delta) > zoomDelta ) {
      delta = delta > 0 ? zoomDelta : -zoomDelta;
    }
    var nextZoom = zoom + delta;

    if (map.options.scrollWheelZoom === 'center') {
      map.setZoom(nextZoom);
    } else {
      map.setZoomAround(this._lastMousePos, nextZoom);
    }
  }

**Comment by Falke-Design** [comment] 2022-04-15 07:13
@jinchun-wang you added
```
    var zoomDelta = map.options.zoomDelta;
    if (Math.abs(delta) > zoomDelta ) {
      delta = delta > 0 ? zoomDelta : -zoomDelta;
    }
```
correct?

**Comment by jinchun-wang** [comment] 2022-04-15 07:15
Yes

**Comment by Falke-Design** [comment] 2022-04-15 08:00
@jinchun-wang thank you for your idea but it is not a good workaround, because it destroys fast scrolling.

@IvanSanchez was on the right way. The problem is that Firefox changed from line scrolling to pixel scrolling like Chrome.

> Can confirm.
> 
> We need to double-check the `getWheelDelta` behaviour at https://github.com/Leaflet/Leaflet/blob/7847cc6913c296fb7e409e086a57366237c42728/src/dom/DomEvent.js#L252-L266
> 
> I wonder if Firefox has taken the behaviour of IE/Edge as in https://github.com/Leaflet/Leaflet/issues/4592. Maybe revert part of https://github.com/Leaflet/Leaflet/commit/d9c5e943d81151b926182d4b12d77817ae73b593 and make Firefox use `window.devicePixelRatio` again?

_Originally posted by @IvanSanchez in https://github.com/Leaflet/Leaflet/issues/8125#issuecomment-1092210598_


We need to adjust the logic for Firefox and make it same as for Chrome:
https://github.com/Leaflet/Leaflet/blob/25546fc04fbff9c5fec26f1cb42bda710be8c7ae/src/dom/DomEvent.js#L248-L250
@IvanSanchez you are using Firefox on Linux correct and having the same issue? So `Browser.win && Browser.gecko` would be not working. Maybe you can test if Chrome is working correct in Linux.

Can please someone test what it does on Mac with Chrome, Firefox & Safari?:

Would be nice if we get data from different Browsers:
```
L.DomEvent.on(map.getContainer(), 'wheel', (e)=>{
	var zoomBefore = map.getZoom();
  var data = ['Win: '+L.Browser.win, 'Gecko: '+L.Browser.gecko, 'Chrome: '+L.Browser.chrome, 'Edge: '+L.Browser.edge, 'Safari: '+L.Browser.safari, 'Retina: '+L.Browser.retina, 'wheelDeltaY: '+e.wheelDeltaY, 'deltaMode: '+e.deltaMode, 'deltaY: '+e.deltaY, 'deltaX: '+e.deltaX, 'deltaZ: '+e.deltaZ, 'wheelDelta: '+e.wheelDelta,  'detail: '+e.detail, 'devicePixelRatio: '+window.devicePixelRatio];
	setTimeout(()=>{
		data.push('Zoom delta: '+(zoomBefore-map.getZoom()));
		console.log(data.join(',\n'))
	}, 200);
});
```

**Comment by Falke-Design** [comment] 2022-04-15 08:03
Windows:
- Chrome 100:
```
Win: true,
Gecko: false,
Chrome: true,
Edge: false,
Safari: false,
Retina: false,
wheelDeltaY: 120,
deltaMode: 0,
deltaY: -100,
deltaX: 0,
deltaZ: 0,
wheelDelta: 120,
detail: 0,
devicePixelRatio: 1,
Zoom delta: -1
```

- Firefox 99:
```
Win: true,
Gecko: true,
Chrome: false,
Edge: false,
Safari: false,
Retina: false,
wheelDeltaY: 120,
deltaMode: 0,
deltaY: -102,
deltaX: 0,
deltaZ: 0,
wheelDelta: 120,
detail: 0,
devicePixelRatio: 1,
Zoom delta: -1
```

- Edge 100:
```
Win: true,
Gecko: false,
Chrome: true,
Edge: false,
Safari: false,
Retina: false,
wheelDeltaY: 120,
deltaMode: 0,
deltaY: -100,
deltaX: 0,
deltaZ: 0,
wheelDelta: 120,
detail: 0,
devicePixelRatio: 0.9599999785423279,
Zoom delta: -1
```

**Comment by jinchun-wang** [comment] 2022-04-15 09:40
Thanks for sharing the info. 

Here is my case:

Use Virtual Machine with Windows 11

2 screens : small one and big one with the same resolution
The result is same for the 2 screens

NOK - 2 zoom steps on Firefox - v99.0.1 (64-bit)
window.devicePixelRatio = 1
win = true
chrom = false
gecko = true

deltaMode: 0
deltaX: 0
deltaY: -102
deltaZ: 0
detail: 0
wheelDelta: 120
wheelDeltaX: 0
wheelDeltaY: 120

OK on Chrome - v100.0.4896.88 (Official Build) (64-bit)
window.devicePixelRatio = 1.100000023841858
win = true
chrome = true
gecko = false

deltaMode: 0
deltaX: -0
deltaY: -100
deltaZ: 0
detail: 0
wheelDelta: 120
wheelDeltaX: 0
wheelDeltaY: 120

**Comment by mourner** [comment] 2022-04-15 20:25
Thanks for the help tracking this down! If there's a good idea on the fix, I think it would be nice to include in 1.8.0 final as well.

**Comment by IvanSanchez** [comment] 2022-04-15 21:12
> @IvanSanchez you are using Firefox on Linux correct and having the same issue?

@Falke-Design Yes. I can only test with the touchpad at the moment, which triggers big, discrete `wheel` events with a delta of 114px:

Firefox 98.0 @ Linux:
```
Win: false,
Gecko: true,
Chrome: false,
Edge: false,
Safari: false,
Retina: false,
wheelDeltaY: 120,
deltaMode: 0,
deltaY: -114,
deltaX: 0,
deltaZ: 0,
wheelDelta: 120,
detail: 0,
devicePixelRatio: 1,
Zoom delta: 0
```

> If there's a good idea on the fix, I think it would be nice to include in 1.8.0 final as well.

@mourner The apparent solution would be...

```
var wheelPxFactor = 2 * window.devicePixelRatio;
```

...but I'd rather get some numbers on Safari first. Can someone get a clicky-wheel USB mouse on a mac and get the `deltaY` of the `wheel` events?

**Comment by Falke-Design** [comment] 2022-04-16 09:06
@IvanSanchez can you please test Chrome too?

MacBook Air (Retina Screen):

Chrome 100:
```
Win: false,
Gecko: false,
Chrome: true,
Edge: false,
Safari: false,
Retina: true,
wheelDeltaY: -240,
deltaMode: 0,
deltaY: 8.00048828125,
deltaX: 0,
deltaZ: 0,
wheelDelta: -240,
detail: 0,
devicePixelRatio: 2,
Zoom delta: 0
```

Safari 15.2:
```
Win: false,
Gecko: false,
Chrome: false,
Edge: false,
Safari: true,
Retina: true,
wheelDeltaY: -12,
deltaMode: 0,
deltaY: 4.000244140625,
deltaX: 0,
deltaZ: 0,
wheelDelta: -12,
detail: 0,
devicePixelRatio: 2,
Zoom delta: 0
```

**Comment by IvanSanchez** [comment] 2022-04-18 19:08
I've made https://plnkr.co/edit/eecQ7iqySIccbB0X to try and compile info, and:

| What             | Chrome 100, win | Firefox 99, win | Edge 100     | Firefox 99.0.1, win | Chrome       | Firefox 98, linux | Chrome 100, OS X | Safari 15.2  | Firefox 98, linux | Chromium 99, linux |
|------------------|-----------------|-----------------|--------------|---------------------|--------------|-------------------|------------------|--------------|-------------------|--------------------|
| Who              | Falke-Design    | Falke-Design    | Falke-Design | jinchun-wang        | jinchun-wang | ivansanchez       | Falke-Design     | Falke-Design | ivansanchez       | ivansanchez        |
| Notes            |                 |                 |              |                     |              | touchpad          | touchpad?        | touchpad?    | Mouse             | Mouse              |
| Leaflet          |                 |                 |              |                     |              |                   |                  |              | 1.8.0             | 1.8.0              |
| Win              | true            | true            | true         | true                | true         | false             | false            | false        | false             | false              |
| Gecko            | false           | true            | false        | true                | false        | true              | false            | false        | true              | false              |
| Chrome           | true            | false           | true         | false               | true         | false             | true             | false        | false             | true               |
| Edge             | false           | false           | false        |                     |              | false             | false            | false        | false             | false              |
| Safari           | false           | false           | false        |                     |              | false             | false            | true         | false             | false              |
| Retina           | false           | false           | false        |                     |              | false             | true             | true         | false             | false              |
| wheelDeltaY      | 120             | 120             | 120          | 120                 | 120          | -120              | -240             | -12          | 120               | 120                |
| deltaMode        | 0               | 0               | 0            | 0                   | 0            | 0                 | 0                | 0            | 0                 | 0                  |
| deltaY           | -100            | -102            | -100         | -102                | -100         | 114               | 8,00048          | 4,00024      | -114              | -53                |
| deltaX           | 0               | 0               | 0            | 0                   | 0            | 0                 | 0                | 0            | 0                 | 0                  |
| deltaZ           | 0               | 0               | 0            | 0                   | 0            | 0                 | 0                | 0            | 0                 | 0                  |
| wheelDelta       | 120             | 120             | 120          | 120                 | 120          | -120              | -240             | -12          | 120               | 120                |
| detail           | 0               | 0               | 0            | 0                   | 0            | 0                 | 0                | 0            | 0                 | 0                  |
| devicePixelRatio | 1               | 1               | 0,959999     | 1                   | 1,1          | 1                 | 2                | 2            | 1                 | 1                  |
| ZoomDelta        | -1              | -1              | -1           | 2                   | 1            | 2                 | 0                | 0            | -2                | -1                 |

@Falke-Design Are you sure you're using a old-timey USB mouse there? In my experience, `wheel` events with such a small delta are typical of touchscreens, or those fancy apple mice with touchpad surface instead of an actual mechanical wheel. Remember, this bug is about big discrete `wheel` events.

**Comment by Falke-Design** [comment] 2022-04-18 20:18
@IvanSanchez yes I used the same [mouse](https://www.amazon.de/zelotes-Gaming-Tasten-Multi-Modi-Gewichtstuning-T90/dp/B07RHYTVMT) as for my windows pc. I added also magic mouse (touchpad) columns

**Comment by jinchun-wang** [comment] 2022-04-19 06:22
Here is my settings

Windows 11
USB mouse
2 display screens : small and big
Dispaly settings - Scale and layout - Change the size of text, apps, and other items - 100% (Recommended)

**Comment by paulatthehug** [comment] 2022-04-19 13:09
Hope these help?

**Chrome 100.0.4896.127 on Linux**

Leaflet: '1.8.0'
Win: false
Gecko: false
Chrome: true
Edge: false
Safari: false
Retina: false
wheelDeltaY: 120
deltaMode: 0
deltaY: -53
deltaX: -0
deltaZ: 0
wheelDelta: 120
detail: 0
devicePixelRatio: 1
Zoom delta: -1

**Firefox 99.0 on Linux**

Leaflet: 1.8.0
Win: false
Gecko: true
Chrome: false
Edge: false
Safari: false
Retina: false
wheelDeltaY: 120
deltaMode: 0
deltaY: -114

**Safari (15.4?) on MacOS Catalina VM running on Linux**

Chrome: false
Edge: false
Gecko: false
Leaflet: "1.8.0"
Retina: false
Safari: true
User-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Ap… (KHTML, like Gecko) Version/15.4 Safari/605.1.15"
Win: false
Zoom delta: -1
deltaMode: 0
deltaX: -0
deltaY: -4.000244140625
deltaZ: 0
detail: 0
devicePixelRatio: 1
wheelDelta: 12
wheelDeltaY: 12

**Comment by zdila** [comment] 2022-04-19 13:21
All on Linux with 4k display:

<details>
  <summary>Click to expand!</summary>

  Vivaldi:

```
{
    "User-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.92 Safari/537.36",
    "Leaflet": "1.8.0",
    "Win": false,
    "Gecko": false,
    "Chrome": true,
    "Edge": false,
    "Safari": false,
    "Retina": true,
    "wheelDeltaY": 225,
    "deltaMode": 0,
    "deltaY": -99.375,
    "deltaX": 0,
    "deltaZ": 0,
    "wheelDelta": 225,
    "detail": 0,
    "devicePixelRatio": 1.875,
    "Zoom delta": -2
}
   ```

Chrome:

```
{
    "User-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36",
    "Leaflet": "1.8.0",
    "Win": false,
    "Gecko": false,
    "Chrome": true,
    "Edge": false,
    "Safari": false,
    "Retina": true,
    "wheelDeltaY": 225,
    "deltaMode": 0,
    "deltaY": -99.375,
    "deltaX": 0,
    "deltaZ": 0,
    "wheelDelta": 225,
    "detail": 0,
    "devicePixelRatio": 1.875,
    "Zoom delta": -2
}
```

Edge:

```
{
    "User-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.39",
    "Leaflet": "1.8.0",
    "Win": false,
    "Gecko": false,
    "Chrome": true,
    "Edge": false,
    "Safari": false,
    "Retina": true,
    "wheelDeltaY": 225,
    "deltaMode": 0,
    "deltaY": -99.375,
    "deltaX": 0,
    "deltaZ": 0,
    "wheelDelta": 225,
    "detail": 0,
    "devicePixelRatio": 1.875,
    "Zoom delta": -2
}
```

Firefox:

```
User-agent
Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0
Leaflet
1.8.0
Win
false
Gecko
true
Chrome
false
Edge
false
Safari
false
Retina
true
wheelDeltaY
120
deltaMode
0
deltaY
-240
deltaX
0
deltaZ
0
wheelDelta
120
detail
0
devicePixelRatio
2
Zoom delta
-2
```
</details>

**Comment by paulatthehug** [comment] 2022-04-19 13:27
> @paulatthehug is it possible for you to install Firefox on your MacOS VM?

Blimey, never occurred to me that I **could** TBH ;-) but I have and here's the result:

User-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
Leaflet: 1.8.0
Win: false
Gecko: true
Chrome: false
Edge: false
Safari: false
Retina: false
wheelDeltaY: 48
deltaMode: 0
deltaY: -16

**Comment by zdila** [comment] 2022-04-19 13:33
Macbook with low-dpi display:

<details>
  <summary>Click to expand!</summary>

Firefox:

```
User-agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0
Leaflet
1.8.0
Win
false
Gecko
true
Chrome
false
Edge
false
Safari
false
Retina
false
wheelDeltaY
-96
deltaMode
0
deltaY
32
deltaX
0
deltaZ
0
wheelDelta
-96
detail
0
devicePixelRatio
1
Zoom delta
0
```

Safari:

```
Chrome
false
Edge
false
Gecko
false
Leaflet
"1.8.0"
Retina
false
Safari
true
User-agent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Ap… (KHTML, like Gecko) Version/15.4 Safari/605.1.15"
Win
false
Zoom delta
-1
deltaMode
0
deltaX
-0
deltaY
-4.000244140625
deltaZ
0
detail
0
devicePixelRatio
1
wheelDelta
12
wheelDeltaY
12
```

Chrome:

```
{
    "User-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36",
    "Leaflet": "1.8.0",
    "Win": false,
    "Gecko": false,
    "Chrome": true,
    "Edge": false,
    "Safari": false,
    "Retina": false,
    "wheelDeltaY": 120,
    "deltaMode": 0,
    "deltaY": -4.000244140625,
    "deltaX": 0,
    "deltaZ": 0,
    "wheelDelta": 120,
    "detail": 0,
    "devicePixelRatio": 1,
    "Zoom delta": 0
}
```

</details>

**Comment by Falke-Design** [comment] 2022-06-18 16:44
Hey guys,

can you please checkout my solution on your Browsers #8298

Demo: https://plnkr.co/edit/gqQUNU9mf6RiqxD4


@zdila, @paulatthehug, @jinchun-wang

**Comment by KommX** [comment] 2022-06-18 19:25
> Hey guys,
> 
> can you please checkout my solution on your Browsers #8298
> 
> Demo: https://plnkr.co/edit/gqQUNU9mf6RiqxD4
> 
> @zdila, @paulatthehug, @jinchun-wang

This works well on my system (Firefox 101.0.1, Win 10).

**Comment by zdila** [comment] 2022-06-19 06:53
@Falke-Design works fine on Firefox and Vivaldi on Linux with HiDPI display.

**Comment by paulatthehug** [comment] 2022-06-19 09:56
Works fine on:

- Linux (Ubuntu 20.04.4 LTS):
  - Firefox 101.0.1
  - Chrome 102.0.5005.115 (Official Build) (64-bit)
  - Waterfox 2020.10 (64-bit) *(yeah, I know, but as I had it hand)*

- macOS Catalina running on a Linux Virtualbox VM
  - Safari 15.4 (15613.1.17.1.13, 15613)

**Comment by Falke-Design** [comment] 2022-07-24 15:13
@paulatthehug are you sure that it worked on Safari? In all Browser simulations that i made with safari, it didn't worked.

Anyway can you please check it again, I updated the logic for macOS.
Old: https://plnkr.co/edit/gqQUNU9mf6RiqxD4
New: https://plnkr.co/edit/vtEzxb7P0EFCkHoq

**Comment by paulatthehug** [comment] 2022-07-25 08:14
Apologies for the delay in replying: Virtualbox upgrade failed. Now fixed.

On both of those the console log is showing a Zoom delta of +/- 1 but I can't help but think we need someone with a real Mac to be sure one way or the other ...

**Closed** 2022-08-04 09:31 UTC
Labels: bug, ux, needs solution

**Comment by KommX** [comment] 2022-09-09 07:47
@Falke-Design 
I still experience this bug with Firefox 104.0.2 on Windows 10.
Is the fix really rolled out to production yet?

**Comment by Falke-Design** [comment] 2022-09-09 08:17
@KommX no it is not in productive yet. It will be released with 1.9.0

**Comment by Gjovani** [comment] 2023-12-19 14:38
Still had this problem even when visiting [OSM](https://www.openstreetmap.org/) in different browsers (Chrome, Firefox, Edge) but it worked on Brave. After a little bit of research [I found out](https://community.openstreetmap.org/t/zooming-with-the-mouse-wheel-skips-zoom-levels/92490/4) that this happens because I was using a Logitech mouse, which had some kind of "Smooth scrolling" feature.

After disabling it, it worked!
![image](https://github.com/Leaflet/Leaflet/assets/61600164/05825366-907c-426b-b609-a1df9ca868d6)

**Comment by neocturne** [comment] 2024-01-03 03:55
Unfortunately, I'm still seeing this issue with Leaflet 1.9.4 in Firefox 121 on Linux with Wayland/Sway. A single step of the mouse wheel of my simple Microsoft USB mouse gives me deltaY 198 and wheelDeltaY -594.

**Comment by Z-28** [comment] 2024-03-05 00:02
I have the same problem, also Linux. With Chromium and Brave, scrolling the mouse one step changes the zoom level two steps. Firefox works as it should be (scrolling one step = one zoom level step).

**Comment by jonkoops** [comment] 2024-03-05 11:01
Please file a new issue if you are still having issues.
