### ISSUE TITLE
Interactions broken on "device emulation mode" on Chrome, Firefox

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3466] opened 2015-05-13 08:04 UTC
How to reproduce:
* Open up http://leafletjs.com/examples/mobile-example.html in a Chrome browser on a desktop computer
* Hit F12, then turn on "device emulation mode" (the small smartphone button top-left in the debug console)
* Select any device to emulate (somehow the bug doesn't reproduce when clearing all the emulation overrides)
* Refresh the page
* Try to interact with the map by dragging

Reproducible at least on my:
* Chromium 42 on Debian 8 
* Chrome 42 on a Win10 VM
* Iceweasel 35 on Debian 8

**Not** reproducible on:
* IE 11 on Win10 VM
* Firefox 38 on Win10 VM

I also noticed it in Chrome on Android 5 on an HTC, but as a non-reproducible heisenbug.

~~I suspect some kind of weird behaviour related to the geolocation code. Somehow the bug doesn't reproduce when accessing the page from localhost, or when allowing/blocking geolocation, but I'm not fully sure yet.~~

I can only reproduce with 0.7.3/stable. Code from master works as expected on `debug/map/map-mobile.html`.

**Comment by mourner** [comment] 2015-05-13 15:43
This is a duplicate of #1890, but I'll close the other one as this issue is more descriptive.

**Comment by oallouch** [comment] 2015-06-08 13:05
Note that the duplicate (and closed) issue #3519 provides a workaround.

**Comment by IvanSanchez** [comment] 2015-06-08 13:14
Pull #3520 should fix this. @oallouch, I didn't notice the root of the problem was at `L.Browser.touch`, nice catch!

**Comment by mourner** [comment] 2015-06-08 20:50
Cool, merged!

**Closed by mourner** 2015-06-08 20:50 UTC
Labels: bug, in progress

**Comment by daniellabirch** [comment] 2016-09-21 21:47
I can't find the official resolution to this. I am having the same issue.

**Comment by blq** [comment] 2020-06-15 10:13
My impression is that this issue has resurfaced in 1.6.0  (at least between 1.4 and 1.6)
Just try using the Chrome emulator on the main page example.
