### ISSUE TITLE
Click events on arrows and custom properties

### ISSUE THREAD

**Issue by Legolash2o** [Leaflet/Leaflet#7362] opened 2020-12-03 15:32 UTC
I'm wanting to add a click event to the layer the arrows are added to, but I'm struggling to pass on custom properties. When I click on the arrow, it prevents me from clicking on the line which already has a working event trigger on it.

Each line has an 'id' property added to it. When I add a test property on arrowLine, i don't seem to be able to see it when I console log.

```
 var arrowLine = L.polylineDecorator(line, {
        patterns: [
             {
                id: 'test',
                clickable: true,
                offset: 40,
                repeat: 40,
                symbol: L.Symbol.arrowHead({
                    pixelSize: 20, pathOptions: {
                        fillOpacity: 0.75,
                        fillColor: 'black',
                        color: '#989898'
                    }
                })
            }
        ]
    });
    arrowLine.test = 'testing';
```

    arrowLine.addTo(trackArrowLayer);

    trackArrowLayer.on("click",
                function (event) {
                    console.log(event.layer);
                });

**Comment by Legolash2o** [comment] 2020-12-03 16:11
Sorry I seemed to have added this in the wrong git.

**Comment by IvanSanchez** [comment] 2020-12-03 16:35
Duplicate of https://github.com/bbecquet/Leaflet.PolylineDecorator/issues/108

**Closed by IvanSanchez** 2020-12-03 16:35 UTC
