### ISSUE TITLE
subsequent calls to setView doesn't work

### ISSUE THREAD

**Issue by prasdeva** [Leaflet/Leaflet#5767] opened 2017-09-08 12:34 UTC
## How to reproduce

- Leaflet version I'm using: 1.03 and latest(1.1.0)
- Browser (with version) I'm using: Chrome Version 60.0.3112.113
- OS/Platform (with version) I'm using:Mac 10.12.5
- Load map with call to setView to centre 
- Add double click event handler to change centre to point where the mouse event occured.

## Minimal example reproducing the issue

- [ ] this example is as simple as possible : yes
- [ ] this example does not rely on any third party code : yes

```
      let map = L.map('map').setView([50.883283, -2.239748], 9);
      var googleLayer = L.gridLayer.googleMutant({ type: 'roadmap' }).addTo(map);

      map.on('dblclick', e => {
        console.log('center : ' + map.getCenter());
        console.log('setting center : ' + e.latlng);

        setTimeout(() => {
          map.setView(e.latlng, map.getZoom());  
          console.log('center : ' + map.getCenter());
        }, 10);
      });      
```

## What behaviour I'm expecting and which behaviour I'm seeing

- Expectation : Map centre changed to new position. In above example, set centre must be equal to value returned by getCentre()
- Behaviour : Map centre doesn't change to set value. As the value of timeout increase, setView results get better. Note : Delay added for trial and error only

http://playground-leaflet.rhcloud.com/vifo/edit?html,output

**Comment by perliedman** [comment] 2017-09-11 07:15
Hi and thanks for reporting!

This looks like a duplicate of #3249, so I'm closing this off.

**Closed by perliedman** 2017-09-11 07:15 UTC
