### ISSUE TITLE
Support HTTPS for CDN

### ISSUE THREAD

**Issue by bhubbard** [Leaflet/Leaflet#4722] opened 2016-07-11 23:35 UTC
I would like to see the CDN support HTTPS.  Example file:

```
http://cdn.leafletjs.com/leaflet-0.7.2/images/layers.png
```

```
https://cdn.leafletjs.com/leaflet-0.7.2/images/layers.png
```

**Comment by IvanSanchez** [comment] 2016-07-12 08:45
Duplicate of #1824

**Closed by IvanSanchez** 2016-07-12 08:45 UTC
