### ISSUE TITLE
Leaflet vs Bulma

### ISSUE THREAD

**Issue by Mongstaen** [Leaflet/Leaflet#6622] opened 2019-04-24 06:51 UTC
Hi!

I'm using Bulma as my CSS framework, and has just started experimenting with leaflet. I'm experiencing that my bulma navbar with dropdowns has stopped working after including the leaflet script. Being a newbie, I'm not really sure how to fix this, nor if it's a bulma or leaflet issue. 

Do you know where the conflict might be? I could use some help figuring this out.

**Comment by IvanSanchez** [comment] 2019-04-24 06:55
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

Seeing it fail by oneself is the only way towards deciding if there's a Leaflet bug, a Bulma bug, or an error on your part.

**Comment by Mongstaen** [comment] 2019-04-24 07:28
Sure! Thanks for the prompt reply!


https://codepen.io/thomasmongstad/full/BPoRKZ

**Comment by IvanSanchez** [comment] 2019-04-24 08:21
I think this is a duplicate of https://github.com/Leaflet/Leaflet/issues/3690 . Please confirm.

**Comment by Mongstaen** [comment] 2019-04-24 08:24
It was indeed. Sorry for the inconvenience.

**Closed** 2019-04-24 08:37 UTC

**Comment by kalwalt** [comment] 2020-04-02 11:47
Hi @Mongstaen  how did you solved? I'm trying to use react-leaflet with bulma but i can't make it work properly. The tip about z-index do not help a lot...

**Comment by kalwalt** [comment] 2020-04-02 14:58
I solved my issue, for anyone interested go to the PR https://github.com/kalwalt/gatsby-starter-i18n-bulma/pull/119 :slightly_smiling_face:
