### ISSUE TITLE
Closing a PopUp calls window.onpopstate

### ISSUE THREAD

**Issue by eliboni** [Leaflet/Leaflet#8203] opened 2022-05-01 20:34 UTC
**Steps to reproduce**
https://leafletjs.com/examples/quick-start/example.html

add

`	window.onpopstate = function(event) {
	  console.log(event);
	  console.log("onpopstate");
	}; `

see [attached ](https://plnkr.co/edit/jZYUUuMVaGkmreIt)

**Expected behavior**
window.onpopstate should not be called when a popup is closed (click on x on top-right of the popup), at least this is the behavior I would expect, if I am wrong let me know

**Current behavior**
window.onpopstate is called when popup is closed.

**Environment**
- Leaflet version: 1.8.0
- Browser (with version): tested on Firefox, Safari
- OS/Platform (with version): Linux / Ipad

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

https://plnkr.co/edit/jZYUUuMVaGkmreIt

**Comment by IvanSanchez** [comment] 2022-05-01 20:40
Duplicate of https://github.com/Leaflet/Leaflet/issues/8159 . Preventing the event's default behaviour (as done in https://github.com/Leaflet/Leaflet/pull/8160) should avoid the change in the window state.

**Closed by IvanSanchez** 2022-05-01 20:40 UTC
