### ISSUE TITLE
locale config option?

### ISSUE THREAD

**Issue by rcrodrigues** [Leaflet/Leaflet#5428] opened 2017-03-31 11:59 UTC
Hello guys, please correct me if I'm mistaken but, as of today, there's no localization config in Leaflet right?
I was trying to translate every tooltip of the control features and I had to go through every plugin and translate them separately.  I believe it could be much more easier if Leaflet had a locale config file so all the plugins could set translations depending on it. This would make translations work in Leaflet as an environment and would be a lot easier to locale the map in global wide applications. 

Thanks in advance :)

**Comment by perliedman** [comment] 2017-04-03 13:33
Hi,
I think I understand your concern, and believe it has some merit. We've had a pretty long discussion about this topic before, so I'm closing this as a duplicate of #1232. I think the problem at this point would be that this is a pretty big change, and there's a lot of work to get a significant portion of existing plugins to adapt such a change.

**Closed by perliedman** 2017-04-03 13:33 UTC
