### ISSUE TITLE
Panning CircleMarker outside device screen makes ghosts on Android browser

### ISSUE THREAD

**Issue by iippa73** [Leaflet/Leaflet#3298] opened 2015-03-10 18:31 UTC
If you pan CircleMarker outside android device screen, you're likely to get marker ghost at the location where the marker originally were. If you pan the original CircleMarker back on screen, you see 2 markers. Here's screencapture from device:

![screenshot_2015-03-10-20-06-56-cut](https://cloud.githubusercontent.com/assets/11397044/6581870/5d9f33c4-c762-11e4-990b-47a3897ae9ba.png)

Full circle is original, half is ghost. When you pan so that keep the original visible, ghost disappears when finger is released.

Simple code similar to this can be used to reproduce:

``` javascript
var map = L.map('map').setView([51.505, -0.09], 13);
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
L.circleMarker([51.52, -0.10]).addTo(map);
```

Happens atleast on Samsung Galaxy Trend Plus (GT-S7580) running android 4.2.2 (API 17) and default browser.

Problem is on master-branch and git bisecting suggests the problem to be happening after -> 4f06ac30b0f1e8fac4778fe37114f3927a074db7 "Don't append/remove the SVG container"

ps. Thanks for superb map engine! :)

**Comment by danzel** [comment] 2015-03-10 20:20
So this happens with the svg renderer? :(

Could you please dom inspector it and see if there are two circles elements in the svg or just 1?

**Comment by iippa73** [comment] 2015-03-10 20:36
Not 100% sure what you mean, but if it's any help, used CircleMarker is the default one coming with the leaflet. I haven't created any svg by myself for it.

If you need extra info, you might need to provide extra instructions :) Do you mean the dom of svg or dom tree of the whole page?

**Comment by danzel** [comment] 2015-03-10 20:39
If you can find any circle element in the dom inspector there may or may not be another one in there next to it.

There will either be two - which would be a leaflet bug, or there will just be one - which would probably be an android svg rendering bug.

**Comment by iippa73** [comment] 2015-03-10 20:47
Sorry, you need to guide me a bit more :) Any hints how I can inspect dom tree from browser inside android device?

**Comment by danzel** [comment] 2015-03-10 20:51
I think you'll need to use weinre :(
http://technical-itch.net/debugging-a-web-app-on-android-stock-browser/

Does the bug reproduce in chrome on android? Would be much easier to debug there (details on the same page)

**Comment by iippa73** [comment] 2015-03-10 20:52
Thanks, I'll have a go with it tomorrow and test the chrome also

**Comment by danzel** [comment] 2015-03-10 20:54
Cool :)

**Comment by iippa73** [comment] 2015-03-10 21:35
Heh, could not let it rest after all :) Tried out chrome, works as it should. So, problem only on android's default browser.

Then played a bit with weinre (actually rather cool tool!) and here is the part I suspect to be the svg in dom? So, only one on dom when there are two visible markers on device screen :/

![screenshot - 10 03 2015 - 23 28 59](https://cloud.githubusercontent.com/assets/11397044/6585842/9b5f17a4-c77d-11e4-994a-79c7f961832f.png)

**Comment by danzel** [comment] 2015-03-10 21:41
Awesome. Yeah Android bug then... :(
If you revert that commit everything behaves correctly?

We might need to add that hack in for the old android browser :(

Or maybe try the canvas renderer?

**Comment by iippa73** [comment] 2015-03-11 19:35
Yes, I can't reproduce the ghost anymore if I revert one commit back.

For me this isn't showstopper. Now when I know the reason, I can always switch to bitmap. Must be annoying to patch bugs of browsers on your side :/ Let me know if you need someone to verify the fix later.

**Comment by mourner** [comment] 2015-04-23 10:45
Yeah, we should probably readd the hack, but only for Android stock browser.

**Comment by IvanSanchez** [comment] 2016-04-02 18:02
@iippa73 I cannot reproduce this on my android 5.0.2. If you still have your galaxy trend, can you still confirm the bug?

**Comment by IvanSanchez** [comment] 2016-04-02 18:18
The issue cannot be reproduced either in Chrome in Android 4, according to @hyperknot. I'll push it back into the future as it looks like it won't affect a lot of users.

**Comment by johnd0e** [comment] 2020-04-14 07:26
Closing this, as it seems that we no longer care about android stock. 
Compare #7013.

**Closed by johnd0e** 2020-04-14 07:26 UTC
Labels: accepted, android, bug, mobile
