### ISSUE TITLE
Zooming (Gesture or Buttons) on LG G4 makes map unresponsive

### ISSUE THREAD

**Issue by pakro** [Leaflet/Leaflet#3832] opened 2015-09-11 10:44 UTC
Hello, 

we experience a problem with the leaflet version 1.0 beta on a LG G4 stock browser (com.android.browser (38.0.2125.102)). After the map is loaded every zooming interaction leads to a unresponsive map and the tiles are not loaded anymore. However just panning the map around works fine. There are no errors on the console. On the stable release (0.7.5) it works just fine. Any clue what might cause this issue on this specific browser? 

Reproduction is simple. Just use the appropriate leaflet version, let the map take up all available space and add zooming controls. We used OSM as tile provider, but it also didn't work for Here.

**Comment by IvanSanchez** [comment] 2015-09-11 10:51
Can you please make sure this is not a duplicate of #3814?

**Comment by pakro** [comment] 2015-09-11 11:36
As far as I'm understanding the pictures of the issue #3814 right, it also happens in Chrome on Android and Safari on iOS. This issue here does only appear in the native LG G4 Browser (which should be Chrome 38 but maybe has some modifications from LG). It works flawlessly on the current available Chrome Browser for Android. However the symptoms sound similar, although this issue here is very simple to reproduce (it does exactly take one gesture or one zoom button press). To be honest I'm not absolutely sure whether this is a duplicate or not. But we had never observed such issues on Chrome and Safari. The G4 and its native browser is the first device.

I will try to investigate the issue and will post it here, if I will find something.

**Comment by IvanSanchez** [comment] 2015-09-11 11:44
I've got no trouble with the default stock Android browsers in a Samsung S3 and in an HTC One. I have no way to try with a LG stock browser, so I cannot know what's wrong here.

**Comment by pakro** [comment] 2015-09-11 12:11
We also do not experience any issues with the S3 stock browser and the HTC One stock browser. But the LG does not work. Maybe someone else can confirm that issue. I can provide a minimal code example, which works every time.

**Comment by IvanSanchez** [comment] 2015-09-11 12:22
> I can provide a minimal code example, which works every time.

That's always useful! :-)

But your description of the bug makes me think that https://github.com/Leaflet/Leaflet/blob/master/debug/map/map-mobile.html might work for reproducing this one.

**Comment by pakro** [comment] 2015-09-11 12:48
Yes, I can confirm that your link does also produces the misbehavior.

**Comment by pakro** [comment] 2015-09-14 11:08
I'm not exactly sure, but I have a possible solution... at least for the LG G4. But I am absolutely not sure what else is affected. 

In the file Map.Zoomanimation.js within the _createAnimProxy there a is listener which does react on 'zooanim'. Within this listener there is a workaround built in. I removed the condition and it is now always calling _onZoomTransitionEnd. This change seems to fix it for the LG G4.

Here is a link to the affected file:
https://github.com/Leaflet/Leaflet/blob/master/src/map/anim/Map.ZoomAnimation.js#L43-L45

Removing the condition around _onZoomTransitionEnd results in no problems with the G4.

**Comment by pakro** [comment] 2015-09-15 19:14
Ok I have the issue for the problem, but sill missing a solution. The LG G4 does not fire a "transitionend" event (but i have to verify that)... That's the reason why my initial quick fix did solve the problems... as the transitionend-handler exactly executes the same method. Removing the condition basically emulated a transitionend every time and reliable.

**Comment by IvanSanchez** [comment] 2015-09-15 22:12
Related to `transitionend`, you say? Let's dig up #3689 then.

@mourner Were we not ditching `transitionend` events in favour of timers?

**Comment by pakro** [comment] 2015-09-17 09:01
ok what i have so far... 

it seems the LG G4 Browser ist throwing a transitionend... but leaflet detects it prefixed. But that alone does not solve the problem. Somehow - and I really don't understand what is going on here - the proxy created on line https://github.com/Leaflet/Leaflet/blob/master/src/map/anim/Map.ZoomAnimation.js#L33 does not receive the transitionend event... if I register the event on the map pane it works flawlessly... 

So instead of using
``` 
L.DomEvent.on(this._proxy, L.DomUtil.TRANSITION_END, this._catchTransitionEnd, this);
```

the LG-Fix is
```
L.DomEvent.on(this._panes.mapPane, L.DomUtil.TRANSITION_END, this._catchTransitionEnd, this);
```

Assuming that the detection is correct and there the L.DOMUtil.TRANSITION_END equals "transitionend".

Anybody any idea why the hell the event is not fired on the proxy element? Any other browser does this...

**Comment by mourner** [comment] 2015-09-18 03:29
@IvanSanchez yeah, I think we just want to forwardport the timer fix to master for b2, and maybe even ditch the proxy hack completely in favor of timers.

**Comment by pakro** [comment] 2015-09-30 20:51
I have prepared a branch with the fixes I made in our project. I will make the pull request in the next days. However you should carefully look into the fix. We don't have any problems yet with the G4 and all other devices seem to work properly too. But that doesn't mean anything :) Maybe you can use it, if not I hope it helps the project in some other way!

**Comment by IvanSanchez** [comment] 2015-10-05 11:24
@pakro Any progress on your pull request?

**Comment by pakro** [comment] 2015-10-05 18:14
I just made the pull request. Sorry for the delay! Hope it helps you in some way :)

**Comment by IvanSanchez** [comment] 2016-08-25 13:45
Closing as "wontfix". See https://github.com/Leaflet/Leaflet/pull/3892#issuecomment-242391615

**Closed by IvanSanchez** 2016-08-25 13:45 UTC
Labels: bug, help wanted, needs more info
