### ISSUE TITLE
Firefox: CircleMarker interactivity broken after dragging the map

### ISSUE THREAD

**Issue by Farami** [Leaflet/Leaflet#5967] opened 2017-12-15 09:02 UTC
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Firefox 57/58
- OS/Platform (with version) I'm using: Windows

- Drag map
- Click on CircleMarker

## What behaviour I'm expecting and which behaviour I'm seeing
Click and mousedown events should trigger after moving the map but they're not.
It's working fine in Chrome.

## Minimal example reproducing the issue
http://jsfiddle.net/3jprmbjv/6/

**Comment by IvanSanchez** [comment] 2017-12-15 09:37
Can reproduce quite consistently. Sometimes the hitbox for the SVG paths is a couple pixels wide on the edge of the circlemarker.

I would suggest creating some more tests using [`document.getElementFromPoint()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint) and maybe prosthetic-hand to automate things.

**Comment by perliedman** [comment] 2017-12-15 15:49
I suspect this is a duplicate of #5773 - I get pretty much exactly the same results on http://leafletjs.com/examples/quick-start/ in Firefox 57 on Ubuntu.

Of course hard to tell, but given how long this has worked well in all browsers, I'm tempted to say something is broken in recent Firefox versions...

**Comment by panupetteri** [comment] 2018-01-08 08:46
I also have this issue.

After dragging the map the SVG element acts as if it does not exist in DOM:
* it does not send events, like click or hover
* it omits interactive CSS rules (like `cursor: pointer`)
* it cannot be selected from Developer tools' "Pick an element from this page" feature
* it cannot be selected with `document.elementFromPoint()`

However, Firefox still renders the SVG element. Any re-render (eh. changing window size or zooming map) fixes the problem and makes the element clickable.

So this might be an issue with Firefox.

**Comment by nrenner** [comment] 2018-01-19 18:29
I would also say this is a duplicate of #5773, see [my comment and demos](https://github.com/Leaflet/Leaflet/issues/5773#issuecomment-359048426) there.

**Comment by perliedman** [comment] 2018-01-22 11:31
Ok, I'm closing this as duplicate of #5773, please tell me if someone thinks this is the wrong decision.

**Closed by perliedman** 2018-01-22 11:31 UTC
Labels: needs investigation
