### ISSUE TITLE
There is a pixel gap between each small image

### ISSUE THREAD

**Issue by zhuyinjing** [Leaflet/Leaflet#6097] opened 2018-03-19 08:23 UTC
hi i use leaflet@1.2.0 in my code
and it shows 1px white line with the image,such like 
There is a pixel gap between each small image
Do I need to adjust some of the parameters?
thanks so much！

**Comment by IvanSanchez** [comment] 2018-03-19 08:28
Duplicate of #3575

**Closed by IvanSanchez** 2018-03-19 08:28 UTC
