### ISSUE TITLE
undefined is not an object (evaluating 'this._startPos.add'

### ISSUE THREAD

**Issue by stripathix** [Leaflet/Leaflet#6242] opened 2018-07-18 16:09 UTC
- Leaflet version I'm using: "1.3.1"
- Browser (with version) I'm using: Mobile Safari UIWebView#11.2.5
--

I am not able to reproduce this bug but it got logged to sentry service by error logging.

Error is in Draggable.js Line:164
	this._newPos = this._startPos.add(offset);

Stacktrace:
add()@http://localhost:8080/app/node_modules/leaflet/dist/leaflet.js:5:61589

_onMove@http://localhost:8080/js/vendor.bundle.4.4.0.0.18.07.03.17.00.js:1:1944633

**Comment by IvanSanchez** [comment] 2018-08-13 07:40
> I am not able to reproduce this bug

But we need to reproduce it in order to know what's wrong :neutral_face:

**Comment by perliedman** [comment] 2018-10-28 10:50
Closing since we unfortunately can't work with issues that we can't reproduce.

**Closed by perliedman** 2018-10-28 10:50 UTC
Labels: compatibility, needs more info

**Comment by Jannnnnn** [comment] 2019-02-12 07:32
Unfortunately, I can not reproduce the error yet. In our Sentry logs, I see that the device has changed orientation and the error only occurs in the Mobile Safari browser

**Comment by stripathix** [comment] 2019-06-08 08:43
Will it cause any bad behavior for the user? Can I add it to my ignore list? I too am not able to reproduce it. But it keeps getting logged in my sentry logs.
