### ISSUE TITLE
polygon layers become unclickable after adding circle markers to another layer

### ISSUE THREAD

**Issue by cscrum** [Leaflet/Leaflet#7015] opened 2020-03-09 19:29 UTC
I've got multiple datasets to add to a map. One layer is a a group of polygons I build to represent regions on a map. The other set is a rather large set of point data that I prefer to represent with circle markers. I can add each dataset separately and they work as expected, but when I try to add the circle objects and the polygon objects to the same map, the polygon objects become unclickable for both click events and the popup. Is there a way around this issue?

**Comment by IvanSanchez** [comment] 2020-03-09 19:44
Same renderer, different renderer? Canvas or SVG?

Possible duplicate of https://github.com/Leaflet/Leaflet/issues/4135

**Comment by cscrum** [comment] 2020-03-09 19:52
Same renderer. I am using prefer canvas to speed up the point object dataset. If I create standard markers for the points instead of circle objects the polygons from the other layer are clickable.

**Comment by IvanSanchez** [comment] 2020-03-09 20:17
So like #5082 then?

I must ask you to provide a complete reproducible example, maybe some screenshots. It's still not clear to me what you mean.

**Comment by cscrum** [comment] 2020-03-09 20:48
OK. Keep in mind I am  using this with in Angular 8 using ngx-leaflet wrapper. This is in TS. Here are the two functions that create my markers and my polygons:

` searchText: any;
  mapModes = GlobalVars.mapModes;
  mapMode: string;
  mapClickmode: string;

  basemap = GlobalVars.basemap;
  sitesLayer = GlobalVars.sitesLayer;
  apsLayer = GlobalVars.apsLayer;
  leadsLayer = GlobalVars.leadsLayer;
  leadMarkers: any = [];
  activeMarkers: any = [];
  inactiveMarkers: any = [];
  activeSites: any = [];
  inactiveSites: any = [];
  proposedSites: any = [];
  apShapes: any = [];
  freqMarkers: any = [];
  
  apData = GlobalVars.apData;
  apLayer = new L.LayerGroup();
  aps = this.apData || this.getAPs();
  siteData = GlobalVars.siteData;
  sites = this.siteData || this.getSites();
  leadData = GlobalVars.leadData;
  leads = this.leadData || this.getLeads();
  
  
  

  mapZoom = GlobalVars.mapZoom || 10;
  mapCenter = GlobalVars.mapCenter || L.latLng({ lat: 33.65, lng: -96.65 });
  mapOptions = GlobalVars.mapOptions;

  currentLat:any;
  currentLon:any;

  map: L.Map;


  osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          detectRetina: true,
          attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        });

  layers = [this.osm];
  layersControl = {
    baseLayers: {
      'Street Map': this.osm
      
    },
    overlays: {
      
    }
  }


  options = {
    zoom: this.mapZoom,
    center: this.mapCenter,
    preferCanvas: true
  };
//function to create the circle markers
createLeadmapobj() {
    
    console.log("creating map objects");
   
    var lm = [];
    var self = this;
    var activeLayer = new L.LayerGroup();
    var leadLayer = new L.LayerGroup();
    var inactiveLayer = new L.LayerGroup();
    var cirrenderer = L.canvas({padding:0.5});
    
    
    this.leadData.forEach(function(leadobj){
      
      var popup = "";
      if (leadobj.company && leadobj.company != ""){
        popup += "<b>Company: " + leadobj.company + "</br>";
      }
      popup += "<b>Name: </b>" + leadobj.first + leadobj.last + "</br><b>Address: </b></br>" + leadobj.address + "</br>";
      if (leadobj.address2 && leadobj.address2 != ""){
        popup += leadobj.address2 + "</br>";
      }
      popup += leadobj.city + "," + leadobj.state + " " + leadobj.zip + "</br>";
      popup += "<b>Status: </b>" + leadobj.status;
      var lat = Number(leadobj.lat);
      var lon = Number(leadobj.lon);
          
      var marker;
      if (leadobj.status == "Active"){
       
        marker = L.circleMarker([lat,lon],{renderer: cirrenderer, fill: true,fillColor: '#00ff00',radius: 5,stroke:false, opacity:0.5}).bindPopup(popup);
        marker.addTo(activeLayer);
        self.activeMarkers.push(marker);
      }
      if (leadobj.status == "Inactive"){
        
        marker = L.circleMarker([lat,lon],{renderer: cirrenderer, fill: true,fillColor: '#ff0000',radius: 5,stroke:false, opacity:0.5}).bindPopup(popup);
        marker.addTo(inactiveLayer);
        self.inactiveMarkers.push(marker);
      }
      if (leadobj.status == "Lead"){
        
        marker = L.circleMarker([lat,lon],{renderer: cirrenderer, fill: true,fillColor: '#0000ff',radius: 5,stroke:false, opacity:0.5}).bindPopup(popup);
        marker.addTo(leadLayer);
        self.leadMarkers.push(marker);
      }

      
      
      
      self.layers.push(marker);
   
      
    })
    
    this.layersControl.overlays.Leads = leadLayer;
    this.layersControl.overlays.Active = activeLayer;
    this.layersControl.overlays.Inactive = inactiveLayer;
   
    return true;
    
  }

//function to create the polygons
createAPsmapobj() {
    
    console.log("creating AP map objects");

    var lm = [];
    var self = this;

    this.apData.forEach(function(apobj){
      
      //console.log("creating marker from "+ JSON.stringify(leadobj));
      var spopup = "";
      spopup += "<b>Name: </b>" + apobj.Name + "</br><b>Position: </b></br>" + apobj.Lat + ", "+ apobj.Lon + "</br>";
      spopup += "<b>Elevation: </b>" + apobj.Elevation+ "</br>";
      spopup += "<b>Azimuth: </b>" + apobj.Azimuth+ "</br>";
      spopup += "<b>Beamwidth: </b>" + apobj.Beamwidth+ "</br>";
      spopup += "<b>Type: </b>" + apobj.Frequency+ "</br>";
      spopup += "<b>IP: </b>" + apobj.ip_address;
      var lat = Number(apobj.Lat);
      var lon = Number(apobj.Lon);
      var shapellarr:any =self.apiService.sectorShapes(apobj,1,null);
       
        var poly = L.polygon(shapellarr, {color:apobj.color, fillColor: apobj.color, fill: true, stroke:false,opacity: 0.75});
        poly.bindPopup(spopup);
        poly.addTo(self.apLayer);
        self.apShapes.push(poly);
        self.layers.push(poly);

    })

    this.layersControl.overlays.APs = apLayer;
    return true;
  }`
This image is showing a click on one of the circle markers which works
![chrome_2020-03-09_15-21-21](https://user-images.githubusercontent.com/921155/76255903-fbb87e80-621c-11ea-819c-8a27a79a2e62.png)

This image is showing that when I move the mouse over the polygon nearby, it does not indicated that it is a clickable object on the map and clicking on it does not bring up the tool tip.
![chrome_2020-03-09_15-21-35](https://user-images.githubusercontent.com/921155/76256032-40441a00-621d-11ea-8de3-fba8f2f37b86.png)

This image shows that when I use regular markers instead of circle markers (only change made, map options all the same) then I can click on the polygon object and get the tool tip.

![chrome_2020-03-09_15-24-20](https://user-images.githubusercontent.com/921155/76256121-62d63300-621d-11ea-99a7-76829a38bb6e.png)


Is that more clear?

**Comment by IvanSanchez** [comment] 2020-03-09 21:20
Do you remember when I asked...

> Same renderer, different renderer?

And now that I see the code there's...

```
        marker = L.circleMarker([lat,lon],{renderer: cirrenderer, fill: true,fillColor: '#00ff00',radius: 5,stroke:false, opacity:0.5}).bindPopup(popup);
                                           ^^^^^^^^^^^^^^^^^^^^^
```

...so that means there's two `L.Canvas` renderers involved.

So closing as duplicate of #4135.

**Closed by IvanSanchez** 2020-03-09 21:20 UTC
Labels: needs more info
