### ISSUE TITLE
IE8 tile loading bug

### ISSUE THREAD

**Issue by Trufi** [Leaflet/Leaflet#3332] opened 2015-03-27 09:09 UTC
Can you look at leaflet (master branch) in IE8? Tiles sometimes freeze and stop loading after several drags and zooms. It looks like:

![screenshot from 2015-03-27 14 30 50](https://cloud.githubusercontent.com/assets/3996552/6864717/06798cc0-d487-11e4-8d7b-afa4916b6cdd.png)
Windows XP, Service Pack 3, IE8

**Comment by perliedman** [comment] 2015-03-27 12:07
I can reproduce this with latest master on IE8/Win7 (virtual machine from MS in Virtual Box) with the `/debug/map/map.html` example.

An interesting question is if Leaflet still aims to support IE8, which starts to get _really_ old, and it seems some libraries are dropping support for it.

I'll try to have a look, but given the state of IE8 debugger, I can't promise anything :)

**Comment by mourner** [comment] 2015-03-27 12:14
Yeah, Leaflet still has to support IE8 since A LOT of government/enterprise apps depend on this. Thanks for looking into this.

**Comment by perliedman** [comment] 2015-03-27 13:01
Follow up: I ran the test specs on IE8, and there are quite a few errors. Some of them appear in `GridLayer`, which I guess might be the issue we're seeing here.

**Comment by perliedman** [comment] 2015-03-30 06:31
So far, I've found out that the tiles load, but for some reason the `leaflet-tile-loaded` class is never applied to the element. I'll try to find some more time to dig into why.

As a side note, this issue can be debugged in IE11 if you set the debugger's document mode to IE8, which makes things a lot easier.

**Comment by RLRR** [comment] 2015-04-01 12:06
I think I've managed to pinpoint the bug, here is a possible solution: #3346

**Comment by mourner** [comment] 2015-04-02 14:04
@RLRR thanks a lot! Merged.

**Closed by mourner** 2015-04-02 14:04 UTC
Labels: major bug
