### ISSUE TITLE
Maps not loading anymore after half a year not touching website

### ISSUE THREAD

**Issue by MR444** [Leaflet/Leaflet#7187] opened 2020-06-27 17:47 UTC
Hi everyone,

I have a website (only private acces for friends) that includes leaflet script and worked quite well. After some months not touching it, I wanted to use the website but the map does not load anymore. Was there something changed in the script that needs to be adopted?

Is maybe the token valid only for limited time period? My mapbox account does not show any problems.

Checked with Firefox 77.0.1 (64-Bit), Google chrome 83.0.4103.116 and internet explorer.
Leaflet.css and leaflet.js still original.

```
<script>

	var mymap = L.map('mapid').setView([20, 5], 3);

	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
		attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
		maxZoom: 18,
		minZoom: 2,
		id: 'mapbox.streets',
		accessToken: '..............................................................'
	}).addTo(mymap);
/*Markers*/
makers deleted because they work correctly
;
		
		var cities = L.layerGroup([city1, city2, city3, city4]).addTo(mymap);
	
	</script>
```
![Leaflet-map not loading](https://user-images.githubusercontent.com/17322455/85928656-f1df8780-b8ae-11ea-996a-40968ba9b3f2.JPG)

**Comment by johnd0e** [comment] 2020-06-27 20:03
Duplicate of #7173.
See https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4

**Closed by johnd0e** 2020-06-27 20:03 UTC
