### ISSUE TITLE
Panes dont work with Clusters

### ISSUE THREAD

**Issue by treecon** [Leaflet/Leaflet#5511] opened 2017-05-14 14:14 UTC
https://jsfiddle.net/fcumj09w/5/

In the above example, we have 2 marker cluster groups (clustRed and clustYellow) and a single marker outside of these groups.

I want the red marker cluster group to be on top (higher z-index) of the yellow marker cluster group, when zooming out.

I have created 3 custom panes to attach each cluster group to a different pane but it seems like panes don't work with cluster groups.
I can only make panes work with the single marker.

**Comment by perliedman** [comment] 2017-05-15 06:35
Hi and thanks for reporting!

I believe this is more or less a duplicate of #4279: the markers and the clusters don't end up on the pane you specify since `pane` isn't "inherited" by a layer's sublayers.

I'm going to close this as duplicate for now. You _could_ also open an issue on the MarkerCluster plugin, it might be that there is actually something the plugin could or should do about this.

**Closed by perliedman** 2017-05-15 06:35 UTC

**Comment by ghybs** [comment] 2017-05-17 19:30
Actually already cross-posted on https://github.com/Leaflet/Leaflet.markercluster/issues/785
