### ISSUE TITLE
Events.js:180 listener not found with maxBounds

### ISSUE THREAD

**Issue by pouemes** [Leaflet/Leaflet#8216] opened 2022-05-05 20:02 UTC
hello
no problem with 1.71 version
but with leaflet 1.8.0
 in chrome console "listener not found" with maxBounds:[[-90,-180],[90,180]]

**Steps to reproduce**

in a test.html file

`<!doctype html><html lang="fr"><head><meta charset="utf-8"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"><style>#map{margin:auto;width:450px;height:450px}</style><script  src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"></script></head><body><div id="map"></div><script>var Url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}";
var map=L.map("map",{maxBounds:[[-90,-180],[90,180]]});L.tileLayer(Url,{attribution:"Powered by Esri | Esri, HERE, Garmin, USGS, NGA"}).addTo(map);map.setView([41.261,19.852],7);</script></body></html>`

in chrome console

Events.js:180 listener not found
  | _off | @ | Events.js:180
-- | -- | -- | --
  | off | @ | Events.js:89
  | setMaxBounds | @ | Map.js:453
  | initialize | @ | Map.js:145
  | i | @ | Class.js:24
  | t.map | @ | Map.js:1748
  | (anonyme) | @ | test.html:13

**Environment**
- Leaflet version: 1.80
- Browser (with version):chrome Version 101.0.4951.54 (Build officiel) (64 bits)
- OS/Platform (with version):window10x64

thanks for your help,

**Comment by IvanSanchez** [comment] 2022-05-05 20:37
Duplicate of https://github.com/Leaflet/Leaflet/issues/7951, already covered by https://github.com/Leaflet/Leaflet/pull/8168.

**Closed by IvanSanchez** 2022-05-05 20:37 UTC
