### ISSUE TITLE
Leaflet tms url bug zoom (decimal value ) on Angular2/Ionic 2 

### ISSUE THREAD

**Issue by FredO81** [Leaflet/Leaflet#4807] opened 2016-08-08 21:01 UTC
Hello, I am developping a WebApp with Leaflet on Angular2 and Ionic 2.

Tiles is not loaded because TMS (z,x,y) url is wrong like `http://tile.opentopomap.org/14.057642068624112/8637/6222.png`
instead of  `http://tile.opentopomap.org/14/8637/6222.png`

z is not an integer value !

Do you know this bug?

fred

**Comment by IvanSanchez** [comment] 2016-08-09 08:46
We only handle "vanilla javascript" bugs, not Angular bugs, not Ionic bugs, not Wordpress plugin bugs, 
not Yeoman bugs, not Polymer bugs, no Django bugs, no Meteor bugs, no Vue bugs.

Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by FredO81** [comment] 2016-08-09 11:48
Here is my Angular 2 MapService
`/// <reference path="../../typings/leaflet/leaflet.d.ts"/>
import {Injectable} from '@angular/core';
import {Http, Headers} from '@angular/http';
import 'Leaflet';

@Injectable()
export class MapService {

    public track;
    public baseMaps: any;

    constructor(private http: Http) {

        this.baseMaps = {
            Carte: new L.TileLayer("https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png", {
                maxZoom: 15,
                tms: true,
                attribution: ''
            }),
            Esri: new L.TileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}', {
            	attribution: ''
            })
        };

    }

    /**
     * Return map
     * @param lat
     * @param lng
    */
    getMap( lat, lng, zoom, minzoom, maxzoom) {
        
        var map = new L.Map('map', {
            center: new L.LatLng(lat,lng),
            zoom:zoom,
            minZoom: minzoom,
            maxZoom: maxzoom,
            scrollWheelZoom:false,
            tap:false,
            layers: [this.baseMaps.Carte]
        });

        L.control.layers(this.baseMaps).addTo(map);
        L.control.scale().addTo(map);
        
        return map;
    }
    
}`

Here is the code who is display map
`import {Component } from '@angular/core';
import {Platform,NavParams,NavController} from 'ionic-angular';
import {Http, Headers} from '@angular/http';
import {MapService} from '../../services/map';
@Component({
    templateUrl: 'build/pages/track/track.html',
    providers: [MapService ]
})

export class TrackPage {

    public map;

    constructor(
        platform: Platform,
        private http: Http,
        private Map: MapService, 
        private nav: NavController, 
        private navParams: NavParams
    ) {
            
    }

    
    // after load view
    ngAfterViewInit() {

        // hook for bug leaflet tile load
        var that = this;
        setTimeout(function(){that.initMap()}, 1000);

    }


    /**
     * Init the map
     */
    initMap(){

        // default map
        this.map = this.Map.getMap(42,2,14, 15, 15);

    }
    

//end
}`

**Comment by IvanSanchez** [comment] 2016-08-09 12:44
Closing due to not being reproducible on vanilla Leaflet.

**Closed by IvanSanchez** 2016-08-09 12:44 UTC
Labels: needs more info
