### ISSUE TITLE
Panning horizontally across the international date line does not reset longitude.

### ISSUE THREAD

**Issue by qhornblow** [Leaflet/Leaflet#7496] opened 2021-03-08 17:48 UTC
When panning across the international date line (IDL), i.e from the America to Australia, or vice versa the longitude defined by map.getBounds().getCenter().lng does not reset at 180/-180.

When panning from America to Australia the resulting longitude is -220 (expected value: +140); and
when panning from Australia to America the resulting longitude is +260 (expected value: -80).

This does not impact the rendering of tile layers but it does impact the rendering of Marker/GeoJson layers. Marker/GeoJson layers are only drawn in one location and not reproduced when panning across the IDL.

**Steps to reproduce**
- step 1
Initiate a map as per the quickstart example here: https://leafletjs.com/examples/quick-start/,
include a coordinate viewer:
        var coordViewer = L.Control.extend({
            onAdd: function (map) {
                var gauge = L.DomUtil.create('div');
                gauge.style.background = 'rgba(255,255,255,0.5)';
                gauge.style.textAlign = 'left';
                map.on('moveend', function (ev) {
                    gauge.innerHTML =
                        'Lat:' + map.getBounds().getCenter().lat.toFixed(3) + '<br>' +
                        'Lon:' + map.getBounds().getCenter().lng.toFixed(3);
                })
                return gauge;
            }
        });

        (new coordViewer).addTo(map);

 
- step 2
scroll 360 deg around the globe, you will observe that the longitude is nonsensical and that the Marker/GeoJson is not present either.

**Expected behavior**
longitude values would transition from -180/180 when panning across the IDL. Marker/GeoJson layers would reproduce when panning around the globe.

**Current behavior**
Longitude is continuous and Marker/GeoJson layers do not reproduce.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Firefox 86
- OS/Platform (with version):

**Minimal example reproducing the issue**
Example using https://leafletjs.com/edit.html: 

-------------------------------------------------------------------------------------------------------------------

<!DOCTYPE html>
<html>
<head>
	
	<title>Quick Start - Leaflet</title>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="shortcut icon" type="image/x-icon" href="docs/images/favicon.ico" />

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>

	
</head>
<body>

<div id="mapid" style="width: 100%; height: 100vw;"></div>
<script>

	var mymap = L.map('mapid').setView([51.505, -0.09], 4);

	L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
		maxZoom: 18,
		attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, ' +
			'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
		id: 'mapbox/streets-v11',
		tileSize: 512,
		zoomOffset: -1
	}).addTo(mymap);

	L.marker([51.5, -0.09]).addTo(mymap)
		.bindPopup("<b>Hello world!</b><br />I am a popup.").openPopup();

	L.circle([51.508, -0.11], 500, {
		color: 'red',
		fillColor: '#f03',
		fillOpacity: 0.5
	}).addTo(mymap).bindPopup("I am a circle.");

	L.polygon([
		[51.509, -0.08],
		[51.503, -0.06],
		[51.51, -0.047]
	]).addTo(mymap).bindPopup("I am a polygon.");

	var popup = L.popup();

	function onMapClick(e) {
		popup
			.setLatLng(e.latlng)
			.setContent("You clicked the map at " + e.latlng.toString())
			.openOn(mymap);
	}

	mymap.on('click', onMapClick);

	var coordViewer = L.Control.extend({
		onAdd: function (map) {
				var gauge = L.DomUtil.create('div');
				gauge.style.background = 'rgba(255,255,255,0.5)';
				gauge.style.textAlign = 'left';
				map.on('moveend', function (ev) {
						gauge.innerHTML =
								'Lat:' + map.getBounds().getCenter().lat.toFixed(3) + '<br>' +
								'Lon:' + map.getBounds().getCenter().lng.toFixed(3);
				})
				return gauge;
			}
	});

	(new coordViewer).addTo(mymap);

</script>

</body>
</html>

**Comment by johnd0e** [comment] 2021-03-08 18:47
Duplicate of #6506

**Closed by johnd0e** 2021-03-08 18:47 UTC
