### ISSUE TITLE
Leaflet Providing Invalid Lng/Lat Coordinates when location duplicates on display

### ISSUE THREAD

**Issue by QuestionDevelopment** [Leaflet/Leaflet#7588] opened 2021-05-30 21:39 UTC
**Steps to reproduce**
Setup a map that repeats.  Click on the repeating section, the click event will return invalid coordinates.

**Expected behavior**
The correct (repeated) coordinate would be provided for each GPS location, regardless if it repeats on the display.

**Current behavior**
It returns incorrect data

**Minimal example reproducing the issue**

https://www.hikerock.com/rock/210/

Click on map -> the console log will output what the gps coordinates are provided by leaflet.

The code is super simple, if you need to access it : 

https://www.hikerock.com/plugin/map/js/map.min.js?cache=6x3cWuxp

function map() => inits leaflet
map.prototype.selectorConfirm () -> is what is collects the event, is doing the console.logging

**Comment by IvanSanchez** [comment] 2021-05-31 02:38
Duplicate of https://github.com/Leaflet/Leaflet/issues/1885

**Closed by IvanSanchez** 2021-05-31 02:38 UTC
