### ISSUE TITLE
Circles are displayed as ovals

### ISSUE THREAD

**Issue by kkdd** [Leaflet/Leaflet#7551] opened 2021-04-12 12:17 UTC
Hello,
Circles are displayed as ovals:

![circles](https://user-images.githubusercontent.com/5372642/114392694-16091c80-9bd4-11eb-9f5f-a30590faa2d1.jpg)

```
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        html,
        body {
            height: 100%;
            padding: 0;
            margin: 0;
            height: 100%;
        }
        #map {
            position: absolute;
            height: 100%;
            width: 100%;
        }
    </style>
</head>
<body>
    <div id="map"></div>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.js"></script>
    <script>
        const map = L.map('map');
        L.control.scale().addTo(map);
        L.tileLayer('https://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}', {
            maxNativeZoom: 22,
            maxZoom: 30,
            subdomains: ['mt0', 'mt1', 'mt2', 'mt3']
        }).addTo(map);
        const len = 500, s = [44.049074, 0.015551], e = [44.049932, 0.014719];
        [...Array(len+1)].forEach((_, i) => {
            const point = [(s[0]*i+e[0]*(len-i))/len, (s[1]*i+e[1]*(len-i))/len];
            new L.circle(L.latLng(point), 0.1).addTo(map);	
        });
        map.fitBounds([s, e]);
        map.setZoom(25);
    </script>
</body>
</html>
```

**Comment by IvanSanchez** [comment] 2021-04-12 12:46
Duplicate of https://github.com/Leaflet/Leaflet/issues/6120

**Closed by IvanSanchez** 2021-04-12 12:46 UTC
