### ISSUE TITLE
Zoom side-effect in IE11 on touch

### ISSUE THREAD

**Issue by surkova** [Leaflet/Leaflet#3218] opened 2015-02-09 09:51 UTC
A member of our team has a laptop with touch support (Lenovo Yoga Pro 2, Windows 10 Technical preview, touch screen with 3200x1800 resolution) and he uses IE11 11.0.9800.0. He experiences a weird zoom bug that you can reproduce even on Leaflet's homepage (currently using version 0.7.3) on Overview Tab. When you try to zoom in / out in the map, it overflows the container and the overflow may take up to whole screen.

**Comment by mourner** [comment] 2015-02-09 15:42
Probably the same issue: #2788 cc @danzel

**Comment by danzel** [comment] 2015-02-09 21:07
Dumb :(

**Comment by danzel** [comment] 2015-02-09 21:08
Yeah dupe of #2788, will copy your details over @surkova thanks. Was hoping Microsoft would fix this.

**Closed** 2015-02-09 21:08 UTC
