### ISSUE TITLE
Unexpected behavior when repeatedly calling map.setZoom with the same zoom level

### ISSUE THREAD

**Issue by tomplex** [Leaflet/Leaflet#7019] opened 2020-03-11 21:20 UTC
**Steps to reproduce**
- go to [this JS Fiddle](https://jsfiddle.net/8x74nwur/) with an example of the issue
- hit the button three times
- the first time, the map zooms to the specified zoom level
- the second time, it zooms to the feature's bounds
- the third time, it zooms back out to the specified zoom level
- the pattern continues each time the button is pressed.

**Expected behavior**
I expect that calling map.setZoom repeatedly with the same argument will result in no change if the zoom is already at that value

**Current behavior**
The map is zooming back and forth between the desired zoom level and the bounds of the feature

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): Firefox 72.0.2
- OS/Platform (with version): MacOS 10.14.6

**Additional context**
I also noted this behavior if you replace lines 12 & 13 with this:

```javascript
map.fitBounds(circle.getBounds());
map.fitBounds(circle.getBounds(), {maxZoom: 14});
```

**Comment by johnd0e** [comment] 2020-03-12 11:07
0. Current zoom level is 14.
1. `map.fitBounds` initiates deferred zoom change to 15:
   <details>

   `map.fitBounds` ➜ `setView` ➜ `_tryAnimatedZoom`: https://github.com/Leaflet/Leaflet/blob/e213469a296ea00e6f9e6e6beb49d081e8d1c4fe/src/map/Map.js#L1664-L1668
   </details>

2. But then `map.setZoom(14)` is executed synchronously, and do nothing, as current zoom is already 14, and there is no clues that zoom level is about to change.
3. On next anim frame zoom level changes to 15.

**Comment by tomplex** [comment] 2020-03-12 13:27
Hey @johnd0e,

Thanks for clarifying! I added a `.then` to my `fitBounds` call and it works as expected now. 

Many thanks for your time.

**Comment by johnd0e** [comment] 2020-03-12 13:29
I still tend to think that this is leaflet flaw

**Comment by tomplex** [comment] 2020-03-12 13:31
I'll admit it would be nice if it was mentioned in the docs for [`fitBounds`](https://leafletjs.com/reference-1.6.0.html#map-fitbounds).

**Comment by tomplex** [comment] 2020-03-12 13:39
Sorry, it's still early here and I'm realizing that `.then` did not actually solve my issue, because it doesn't return a promise - I just saw the map not toggle back and forth and thought oh hey, it's fixed. 

Time to go get some coffee.

**Comment by johnd0e** [comment] 2020-03-13 15:40
Workaround: use option [`{animate:false}`](https://leafletjs.com/reference-1.6.0.html#zoom/pan-options-animate).

```js
        map.fitBounds(circle.getBounds(), {animate:false});
        map.setZoom(14, {animate:false});
```

Note that you need to disable animation for both command, otherwise you will get funny effect.

**Comment by tomplex** [comment] 2020-03-13 22:03
I also found that I could use the [`maxZoom` option](https://leafletjs.com/reference-1.6.0.html#fitbounds-options) in `fitBounds`, and avoid explicitly calling `setZoom`:

```javascript
map.fitBounds(circle.getBounds(), {maxZoom: 14});
```

This can be called over and over and the effect is stable.

**Comment by johnd0e** [comment] 2020-03-18 14:01
Duplicate of #3249

**Closed by johnd0e** 2020-03-18 14:01 UTC
