### ISSUE TITLE
Event handlers not cleared up when clearing a layergroup

### ISSUE THREAD

**Issue by LuSilf** [Leaflet/Leaflet#4840] opened 2016-08-24 14:04 UTC
1) http://playground-leaflet.rhcloud.com/gog/1/edit?html,console,output
2) Drag a map few times.
3) Open console.
4) Execution time increases almost each time you drag a map.

Reproducible in rc3.
Appears after this commit: https://github.com/Leaflet/Leaflet/commit/8047b0b7a99ab1bed75bab7cca9c1c3a0601da87

**Comment by IvanSanchez** [comment] 2016-08-25 08:08
@yohanboniface Some event listeners are not being cleared up properly after that commit. Under the circumstances of the reproducible example provided by @LuSilf, they create both a memory leak and a slowdown (by being fired again?) somehow.

**Comment by perliedman** [comment] 2016-08-25 12:49
So, the culprit is this line: https://github.com/Leaflet/Leaflet/commit/8047b0b7a99ab1bed75bab7cca9c1c3a0601da87#diff-0e79846ee2c407aa1ac0ccbfd8b15a44R168

We copy the listeners to a new array, but never actually _assign_ that copy to the `_events` array. Instead, we never clear up listeners, but it still works since all the listeners are assigned to the `falseFn`. It only shows up if you have _a lot_ of listeners. So... good catch, @LuSilf!

I'll try to make a fix shortly.

**Comment by yohanboniface** [comment] 2016-08-25 12:51
And good investigation @perliedman :)

**Comment by perliedman** [comment] 2016-08-25 12:55
@yohanboniface thanks :smile: Trying to figure out how to test this without digging into the internals...

**Closed** 2016-08-25 13:28 UTC
Labels: bug, needs investigation
