### ISSUE TITLE
1.0 incompatible with dat.gui while 0.7 work well

### ISSUE THREAD

**Issue by supyoung** [Leaflet/Leaflet#5193] opened 2016-12-15 08:34 UTC
## What behaviour I'm expecting and which behaviour I'm seeing
In version 1.0, the dat.gui panel would appear at first, but then it seems would be covered by some Layer 
Even setting the 9999 z-index, it still can't appear.
In version 0.7, it just fine.

## Minimal example reproducing the issue
https://gist.github.com/anonymous/9ed1e4b8864b08b1176a8b771bef5ad5
https://gist.github.com/anonymous/53f59a76718f8390146affa92aef8821

**Comment by IvanSanchez** [comment] 2016-12-15 08:41
This is a duplicate of #3690 - even if the library is a different one, the cause is the same: the map container not creating its own stacking context.

**Closed by IvanSanchez** 2016-12-15 08:41 UTC

**Comment by supyoung** [comment] 2016-12-15 10:18
impressive! just set  
 .leaflet-container {
    isolation: isolate;
 }
