### ISSUE TITLE
"invalid name of certificate" from cdn.leafletjs.com

### ISSUE THREAD

**Issue by mikemcc** [Leaflet/Leaflet#7287] opened 2020-09-23 15:44 UTC
see attached screen shot

![image](https://user-images.githubusercontent.com/528841/94036242-552f6780-fd81-11ea-8cd7-a722dfc494fc.png)

**Comment by IvanSanchez** [comment] 2020-09-23 22:16
Closing as duplicate of #7165.

**Closed by IvanSanchez** 2020-09-23 22:16 UTC
