### ISSUE TITLE
Edge Browser (Windows 10) touch drag fails

### ISSUE THREAD

**Issue by jaybo** [Leaflet/Leaflet#3674] opened 2015-07-26 23:58 UTC
Using http://leafletjs.com/examples/mobile-example.html on Win10 RTM Edge browser V20.10240 I find that touch drag of the map is not functional.  The same site works fine using the Windows 10 RTM Internet Explorer browser.

This problem happens with both leaflet V0.7.3 as well as the 1.0 beta 1 master branch.

It appears the same problem affects the Windows Phone Windows 10 Edge browser.

I've verified this problem also on my personal site, www.deepzoom.com as well as delorme.com and presumably all other leaflet sites.

Ouch.

**Comment by mourner** [comment] 2015-07-27 06:30
Eh, Microsoft is so fun as always...

**Comment by mourner** [comment] 2015-07-27 11:16
@csuwildcat according to the report above, there seems to be an issue with touch events in Edge for Leaflet (works in Win8 and all other modern mobile platforms and browsers). Any clues?

cc @danzel do you have access to Edge? Wanna take a look? Shouldn't be a hard fix probably.

**Comment by danzel** [comment] 2015-07-27 12:18
@jacobtoye and @kerryarts have win10 on their pcs afaik, hopefully one of them can take a look.
Hopefully there is an emulate touch events option in the dev tools, otherwise device emulator should let you do it.

**Comment by jaybo** [comment] 2015-07-27 15:50
Possibly user agent?

        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by mourner** [comment] 2015-07-27 16:45
@jaybo unlikely since user agent-derived checks are not used in any touch-related code in Leaflet...

**Comment by IvanSanchez** [comment] 2015-07-28 17:35
Apparently Microsoft decided to change the touch events API **again**:

https://msdn.microsoft.com/en-us/library/dn304886%28v=vs.85%29.aspx

I *guess* that proper detection of `L.Browser.msPointer` should fix the problem.

**Comment by IvanSanchez** [comment] 2015-07-28 17:40
@jaybo Can you please check out the value of `L.Browser.msPointer` in your Edge dev console?

**Comment by mourner** [comment] 2015-07-28 17:45
Keeping open until we confirmed that it's fixed. @jaybo can you check the latest master?

**Comment by csuwildcat** [comment] 2015-07-28 18:12
@IvanSanchez to be fair, and provide clarity: Microsoft and the other Pointer Events spec contributors changed the spec at the late request of another browser vendor who wanted to adopt Pointer Events as a standard, after a few modifications.

**Comment by csuwildcat** [comment] 2015-07-28 18:13
@IvanSanchez I know this because I was at Mozilla when Pointer Events was created ;)

**Comment by mourner** [comment] 2015-07-28 20:15
@csuwildcat cool, thanks for the clarification! Personally I'm excited about such a solid touch spec coming up and agreed upon by browser vendors :)

**Comment by jaybo** [comment] 2015-07-28 21:37
@mourner @csuwildcat @IvanSanchez Fix confirmed.  Tested on Win10 Edge, IE, and Chrome.  Drag OK.  Tap OK.

Aside:  Touch pinch and zoom often doesn't repaint all tiles in Edge, IE, and Chrome.  Is this presumably separate bug already being tracked?

**Comment by IvanSanchez** [comment] 2015-07-28 21:54
@jaybo Yeah, that's a different bug which is not browser-specific.

Thanks for testing the fix!

**Comment by jplante** [comment] 2015-08-04 19:28
I see that this fix has been applied to the master branch, however, this faulty behavior is also exhibited in the Leaflet home page map using the Edge browser, which I assume uses 0.7.3.  Is there a plan to integrate a fix for Edge browsers in the current "stable" release of Leaflet.

**Comment by IvanSanchez** [comment] 2015-08-04 19:33
@mourner Is this worth a backport? Should be easy enough.

**Comment by danzel** [comment] 2015-08-04 19:47
I think this is one worth a backport. Don't want a bad experience on a
browser we want people to upgrade to.

**Comment by IvanSanchez** [comment] 2015-08-04 19:59
@danzel OK, #3710 should do it.

**Closed** 2015-08-05 12:18 UTC
Labels: blocker, bug
