### ISSUE TITLE
[CSS] leaflet.css doesn't pass W3C validation

### ISSUE THREAD

**Issue by Stemby** [Leaflet/Leaflet#4182] opened 2016-01-29 18:07 UTC
Currently there are 10 errors:

http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fcdn.leafletjs.com%2Fleaflet%2Fv0.7.7%2Fleaflet.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=it

Best regards,
Carlo

**Comment by IvanSanchez** [comment] 2016-01-29 18:11
Those are needed for proper behaviour in IE7/IE8. Duplicate of #4162.

**Closed by IvanSanchez** 2016-01-29 18:11 UTC

**Comment by hyperknot** [comment] 2016-01-29 18:43
Also, in other validators, like http://codebeautify.org/cssvalidate there are no errors, only warnings.
