### ISSUE TITLE
Problem with zipCode brasil 69049-630

### ISSUE THREAD

**Issue by marceloagil** [Leaflet/Leaflet#6925] opened 2019-12-01 14:11 UTC
**When I search in map a zipCode 69049-630, it throws this result:**
(This is close to Italy)
![image](https://user-images.githubusercontent.com/17890658/69915195-2b403980-142b-11ea-8734-b64df614e5e0.png)

**But the real result should be Manaus, Brasil:**
![image](https://user-images.githubusercontent.com/17890658/69915200-372bfb80-142b-11ea-87a9-aa2030c2b51d.png)

How to solve this?

**Comment by IvanSanchez** [comment] 2019-12-01 16:43
Duplicate of #3896, #4661, #4332, #4819, #5056, #6284.

**Closed by IvanSanchez** 2019-12-01 16:43 UTC
