### ISSUE TITLE
feature:  dark mode 

### ISSUE THREAD

**Issue by Subrat29** [Leaflet/Leaflet#9115] opened 2023-10-05 20:33 UTC
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

dark mode is very important for all websites

### Suggested solution

Hello @michael @kshepard @palewire @grossbart @klaftertief ,

I want to add dark mode in leaflet.
I'd like to work on this issue. Could you please assign it to me?

Thank you,
Subrat

**Comment by Falke-Design** [comment] 2023-10-06 16:29
Duplicate of #7577 and PR is also already existing #7612

**Closed by Falke-Design** 2023-10-06 16:29 UTC
Labels: feature, needs triage
