### ISSUE TITLE
Paths off screen are not updated when moved into screen

### ISSUE THREAD

**Issue by yohanboniface** [Leaflet/Leaflet#3836] opened 2015-09-12 04:25 UTC
![polygon-bug](https://cloud.githubusercontent.com/assets/146023/9829838/acbbc5e4-5916-11e5-9133-a59ac58dace6.gif)

According to `git bisect`, the guilty commit is 61c07bd3e3d9a5a2bb4855ba81e1f368cc80090b

And indeed when I revert it it works back as expected. Swimming pool time, but I'll try to have a shot at investigating today. :)

**Comment by mourner** [comment] 2015-09-19 01:13
Nope, vectors are still pretty much broken in master :( cc @IvanSanchez

**Comment by IvanSanchez** [comment] 2015-09-19 07:38
Yeah, looks like a problem related to the order the events are being registered and fired. I think `Renderer._draw` is being called *before* `Renderer._update` somehow. Need to check later.

**Comment by yohanboniface** [comment] 2015-09-19 08:23
> Nope, vectors are still pretty much broken in master :(

Can you be a bit more specific? Seems to work for me **on branch rendered-update**.

**Comment by IvanSanchez** [comment] 2015-09-19 08:45
@yohanboniface In current `master`, canvas layers disappear when panning, and SVG vectors use the bbox from the last map pan when panning several times in sequence.

**Comment by yohanboniface** [comment] 2015-09-19 08:45
But `rendered-update` branch is supposed to fix that I think.

**Comment by yohanboniface** [comment] 2015-09-19 08:58
Well, included in `canvas-redrawbounds` actually now.

**Comment by IvanSanchez** [comment] 2015-09-19 10:06
@yohanboniface Is there a PR for those branches?

**Comment by yohanboniface** [comment] 2015-09-19 10:07
#3840 :)

**Comment by IvanSanchez** [comment] 2015-09-19 13:23
@yohanboniface So is this bug reproducible when using `canvas-redrawbounds`? :-)

**Comment by yohanboniface** [comment] 2015-09-19 13:24
> So is this bug reproducible when using canvas-redrawbounds? :-)

Nope

**Comment by mourner** [comment] 2015-09-19 15:07
Right, I remember now! It was a part of a bigger PR which I wanted to merge but it has problems, so merged just this fix instead.

**Closed** 2015-09-19 15:06 UTC
Labels: in progress
