### ISSUE TITLE
Interactivity bug with Firefox

### ISSUE THREAD

**Issue by svetlins** [Leaflet/Leaflet#6345] opened 2018-09-23 10:14 UTC
Polygons stop being clickable after the map viewport has been changed.

## How to reproduce

- Leaflet version I'm using: 1.3.4
- Browser (with version) I'm using: Firefox 62.0.2 
- OS/Platform (with version) I'm using: MacOS High Siera 10.13.3

- Add a polygon to a map with a bound popup.
- The polygon is clickable
- Move the map in any way
- The polygon is no longer visible (clickable only on any overlapping area with the original position)

## What behaviour I'm expecting and which behaviour I'm seeing

I'm expecting the polygon to remain clickable but it's only clickable if the map is in the position it was at the time of adding the polygon. This only happens on Firefox (with indicated version above and several newer betas)

## Minimal example reproducing the issue
Here are JSFiddle and Plunker links showcasing the issue:
http://jsfiddle.net/z6gsnvw3/6/
https://next.plnkr.co/edit/KM3QjD8vm1KqrY8E?preview

I'm pretty sure this is a bug of Firefox and I feel it might be related to: 
https://github.com/Leaflet/Leaflet/issues/997 and https://bugzilla.mozilla.org/show_bug.cgi?id=759993 becase setting `window.L_DISABLE_3D` fixes the issue - I'd be happy to try to submit a Firefox bug if anybody can confirm this suspicion or provide pointers.

**Comment by nrenner** [comment] 2018-09-24 16:08
Duplicate of #5773

**Closed** 2018-09-25 04:57 UTC
