### ISSUE TITLE
Leaflet- How to show states/cities with Latin Alphabet?

### ISSUE THREAD

**Issue by cranberriess89** [Leaflet/Leaflet#5096] opened 2016-11-13 14:52 UTC
Hi,
With default settings, leaflet shows only the local names of states and cities. It is not convenient for the end user who does not know the Russian alphabet, or Arabian alphabet.. Is it possible to show the names with Latin alphabet ? As another solution way, is is possible to show the places with English names ? Could you please provide if there is any setting for the statements written above ?

Thanks & Best Regards,
Crenaberries89

**Comment by IvanSanchez** [comment] 2016-11-13 18:33
Duplicate of https://github.com/Leaflet/Leaflet/issues/4661 https://github.com/Leaflet/Leaflet/issues/4332 *et al*.

**Closed by IvanSanchez** 2016-11-13 18:33 UTC
