### ISSUE TITLE
Text in popups not selectable in Leaflet 0.7.4 and .5 in IE10

### ISSUE THREAD

**Issue by alexgleith** [Leaflet/Leaflet#3804] opened 2015-09-03 21:12 UTC
I'm sorry, I haven't got a reproducible case yet, but I'll add it soon.

The issue occurred when I upgraded an internal app from Leaflet 0.7.3 to 0.7.4, where selecting text wouldn't work. I tried upgrading again to 0.7.5, but that failed too. Downgrading back to 0.7.3 fixed the issue.

**Comment by IvanSanchez** [comment] 2015-09-03 21:26
IE8, IE9, IE10, IE11, or all of the above?

**Comment by alexgleith** [comment] 2015-09-06 12:46
IE10 is all I've tested.

**Comment by IvanSanchez** [comment] 2015-09-06 12:55
Weird. I've just had a look at the code, and cannot see any changes from 0.7.3 to 0.7.5 that might affect text selection. I'm puzzled :-/

There's something you can try: use the non-minified files, and set a couple of breakpoints around [L.DomUtil.disabletextselection](https://github.com/Leaflet/Leaflet/blob/stable/src/dom/DomUtil.js#L250) to see if it's being called from somewhere else.

**Comment by alexgleith** [comment] 2015-09-07 04:08
Ok, so I can reproduce on the quick-start example: http://leafletjs.com/examples/quick-start-example.html

Using IE 10.0.9 and standards mode.

![image](https://cloud.githubusercontent.com/assets/3445853/9709167/b49727f0-5569-11e5-981b-320a328c288c.png)

**Comment by IvanSanchez** [comment] 2015-09-07 12:16
Amazingly enough, the bug is reproducible in IE10 but *not* in IE9 nor IE11. (Tested with IE11 emulating IE9/IE10)

**Comment by mourner** [comment] 2015-09-07 12:21
What does the `git blame` say?

**Comment by IvanSanchez** [comment] 2015-09-07 12:22
@mourner Nothing - but `L.Browser.touch` are different in IE10 between 0.7.3 and 0.7.5, because of https://github.com/Leaflet/Leaflet/pull/3520

**Comment by IvanSanchez** [comment] 2015-09-07 12:45
So apparently, as now IE10 registers as touch-capable (good), it fires a `MSPointerDown` event when dragging the map (good) but it doesn't fire a `MSPointerUp` event (or Leaflet is not catching it somehow) (vary bad).

Clicking on a marker registers as a zero-pixel drag, which also runs disableTextSelection() et cetera.

@alexgleith I guess you could work around the issue by forcing `L.Browser.msPointer = false` and `L.Browser.touch = false` ?

**Comment by danzel** [comment] 2015-09-08 01:21
In our software we put an element above a leaflet map.

On all browsers except IE10 we can add ```mousedown: cancelBubble``` to the element to stop mouse movement falling through to the map.
In IE10 we have to add a ```MSPointerDown: cancelBubble``` listener as well. otherwise all mouse events fall through and drag the map instead of selecting text in the element.
We are running leaflet master, but this has the same code change AFAIK.

Hope that helps.

**Comment by IvanSanchez** [comment] 2015-09-08 07:15
> In IE10 we have to add a MSPointerDown: cancelBubble listener as well. otherwise all mouse events fall through and drag the map instead of selecting text in the element.

So it looks like we know what kind of ugly hack we need to do for IE10 in `L.Popup`. I'll let this one up for grabs.

**Comment by danzel** [comment] 2015-09-13 23:38
I think we might have broken something more than we thought in IE10.
If you try listen to ```mousedown``` or ```mouseup``` on the map, they aren't fired when expected.

These still work fine in other browsers.

**Comment by danzel** [comment] 2015-09-13 23:46
Okay, mouseup/down broken since #3684

**Comment by danzel** [comment] 2015-09-13 23:51
I think we need to add ``` && navigator.msMaxTouchPoints``` back in... I might just be hacking around the problem though.

**Comment by danzel** [comment] 2015-09-14 00:07
If we remove the preventDefault in the pointer event remapping it means we get mousedown/up events too.
https://github.com/danzel/Leaflet/commit/67cef751736ad4439870913fda0729d8648dd84e

I think this might be what we should do maybe?

**Comment by danzel** [comment] 2015-09-14 01:23
OK, PR sent in #3839

**Comment by bodaniel** [comment] 2015-09-24 07:56
I start by saying that I am sorry if I am misusing this thread. But to me it seems like the text in the popup is still not selectable. I am testing using IE11 and Edge on Windows 10. NOTE: I am using branch stable when testing. I guess branch stable is where the fixes have been made? I can see other improvements regarding Edge though. Touch zoom and touch pan works in Edge. I compare between 0.7.5 and stable.

**Comment by IvanSanchez** [comment] 2015-09-24 08:07
@bodaniel You're in the right place. Everything should work in `stable` (which is maybe 5 commits ahead of `0.7.5`).

#3839 should have fixed selection in IE10 (so it doesn't work on `0.7.5` but should work OK on `stable`). Can you elaborate a bit on what happens in IE11/Edge? Did it work OK in `0.7.5` but is failing on `stable`, or something else?

**Comment by bodaniel** [comment] 2015-09-24 08:47
@IvanSanchez I am testing on a Windows 10 pc. A pc with a touch screen. I am using IE11 and Edge. I cannot select the text in the popup on any of those browsers. I cannot select text using the mouse or by touching the screen. A map pan is triggered instead of text being selected. None of 0.7.5/stable works.

I have tried to switch to IE10 (in IE11 developer tools) but I still cannot select text. If I switch to IE9 I can select text, but then touch events seems to be completely turned off.

**Comment by danzel** [comment] 2015-09-24 20:36
Dumb ok :(

**Comment by danzel** [comment] 2015-09-24 23:30
On IE11 on Windows 8.1 everything works fine on latest stable and master branch.
I'm using the map-mobile debug example.

I'm using a mouse, but I have a touch screen.
You cannot select text with a finger.

I don't think we have a touch device on windows 10 here to test.

**Comment by mourner** [comment] 2016-09-27 14:17
Closing because we just released 1.0 and minor issues in 0.7.x are unlikely to be fixed. Let's reopen if the issue is still relevant in 1.0.

**Closed by mourner** 2016-09-27 14:17 UTC
Labels: 0.7.x, bug, help wanted
