### ISSUE TITLE
Dragging issue with ionic2

### ISSUE THREAD

**Issue by kaynz** [Leaflet/Leaflet#4588] opened 2016-05-20 20:25 UTC
Hey guys,

I just set up a clean ionic2 beta7 TypeScript project and added leaflet (latest master + rc1) but got some really strange issues while dragging.

I captured my screen: https://paste.xinu.at/KISMRj/

(old: https://paste.xinu.at/YRO9/ )

And here's the code: https://paste.xinu.at/MQm2gI/js

I'm not sure if its a leaflet or ionic2 issue =/

**Comment by IvanSanchez** [comment] 2016-05-20 20:33
Hi,

Unfortunately this is not enough for a proper bug report - "really strange issue" doesn't describe the problem, I don't see anything weird in your screencap, and unless we can reproduce the bug *outside an ionic project*, we won't be able to diagnose and fix it.

**Comment by kaynz** [comment] 2016-05-20 20:35
Hello Ivan,

for example seconds 16 to seconds 20. You can see that the screen is being reverted to where the drag started. I didnt release the mouse.

**Comment by IvanSanchez** [comment] 2016-05-20 20:43
What's a ***reproducible*** *exact sequence of actions* that triggers such a behaviour? Are you moving the pointer outside of the map area? Are all mouse events being correctly propagated through ionic into leaflet?

**Comment by kaynz** [comment] 2016-05-20 20:55
The flickering is caused while moving and holding the pointer (_dragging_). The repositioning is caused right after I release the pointer (_dragend_).

This does not happen at the first drag. It can be reproduced at 2nd (sometimes 3rd) drag.

The issue has nothing to do with the border of the map area. I can reproduce it staying in the map area.

How can I check your last point?

**Comment by jordane51** [comment] 2016-05-23 10:35
I'm having the same problem, the only thing i can add is that the issue doesn't happen using leaflet 0.7.7.

**Comment by perliedman** [comment] 2016-05-23 12:37
To narrow this down, you need to illustrate that this is reproducible in a browser just using Leaflet.

If it's not reproducible, the problem is with Ionic, or whatever you need to integrate Leaflet into Ionic, which is outside the scope of the Leaflet project. If it _is_ reproducible in a browser with just Leaflet, it's a bug we can work with.

**Comment by jwoyame** [comment] 2016-05-23 15:09
From Ionic's doc on their custom tap system:

"In some cases, third-party libraries may also be working with touch events which can interfere with the tap system. For example, mapping libraries like Google or Leaflet Maps often implement a touch detection system which conflicts with Ionic’s tap system."
http://ionicframework.com/docs/api/page/tap/

**Comment by IvanSanchez** [comment] 2016-05-23 15:13
Wait, is this the old ["disable the `L.Map.Tap` handler when using a touch UI library"](https://github.com/Leaflet/Leaflet/issues/3184#issuecomment-130820995) bug all over again?

**Comment by jwoyame** [comment] 2016-05-23 15:40
I see you added the `data-tap-disabled="true"` attribute, but even with this setting, other developers have still encountered Ionic-related click event problems ([here](https://forum.ionicframework.com/t/tap-event-with-google-maps-api-not-received/13245) and [here](https://github.com/driftyco/ionic/issues/4506) for example). Try 0.7.7 as @jordane51 mentioned and let us know. If you can get your page onto the Web I can take a look, and maybe there is something to that can be improved on the Leaflet side to prevent this class of compatibility issues. But as others have stated you will probably find more success asking Ionic people at https://forum.ionicframework.com/.

**Comment by kaynz** [comment] 2016-05-23 16:16
Thanks, I will provide you ASAP (~24h) with informations and edit this post.

**Comment by jordane51** [comment] 2016-05-24 15:00
@jwoyame @kaynz I've uploaded an example [here](http://jord.fr/tmp/0524/). What's weird is that if i scroll slowly it works fine. Setting  `tap: false` didn't work for me either.

**Comment by jwoyame** [comment] 2016-05-24 22:46
Thanks @jordane51. With your example I was able to figure out what is happening.

The map's move animation (in `L.PosAnimation`) uses the browser's `window.requestAnimationFrame` function. When the animation is finished, it calls `window.cancelAnimationFrame`. I noticed that even after calling `cancelAnimationFrame`, the map's animation never stops playing. Leaflet has a protection so that the animation always stops at the desired endpoint. So what's happening is, as you drag, the prior animation is still ongoing, and it keeps resetting you back to where that animation was supposed to end.

Reason:
Angular uses a library called zone.js that overrides the browser's `requestAnimationFrame` and `cancelAnimationFrame` functions. The problem is, their implementation of `cancelAnimationFrame` is broken! This is a known bug with Angular/zone.js: https://github.com/angular/zone.js/issues/326

Your options:

1. Disable animation for now using the [`animate` option](http://leafletjs.com/reference.html#map-animate).

2. Fix zone.js yourself. I'm surprised this very serious bug has not been addressed yet. You can try to get this escalated with them.

**Comment by kaynz** [comment] 2016-05-25 05:49
@jwoyame Thanks! :)

**Comment by perliedman** [comment] 2016-05-25 06:42
Given this is the result of a broken implementation of `requestAnimationFrame`/´cancelAnimationFrame`, I'm closing this.

**Closed by perliedman** 2016-05-25 06:42 UTC
Labels: needs more info

**Comment by IvanSanchez** [comment] 2016-05-25 07:13
@jwoyame Wow, thanks for the detailed analysis!!

**Comment by jwoyame** [comment] 2016-05-25 10:31
Thank @tom5760 for the fix! I just learned yesterday that zone.js existed, I didn't feel comfortable fixing it myself.

**Comment by tom5760** [comment] 2016-05-25 13:04
No problem @jwoyame, I'm not very familiar with zone.js, but I just implemented the fix you suggested!  After testing it, it seems to have fixed the same issue I was having (Leaflet in Angular 2).

**Comment by jordane51** [comment] 2016-05-25 13:09
Your fix did work here too, thanks!
