### ISSUE TITLE
Incorrect latlng returned by getlatlng() function after zoom or pan

### ISSUE THREAD

**Issue by christianpeg** [Leaflet/Leaflet#7546] opened 2021-04-09 00:33 UTC
I have a weird issue about getlatlng() function using any drawing tool like rectangle, polygon etc. My mapping server is cartodb hosted in my dedicated server. To demonstrate the issue, i have group of markers located in the US country and have several markers in Australia. The drawing tool is returning the correct location of the drawn polygon in the US country. This is working perfectly. So the problem now is that whenever i pan or zoom to other area like in Australia and use the drawing tool, the returned latlng of the drawn polygon is already incorrect. It seems that the panning/zooming is causing the layers of the based map and the layer of the polygon to stop synching causing the polygon to not recognize the correct latlng of the based map.

To demonstrate this issue please check first link. This is where i initial the center to australia. This is returning the correct lat lng and can select the marker. 

https://www.screencast.com/t/Av5nErng7RPm

You will notice the center is initially located in australia. I selected a marker and the drawing tool is returning the correct latlng and can select the marker perfectly. I also show the console to show the correct lat ang lng returned by the polygon.

The second link to shows the issue. Initially the center is located in the US country. I will pan the map in australia and select the same marker. You will notice that the drawing tool is no longer selecting the marker because the returned latlng is already incorrect. Please check the value of the lat and lat. It is different from the first test.

https://www.screencast.com/t/dXpxEpXmWh

**Comment by IvanSanchez** [comment] 2021-04-09 00:52
Duplicate of https://github.com/Leaflet/Leaflet/issues/6772

**Closed by IvanSanchez** 2021-04-09 00:52 UTC

**Comment by christianpeg** [comment] 2021-04-09 01:10
how to use the wrapLatLng? sorry any sample code? thanks
