### ISSUE TITLE
L.Control.Layers {collapse: false} - collapses control on mouseout event

### ISSUE THREAD

**Issue by JoHae** [Leaflet/Leaflet#5210] opened 2016-12-22 01:28 UTC
I'm using leaflet v1.0.2.
If i set the control Option "collapsed: false", the control is collapsed at first.
But a mouseout event removes the necessary "leaflet-control-layers-expanded" class from the control div.
A change of `L.Control.Layers` `collapse` function to: 

```
if(this.options.collapsed) {
  L.DomUtil.removeClass(this._container, 'leaflet-control-layers-expanded');
}
```

fixed this issue for me.

**Comment by IvanSanchez** [comment] 2016-12-22 09:10
This is a duplicate of https://github.com/Leaflet/Leaflet/issues/5126 , which has already been fixed in `master`.

**Closed by IvanSanchez** 2016-12-22 09:10 UTC
