### ISSUE TITLE
Flickering map on Firefox 35

### ISSUE THREAD

**Issue by klimashkin** [Leaflet/Leaflet#3133] opened 2015-01-13 17:21 UTC
**summary by @mourner**: 

- in FF 35 (stable) under OS X, panning to the left or up in any Leaflet map causes **severe flickering**
- caused by **tiled Rendering in OS X** mentioned in FF release notes
- it affects thousands of people and there is **no known workaround** yet

**original report by @klimashkin**:
Tiles is flickering when map moves.
Leaflet 0.7.3, OS X 10.10.1

**Comment by snkashis** [comment] 2015-01-13 17:45
Confirmed. I get black bars near the edges of my viewport after zooms & some drags. OSX 10.9.5

**Comment by klimashkin** [comment] 2015-01-13 17:58
Perhaps it is affected by two changes:
* Improved handling of dynamic styling changes to increase responsiveness
* On the OS X tiled rendering mode is enabled

**Comment by mourner** [comment] 2015-01-13 18:06
I hate when things like this happen. Very frustrating, and I don't know how to approach this...

**Comment by mourner** [comment] 2015-01-13 18:23
Does this only affect OS X?

**Comment by mourner** [comment] 2015-01-13 18:26
A more specific way to reproduce: on a map, pan left or up. Apparently FF tries to be to smart optimizing things outside of the element's formal bounding box, and breaks Leaflet horribly. This is ridiculous.

**Comment by mourner** [comment] 2015-01-13 18:29
Disabling transforms & 3d acceleration doesn't help.

**Comment by mourner** [comment] 2015-01-13 18:31
Same bug when calling `map.panBy` programmatically.

**Comment by mourner** [comment] 2015-01-13 18:35
Same shit when manipulating translate values of map pane manually (just to exclude any Leaflet stuff). Same shit in grid.html (divs instead of images). Fucking Firefox.

**Comment by jfirebaugh** [comment] 2015-01-13 19:11
Definitely seems to be caused by "tiled rendering mode". Disabling `layers.enable-tiles` in `about:config` makes the issue disappear.

**Comment by jfirebaugh** [comment] 2015-01-13 19:14
Upstream issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1085024

**Comment by mourner** [comment] 2015-01-13 20:06
Thanks a lot to @cwiiis of Mozilla who quickly reacted to my tweet. The bug is now picked up by developers. It also seems that it's fixed in FF Aurora (36) and FF Nightly (38), so we can close this on the Leaflet side.

**Closed by mourner** 2015-01-13 20:06 UTC
Labels: major bug

**Comment by klimashkin** [comment] 2015-01-26 21:52
Fixed in 35.0.1
https://www.mozilla.org/en-US/firefox/35.0.1/releasenotes/

**Comment by mourner** [comment] 2015-01-26 23:38
Yay!
