### ISSUE TITLE
Opening PopupBox brings "invalid LatLng object (NaN, 11.3850302945) in LatLng.js:32

### ISSUE THREAD

**Issue by juedan** [Leaflet/Leaflet#8162] opened 2022-04-19 13:59 UTC
Opening a popup box which is bound to an marker show the following error:

```
LatLng.js:32 Uncaught Error: Invalid LatLng object: (NaN, 11.385030294575534)
    at new LatLng (LatLng.js:32:9)
    at Object.unproject (Projection.SphericalMercator.js:35:10)
    at Object.pointToLatLng (CRS.js:41:26)
    at NewClass.unproject (Map.js:987:27)
    at NewClass.panInside (Map.js:536:20)
    at NewClass._panOnFocus (Marker.js:397:7)
    at HTMLDivElement.handler (DomEvent.js:108:13)
LatLng @ LatLng.js:32
unproject @ Projection.SphericalMercator.js:35
pointToLatLng @ CRS.js:41
unproject @ Map.js:987
panInside @ Map.js:536
_panOnFocus @ Marker.js:397
handler @ DomEvent.js:108
```

First, this behaviour is new since Leaflet 1.8.0 and second in the whole data there is no such longitude " 11.385030294575534". I think this is somewhere calculated.
With Leaflet 1.7.1 I don't get this error.

**Environment**
- Leaflet version: 1.8.0
- Browser (with version): Chromium 99.0.4844.84 / FireFox 99.0
- OS/Platform (with version): Ubuntu 18.04 (64-Bit)

**Comment by juedan** [comment] 2022-04-20 07:40
Meanwhile I found out that there are more troubles with version 1.8.0 than I have exprected. Please close this issue.

**Comment by Falke-Design** [comment] 2022-04-20 07:43
@juedan Please share your problems, and it would be good anyway if you share the code for this problem. We would like to fix it.

**Comment by Falke-Design** [comment] 2022-04-20 08:01
Have you a online example with that error?

**Comment by juedan** [comment] 2022-04-20 09:49
The next days I will create an code snippet.
Coincidently I found when 
```
LatLng {
  "lat": NaN,
  "lng": 11.384941347419534
}

```
comes up. When the L.Marker attribute "autoPanOnFocus" is set to true, then I get this error message. Turning it off, all works perfect.

**Comment by IvanSanchez** [comment] 2022-04-20 12:16
> When the L.Marker attribute "autoPanOnFocus" is set to true, then I get this error message. Turning it off, all works perfect.

Sounds like a bug introduced by #8042, then. 

This sounds more and more like a valid Leaflet bug, but we still need to see a reproducible case of this. I'm curious about the values of the marker icon's `iconSize` and `iconAnchor`, since the calculations applied (get map center, unproject, add/subtract pixel margins, project again) depend on that. Looking at line 536 of `src/map/Map.js` I can see how that'll fail whenever there's an `iconSize` with a value of `NaN` or `undefined` or `Infinity`, but I cannot know how that fails with "normal" values for the icon's size & anchor.

**Comment by juedan** [comment] 2022-04-20 20:15
As promised here an link for the test code: https://juedan.nerdcamp.net/Test/test_leaflet.html
If the iconSize is set to [<pixel number>, "auto"] then an error is thrown. But with Leaflet 1.7.1 this works without any issues.

**Comment by IvanSanchez** [comment] 2022-04-20 21:08
@juedan Thanks! That certainly clarifies things.

However, I'll close this bug as "user not following the API reference". The `iconSize` option is supposed to be a `L.Point`, or an array of two numbers (and it should be obvious that the `"auto"` string is not a number). The fact that this way of defining icon sizes work at all is a chain of coincidences:

* `L.Point` is not enforcing any strict type checks
* When setting the size of the `HTMLImageElement` at ...

https://github.com/Leaflet/Leaflet/blob/da386bec18d2e103acb207e97cf332bd388bb575/src/layer/marker/Icon.js#L145

  ..., the "sum" of `"auto" + "px"` is calculated as `"autopx"` (because that's how ECMAscript works); 
* Now, when setting a value of `"autopx"` for the CSS property "height", the browser silently ignores that invalid value, and sets the CSS property "height" to a value of `""`
* Finally, when the browser adds a `HTMLImageElement` to the DOM with an empty value for the height, its height is calculated from the intrinsic image height

All things considered, I think the bug is invalid because it relies on passing values contrary to what's specified in the API documentation. Fetching the icon size from the intrinsic image dimensions is a possibility but is (a) out of the scope of this bug and (b) a potential source of asynchronous hell.

---

As a side note: You just provided a reproducible use case, and I replied deciding that the bug is invalid... and maybe that makes you feel bad, or you feel that you wasted time on that reproducible use case. But: Please don't! These things are informative, and clarifying, and overall good, and I do appreciate it!

**Closed by IvanSanchez** 2022-04-20 21:08 UTC
Labels: bug, needs more info
