### ISSUE TITLE
Black border in the bounds of a polygon with bound tooltip

### ISSUE THREAD

**Issue by pingumen96** [Leaflet/Leaflet#9126] opened 2023-10-12 09:21 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

You can check what happens here: https://plnkr.co/edit/a3ZpKDqAPqlA80Db
The example is very minimal

```
let geojson = L.geoJSON(geojsonData).addTo(map)
let geojsonCenter = geojson.getBounds()?.getCenter()

let tooltip = L.tooltip()
tooltip.setContent("test")
tooltip.setLatLng(geojsonCenter)
geojson.bindTooltip(tooltip)
```

### Expected behavior

No black border around the polygon bounds

### Current behavior

A black border is shown in the bounds of a clicked polygon with a tooltip

![image](https://github.com/Leaflet/Leaflet/assets/11261364/6f39e447-b879-4333-b32f-ecb12fddbc85)

### Minimal example reproducing the issue

https://plnkr.co/edit/a3ZpKDqAPqlA80Db

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Chrome 117.0.5938.132
- OS/Platform (with version): Ubuntu but I think it happens everywhere

**Comment by pingumen96** [comment] 2023-10-12 10:05
I noticed that it happens due to the MultiPolygon, because if I bind the tooltip to a single feature inside the polygon it doesn't happen. I don't know if that's ok as default behaviour

**Comment by Malvoz** [comment] 2023-10-12 10:13
Duplicate of https://github.com/Leaflet/Leaflet/issues/8659.

**Closed by Malvoz** 2023-10-12 10:13 UTC
Labels: bug, needs triage
