### ISSUE TITLE
Safari cuts off ImageOverlay

### ISSUE THREAD

**Issue by miro94** [Leaflet/Leaflet#6322] opened 2018-08-31 06:23 UTC
**Problem**
In safari, the non geopgraphical map content (image) gets cropped at the bottom, when in all other browsers (e.g. Chrome, Firefox) the full image is shown.

![xlpdo](https://user-images.githubusercontent.com/19932813/44896005-ff4d7a00-acf6-11e8-9ae6-ec96fd3ee160.png)

[JSFiddle](https://jsfiddle.net/162xgpLr/)

**Environment**
- Leaflet 1.3.4
- Safari 11.1.2

**Comment by IvanSanchez** [comment] 2018-08-31 08:13
Same fiddle but without jquery and with a placeholder image that doesn't trigger a HTTP 403 error: https://jsfiddle.net/zb60as49/10/

**Comment by miro94** [comment] 2018-08-31 08:31
Thanks @IvanSanchez. Your cleaned fiddle with the original image: https://jsfiddle.net/162xgpLr/.
Is there a problem with larger images?

**Comment by IvanSanchez** [comment] 2018-08-31 08:37
> Is there a problem with larger images?

Depends on the browser. Based on my experience, images wider/higher than 16000px start causing problems (depending on the browser and the CSS transforms applied).

Unfortunately I don't have access to a computer running Safari to debug this.

**Comment by miro94** [comment] 2018-09-03 07:26
I make some further investigations...
The problem appears when the image file size is larger than 2 MB, the pixel size is not relevant.
As a quick fix, I cache the image before loading the image, after that, the leaflet map is shown correctly.

https://jsfiddle.net/h7cym8kv/

**Comment by IvanSanchez** [comment] 2018-09-03 07:34
Does this cut happen also if you put a bigger-than-2MB image inside a `<img>` tag in your HTML document? (without using Leaflet)

**Comment by miro94** [comment] 2018-09-03 07:38
No, in this case the full image is loaded.

**Comment by jensolsson** [comment] 2019-03-02 12:28
I also have this problem and i do not believe there is an image with a 2MB. This rather seem to be a problem when adding the image before it is fully loaded.

Looking into the source of ImageOverlat there is a nice "load" event being fired when the image is loaded.
```
// @event load: Event
// Fired when the ImageOverlay layer has loaded its image
img.onload = Util.bind(this.fire, this, 'load');
```

As a workaround I am currently calling the private _initImage function to force the image to load. Then I add it to the map when the load-event fires. This seem to work regardless of image size.
```
image = L.imageOverlay('http://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg', imageBounds);
image.on("load", function() { image.addTo(map); });
image._initImage();
```

I think a great solution would be when I call image.addTo(map) it should not actually add itself to the map until the image is loaded, but I am not entirely sure on how to change the behaviour to this.

**Comment by sashadev-sky** [comment] 2019-09-23 04:21
I do something similar, but I allow `image.addTo(map)` to be called right away and `#initImage`, I just use the `load` event to wait to fire the line that actually adds the image to the map ( `this.getPane().appendChild(this._image);`) : 
```JS
onAdd: function(map) {
    this._map = map;
    if (!this._image) { L.ImageOverlay.prototype._initImage.call(this); }

    map.on('viewreset', this._reset, this);

    // Have to wait for the image to load because need to access its w/h
    L.DomEvent.on(this._image, 'load', function() {
      this.getPane().appendChild(this._image);
      this._initImageDimensions();
      this._reset();
    }, this);

    // add rest of events here too

    this.fire('add');
  },
```

**Comment by jonkoops** [comment] 2022-11-02 20:26
@Malvoz considering the issue is fixed in Safari 16 we might just close this. See #8633

**Closed** 2022-11-02 20:36 UTC
Labels: needs investigation, compatibility
