### ISSUE TITLE
Doesn't preload in invisible iframe

### ISSUE THREAD

**Issue by BryanCrotaz** [Leaflet/Leaflet#5738] opened 2017-08-29 12:03 UTC
I have a leaflet map inside an iframe. I start the iframe with css `display:none` and after ten seconds I show it with css `display:block`. 

The map tiles only start to load when `display:block` is set. What browser event causes them to load? How can I set the iframe up so that they preload before it's visible?

**Comment by IvanSanchez** [comment] 2017-08-29 12:09
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by BryanCrotaz** [comment] 2017-08-29 12:21
I'm not saying this is a bug. But I can't find what causes tiles to load in the source. I'm looking to make my iframe work with all sorts of sites and clearly I'm not simulating the environment correctly

**Comment by perliedman** [comment] 2017-08-29 12:24
@BryanCrotaz I would check to see that the map container has the correct size; often, an invisible container will have a zero size, which causes Leaflet to not load any tiles.

But, as @IvanSanchez says, it's hard to tell the cause without seeing an example of what you're doing.

**Comment by BryanCrotaz** [comment] 2017-08-29 12:39
So are the tiles loaded on body.onload, or on a resize event?

**Comment by perliedman** [comment] 2017-08-29 13:06
They are loaded once you set the view on the map (`setView`, `fitBounds`, etc.) as long as the tile layer is also added. As mentioned, the containers size is then used to figure out which tiles actually fit into the view.

Leaflet normally tracks _window_ resize (http://leafletjs.com/reference-1.2.0.html#map-trackresize), but not if the map container changes size. If the container changes size, you have to call  [`invalidateSize`](http://leafletjs.com/reference-1.2.0.html#map-invalidatesize) to inform Leaflet of the size change, and it will load tile accordingly.

I'm going to close this issue now, since it's turning into more of a support question than an issue report/feature request.

**Closed by perliedman** 2017-08-29 13:06 UTC
Labels: needs more info
