### ISSUE TITLE
Event needed for when layer finishes rendering (vs. load)

### ISSUE THREAD

**Issue by UsgsMonkey** [Leaflet/Leaflet#5390] opened 2017-03-16 15:03 UTC
## What behavior I'm expecting and which behavior I'm seeing

I've reviewed issue #2453 and for my needs the 'load' event is still firing too quickly.  If you check out the Fiddle code that user submitted, it appears the problem still persists even though that issue has been closed.  That said, what I'm looking for is an event that will fire when a layer has completed loading to memory AND finished rendering to the map.  I'd like to display a 'spinner' on initial page load and have that graphic stay up till the layers have completed drawing (because for the Leaflet application purposes, it's still not ready to start acting upon user-click input).  If I use the 'load' event, that event fires much too quickly for the layers I'm using where the number of total complex polygon features is approximately 100 +/-.  In fact, the layers have barely started rendering (if at all) by the time the load event actually fires.  The fiddle example provided in issue #2453 adequately demonstrates the timing problem.

## Environment

- Leaflet version: 1.0
- Browser: Chrome (56.0.2924.87)
- OS/Platform: Windows 7 Enterprise sp1

**Comment by IvanSanchez** [comment] 2017-03-16 15:08
The example in #2453 is about tile layers. You mention polygon features. Please clarify (and/or provide an example with vector data and using a recent version of Leaflet).

**Comment by UsgsMonkey** [comment] 2017-03-16 15:11
In my case, I'm using Esri Leaflet and leveraging that API's "FeatureLayer" along with a "BaseMapLayer" of "Streets" from ArcGIS Online.  I'll see if I can pull together an example.

**Comment by IvanSanchez** [comment] 2017-03-16 15:13
May I remind you that this repo is for core leaflet, not for any plugins. Make sure that your example does not depend on any plugins (or, alternatively, send the feature request to the esri-leaflet repo instead)

**Comment by UsgsMonkey** [comment] 2017-03-16 15:16
I appreciate that - no offense intended.  It seemed to me that an event that triggered off layer rendering however would be helpful for the core library.

**Comment by IvanSanchez** [comment] 2017-03-16 15:19
There is already an `update` on the `L.Renderer`s. It shouldn't be too difficult to add another event when the renderer signals completion, but I'm not fully sure that's what you need. And it would fire at the end of *each* update, which might not be what you want.

**Comment by UsgsMonkey** [comment] 2017-03-16 15:21
Well if I at least had that as a hook, I could track the complete set collectively and disable my spinner graphic when the last completed.  Right now, I don't have that hook so it's not working for me.  I've also tried responding to document.ready and window.load but those are both firing a bit too quickly as well.

**Comment by IvanSanchez** [comment] 2017-03-16 15:26
I suggest you try having a explicit `L.Renderer` (`L.SVG` or `L.Canvas`, or even a `map._renderer` hack), and listening to its `update` event. For what I see in the code, that event is fired at the *end* of each update cycle. 

If the esri-leaflet code doesn't allow you to get a reference to the vector renderer used, then well... that's a different problem.

**Comment by UsgsMonkey** [comment] 2017-03-16 16:19
I hadn't noticed that component.  Thank you, I'll give it a shot!

**Comment by UsgsMonkey** [comment] 2017-03-16 16:53
Rats - it looks like for my application, L.Renderer gives me similar behavior as document.ready (i.e. it fires after rendering has started, but well before all the features are fully drawn to screen).  My test app is inside the firewall so it may take me a bit to pull a publicly accessible demo together but I'll do my best.

**Comment by UsgsMonkey** [comment] 2017-03-16 16:57
I may take your advice and push this issue to the ESRI Leaflet page since it will be easier for me to demonstrate there.  I'm still not entirely sure where the best solution implementation might be (you guys who work in the guts of these APIs surely have a better sense of that), but it's probably worth staging it there if nothing else.

**Comment by IvanSanchez** [comment] 2017-03-16 17:00
> I'm still not entirely sure where the best solution implementation might be (you guys who work in the guts of these APIs surely have a better sense of that)

Not sure, really. The `update` event happens then Leaflet has finished updating the DOM, and there is no (reliable, sane) way to detect when the browser has finished all the paint operations. Not sure if there is something else going on on the `FeatureLayer` side of things.

**Comment by UsgsMonkey** [comment] 2017-03-16 17:07
> Not sure if there is something else going on on the FeatureLayer side of things.

Gotcha.  Well, based on that thought, I think my next step then will be to migrate this issue to the ESRI Leaflet page to see if that's the case.  Barring that, I think I'll just have to be happy with what I've got so far.

**Comment by IvanSanchez** [comment] 2017-03-16 17:10
Once again, if you can reproduce this in a stand-alone fashion, please provide an example with vector geometries which takes time to load (and where there is a *noticeable* or measurable delay between the `update` event and the paint operation). Then we can have a look at the performance graphs and see if it's possible.

I'll be closing this for now, due to the lack of a reproducible example. Will reopen if provided.

**Closed by IvanSanchez** 2017-03-16 17:10 UTC
Labels: needs more info

**Comment by UsgsMonkey** [comment] 2017-03-16 19:41
For what it's worth, here's a reproducible example using ESRI Leaflet.  I know this isn't the Leaflet API on it's own, but it's a good representation of what was discussed so far in this issue.  I'll be posting this on the ESRI Leaflet issue page and seeing where they can take it from there.

[ESRI Leaflet JsFiddle Example](https://jsfiddle.net/UsgsMonkey/vojbLfec/)
