### ISSUE TITLE
circle getBounds affected by zoom level

### ISSUE THREAD

**Issue by ctronisaac** [Leaflet/Leaflet#5933] opened 2017-11-21 22:20 UTC
- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: Windows 10

Create a circle
get the bounds (b1)
change the zoom
get the bounds (b2)

**Expected results:**   b1 == b2
**Actual results:**  b1 != b2

js fiddle
https://jsfiddle.net/risaac/e0bk7jzj/1/

**Comment by perliedman** [comment] 2017-11-22 12:02
Hi, thanks for reporting. I think this is a duplicate of #4582, which in turn has been fixed by #5859, so I'm going to close this!

**Closed by perliedman** 2017-11-22 12:02 UTC

**Comment by ctronisaac** [comment] 2017-11-22 13:05
thanks, and I agree.

Do you know when it will make it into the next stable release?
(Sorry if that information is available, but I don't see it; I'm a bit new
to all of this.)

Ron Isaac
ctRonIsaac@gmail.com
(203) 482-2449

**Comment by perliedman** [comment] 2017-11-22 13:44
@ctronisaac sorry, no time table for next release at this moment. But it's overdue, so we should try to make time for a release soon.
