### ISSUE TITLE
Zoom Icons render differently on browsers

### ISSUE THREAD

**Issue by googol7** [Leaflet/Leaflet#5808] opened 2017-09-27 14:35 UTC
Leaflet 1.2.0

Safari Version 11.0 (12604.1.38.1.7)
Chrome Version 61.0.3163.100 (Offizieller Build) (64-Bit)
Firefox 55.0.3 (64-Bit)
Opera 47.0.2631.83
Microsoft Edge 38.14393.0.0

This screenshot is taken from the homepage http://leafletjs.com

<img width="470" alt="bildschirmfoto 2017-09-27 um 16 27 49" src="https://user-images.githubusercontent.com/282412/30919299-4277ed0c-a3a1-11e7-8f83-f3e6ffad38c1.png">

**Comment by cherniavskii** [comment] 2017-09-27 16:00
Please do not ignore Issue Template.
It's not clear what behavior you expect.
Every browser renders fonts / borders / shadows / etc differently. So it's okay, that those controls look different in different browser.

**Comment by googol7** [comment] 2017-09-27 16:14
I expect that the icons look the same in every browser. I might add custom icons below the zooming icons and I want to be sure that the style of my icons match the style of the built in zooming icons (same height and width).

**Comment by cherniavskii** [comment] 2017-09-27 18:35
Styles are slightly different depending on Browser, because in case of [Browser.touch](https://github.com/Leaflet/Leaflet/blob/ca6025c8bdc00f6bb08dad49948a36fee881a8ec/src/core/Browser.js#L102) `leaflet-touch` class is added to map containers, which [overrides some styles](https://github.com/Leaflet/Leaflet/blob/8bd557886001ed87df4ab4a2ae265ccb622e855e/dist/leaflet.css#L308).
You can easily override default Leaflet styles if you want to.

**Comment by perliedman** [comment] 2017-09-27 20:10
Hi @googol7, @cherniavskii describes the situation well.

The major difference is whether Leaflet detects touch or not, which affects the size of the controls (slightly larger for touch to make them easier to hit), as well as the shadow/border, presumably since some lower end devices had/have problems with `box-shadow`.

I'm closing this issue, since this is not a bug, but rather works as designed as far as I can tell.

**Closed by perliedman** 2017-09-27 20:10 UTC

**Comment by nrenner** [comment] 2017-09-29 11:23
See also #5266

**Comment by anatel** [comment] 2020-09-16 19:54
Is there an option to avoid the `leaflet-touch` from being added? 
If not, how can it be overridden easily?

**Comment by johnd0e** [comment] 2020-09-17 06:47
> Is there an option to avoid the `leaflet-touch` from being added?

Use `L_NO_TOUCH` switch.

https://leafletjs.com/reference-1.7.1.html#global-switches
