### ISSUE TITLE
Tiles disappear when pinch-zooming past maxZoom

### ISSUE THREAD

**Issue by fnicollet** [Leaflet/Leaflet#4655] opened 2016-06-20 20:14 UTC
Hello,

This issue can be reproduced with the most basic example on the playground.
Pinch zoom until max zoom. When you zoom past, the tiles disappear and show the map's background. When you release, it snaps back to max zoom
I don't think this should be the expected behaviour. Previous version of leaflet would just stretch last zoom while pinch-zooming, then snap back to max zoom

I looked through issues and pull requests but couldn't find any similar.

Reproduced with leaflet 1.0.0-rc1, on Chrome Windows x64, on a laptop with a touch screen

**Comment by IvanSanchez** [comment] 2016-06-21 08:32
This is different from https://github.com/Leaflet/Leaflet/issues/3530, right?

Is this reproducible in `master` or just in rc1?

**Comment by fnicollet** [comment] 2016-06-26 07:39
Hello, sorry for the delay

Reproducible in both master and RC1 using debug/map.html on a laptop with touch screen

Using the bounceAtZoomLimits with a false value prevents the bug from happening as the map is forced not to go further than the maxZoom. But by default this option is true so the bug is happening with the basic leaflet examples

**Comment by mattrothenberg** [comment] 2016-07-09 14:19
@fnicollet Thanks for digging in to this! I'm experiencing the same thing in an Angular 2 application using the latest build of Leaflet.

[https://gfycat.com/PoliteMatureHuemul](https://gfycat.com/PoliteMatureHuemul)

Any ideas what is causing the temporary disappearance of the tiles? It doesn't seem like it's related to the `bounceAtZoomLimits` option, as pinch-zooming randomly seems to make the tiles disappear.

All I'm doing to initialize the map is:
```
let mymap = L.map('map', {
      center: L.latLng(40.7233, -74.0030),
      zoom: 15,
      maxZoom: 17,
      bounceAtZoomLimits: false,
});
```

**Comment by perliedman** [comment] 2017-08-09 07:56
I couldn't reproduce this on latest master, so I'm closing this for now. Please tell me if you still think this is a problem.

**Closed by perliedman** 2017-08-09 07:56 UTC
Labels: bug, needs more info
