### ISSUE TITLE
layerPointToContainerPoint does not work 

### ISSUE THREAD

**Issue by AndreasSchmid1** [Leaflet/Leaflet#6058] opened 2018-02-15 10:34 UTC
## Environment

- Leaflet version I'm using:
- Browser (with version) I'm using: Chrome latest
- OS/Platform (with version) I'm using: Leaflet 1.3.1 

## What behaviour I'm expecting and which behaviour I'm seeing

After running the small sample the "ConvertedMapWidth" output is still 500 and not the converted distance relative to the map coordinate system.

## Minimal example reproducing the issue

https://jsfiddle.net/4b2cn24w/9/

**Comment by IvanSanchez** [comment] 2018-02-15 11:19
Can you provide a *complete* example that other people can run and see, please?

**Comment by AndreasSchmid1** [comment] 2018-02-15 15:55
done

**Comment by tvfire** [comment] 2018-02-19 10:13
same issue here

**Comment by perliedman** [comment] 2018-02-20 07:25
It looks to me like this is working as expected. Can you elaborate on what results you expected to see?

Note that a layer point and container point have the same scale, only different origins, so distances between two of them should be the same. As stated in [the docs for `layerPointToContainerPoint`](http://leafletjs.com/reference-1.3.0.html#map-layerpointtocontainerpoint), both are _pixel coordinates_, the scale is screen pixels for both.

**Comment by AndreasSchmid1** [comment] 2018-02-20 10:12
I would expect same coordinates only in the highest zoom level (zoom scale 1to1). But in every other zoomlevel I would expect (Given monitor pixels / 2^zoomlevel). In the case of CRS Simple

**Comment by IvanSanchez** [comment] 2018-02-20 10:25
As @perliedman just said:

> As stated in the docs for `layerPointToContainerPoint`, both are **pixel coordinates**, the scale is screen pixels for both.

This is behaviour as expected.

> But in every other zoomlevel I would expect (Given monitor pixels / 2^zoomlevel). In the case of CRS Simple

If you want CRS coordinates, use `map.options.crs.project()` and `map.crs.options.unproject()`.

Behaviour as expected, everything is documented, not a bug. Closing.

**Closed by IvanSanchez** 2018-02-20 10:25 UTC
Labels: needs more info
