### ISSUE TITLE
Marker position freezes while zooming animation.

### ISSUE THREAD

**Issue by MatixYo** [Leaflet/Leaflet#7915] opened 2022-01-15 13:10 UTC
### Discussed in https://github.com/Leaflet/Leaflet/discussions/7910

<div type='discussions-op-text'>

<sup>Originally posted by **MatixYo** January 14, 2022</sup>
I'm building an app where markers' position is updated with approximated position of cars.
During zooming animation marker stays in position where it was before zooming and only moves to the correct position after the map was zoomed in. Here's an example: https://codesandbox.io/s/leaflet-awesome-markers-forked-wrjnt?file=/src/index.js
Follow the marker and try to zoom it. My question is, is there any way to prevent that marker glitching when zooming?</div>

It happens on both Windows 11, Chrome 97, and on Android. Chrome 97. On a Mobile device, you can see it very well when zooming with + and - buttons. Using Leaflet 1.7.1

**Comment by Malvoz** [comment] 2022-01-15 17:45
Is this duplicate of https://github.com/Leaflet/Leaflet/issues/7401?

**Comment by MatixYo** [comment] 2022-01-16 00:03
> Is this duplicate of/related to #7401?

May be related, however, this one applies to moving markers. It happens when marker changes position during zoom.

**Comment by Falke-Design** [comment] 2022-02-04 10:54
Duplicate of #7017

**Closed by Falke-Design** 2022-02-04 10:54 UTC
