### ISSUE TITLE
Slow map initialization in IE in 0.7.7

### ISSUE THREAD

**Issue by t-sch** [Leaflet/Leaflet#4041] opened 2015-11-23 08:52 UTC
See there - my fiddle with 0.7.7 is slow again

**Comment by IvanSanchez** [comment] 2015-11-24 10:22
@t-sch See where?

**Comment by t-sch** [comment] 2015-11-24 10:26
In #2908, I meant. Here's the link again: http://jsfiddle.net/v6rkyc7d/3/ please change the leaflet version in the code to 0.7.7.

**Comment by t-sch** [comment] 2015-11-25 10:33
I have to correct myself.
It seems not to be a regression but another issue with the same symptoms.
I forgot I had switched the touch USB cable off, it now happens on non-touch devices, too. And Edge, but not Chrome.

**Comment by IvanSanchez** [comment] 2015-11-25 10:56
@t-sch That fiddle just shows a grey area when switching to 0.7.7. Please provide a working fiddle (or similar) with 0.7.7 already written in.

**Comment by t-sch** [comment] 2015-11-25 12:30
Yes, you're right. The CDN address has changed for 0.7.7.
Please try http://jsfiddle.net/v6rkyc7d/6/ and allow about 15 min to complete.

**Comment by IvanSanchez** [comment] 2015-11-25 13:17
Changing the fiddle to http://jsfiddle.net/c84974he/5/ allowed me to get some timings:

IE 11:
![ie-timing](https://cloud.githubusercontent.com/assets/1125786/11398010/089d84aa-937e-11e5-908e-05107575bf8c.png)

Chrome 46:
![chrome-timing1](https://cloud.githubusercontent.com/assets/1125786/11398012/0a3b85fa-937e-11e5-9ba6-c4f3d926bed7.png)

However, profiling the code in IE points to the culprit, which none other than the native `addEventListener`:
![ie-profile](https://cloud.githubusercontent.com/assets/1125786/11398152/1940d54a-937f-11e5-8068-a36293b7d970.png)

The only solution is to use event delegation, which is exactly what the 1.0.0-betas do.

**Comment by t-sch** [comment] 2015-11-25 13:22
But why was it no problem in 0.7.4? Something must have changed.
I went back to use an older version as a workaround because I can't use a beta for production.

**Comment by IvanSanchez** [comment] 2015-11-25 13:33
Hm, looks like this will need a `git bisect` to locate the root cause.

**Comment by mourner** [comment] 2016-03-31 22:28
Closing as duplicated of #4357

**Closed by mourner** 2016-03-31 22:28 UTC
Labels: bug, help wanted, needs investigation, stable
