### ISSUE TITLE
Grid lines showing around tiles

### ISSUE THREAD

**Issue by ttback** [Leaflet/Leaflet#5078] opened 2016-11-03 21:03 UTC
## How to reproduce

- Leaflet version I'm using: 1.0.1
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: OSX 10
Steps to reproduce:
Open http://timesmachine.nytimes.com/timesmachine/2001/09/12/issue.html and you'd see grid lines.

## What behaviour I'm expecting and which behaviour I'm seeing
We are not doing any fancy things with the map rendering but the default API calls through tilelayer() etc. It has been working in production for 2 years, but after upgrading to Leaflet 1.0.1, it's start showing lines on Desktop version only.

I tried `.leaflet-tile { border: 0px; }` but it can't get rid of the lines

**Comment by ttback** [comment] 2016-11-03 21:04
I am not sure if this has anything to do with https://github.com/Leaflet/Leaflet/issues/1066

**Comment by perliedman** [comment] 2016-11-04 07:10
Hi, this is a duplicate of #3575. If you need a fix ASAP, you can use this plugin: https://github.com/Leaflet/Leaflet.TileLayer.NoGap, or you can wait for #4941 to fix this.

**Closed by perliedman** 2016-11-04 07:10 UTC
