### ISSUE TITLE
setView and setZoom firing simulateously freezes the map in Safari

### ISSUE THREAD

**Issue by stepladder** [Leaflet/Leaflet#3121] opened 2015-01-09 11:57 UTC
Please check the link, 

http://stepladderuk.com/dev/chiltern/exp/1/location-map.html

Hover over the logo in the top left. This will run this function;

$('.home').mouseenter(function(){
 map.setView( [51.522772, -0.153286] );
 map.setZoom( 17 );
});

When the animation is complete, the map 'fixes' for a few seconds and you can't move the map by dragging the mouse.

I think there's an issue with running setView and setZoom simultaneously, If I drop either one of the methods it works ok.

This happens in Safari for mac, ipad and iphone. Works fine in all other browsers.

I disabled all other scripts on the page.

version: leaflet-0.7.3 stable
tested on a mac Safari 7.1.2

Thanks in advance

**Comment by javisantana** [comment] 2015-01-09 12:00
probably related: https://github.com/Leaflet/Leaflet/issues/2021

**Comment by stepladder** [comment] 2015-01-09 17:35
Thanks Javi,

I fixed it with this;

$('.home').mouseenter(function(){
 setTimeout(function() {
 map.setZoom( 17 );
 }, 0);
 map.setView( [51.522772, -0.153286] );
 });

**Comment by stepladder** [comment] 2015-01-09 18:10
Ok, that wasn't the fix.

I just noticed the problem only happens when the new co-ordinates declared by setView is within the browser view.

In this example, if you move the view outside the original viewport and then fire the function, it works.

You can see how this happens in the link;

http://stepladderuk.com/dev/chiltern/exp/1/location-map.html

**Comment by mourner** [comment] 2015-01-09 18:56
Yes, because it tries to animate the position twice and stucks — it's a known issue. Did you try the master version? It should be fixed there as far as I remember.

**Comment by patrickarlt** [comment] 2015-01-10 21:52
@stepladder `setView` also takes a zoom level so you can do

```
$('.home').mouseenter(function(){
  map.setView( [51.522772, -0.153286], 17);
});
```

**Comment by stepladder** [comment] 2015-01-22 19:03
Thanks Mourner, I tried the master version with setTimeout I posted above and it works ok now.

**Comment by mourner** [comment] 2015-02-24 19:34
Closing as duplicate of #3249

**Closed by mourner** 2015-02-24 19:34 UTC
