### ISSUE TITLE
Can Leaflet Support Map Rotate

### ISSUE THREAD

**Issue by bingv150** [Leaflet/Leaflet#5167] opened 2016-12-05 12:44 UTC
I am using Leaflet on PC, but i need to rotate the map , i try to change it by setting the transform

transform:rotate(7deg);
-ms-transform:rotate(7deg); 	/* IE 9 */
-moz-transform:rotate(7deg); 	/* Firefox */
-webkit-transform:rotate(7deg); /* Safari 和 Chrome */
-o-transform:rotate(7deg); 	/* Opera */

but the point i click was not the actually point i want !,can somebody tell me how can i rotate the map?

![image](https://cloud.githubusercontent.com/assets/4651436/20885374/72908fda-bb2b-11e6-9153-8a6399ee1692.png)

**Comment by IvanSanchez** [comment] 2016-12-05 12:46
Duplicate of #268

**Closed by IvanSanchez** 2016-12-05 12:46 UTC
