### ISSUE TITLE
svg with ImageOverlay not rendering properly

### ISSUE THREAD

**Issue by sebmat003** [Leaflet/Leaflet#6630] opened 2019-04-30 08:13 UTC
I am using ImageOverlay to display one single svg. But this svg contains `<image>` tags which is not render by `<img>` html tag. 
It would works with something like this:
`<object type="image/svg+xml" data="image.svg"></object>`
or
`<embed type="image/svg+xml" src="image.svg" />`

Here is the screen with my problem:
![1](https://user-images.githubusercontent.com/25228272/56949570-917e7a00-6b33-11e9-822c-47c2be753933.png)

I suggest to add ObjectOverlay with tag `<object>` and data instead of src.

**Comment by IvanSanchez** [comment] 2019-04-30 09:17
Closing as duplicate of https://github.com/Leaflet/Leaflet/pull/6517

**Closed by IvanSanchez** 2019-04-30 09:17 UTC
