### ISSUE TITLE
flags

### ISSUE THREAD

**Issue by beatnickgr** [Leaflet/Leaflet#8809] opened 2023-01-22 11:40 UTC
### Checklist

- [ ] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [ ] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

I'm zooming on conflict zones (Palestina, Taiwan, Kurdistan, etc) but I see the flag of another conflict zone (Ukraine). Just because Leaflet was created by an Ukrainian person doesn't mean that only their country should be supported.

### Suggested solution

The Ukrainian flag should appear only when the map is centered on Ukraine.
When elsewhere, it should show the respective flag.

### Alternatives considered

Alternative 1 : Randomize the flags of conflict zones independently of where the map is centered

Alternative 2 : Do not display any flag.

**Comment by IvanSanchez** [comment] 2023-01-22 12:44
I'm closing this as a duplicate of https://github.com/Leaflet/Leaflet/issues/8295 .

While I agree that other parties in other conflict zones *should* be supported, the current point of the flag is to show that Leaflet is **directly** affected by this conflict.

**Closed by IvanSanchez** 2023-01-22 12:44 UTC
Labels: feature, needs triage

**Comment by beatnickgr** [comment] 2023-01-22 16:35
> the current point of the flag is...

If you have to explain that to me, then the flag alone is not enough. It only reminds users scrolling another conflict zone about that conflict in Ukraine. 
If you're not in Russia, there's no hint that Leaflet is unavailable in Russia. I personally just found out now that you posted the other thread.

Leaflet is also unavailable in N. Korea, but i don't see any reminder of that.
