### ISSUE TITLE
Custom Handler dont stop propagate event

### ISSUE THREAD

**Issue by destus90** [Leaflet/Leaflet#5593] opened 2017-06-29 07:27 UTC
Hi guys. I create custom handler by extending L.Handler. In addHooks method i just add handler for map click and try to stop propagate that event. From outer code, i`m have a handler for click event too.
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using: Chrome 59
- OS/Platform (with version) I'm using: Windows 10 (x64)
- step: open developer console and click on a map

## What behaviour I'm expecting and which behaviour I'm seeing
expect: click event will not bubble.
## Minimal example reproducing the issue

Using https://plnkr.co/edit/yuh67rrsOZYSpUjXam4g?p=preview

**Comment by perliedman** [comment] 2017-11-16 15:44
Hi and sorry for a very late reply!

I think this issue stems from the wrong expectations on how internal events in Leaflet work.

Note that your code attach click event handlers to the map instance - these are not DOM event handlers, so when your `click` event handlers are called, they are called from Leaflet's event system, not your browser's native events. Your code stops propagation on the DOM event, but this will not stop the Leaflet event.

Further, the two event handlers you have attached are both on the `map` instance, so even if it were native DOM events, `stopPropagation` would not prevent both handlers from running: stopping propagation means the event will not bubble up further, but it will still run all event handlers on the current element.

Hope this clears up the situation!

I'm going to close this, since I think Leaflet works as intended and this is not a bug.

**Closed by perliedman** 2017-11-16 15:44 UTC
