### ISSUE TITLE
I want to disable map.on.click event when i click over pop-up. 

### ISSUE THREAD

**Issue by darda-ergo** [Leaflet/Leaflet#7189] opened 2020-06-30 08:45 UTC
![image](https://user-images.githubusercontent.com/61325474/86104638-21290b00-bae0-11ea-8573-172eefc1d0eb.png)
Anyone have any Idea. When click on this input field the click function work over this and i dont want this. 

I have followed this way . link:https://gis.stackexchange.com/questions/303331/how-to-temporary-disable-map-click-event-in-openlayers

but not got any result

**Comment by IvanSanchez** [comment] 2020-06-30 09:21
Duplicate of  #4258, #6213

**Closed by IvanSanchez** 2020-06-30 09:21 UTC
