### ISSUE TITLE
Feature: add a 'error' event to ImageOverlay

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#5281] opened 2017-01-25 10:38 UTC
As per https://stackoverflow.com/questions/41841381/leaflet-imagelayer-seturl-error-handling , it should be useful to have a `error` event in `L.ImageOverlay`, akin to the `tileerror` event in `L.TileLayer`.

**Comment by AP-whitehat** [comment] 2017-02-03 16:06
Looking into this issue.
The problem is in 
https://github.com/Leaflet/Leaflet/blob/master/src/layer/ImageOverlay.js
I suppose ... ?

**Comment by IvanSanchez** [comment] 2017-02-03 16:10
Yeah. See:

https://github.com/Leaflet/Leaflet/tree/ad75456fa54aee4d38e92dd7654128819cf8e31a/src/layer/ImageOverlay.js#L167
and also:
https://github.com/Leaflet/Leaflet/tree/ad75456fa54aee4d38e92dd7654128819cf8e31a/src/layer/tile/TileLayer.js#L144

**Comment by perliedman** [comment] 2017-02-03 16:12
@AP-whitehat yes, exactly. From a quick look, an error handler should probably be added in [`_initImage`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/ImageOverlay.js#L160).

**Comment by AP-whitehat** [comment] 2017-02-03 20:40
What would be better to use as a dummy placeholder  for error links
http://www.birthdaydirect.com/popup_image.php?pID=16068
or http://hdimagesnew.com/wp-content/uploads/2016/09/404.png
or something else .

I'll have to include the png in dist/images/

**Comment by AP-whitehat** [comment] 2017-02-03 21:26
Issue not yet Fixed ,
am I going in the right direction ?

please point out my mistakes 😛

**Comment by IvanSanchez** [comment] 2017-02-03 23:21
@AP-whitehat Please open up a pull request, so we can comment on specific lines of your code :-)

**Comment by AP-whitehat** [comment] 2017-02-06 07:39
@IvanSanchez 
Please Review my PR

**Comment by rhberro** [comment] 2017-06-02 03:09
A pull request related to this issue was merged, can we close this one?

**Comment by perliedman** [comment] 2017-06-02 06:05
Closed by #5307!

**Closed by perliedman** 2017-06-02 06:05 UTC
Labels: easy fix, feature, help wanted
