### ISSUE TITLE
Controversy statements

### ISSUE THREAD

**Issue by dmitrygorbenko** [Leaflet/Leaflet#8873] opened 2023-03-01 18:42 UTC
### Checklist

- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this change hasn't been suggested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Which documents need updating?

https://leafletjs.com/

### Motivation

To make things clear.

### Suggested changes

Once you visit the main page you can see a statement regarding russian invasion, it's clearly you don't support it.
At the same time you display Crimea as a part of russia federation. 
These statements are conflicting with each other.
![statement](https://user-images.githubusercontent.com/1971759/222234806-8ca5d8cd-7714-4277-b207-cba77118fc93.jpeg)
![crimea_under_occupation](https://user-images.githubusercontent.com/1971759/222234820-8379911d-1b52-43a3-b9e8-b523b727f0f7.jpeg)

**Comment by IvanSanchez** [comment] 2023-03-01 19:48
Closing as a duplicate of https://github.com/Leaflet/Leaflet/issues/5056 - Leaflet is the map display library, not the underneath map data.

What you're seeing is OpenStreetMap data (as you should be able to discern from the attribution). The subject of Crimea has been contentious in the past (as have been Kosovo, Cyprus, and a dozen other places). And just to make this clear: even though the Leaflet folks know the OSM folks (and vice versa), that doesn't mean that both groups operate as a whole (as opposed to commercial providers, which have the map interface and the dataset under the same umbrella).

The people taking care of territorial disputes is the OSMF DWG (see https://wiki.openstreetmap.org/wiki/Data_working_group ). Alas, maintaining Leaflet keeps us busy enough, and (I have some second-hand accounts that) working in the DWG is quite draining. As much as we'd love to move the OSM border, it's not an easy task and it has its own geopolitical implications.

Do have a look at https://wiki.openstreetmap.org/wiki/Disputed_territories#Europe for a bit more background.

**Closed by IvanSanchez** 2023-03-01 19:48 UTC
Labels: docs, needs triage

**Comment by nickpasiuk** [comment] 2023-06-27 12:50
@dmitrygorbenko do you find a way to change the border of Ukraine?
