### ISSUE TITLE
Leaflet rotate icon in degree

### ISSUE THREAD

**Issue by sintret** [Leaflet/Leaflet#9132] opened 2023-10-14 18:26 UTC
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

i'm always frustated when i search this plugin is not working

### Suggested solution

make it default icon class

**Comment by Falke-Design** [comment] 2023-11-02 18:54
Duplicate of #143 and #7870

**Closed by Falke-Design** 2023-11-02 18:54 UTC
Labels: feature, needs triage
