### ISSUE TITLE
ZoomLevel and Meter in leaflet map

### ISSUE THREAD

**Issue by minhkwan** [Leaflet/Leaflet#9463] opened 2024-09-05 05:31 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

When I'm using my map, in some places: The zoom level at 19 represents 50m but in some other places, it will represents 30m when the zoom is 19. Why this is happening? Or it's a normal behaviour because of ...

### Expected behavior

The meter will be always 30m when zoom level is 19

### Current behavior

In some places, zoomLevel 19 represents 50m while in some other places, it represnets 30m.

### Environment

- Leaflet version: 1.3.1
- Browser (with version): WebView React Native 
- OS/Platform (with version): IOS / Android

**Comment by IvanSanchez** [comment] 2024-09-05 18:52
Do read https://en.wikipedia.org/wiki/Tissot%27s_indicatrix and https://en.wikipedia.org/wiki/Mercator_projection

Closing because it's not a bug.

**Closed by IvanSanchez** 2024-09-05 18:52 UTC
Labels: bug, needs triage
