### ISSUE TITLE
Browser zoom should keep basemap crisp

### ISSUE THREAD

**Issue by neothemachine** [Leaflet/Leaflet#3599] opened 2015-07-06 10:16 UTC
When I use the standard browser zoom to make everything (controls, text etc.) bigger then the basemap tiles just zoom in but their more detailed levels don't get loaded, meaning they get blurry when zooming in. I think this should not be the case however I have no experience on what JS and the browsers offer to handle this properly and how much change in leaflet would be required. Having said that, I think this issue is very important as people who cannot see clearly (think of people with cloudy eyes etc.) often zoom in to make text bigger. My personal use case is to display a leaflet map on a massive touch-enabled wall of screen (4x2 hd screens, 7680x2160) where the browser is zoomed in by default to 300% to make it easy to see things and also to touch controls.

**Comment by IvanSanchez** [comment] 2015-07-06 16:35
> their more detailed levels don't get loaded

... and that's exactly the expected behaviour.

If a user increases the CSS-pixel-to-screen-pixel scale factor, the right way to behave is to load the tiles at the same zoom level. If a different zoom level is loaded, then all the pixel-dependant cartographic attributes (read: "the width of the roads") will be halved, effectively nulling the effect of scaling.

Let me illustrate:

![scaling](https://cloud.githubusercontent.com/assets/1125786/8527551/77359262-240d-11e5-9401-9848e8970577.png)

Yes, the image is crisper, but the text size, line widths and size of cartographic symbols (see the brown triangles indicating peaks) gets reduced, which is what you do not want when scaling things up.

If you're using a tilelayer which looks the same as you zoom in (i.e. aerial imagery), then you can use http://leafletjs.com/reference.html#tilelayer-detectretina , or simply change the `tileSize` option of your tileLayers.

> I think this issue is very important as people who cannot see clearly

No. Users with visual impairment have an assortment of tools at their disposal, including screen magnifiers, which work on any windowed program (not just web browsers). Should visually impaired users use scaled webpages but browser buttons and URL bar at the same size? Nope.

> My personal use case is to display a leaflet map [...] zoomed in by default to 300%.

You're doing it wrong. Use CSS to scale the UI elements, and use tiles designed for high-resolution displays (called sometimes "retina", "HighDPI" or "@2x"), or even render your own 3x tiles. Trying to make Leaflet gracefully scale up rasterized maps is pretty much impossible.


As this is not a bug but a usage question, I'm closing it.

**Closed by IvanSanchez** 2015-07-06 16:35 UTC

**Comment by neothemachine** [comment] 2015-07-06 17:13
Thanks a lot for the detailed explanation. I really wasn't aware of all those details. It makes sense. I wonder what effect the `L_PREFER_CANVAS` option has on this though, as detectRetina is only for tile layers.
