### ISSUE TITLE
Tooltip setContent not documented

### ISSUE THREAD

**Issue by cgutteridge** [Leaflet/Leaflet#6954] opened 2020-01-02 15:50 UTC
Hi, https://leafletjs.com/reference-1.6.0.html does not mention setContent() as a method of Tooltip and I had to dig in the code to find it. It's important as if you want to create a tooltip with options, you need to then setContent() to set the text.

**Comment by johnd0e** [comment] 2020-01-03 08:06
Duplicate of #6597

**Closed** 2021-04-04 14:25 UTC
