### ISSUE TITLE
raster lines are visible when dpi is set to a bigger value in windows

### ISSUE THREAD

**Issue by j-dc** [Leaflet/Leaflet#5152] opened 2016-11-30 16:13 UTC
- [ x ] I'm reporting a bug, not asking for help
- [ x ] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x  ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using:  1.0.2
- Browser (with version) I'm using: 54.0.2840.99 m (64-bit)
- OS/Platform (with version) I'm using: Windows 10
   !!DPI 125%
- step 1
   Right click on your desktop:  
   Change the setting   (Change the size of text, apps, and other items:)
    put it on 125%
- step 2
    Load a TileMap in leaflet

## What behaviour I'm expecting and which behaviour I'm seeing
   I expect a nice map.
   Instead I am seeing the borders of the tiles

## Minimal example reproducing the issue
   No problem using Leaflet 0.7:  
    https://jsfiddle.net/JanDeclercq/thk56xqm/

    Problem introduced using  Leaflet 1.0.2
  https://jsfiddle.net/JanDeclercq/2mnp9L3t/1/

- [ x ] this example is as simple as possible
- [ x ] this example does not rely on any third party code

![image](https://cloud.githubusercontent.com/assets/8330653/20760019/fa756e0e-b71e-11e6-8c60-034ff0eca862.png)

**Comment by j-dc** [comment] 2016-12-07 10:56
The change causing this effect is the  inline css applied to every tile for there correct position.

CSS causing the error:  (Version 1.x)
     transform: translate3d(295px, 82px, 0px);

CSS with correct behavior: (version 0.7.x)
    left: 295px;
    top: 82px;

This is most likely a webkit chrome error..??


![lefttop](https://cloud.githubusercontent.com/assets/8330653/20964804/4b4b05ce-bc73-11e6-9c13-6688db34aeb8.png)

![translate3d](https://cloud.githubusercontent.com/assets/8330653/20964796/42f9ce8c-bc73-11e6-891c-1451bb9ab1b0.png)

**Comment by IvanSanchez** [comment] 2016-12-07 10:59
This is a duplicate of https://github.com/Leaflet/Leaflet/issues/3575. Apparently the bug shows not only on fractional zooms, but on high-DPI displays as well.

**Closed by IvanSanchez** 2016-12-07 10:59 UTC
