### ISSUE TITLE
Leaflet does not correctly render in chrome with CSS columns

### ISSUE THREAD

**Issue by ThorbenKuck** [Leaflet/Leaflet#6717] opened 2019-07-03 13:15 UTC
- [X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Create a div and give it a "column-count: 1" css attribute.
- Create a "map" div and render the leaflet inside it

**Expected behavior**

I expected leaflet to render normaly inside the "map" div.

**Current behavior**

Leaflet does not render inside this div. Instead, the "cached" tiles around the currently viewed one are also displayed, around the "map" div.

If you zoom in or out, the cached tiles are still displayed, even though they are no longer inside of the div the map is rendered into.

**Environment**
- Leaflet version: >= 1.4
- Browser (with version): Google Chrome Version 75.0.3770.100 (64 Bit)
- OS/Platform (with version): Independent (verified in Ubuntu 18.04, Mac 10.14.5 and Windows 10)

**Additional context**

The unexpected behaviour is triggered if the map is found inside of a **css grid**. Any other display property does what was expected. This isue also does not surface in firefox or safari. Only Chrome appears to have this issue, which leads to the conclusion, that either chromes webkit has a bug, or some _-webkit-_ property is missing in the css, or something similiar.

**MVE**

http://jsfiddle.net/dz8L3us5/ (Leaflet 0.7.2)

edit: Same bug can be found in Leaflet 1.5.1. Link to the jsfiddle: http://jsfiddle.net/9eqc1fpm/

To see the difference, remove "column-count" from "theBug".

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by ThorbenKuck** [comment] 2019-07-03 13:27
Changed MVC => MVE (Minimal Verifiable Example)

**Comment by IvanSanchez** [comment] 2019-07-04 08:55
That fiddle is loading Leaflet 0.7.2. Please update it to 1.5.0 and see if it's still reproducible.

**Comment by ThorbenKuck** [comment] 2019-07-04 10:17
I added a jsfiddle for the new version. Bug still exists. Sorry, i did not doublecheck the version.

**Comment by ThorbenKuck** [comment] 2019-07-08 15:03
@IvanSanchez Does this issue need more infos?

**Comment by qligier** [comment] 2019-07-16 19:28
I have the same issue, it seems to be caused by Chrome/Chromium.
Chrome 75.0.3770.142 (the current version) and 76.0.3797.0 (beta version) have the same bug; Chrome 74.0.3729.169 and 77.0.3840.0 (dev version) don't.
Let's hope the fix will be backported to v75 soon.

**Comment by Malvoz** [comment] 2021-12-18 23:27
> The unexpected behaviour is triggered if the map is found inside of a **css grid**. Any other display property does what was expected.

@ThorbenKuck I'm not seeing CSS grid in use, only CSS columns?

Anyhow, I'm not seeing any issues in your fiddles, but it sounds like what you're describing is similar to https://github.com/Leaflet/Leaflet/issues/7699. If that's the case and you still have this problem, can you try the solution described in https://github.com/Leaflet/Leaflet/issues/7699#issuecomment-950251395?

**Comment by Malvoz** [comment] 2022-02-16 13:49
@ThorbenKuck If you're still able to reproduce the bug; can you try [`page-break-inside: avoid`](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-inside) and/or [`break-inside: avoid`](https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside) (or `avoid-column`) and see if that solves the problem?

I can't reproduce the bug, and the above https://github.com/Leaflet/Leaflet/issues/6717#issuecomment-511953262 suggests that it was fixed in Chrome shortly after this issue was opened.

I don't think there's anything Leaflet can do here, even if `break-inside` works to solve the browser bug, it'd be an opinionated change that changes the behavior for authors who actually want to use CSS columns with Leaflet maps.

**Closed by Malvoz** 2022-02-16 13:49 UTC
Labels: needs more info
