### ISSUE TITLE
Draggable L.Marker (with divIcon) - unwanted map click event in Chrome on dragend

### ISSUE THREAD

**Issue by apdevelop** [Leaflet/Leaflet#6112] opened 2018-03-29 07:21 UTC
## How to reproduce
- Leaflet version I'm using: 1.3.1 (from https://unpkg.com/leaflet@1.3.1/dist/)
- Browser I'm using: Chrome 65.0.3325.181 (64-bit)
- OS/Platform I'm using: Windows 7 Professional x64

- run the example [JSFiddle Leaflet draggable marker Chrome issue](https://jsfiddle.net/apdevelop/scgvvmaw/)
![leafletissue](https://user-images.githubusercontent.com/19760379/38165712-5f29ae0c-3520-11e8-85c0-efb315cb4842.png)
- press left mouse button down when cursor **is near the border of marker** (near to marker's border as possible, when cursor is just changed to 'hand')
- drag marker to some distance, the cursor will move out a bit from the marker border 
- after releasing mouse button, the blue marker with popup will be added to map - it means, that map `click` event was handled, but actually no click was intended

## What behaviour I'm expecting and which behaviour I'm seeing
Expecting behavior: map `click` event should not be fired after marker dragging complete.
In Firefox 56.0.2 (32-bit) on the same system the behaviour is different (and it is how it should work): no map `click` event is fired after mouse button release, but clicking on map just after drag ended will fire `click` event. The same behaviour is on Firefox Nightly 61.0a1 (2018-03-28) (64-bit).

## Minimal example reproducing the issue
[JSFiddle Leaflet draggable marker Chrome issue](https://jsfiddle.net/apdevelop/scgvvmaw/)

```js
var map = L.map('map').setView([50, 1.0], 15);

map.on('click', function(e) {
  L.marker(e.latlng)
    .addTo(map)
    .bindPopup("Was clicked at " + e.latlng)
    .openPopup();
});

L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
  attribution: 'Map data &copy; <a href="https://openstreetmap.org">OpenStreetMap</a>',
  maxZoom: 18
}).addTo(map);

L.marker([50, 1.0], {
    icon: L.divIcon({}),
    draggable: true
  })
  .on('drag', function(e) {})
  .on('dragstart', function(e) {})
  .on('dragend', function(e) {})
  .on('click', function(e) {
    L.DomEvent.stopPropagation(e);
  })
  .addTo(map);
```

**Comment by PoLePanda** [comment] 2020-07-01 20:38
Only add `pointer-events: none` in CSS property

**Comment by johnd0e** [comment] 2020-07-02 07:31
Seems duplicate of #4457

**Comment by apdevelop** [comment] 2020-07-02 09:58
Checked using Leaflet version 1.6.0 [JSFiddle Leaflet draggable marker Chrome issue](https://jsfiddle.net/apdevelop/78uL1krv/), the issue still here.

**Closed** 2021-01-31 21:33 UTC

**Comment by johnd0e** [comment] 2021-02-01 12:08
@apdevelop 
Please check this solution: #7446
