### ISSUE TITLE
Uncollapsed layer controls are collapsing on mouseout

### ISSUE THREAD

**Issue by bmcbride** [Leaflet/Leaflet#5251] opened 2017-01-12 22:26 UTC
## How to reproduce

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Chrome 55.0.2883.95 (64-bit)
- OS/Platform (with version) I'm using: OS X El Capitan 10.11.6

## What behaviour I'm expecting and which behaviour I'm seeing

Uncollapsed layer controls should not collapse on mouseout.

## Minimal example reproducing the issue

See: http://leafletjs.com/examples/wms/wms-example3.html

The layer control is initially uncollapsed, but once you mouseover it to switch a layer, and mouseout of the control, it collapses.

**Comment by IvanSanchez** [comment] 2017-01-13 08:27
Duplicate of #5126, which has been already fixed in the `master` branch.

**Closed by IvanSanchez** 2017-01-13 08:27 UTC

**Comment by bmcbride** [comment] 2017-01-13 14:41
Apologies for not seeing that. Thanks!
