### ISSUE TITLE
IOS pinch to zoom bug

### ISSUE THREAD

**Issue by czb** [Leaflet/Leaflet#3930] opened 2015-10-14 11:55 UTC
When I use pinch to zoom on IPhone 6 IOS 9 and Ipad IOS 8 on this page

http://leafletjs.com/examples/mobile-example.html

sometimes I get weird behaviour. See screenshot. As soon as I release fingers from the screen, the marker moves to correct position.

EDIT: I start zooming by moving fingers from each other. Usually everything works as expected and the marker stays all the time in the middle of the circle. But sometimes the marker is "frozen" and does not stay in the middle of the circle. When I release the fingers from the screen the marker jumps to the center of the circle.

![005](https://cloud.githubusercontent.com/assets/37391/10482762/1a8ee470-727b-11e5-8bea-049093b7c205.PNG)

**Comment by IvanSanchez** [comment] 2015-10-14 12:00
> sometimes I get weird behaviour

What is "weird behaviour"? The movement is locked? Things get out of place? Movement of the base map doesn't correlate to movement of the fingers? Movement of the overlays doesn't correlate to movement of the fingers? Unicorns appear on the map? [**Be specific**](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by czb** [comment] 2015-10-14 12:02
You can see it on the screenshot. The marker is outside of the circle. It should never be outside of the circle.

**Comment by IvanSanchez** [comment] 2015-10-14 12:11
Does the marker move away form its place as you pinch zoom, or does the circle move away from its place when you pinch-zoom?

Be.
More.
Specific.

**Comment by czb** [comment] 2015-10-14 12:13
It is the circle that moves from its position. Not the marker.

**Comment by mourner** [comment] 2015-10-14 12:13
Also, did you try the same on Leaflet beta1? Leaflet master version?

**Comment by mourner** [comment] 2015-10-14 12:14
For what it's worth, I also notice this behavior ocassionally.

**Comment by IvanSanchez** [comment] 2015-10-14 12:15
Probably a duplicate of #3919

**Comment by mourner** [comment] 2015-10-14 12:16
@IvanSanchez this is reproducible on 0.7.5 though. As far as I remember, this was easier to trigger by starting a pinch and then dragging with two fingers. The marker will often get stuck in one position and not move with the map.

**Comment by IvanSanchez** [comment] 2015-10-14 12:17
@mourner Worth a backport? This is a potential brainmelt.

**Comment by mourner** [comment] 2015-10-14 12:19
@IvanSanchez yeah, we need to confirm whether this is still reproducible on Leaflet master before looking into it.

**Comment by czb** [comment] 2015-10-14 12:21
I have installed Leaflet from bower and package.json says 0.7.5. I can always reproduce the error by panning the map with one finger and then touching the other finger and zooming.

**Comment by IvanSanchez** [comment] 2015-10-14 12:27
Hmmm. Might be a duplicate of #3798 instead.

@czb Try downloading 1.0.0-beta1 (not via bower, we're working on that) - it should get rid of the bug.

**Comment by czb** [comment] 2015-10-14 12:36
I have tested 1.0.0-beta1 and I could not reproduce the bug.

**Comment by IvanSanchez** [comment] 2015-10-14 12:38
Closing as a duplicate of #3798 then.

**Closed by IvanSanchez** 2015-10-14 12:38 UTC
Labels: bug, needs more info
