### ISSUE TITLE
can't use CDN with https: "ERR_INSECURE_RESPONSE"

### ISSUE THREAD

**Issue by teo1978** [Leaflet/Leaflet#3337] opened 2015-03-29 19:12 UTC
On a webpage served over https, I have:
```
<link rel="stylesheet" type="text/css" href="//cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />
<script type="text/javascript" src="//cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>
```
and the browser issues these errors:
```
GET https://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css net::ERR_INSECURE_RESPONSE
GET https://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js net::ERR_INSECURE_RESPONSE
```

It seems that cdn.leafletjs.com doesn't have a valid certificate?

However, I **CAN'T** use:
```
<link rel="stylesheet" type="text/css" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />
<script type="text/javascript" src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>
```
in a page served over https, because the browser will block the requests

**Comment by snkashis** [comment] 2015-03-31 14:25
Duplicate of https://github.com/Leaflet/Leaflet/issues/2944

**Closed by snkashis** 2015-03-31 14:25 UTC
