### ISSUE TITLE
GPS points at 179 and -179 causes whole world to be displayed

### ISSUE THREAD

**Issue by dewitpj** [Leaflet/Leaflet#6356] opened 2018-10-04 00:54 UTC
## How to reproduce

- Leaflet version I'm using: Not sure - it's the one in Observium - source shows v=18.9.9449
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Mac OS

- Make a point at lat long 16 179
- Make a point at lat long 16 -179 

These points are "close" to each other, but the whole world is shown

## What behaviour I'm expecting and which behaviour I'm seeing
- Zoom in on that area and display the points

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

Sorry - I am not to familiar with leaflet to code up an example :(

**Comment by ghybs** [comment] 2018-10-05 22:04
Duplicate of #https://github.com/Leaflet/Leaflet/issues/2333

**Comment by ghybs** [comment] 2018-10-05 22:04
See also PR https://github.com/Leaflet/Leaflet/pull/1293 for further details.

**Closed by ghybs** 2018-10-05 22:04 UTC
