### ISSUE TITLE
Glitchy marker clicks / taps in Windows.

### ISSUE THREAD

**Issue by springlab** [Leaflet/Leaflet#2356] opened 2014-01-08 13:34 UTC
I'm building an app using Mapbox / Leaflet in Windows. 

When you mousedown on a marker and move slightly (even 1px) it will not activate a marker click on mouseup. Same happens with emulated touch events and real touch input.

I need some sort of click tolerance similar to the tap tolerance. But I'm not sure how to implement that.

To reproduce the issue, open any Mapbox / Leaflet map in Chrome on Windows. Mouse down on a marker, move the mouse just a hair, then release.
Also, trying to tap on a marker using a Windows touch screen rarely results in marker activation. You usually have to double tap to fire the popup.

Tested with Chrome / Chromium in Windows 8. Also testing with Mouse, Emulated Touch and real Touch Events.

Any help is greatly appreciated.

**Comment by mourner** [comment] 2015-10-07 10:21
Can anyone confirm this being fixed on master?

**Comment by HarelM** [comment] 2016-08-07 20:07
I'm not sure this is related to this issue or not, but I can open a new one if needed.
I have an issue with firefox on android device and the code throws an error on the following line:
```js
// this is a horrible workaround for a bug in Android where a single touch triggers two click events
	_filterClick: function (e, handler) {
		var timeStamp = (e.timeStamp || e.originalEvent.timeStamp),
```
the error is: ```TypeError: e.originalEvent is undefined```
The steps to reproduce are:
surf to: http://israelhiking.osm.org.il on android with firefox, click on the marker on the right pane.
click on the map to add a marker.
click the "V" to close it and click on the marker again to open popup.
runs well on any device/browser except this combination (popup doesn't open).
uses leaflet 7.7.
Any thoughts?
PS, great library.

**Comment by HarelM** [comment] 2016-08-07 21:27
OK, Managed to create a fully reproducible scenario:
Click doesn't work for divIcon in firefox for android:
steps to reproduce: click once to add the icon, click on the icon.
The code below works on firefox on desktop but doesn't work on firefox on android.
```html
<!DOCTYPE>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<link rel="stylesheet" href="https://npmcdn.com/leaflet@0.7.7/dist/leaflet.css" />
	<script src="https://npmcdn.com/leaflet@0.7.7/dist/leaflet.js"></script>
</head>
<body>
	<div id="map" style="position: absolute;top: 0;bottom: 0;right: 0;left: 0;overflow: hidden;"></div>
	<script>
		var map = L.map('map').setView([51.495, -0.09], 15);
		map.on("click", function(e) {
			let divIcon = L.divIcon({
                html: "<span>Marker</span>",
                iconSize: L.point(20, 36),
                iconAnchor: L.point(10, 36),
                popupAnchor: L.point(0, -40)
            });
			let marker = L.marker(e.latlng, { draggable: true, clickable: true, riseOnHover: true, icon: divIcon, opacity: 1.0 }).addTo(map).bindPopup("<a href='#'>marker!</a>");
		});
	</script>
</body>
</html>```

**Comment by vdemin** [comment] 2016-08-12 12:04
@HarelM See https://github.com/Leaflet/Leaflet/issues/3724

**Comment by HarelM** [comment] 2016-08-12 14:17
Look like the same issue, but the issue is closed and this is still happening, do I need to add the code written there (the ```null``` check) to my leaflet version or is there a planned fix?

**Closed** 2020-03-21 16:18 UTC
Labels: mobile
