### ISSUE TITLE
Two-Finger gestures disabled when dragging disabled in samsung browser

### ISSUE THREAD

**Issue by synonymousz** [Leaflet/Leaflet#5969] opened 2017-12-15 15:09 UTC
I use the Samsung Internet Browser from my tablet and verified the issue with my Huawei smartphone by downloading the Samsung Internet Browser.
When I do "draggable: false", it also disables to pan with 2 fingers on the Samsung Browser but in none of the other browsers I tested. (Chrome, Firefox, IE, Edge, Safari)

## How to reproduce
- Leaflet version I'm using: Leaflet 1.2.0
- Browser (with version) I'm using: Samsung Internet Browser (latest 20171215)
- OS/Platform (with version) I'm using: Samsung/Android, other Devices Android with the specified browser installed.
Just use any example from the leaflet docs and disable dragging.

## What behaviour I'm expecting and which behaviour I'm seeing
I can not use 2 fingers to do 2 finger gestures like panning/zooming.
I expected it to do so, since all other browsers do.

## Minimal example reproducing the issue
https://plnkr.co/edit/Xm59tidxPV804zsBlopu?p=preview

**Comment by perliedman** [comment] 2017-12-15 15:35
Hi, thanks for reporting.

I don't have access to the Samsung Internet Browser, so it will be hard for me to verify this, but it sounds like this might be a duplicate of, or at least similar to #5779.

Fortunately, there's #5952 which should address this. If possible, could you try out this fix and see if it works for you?

**Comment by cherniavskii** [comment] 2017-12-15 16:31
I don't think it's related to #5952, since it fixes an issue with `dragging: true, touchZoom: false` and doesn't change behavior of `dragging: false`

**Comment by synonymousz** [comment] 2017-12-18 09:08
@perliedman You can download the Samsung Browser on any Android-device. I verified on my Huawei that its not just the Samsung-Devices but also on other devices using this browser.
I tested to add the CSS-changes you made in the merge you linked and unfortunate as @cherniavskii mentioned, it does not address this issue.

**Comment by ajhbh** [comment] 2018-07-06 11:00
I have downloaded the Samsung Browser to my HTC device and confirm the issue is there in that with dragging disabled, 2 finger interactions are also stopped. 
I haven't checked myself but from the [leaflet gestureHandling addon issue here](https://github.com/elmarquis/Leaflet.GestureHandling/issues/2#issuecomment-392798893):

> In SamsungBrowser there's always a burst of single fingered interactions immediately before any two fingered zoom. No matter how hard you try to avoid it.
This seems to be intermittently disabling the map interactions mid pinch giving an ugly jumpy effect. 

Hopefully this helps point in the right direction for a fix.

**Comment by johnd0e** [comment] 2020-04-06 19:54
Looks similar to #5425

**Comment by johnd0e** [comment] 2020-04-07 13:24
Test with latest master: https://gist.githack.com/johnd0e/a3647bebc3a65440d2f7ea470998816b/raw/issue-6959.html

**Comment by johnd0e** [comment] 2020-04-07 15:19
Alternative fix: just add `L.DomUtil.addClass(map._container, 'leaflet-grab leaflet-touch-drag');`, like `dragging` does:
https://gist.githack.com/johnd0e/a3647bebc3a65440d2f7ea470998816b/raw/issue-6959-ns.html

(Though for ultimate fix we need separate class for `touchZoom` handler)

**Comment by johnd0e** [comment] 2020-04-07 16:03
My explanation: when only `touchZoom` handler is enabled `touch-action: pan-x pan-y;` rule is active.
<details>

https://github.com/Leaflet/Leaflet/blob/d843c3b88486713827d7e860b58bdba75bfbd5a2/dist/leaflet.css#L58-L61
</details>

And with this rule* `pointerdown` event get canceled (by browser) early, see #5745.
And this is the problem, 'cause currently all touch events are remapped with their pointer counterparts (which is fixed by #7029).

So:
- May be `css` should be refactored (too many different `touch-action`-rules).
- I still tend to think that proper way to fix this issue - apply #7029.

**Comment by johnd0e** [comment] 2020-04-09 06:46
BTW, I found why Samsung browser behaves in such way: the culprit is option `Control the zoom on webpages`. 
Luckily, it's possible to opt out. 

Immediately after turning it off touchZoom get working again. 
Still, #7026 makes it working smoother.

**Comment by rhysstubbs** [comment] 2020-10-20 11:57
Are there any updates on this issue? I am experiencing the same problem in Samsung Internet.

I'm using the Leaflet.GestureHandling plugin and setting `touch-action: none !imporant` which fixes the issues with the map. However this obviously leaves the map stuck as the natice scrolling does not work.

Does [#7026](https://github.com/Leaflet/Leaflet/pull/7026) solve the issue and will it be merged anytime soon?

**Comment by johnd0e** [comment] 2020-10-21 07:19
> I am experiencing the same problem in Samsung Internet.

So why not disable `Control the zoom on webpages` option in your browser?

**Comment by rhysstubbs** [comment] 2020-10-21 07:56
@johnd0e 

> So why not disable Control the zoom on webpages option in your browser?

That may solve the issue for me but it wouldn't solve the issue for thousands of my users unfortunately. Samsung Internet makes up ~ 9% of my userbase so its not an option.

**Comment by johnd0e** [comment] 2020-10-21 08:13
Good point.

> Does [#7026](https://github.com/Leaflet/Leaflet/pull/7026) solve the issue and will it be merged anytime soon?

It'd be cool if you test 7026 and report back if it 1) solve your issues 2) does not break anything else for you.

**Comment by rhysstubbs** [comment] 2020-10-21 08:51
@johnd0e 

I forked and merged #7026 yesterday, I don't have an Android device to test with unfortunately but one of my colleagues confirmed it didn't fix the issue in Samsung Internet.

Whether or not it breaks anything else I cannot say for certain, in our usecase with raster tiles, zoom +/- and a marker popup, everything seemed to function normally.

**Comment by johnd0e** [comment] 2020-10-21 10:13
Well, there is mistake: 7026 was in your message, but it should be #7029 instead.

**Closed** 2021-11-01 08:32 UTC
