### ISSUE TITLE
beta1 dist files on bower install

### ISSUE THREAD

**Issue by kuzkok** [Leaflet/Leaflet#3732] opened 2015-08-11 09:18 UTC
Hi, i tried install beta1 with bower

```
>bower install leaflet#v1.0.0-beta.1
```
but there is no "compiled" files in dist folder
I expect to see leaflet.js and leaflet-src.js there

**Comment by IvanSanchez** [comment] 2015-08-11 09:21
Duplicate of #3635

**Closed by IvanSanchez** 2015-08-11 09:21 UTC
