### ISSUE TITLE
GeoJSON create invalid LatLng

### ISSUE THREAD

**Issue by mdwillian** [Leaflet/Leaflet#5677] opened 2017-07-31 19:06 UTC
## How to reproduce

- Leaflet version I'm using: Latest (1.1.0)

## What behaviour I'm expecting and which behaviour I'm seeing
Expected behavior: Multidimensional array of `LatLng`s from a GeoJSON coordinates
What I am seeing:  Invalid LatLng object: (undefined, undefined)

## Minimal example reproducing the issue

- In version 1.0.3  L.GeoJSON.coordsToLatLngs(coords) return array. 
- In version 1.1.0  L.GeoJSON.coordsToLatLngs(coords) return error.
- The problem is highlighted in the images below.

![error](https://user-images.githubusercontent.com/7854587/28793381-33348bc2-7609-11e7-9b0d-19b90af69a37.PNG)
![leaflet-1 0 3](https://user-images.githubusercontent.com/7854587/28793391-38dc3c82-7609-11e7-9577-b2b6c42f5c08.PNG)
![leaflet-1 1 0](https://user-images.githubusercontent.com/7854587/28793395-3cdb5da4-7609-11e7-9773-966f76f4a2f9.PNG)

**Comment by ghybs** [comment] 2017-08-01 07:41
Hi,

Thank you for your message.
**Please can you provide a live reproduction case?**

The code difference that you show in your screenshots is normal, it is due to a change in the code structure (see the `coordsToLatLng` ES6 module function just above in `1.1.0`, whereas in `1.0.3` they are static methods).

I cannot reproduce your issue with your bug description:
http://playground-leaflet.rhcloud.com/diza/1/edit?html,output

**Comment by perliedman** [comment] 2017-08-08 15:11
Closing for now, happy to re-open when we get more information on the issue!

**Closed by perliedman** 2017-08-08 15:11 UTC
Labels: needs more info
