### ISSUE TITLE
Tiles / Page breaks when zooming in chrome.

### ISSUE THREAD

**Issue by optical** [Leaflet/Leaflet#3198] opened 2015-02-04 23:59 UTC
When zooming/panning in chrome, occasionally the tile layer will stop working altogether. Tiles will stop loading, and the page will basically break - although layers still seem to render. Having a very heavy map with many layers seems to exacerbate the issue, which is what I have done in the fiddle.

Fiddle: http://jsfiddle.net/su538mh8/
Load the fiddle, and then start zooming in and out of the sea of markers, panning around etc. After a short period of time (30-60s), the tiles will stop loading, so if you zoom in all the way / move to a new area, etc you will never get tiles. Interestingly, if you reload the page it will not succeed. In order to get things working again you have to create a new tab.
Note that this can occur in more sane maps; I have reproduced it on a demo page at http://leafletjs.com/examples/choropleth-example.html - it just requires a bit more time when zooming / panning for the issue to appear. 

Disabling 3d transformation using L_DISABLE_3D makes the issue go away.

I suspect this might be out of Leaflets hands, as it looks like it might be a Webkit / Blink / Chrome bug of sorts. But perhaps there is a different workaround or change would could be made that I am unaware of?

This seems related to issue #2612 - possibly the same bug.
Tested in Chrome 40, windows 8.1, as well as firefox and IE11. Only able to reproduce it in chrome.
Have used master & stable, both have the issue. Rendering to SVG and canvas doesn't seem to matter - both end up breaking the page.

**Comment by mourner** [comment] 2015-02-05 00:08
Can't reproduce so far, works well for me... Will try more. What's your OS?

**Comment by optical** [comment] 2015-02-05 00:23
Using windows 8.1. I recorded it in action, which you can see here: http://opticraft.net/leaflet/chrome-crash.swf

**Comment by optical** [comment] 2015-02-05 00:33
And heres one where it crashes on the example page. Doesn't take too long, although its more of a trashing then one would normally give it.

http://www.opticraft.net/leaflet/choro-example-crash.swf

**Comment by yohanboniface** [comment] 2015-10-07 14:04
I'm unable to reproduce.
Can you check again with latest master: http://playground-leaflet.rhcloud.com/faz/edit?html,output ?

**Comment by grzegorzpawlowski** [comment] 2015-10-14 01:04
I discovered the same problem and I can reproduce it on any leaflet map on any page, when I use Chrome (even maps on leaflet's home page).
In order to reproduce you just have to keep zooming in an out for a while. If you continue zooming and panning before previous files are loaded, the page will break. In browser's developer tools (network tab) you will see that call for tile images are pending.

This seems like corner case because who would keep zooming in and out all the time but if you have a map with a lot of markers and a sidebar referencing them and interacting with the markers and zoom level you can end up with a broken map.

What I found so far:
- it is not related to a tile provider (tried openstreetmaps, arcgisonline and here maps),
- independent from layers/marker (fails also with a plain map),
- I could reproduce it with leaflet 0.7.3, 0.7.5, 1.0.0-beta2 (yesterday's master branch),
- L_DISABLE_3D set to true helps but this is not an option for me,
- reproduced on chrome on windows 8.1 and on fedora,
- after it occurs it makes some network calls pending indefinitely (js scripts, tiles).

The biggest problem is that you have to close the tab or the entire browser, refresh doesn't help.

Leaflet map opened in chrome doesn't cancel calls for tiles that are not visible anymore (from previous zoom level). I noticed that OpenLayers for example does cancel calls for old tiles (e.g after zoom).

**Comment by optical** [comment] 2015-10-14 07:52
I personally can't seem to repro this anymore, using Version 45.0.2454.101 m on Windows 10. Haven't tried other versions

**Comment by yohanboniface** [comment] 2015-10-14 08:35
@grzegorzpawlowski are you by chance able to have a try without any Chrome plugin or extension or whatever? Just in case.

**Comment by IvanSanchez** [comment] 2015-10-16 11:04
Due to playground maintenance, I messed up the existing examples, so the one for this bug now lives at http://playground-leaflet.rhcloud.com/kag/edit?html,output

**Comment by grzegorzpawlowski** [comment] 2015-10-19 21:52
@yohanboniface, thanks for the suggestion.
I couldn't reproduce it in incognito mode. When I disabled user agent switcher plugin in "regular" Chrome, I couldn't reproduce it also.
It seems that this was the root cause. Thanks!

**Comment by j16sdiz** [comment] 2015-10-29 08:49
I can reproduce with your jsbin. This is what I did:

1. Change the width/height to 1000px.
2. Use a slow network (or set throttling in chrome developer console)
3. Zoom and pan the map. Keep doing this.
4. You can see some tile request is marked as "(cancelled)" in chrome developer console. I guess this is expect.
5. Keep scrolling the map. You can see "pending" network request in chrome console stack up.

The syndrome:
 -  Refreshing / New tab don't recover from the problem
 -  Switching to incongito mode give you a "second chance"

It look like the max-request-per-server limit is hit in chrome.

This is one example "pending" request in the chrome://net-internals/#events page:
```
242644: URL_REQUEST
http://b.tile.openstreetmap.org/4/12/7.png
Start Time: 2015-10-29 16:49:57.170

t=497326 [st=    0] +REQUEST_ALIVE  [dt=87837]
                     --> delegate_info = "ResourceScheduler"
                     --> has_upload = false
                     --> is_pending = false
                     --> load_flags = 205056 (DO_NOT_USE_EMBEDDED_IDENTITY | MAYBE_USER_GESTURE | REPORT_RAW_HEADERS | VERIFY_EV_CERT)
                     --> load_state = 3 (WAITING_FOR_DELEGATE)
                     --> method = "GET"
                     --> status = "SUCCESS"
                     --> url = "http://b.tile.openstreetmap.org/4/12/7.png"
t=585162 [st=87836]    CANCELLED
t=585163 [st=87837] -REQUEST_ALIVE
```

Compare to a "cancelled" request:
```
240020: URL_REQUEST
http://b.tile.openstreetmap.org/5/3/13.png
Start Time: 2015-10-29 16:41:39.844

t=0 [st=0] +REQUEST_ALIVE  [dt=?]
            --> has_upload = false
            --> is_pending = false
            --> load_flags = 205056 (DO_NOT_USE_EMBEDDED_IDENTITY | MAYBE_USER_GESTURE | REPORT_RAW_HEADERS | VERIFY_EV_CERT)
            --> load_state = 0 (IDLE)
            --> method = "GET"
            --> net_error = -3 (ERR_ABORTED)
            --> status = "CANCELED"
            --> url = "http://b.tile.openstreetmap.org/5/3/13.png"
```

You can see the "pending" request is hold in "WAITING_FOR_DELEGATE" state. 
I am not sure if this is a chrome bug, or just or mis-handling of event callbacks.

**Comment by j16sdiz** [comment] 2015-10-29 08:58
Related to https://code.google.com/p/chromium/issues/detail?id=495813  ?

**Comment by IvanSanchez** [comment] 2015-10-29 09:40
> I am not sure if this is a chrome bug, or just or mis-handling of event callbacks.

Maybe, just *maybe*, it's event mishandling. As of now, Leaflet only cares for the `load` and `error` events on the tile images, ignoring any other events such as `abort` and `cancel`. It might be possible that Chrome is firing either `cancel` or `abort` without firing `error`. If that's the case, we could add some code to destroy the tiles and see if that'd free the network requests.

I think it's a long shot anyway.

**Comment by fenwick67** [comment] 2015-10-30 20:10
I have been experiencing what seems to be the same issue in my chrome browser at work, with Chrome version 46.0.2490.80 m on windows 7.

Reloading does not fix the problem, I have to open up another tab and paste the URL in to get the tiles to load again.

I was really worried this was a problem with my application or the tile server I was using, but it seems to happen on any page with Leaflet (OSM, the leaflet homepage, etc).

**Comment by kellyelton** [comment] 2015-11-03 17:43
I noticed that tampermonkey can cause this issue as well 

derjanb/tampermonkey/issues/245

**Comment by fenwick67** [comment] 2015-11-16 15:53
Thanks @kellyelton, it looks like that was causing the issue for me.  Disabling the tampermonkey extension fixed the issue for me.  It also looks like @optical had tampermonkey installed based on the video he uploaded.

**Comment by mourner** [comment] 2015-11-16 16:29
So looks like it's not something that could be fixed on the Leaflet side then, right? Closing then. Will reopen if anyone confirms that issue is present with the extension.

**Closed by mourner** 2015-11-16 16:29 UTC
Labels: bug, help wanted, needs investigation
