### ISSUE TITLE
Leaflet 1.0.3 not loading on Firefox

### ISSUE THREAD

**Issue by chaturvedijai** [Leaflet/Leaflet#5732] opened 2017-08-24 23:54 UTC
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Firefox
- OS/Platform (with version) I'm using: Windows
- step 1
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing
I am getting an error on page load:
"This page had an error. NoErrorObjectAvilable". This is because leaflet js is not loading i think.
This is the page:
https://s3-us-west-2.amazonaws.com/lightningout.com/testduplicate.htm

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by ghybs** [comment] 2017-08-25 02:25
Hi,

Please can you reproduce your issue on the [Playground](http://playground-leaflet.rhcloud.com/boze/1/edit?html,output)?
You can use that page to mimic your HTML code and see if it shows the same issue.
If so, please send the link (it will save your code so that other people can test it as well)

**Comment by perliedman** [comment] 2017-10-27 11:02
Closing since there hasn't been any activity or more info.

**Closed by perliedman** 2017-10-27 11:02 UTC
Labels: needs more info
