### ISSUE TITLE
[BUG?] Map tiles offset with random empty tiles.

### ISSUE THREAD

**Issue by trusktr** [Leaflet/Leaflet#3771] opened 2015-08-25 09:48 UTC
For example, it looks like this:

![screenshot from 2015-08-25 02-43-47](https://cloud.githubusercontent.com/assets/297678/9463702/59c6cdb2-4ad3-11e5-8362-87fd54892663.png)

I'm using 1.0.0-beta.1 and I've got code that looks like this:

```js
        this.map = new L.Map(
            document.getElementById('map'),
            {
                zoomControl: false,
                center: [ lat, lng ],
                zoom: 15
            }
        );

        // Open Street Map layer for our leaflet instance.
        var osmUrl='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
        var osmAttrib='Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors';
        var osm = new L.TileLayer(osmUrl, {
            minZoom: 0,
            maxZoom: 18,
            attribution: osmAttrib
        });
        this.map.addLayer(osm)
```

**Comment by mourner** [comment] 2015-08-25 09:53
I can't reproduce this. Can you set up a JSFiddle test case that demonstrates the issue?

**Comment by trusktr** [comment] 2015-08-25 09:57
Hmmm, actually, I'm also getting this with 0.7.3.

![screenshot from 2015-08-25 02-55-53](https://cloud.githubusercontent.com/assets/297678/9463929/f54f1838-4ad4-11e5-90a3-e7bc33dcbf42.png)

Let me see if I can make a reproduction.

**Comment by mourner** [comment] 2015-08-25 10:06
This is probably an issue with your app CSS. Closing here for now.

**Closed by mourner** 2015-08-25 10:06 UTC

**Comment by trusktr** [comment] 2015-08-25 16:38
@mourner I just took a look, and there doesn't seem to be any CSS affecting any of the Leaflet DOM. For example, they all just have `element.style` and `Style Attribute`, like this:

![screenshot from 2015-08-25 09-33-27](https://cloud.githubusercontent.com/assets/297678/9472855/8596c260-4b0c-11e5-9c95-06b90e634686.png)

Any other ideas? The spaces between the tiles seems to be the size of the map tiles, but there's nothing in those tiles. Here's what hovering on the `.leaflet-pane.leaflet-map-pane` in the inspector looks like:

![screenshot from 2015-08-25 09-38-25](https://cloud.githubusercontent.com/assets/297678/9472955/1220495e-4b0d-11e5-8ec6-9611d4808c41.png)

Is it fine for it to be shifted off like that?

**Comment by mourner** [comment] 2015-08-25 16:51
@trusktr can't say much until I see a reproduced JSFiddle test case. Maybe you forgot to include Leaflet CSS?

**Comment by trusktr** [comment] 2015-08-25 17:40
@mourner Aah, indeed. That was easy to overlook (it's been a while since I used Leaflet so I forgot). Would it make sense to load styles automatically/programmatically?

**Comment by mourner** [comment] 2015-08-25 18:02
@trusktr no, the idea was considered but ultimately rejected. You can probably find the discussion somewhere in GH issues or PRs.

**Comment by BADAKAA** [comment] 2021-10-17 17:31
I was experiencing similar issues that had an entirely different cause.

This solution may not apply to you, but this might help any passerby using OpenStreetMaps:

In the URL, **x**, **y** and **z** must **NOT** be in alphabetical order like so:

`    const tileURL =`"https://{s}.tile.osm.org/{x}/{y}/{z}.png";`

but must instead be **in this order**>:

`    const tileURL = "https://{s}.tile.osm.org/{z}/{x}/{y}.png";`

Otherwise, invalid tiles will be requested, resulting in an unusable, faulty map.
