### ISSUE TITLE
Hover over Polygon or Circle, no hit after map is moved/dragged

### ISSUE THREAD

**Issue by EkkehardDomning** [Leaflet/Leaflet#6142] opened 2018-04-25 10:32 UTC
## How to reproduce

- Leaflet version I'm using: Probably 1.3.1 (used on the leafletjs.com site)
- Browser I'm using: Firefox Quantum 59.0.2 (64-Bit)
- OS/Platform I'm using: Windows 7

- Open web-page [LeafletJS Quick start guide](http://leafletjs.com/examples/quick-start/).
- Scroll to "City of London" example.
- Hover the mouse over the triangular polygone. The cursor is changing to the "index finger"-Symbol while the mouse is inside the polygone.
- Click on "-" symbol to zoom out one step.
- Hover the mouse as before, still operating as before.
- Drag the map to the left, so that the red circle is close to the left border of the map frame.
- Hover the mouse over the polygon and/or circle, the hand cursor is not longer switching to the "index finger"-Symbol, the items are not longer hit.
- Drag the map back to the right, near to the center
- Hover the mouse over the polygon and/or circle, surprise - the items are not hit again.

## What behaviour I'm expecting and which behaviour I'm seeing
I expect that the polygons and circles are staying responsible for mouse hover operations, even if the map is dragged. This behaviour is interrupted when a zoom on the map is made.

P.S.: With Internet Explorer 11.0.9600.18977 the problem is not existing!

**Comment by cherniavskii** [comment] 2018-04-25 11:04
Duplicate of #5773?

**Comment by IvanSanchez** [comment] 2018-04-25 11:05
Closing as duplicate of #5773

**Closed by IvanSanchez** 2018-04-25 11:05 UTC
Labels: bug, compatibility, needs investigation

**Comment by EkkehardDomning** [comment] 2018-04-25 12:41
Sorry, but I was not aware the a SVG related problem is the same as mine. But You're right, #5773 describes the same problem.

**Comment by IvanSanchez** [comment] 2018-04-25 13:05
@EkkehardDomning No problem. In this case it was a bit hard to know there's a duplicate.
