### ISSUE TITLE
setStyle on GeoJSON-layers doesn't set className

### ISSUE THREAD

**Issue by fab1an** [Leaflet/Leaflet#3791] opened 2015-08-31 09:15 UTC
I have a mouseOver-function which calls `setStyle({className: "xyz"})` on a GeoJSON-layer.

This change isn't applied, if I set a property like `stroke: "none"` that works.

**Comment by mourner** [comment] 2015-08-31 09:18
Duplicate of #2662

**Closed by mourner** 2015-08-31 09:18 UTC
