### ISSUE TITLE
Using OSM based tiles should give an 'Edit the map' link in the attribution by default

### ISSUE THREAD

**Issue by planemad** [Leaflet/Leaflet#4140] opened 2016-01-13 05:45 UTC
A link to OSM to edit the map at a given location along with the attribution can help drive more contributions to the map and makes it convenient for existing mappers to correct any map issues they see on any website that uses OSM on leaflet.

Right now its quite painful to see obvious map mistakes, but there is no convenient way for me to edit the location easily on 3rd party sites that use OSM tiles.

**Comment by planemad** [comment] 2016-01-13 05:47
Editing the map directly is a core feature and usp of OSM, so this should be the default setting, which can be turned off as an option if required.

**Comment by yohanboniface** [comment] 2016-01-13 07:05
Leaflet has no way to know if the map tiles are OSM based or not. I appreciate the attention (help making OSM better), but I don't think the suggestion here can be done.
There are plugins to take care of this (http://leafletjs.com/plugins.html#suprdsup-party-integration, not all are referenced AFAIK).

I'm closing because I think there is nothing here that Leaflet can do (and thus no action required from us), but the debate is still open in case I'm missing something :)

**Comment by yohanboniface** [comment] 2016-01-13 07:06
I know at least this one not on the list https://github.com/osmlab/leaflet-edit-osm

**Closed by yohanboniface** 2016-01-13 07:05 UTC

**Comment by mourner** [comment] 2016-01-13 10:05
> Editing the map directly is a core feature and usp of OSM, so this should be the default setting, which can be turned off as an option if required.

Yeah, that's true. But as @yohanboniface said, the problem is that OSM is not part of Leaflet default. Leaflet doesn't come with any tile layers by default. So this is developer's responsibility.

**Comment by planemad** [comment] 2016-01-13 10:13
This is unfortunate. The issue is that developers would not really  care to take the extra effort to add a plugin since it makes no difference to their app.

@mourner @yohanboniface any other alternate ideas on how this could be achieved? maybe checking if the attribution text contains `OpenStreetMap`?

**Comment by mourner** [comment] 2016-01-13 10:45
> maybe checking if the attribution text contains OpenStreetMap?

Leaflet doesn't contain any vendor-specific code in principle and never had any. We can't change this. Perhaps we could improve examples on leafletjs.com, but I don't think we can do anything beyond that.

**Comment by planemad** [comment] 2016-01-13 10:57
Yes, considering everyone looks at the examples to create their first leaflet map, we should definitely have one that shows how this could be done. 

i'll take a look at https://github.com/osmlab/leaflet-edit-osm to see if that can be spruced up to do this in the attribution control.

cc @tmcw
