### ISSUE TITLE
Uncaught exception in _checkDisabledLayers

### ISSUE THREAD

**Issue by marcellangmaier** [Leaflet/Leaflet#5364] opened 2017-03-02 08:04 UTC
When I am using a Map on a page where a Devexpress PageControl resides, there are uncaught exceptions in the _checkDisabledLayers and _onInputClick functions when hovering the layer control or after zoom. During debugging I found out, that the DevExpress control is adding some inputs called 'DXCss' and 'DXScript', which of course have no layerId property.

If I add the layerId undefined check in both functions, no exception occurs and everything works as expected.
```
            for (var i = inputs.length - 1; i >= 0; i--) {
                input = inputs[i];
                if (input.layerId === undefined) continue;  // adding this line prevents exception
```

Maybe there are other controls/frameworks outside, where this behaviour occurs.
Could you add such a check? So that I can use the official version again?

## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome 56
- OS/Platform (with version) I'm using: Windows 10
- add DevExpress PageControl to page (ASPX WebForms)
- add Leaflet Map
- zoom in or out, or hover the layer control

## What behaviour I'm expecting and which behaviour I'm seeing
no javascript exception

**Comment by IvanSanchez** [comment] 2017-03-02 09:06
> During debugging I found out, that the DevExpress control is adding some inputs called 'DXCss' and 'DXScript', which of course have no layerId property.

Then this is a duplicate of #5116. Should be an easy fix, but nobody has sent a PR for that yet. :-|

**Comment by perliedman** [comment] 2017-03-02 11:39
Closing as duplicate.

**Closed by perliedman** 2017-03-02 11:39 UTC
