### ISSUE TITLE
scrolling inside control container not possible

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet#5408] opened 2017-03-24 10:14 UTC
## How to reproduce

- Leaflet version I'm using: 1.0.3

I implemented a custom menu that I placed into the control container. When the screen is to small the menu doesn't fit anymore so I'd like to be able to scroll it. But no matter what I do the scroll is just passed through to the map.

As far as I can tell this is a Problem across all Browsers with the exception of Chrome on Android. 

I already tried using `L.DomEvent.disableScrollPropagation(menu)` but that didn't change anything.

## Minimal example reproducing the issue
http://playground-leaflet.rhcloud.com/nevo/edit?html,css,output

**Comment by IvanSanchez** [comment] 2017-03-24 10:18
Closing as a duplicate of https://github.com/Leaflet/Leaflet/pull/5280/files - in order to allow scrolling inside a control's elements, apply the same technique.

**Closed by IvanSanchez** 2017-03-24 10:18 UTC

**Comment by Eschon** [comment] 2017-03-24 10:32
Thanks for the quick answer!

My bad, `L.DomEvent.disableScrollPropagation(menu)` did fix it for Desktop browsers.  
For mobile devices I also had to add `L.DomEvent.disableClickPropagation(menu)`.
