### ISSUE TITLE
Leaftlet 1.0.0-beta.1 doesn't inject into HTML as dependency via grunt wiredep

### ISSUE THREAD

**Issue by 47ronin** [Leaflet/Leaflet#3851] opened 2015-09-18 01:03 UTC
Use `bower install --save leaflet#1.0.0-beta.1` or `npm install --save leaflet@1.0.0-beta.1` to create a Leaflet dependency in any Grunt project. `grunt wiredep` will normally inject the Leaflet jS/CSS link references into index.html but this does not happen.

Is this a bug and is there a workaround?

**Comment by IvanSanchez** [comment] 2015-09-18 01:22
Duplicate of #3635.

**Closed** 2015-09-18 01:22 UTC

**Comment by IvanSanchez** [comment] 2015-09-18 01:26
@47ronin See related issues for workarounds. Everything should go back to normal in the next release. And look for existing bug reports before creating a new one ;-)

**Comment by 47ronin** [comment] 2015-09-19 04:20
Sorry, I think the problem most people have is, they can't figure out what part of the process is broken —just that 1.0.0-beta.1 is new and everything else seems to work… so we're searching for all sorts of related issues but different keywords. In my case, I searched the issues for 'grunt' because that's normally what injects the dependencies into the project code and it failed in both `bower install --save` and `npm install --save`. I'll try to read all these and interpret a solution, thanks.
