### ISSUE TITLE
Popup content select in IE11 with touch support

### ISSUE THREAD

**Issue by surkova** [Leaflet/Leaflet#3149] opened 2015-01-16 09:51 UTC
Our product owner has a Lenovo laptop with touch display and Windows 8 onboard. He can neither select text in a popup (native for Leaflet) nor can he input text in a textarea in a popup. The easiest example, to test with, is the first popup example on Leaflet's homepage.

Leaflet disables all touch actions with `-ms-touch-action: none;` and it seems to be in the way of text selection. However, removing this property makes it impossible to use the map.

**Comment by danzel** [comment] 2015-01-18 21:54
What version of leaflet are you using?
JSFiddle to reproduce would be best.

**Comment by bodaniel** [comment] 2015-01-19 09:19
Version 0.7.3. Is this good enough? http://jsfiddle.net/n99tdn5b/embedded/result/. The text in the popup is not selectable in IE on a touch device.

**Comment by mourner** [comment] 2015-05-11 10:18
Looks like IE seems to inherit this property down to the popup element. An easy fix would be overriding the property on it.

**Comment by dijam** [comment] 2015-11-16 13:19
I've been looking for something similar in issues and this topic was the closest one to what I was looking for and it seems, it's been inactive for a while. 
I checked the select and it seems touch and text select is kind of impossible in Edge. But I have another issue. When I have textarea inside popup, I cannot touch in order to edit it or input any text in it.
I could make this fix for it in my code: http://jsfiddle.net/kxkdf8k1/5/
But I thought to share maybe you guys already thought about it.

**Comment by loisgh** [comment] 2017-09-02 21:19
If this is still open, I'll be happy to take this on.

**Comment by IvanSanchez** [comment] 2017-09-04 07:22
@loisgh Feel free to work on it 🙂

**Comment by MariamBashir** [comment] 2018-10-02 14:48
Hi, is this issue still open, ill be happy to take it on.

**Comment by techtimo** [comment] 2019-09-25 21:53
I have just chased up this issue. As the provided js fiddle seems not to work i have just used the example map from the [quick start example](https://leafletjs.com/examples/quick-start/).
I am using a HP Elitebook with Touch on Windows 10. I was able to select the text in the sample popup in IE11 as welll as in Edge 41.
I'm happy to to any further tests and answer questions.
If someone can confirm this, the issue can be closed.

**Comment by shwilliam** [comment] 2019-10-15 19:16
Using the [this fiddle](http://jsfiddle.net/n99tdn5b/embedded/result/) and testing on a ThinkPad X1E running Windows 10 I am able to both select text and close the marker using touch controls on Edge 44. However, on IE 11, while closing the marker works as expected, I am **not** able to select any text using touch controls.

**Closed** 2022-01-20 13:14 UTC
Labels: bug, help wanted, compatibility

**Comment by Falke-Design** [comment] 2022-01-20 14:26
@surkova why have you closed the issue? is this bug not existing anymore?

**Comment by surkova** [comment] 2022-01-20 18:24
This issue is 7 years old, the audience of Internet Explorer 11 has shrunken significantly. If it hasn’t been prioritized for such a long time, it will never get done.

**Comment by jonkoops** [comment] 2022-01-21 12:36
Fair enough, I think we might actually drop support for Internet Explorer entirely at some point after the 1.8 release.
