### ISSUE TITLE
Smoother tile updates

### ISSUE THREAD

**Issue by AndiLeni** [Leaflet/Leaflet#8360] opened 2022-07-30 18:07 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

When updating a WMS layers parameters, the transition when the tiles are updated is rather unpleasant.
Code used to update: `wms_layer.setParams({ time: "xyz" });`

### Expected behavior

The transition should be smoother.

### Current behavior

Comparison between leaflet (top) and openlayers (bottom):

https://user-images.githubusercontent.com/13385771/181936042-410aec1d-b16e-4d7d-838a-7933385dba60.mp4

### Environment

- Leaflet version: 1.8
- Browser (with version): FF 102
- OS/Platform (with version): Win 10

**Comment by IvanSanchez** [comment] 2022-07-30 18:44
Duplicate of https://github.com/Leaflet/Leaflet/issues/6659

**Closed by IvanSanchez** 2022-07-30 18:44 UTC
Labels: bug
