### ISSUE TITLE
Vandalism report: label for the Persian Gulf has been removed

### ISSUE THREAD

**Issue by psatarnamaha** [Leaflet/Leaflet#8798] opened 2023-01-14 11:15 UTC
Hello,

I noticed that the name label for the Persian Gulf has been removed.
Someone please fix it.

Cheers,

![image](https://user-images.githubusercontent.com/90156049/212469191-a227476d-d3d3-4b24-835d-a2ac8be4bf0a.png)

**Comment by Falke-Design** [comment] 2023-01-14 11:35
Duplicate of #4819.

We are not providing any map tiles. Leaflet is just a map display library. Look for the data provider. For example the map tiles on our demo are provided by [OpenStreetMap](https://www.openstreetmap.org/).

**Closed by Falke-Design** 2023-01-14 11:35 UTC

**Comment by IvanSanchez** [comment] 2023-01-14 11:43
Duplicate of #7569 and a bunch of others.
