### ISSUE TITLE
_handleGeolocationResponse: exception when map is already removed

### ISSUE THREAD

**Issue by googol7** [Leaflet/Leaflet#7508] opened 2021-03-15 13:10 UTC
See #2001

Seeing this error at 

[./src/dom/DomUtil.js:247](https://github.com/Leaflet/Leaflet/blob/0f904a515879fcd08f69b7f51799ee7f18f23fd8/src/dom/DomUtil.js#L247):	`return el._leaflet_pos || new Point(0, 0);`

**Comment by johnd0e** [comment] 2021-03-15 14:29
Why do you think that it is leaflet bug?
Can you provide sample code to reproduce the issue?

**Comment by googol7** [comment] 2021-03-15 15:00
I see such stacktraces:

/build/src/dom/DomUtil.js:247:11 getPosition
```
	// this method is only used for elements previously positioned using setPosition,
	// so it's safe to cache the position for performance
	

	return el._leaflet_pos || new Point(0, 0);
}
	

// @function disableTextSelection()
```


/build/src/map/Map.js:1476:29 _getMapPanePos
```
	// private methods for getting map state
	

	_getMapPanePos: function () {
		return DomUtil.getPosition(this._mapPane) || new Point(0, 0);
	},
	

	_moved: function () {
```


/build/src/map/Map.js:1493:66 _getNewPixelOrigin
```
	_getNewPixelOrigin: function (center, zoom) {
		var viewHalf = this.getSize()._divideBy(2);
		return this.project(center, zoom)._subtract(viewHalf)._add(this._getMapPanePos())._round();
	},
	

	_latLngToNewLayerPoint: function (latlng, zoom, center) {
```


/build/src/map/Map.js:1235:46 _move
```
		this._zoom = zoom;
		this._lastCenter = center;
		this._pixelOrigin = this._getNewPixelOrigin(center);
	

		// @event zoom: Event
		// Fired repeatedly during any change in zoom level, including zoom
```


/build/src/map/Map.js:1708:13 _onZoomTransitionEnd
```
		this._animatingZoom = false;
	

		this._move(this._animateToCenter, this._animateToZoom);
	

		// This anim frame should prevent an obscure iOS webkit tile loading race condition.
		Util.requestAnimFrame(function () {
```


/build/plugin-inline-script-content/inline-script-content.js:141:26
```
              // if this cb throws an error the line after will not get run so schedule
              // an almost-immediate aysnc update too
              _setTimeout(function () { updateLastScript(null) }, 0)
              const ret = cb.apply(this, arguments)
              updateLastScript(null)
              return ret
            }
```

**Comment by IvanSanchez** [comment] 2021-03-15 15:55
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by johnd0e** [comment] 2021-03-15 15:56
`this._mapPane` never should be `undefined`.
So you issue is not related to `getPosition`.

**Comment by googol7** [comment] 2021-03-15 16:09
@johnd0e any idea how this is likely to happen?

**Comment by johnd0e** [comment] 2021-03-15 16:20
Nobody can tell you unless you publish sample of code with reproducible issue.

**Comment by IvanSanchez** [comment] 2021-03-16 15:14
Closing this until a fully reproducible example is provided.

**Comment by googol7** [comment] 2021-11-05 20:19
@IvanSanchez Created an example [here](https://codepen.io/googol7/pen/yLoKyYm?editors=1111).

## Steps to reproduce:
1. Open the Browser console
1. Click "Locate me"
1. Click "Next". Make sure that you quickly press it so that the event `onHandleLocationFound` doesn’t fire.
1. Wait 5 to 10 seconds.

## Actual behavior
On the browser console you will see the error

```
DomUtil.js:247 Uncaught TypeError: Cannot read properties of undefined (reading '_leaflet_pos')
    at getPosition (DomUtil.js:247:12)
    at NewClass._getMapPanePos (Map.js:1476:10)
    at NewClass.containerPointToLayerPoint (Map.js:1050:39)
    at NewClass._getCenterLayerPoint (Map.js:1513:15)
    at NewClass._getCenterOffset (Map.js:1518:56)
    at NewClass._tryAnimatedPan (Map.js:1593:21)
    at NewClass.setView (Map.js:196:10)
    at NewClass._handleGeolocationResponse (Map.js:711:9)
```

## Expected behavior
The callback should detect that the map is not available anymore as it was unmounted in the meantime and prevent the error.


![Bildschirmfoto 2021-11-05 um 21 11 11](https://user-images.githubusercontent.com/282412/140573387-5065fa6f-5c39-4a9c-adeb-fe92e71239e6.png)

**Comment by Falke-Design** [comment] 2021-11-16 14:55
@googol7 I was not able to reproduce this. I can't be fast enough to press `next` without sending `onHandleLocationFound`
@trickreich can you reproduce this?

Cheers from Bregenz ✌

**Comment by trickreich** [comment] 2021-11-16 15:42
@Falke-Design Yep, just use a incognito session and don't accept the locataion and click the next step instead.

**Comment by googol7** [comment] 2021-11-16 15:43
@Falke-Design Try the second approach please:

You can also do the following:
1. Open the Browser console
1. Click "Locate me"
1. Click "Next"
1. Allow the browser to locate by confirming the dialog:
![Bildschirmfoto 2021-11-16 um 15 44 17](https://user-images.githubusercontent.com/282412/142007873-72a8fc12-44d5-4e9e-a511-b08a56ea6252.png)
![Bildschirmfoto 2021-11-16 um 15 49 49](https://user-images.githubusercontent.com/282412/142007879-682f1d52-6749-419f-a487-485758ce574e.png)
1. Wait 5 to 10 seconds.

Greetings from Bregenz :smiley:

**Comment by Falke-Design** [comment] 2021-11-16 18:23
**Problem**
I dig into it and it is caused because the map is removed before the geolocation request is finished. Also I found out that this error is only happening if the zoom levels are equal:
https://github.com/Leaflet/Leaflet/blob/3466cbba34351ee0d7477a83eb0215cc0e6b454b/src/map/Map.js#L194-L196

In `map.remove()` the `mapPane` is removed.
https://github.com/Leaflet/Leaflet/blob/3466cbba34351ee0d7477a83eb0215cc0e6b454b/src/map/Map.js#L762

------

**Solution**
@johnd0e I suggest to add a check in `_handleGeolocationResponse` if map container is still on the document or if `this._mapPane` is set else return. If a user keeps  the "grant access request alert" open and then the map is removed for example after X minutes of waiting, it still executes the code and then the error will thrown. This error can not easy catched by the developers because it is a own thread.

------

**Test**
You can use the following code and then grant the access. After a few seconds the error should be show up. If `locationerror` is fired, try it again until it works.
```
map.locate({
	maxZoom: 14,
	setView: true,
}).on('locationfound', () => {
	console.log("onHandleLocationFound");
}).on('locationerror', () => {
	console.log("onLocationError. Try it again until a location is found");
});
map.remove()
```
https://jsfiddle.net/falkedesign/7cy2n3h0/

@googol7 I think your problem is that `map.remove()` is called internally from react-leaflet.

**Comment by trickreich** [comment] 2021-11-16 18:38
Thanks for the quick response!
In fact we have the error when the map dom node is removed an the callback is trigger.

Greetings from the Bregenzerwald 🗻

**Comment by johnd0e** [comment] 2021-11-17 07:26
> I suggest to add a check in `_handleGeolocationResponse` if map container is still on the document or if `this._mapPane`

Either check for `_leaflet_id` property, or check if there are real "locationfound" listeners.

**Comment by Falke-Design** [comment] 2021-11-17 07:53
It can't be checked on the `_leaflet_id ` because the map instance self has still the id. 

>  real "locationfound" listeners

What exactly do you mean with this? To still call `this.fire('locationfound', data)`? 
https://github.com/Leaflet/Leaflet/blob/3466cbba34351ee0d7477a83eb0215cc0e6b454b/src/map/Map.js#L713

**Comment by johnd0e** [comment] 2021-11-17 08:00
> map instance self has still the id.

`map.getContainer()._leaflet_id`


> What exactly do you mean with this?

```js
if (!this.listens('locationfound')) { return; }
```

**Closed** 2021-12-02 17:59 UTC
Labels: bug

**Comment by Falke-Design** [comment] 2021-12-13 13:23
When this [milestone](https://github.com/Leaflet/Leaflet/milestone/37) is completed, I think it will need sure 2 months.

**Comment by googol7** [comment] 2024-11-18 14:08
Another reproduction:

1. Use Firefox because it's slower
2. Add `onClick={() => window.setTimeout(() => window.history.back(), 0)}`to [src/components/Vehicle/Vehicle.tsx](https://github.com/zemtu/mobile/blob/db19591bf7fc6422d191ab7601f3f4991877f30d/client/src/components/Vehicle/Vehicle.tsx#L219-L230)
```ts
<Link
  onClick={() =>
      window.setTimeout(() => window.history.back(), 0)
  }
  style={{
      color: "inherit",
      textDecoration: "none",
  }}
  to={link}
>
```
