### ISSUE TITLE
leaflet js on android browser and android chrome cant't locate

### ISSUE THREAD

**Issue by fmiguelroliveira** [Leaflet/Leaflet#3434] opened 2015-05-06 14:25 UTC
I'm developing a website that uses leaflet js for building maps that uses locate function to get user location.

The website works fine (locates user) in desktop browsers although in android browser as well in android chrome it always return:

geolocation error: timeout expired

I believe android tries to locate, because the first time he accesses the site, browser asks for permission to access current location. After a while e returns the geolocation error: timeout expired

I've tried to find solutions for this issue with no success.

Thanks in advance

**Comment by IvanSanchez** [comment] 2015-05-06 14:34
This is possibly a duplicate of #3384.

Also, when reporting a possible bug, provide a use case or a way for developers to reproduce the problem. Does http://leafletjs.com/examples/mobile-example.html work for you? Are you using geolocation with custom options?

**Comment by fmiguelroliveira** [comment] 2015-05-06 14:50
Nope, it also returns:

geolocation error: timeout expired

This is my code:

function initAllInMap(divMap)
{
	map = L.map(divMap, {
	    contextmenu: false,
	});
	
	map.setView([0,0], 13);
	
	L.tileLayer('http://{s}.tiles.mapbox.com/v3/{id}/{z}/{x}/{y}.png', {
		attribution: localeText.quote,
		maxZoom: 18,
		id: 'myid'
	}).addTo(map);
	
        map.attributionControl.setPrefix(localeText.udereUrl);
	map.on('locationfound', onLocationFound);
	map.on('locationerror', onLocationError);

        map.on('moveend', function(e) {markAllUsersCheckedIn();});
        map.locate({watch: false, setView: true, maxZoom: Infinity, timeout: 1000*60, enableHighAccuracy: true, maximumAge: 1000*60*60});
}

**Comment by IvanSanchez** [comment] 2015-05-06 15:11
And what happens when you use the raw HTML5 geolocation API? e.g.:

```js
navigator.geolocation.getCurrentPosition(
    function(response){ console.log(response)},
    function(error)   { console.error(error)},
    {timeout: 1000*60, enableHighAccuracy: true, maximumAge: 1000*60*60} 
);
```

**Comment by fmiguelroliveira** [comment] 2015-05-06 15:43
Same problem.

**Comment by IvanSanchez** [comment] 2015-05-06 15:45
> Same problem.

Then it is not a Leaflet issue.

**Closed by IvanSanchez** 2015-05-06 15:45 UTC

**Comment by fmiguelroliveira** [comment] 2015-05-06 16:09
Raw html5 works fine in desktop but the timeout appears on several devices. Do you know any reason for that happening?

**Comment by kanishk-mehta** [comment] 2015-07-31 05:00
hi fmiguelroliveira,
I ran into the same issue and ended up using the Mapbox api to solve my issue.
[check this page] https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-locatecontrol/

add this to the body section of your code:
<script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js'></script>
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css' rel='stylesheet' />
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/css/font-awesome.min.css' rel='stylesheet' />

and then add this control to your map

L.control.locate().addTo(map);

**Comment by kanishk-mehta** [comment] 2015-07-31 05:04
hi fmiguelroliveira, 
i ran into the same issue a while back. try using the mapbox api:
[check this page] https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-locatecontrol/

im trying to work it out myself right now.

add this to the body section of your code:
< script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js'></script>

< link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css' rel='stylesheet' />

< link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/css/font-awesome.min.css' rel='stylesheet' />

and then add this control to your map

L.control.locate().addTo(map);

**Comment by hitecSmartHome** [comment] 2024-03-29 21:32
Location still sucks on android
