### ISSUE TITLE
Input elements in controls on top of the map won't respond to touch on IE11

### ISSUE THREAD

**Issue by fnicollet** [Leaflet/Leaflet#2699] opened 2014-05-21 22:58 UTC
Hi,

This issue only happens on recent version of IE11 with touch enabled. If you have a select tag in a leaflet-control, it won't open when you tap on it.
Debugging the code, the function addPointerListenerStart is called when initializing the map and adds a "pointerdown" listener on the map (and all his descendants).
In the callback function, the first instruction is:

L.DomEvent.preventDefault(e);

Which prevent the default select behaviour (opening the options). From what I see, it should also affect inputs in other components such as marker popups.

I am not sure how to fix this

Thanks,
Fabien

**Comment by yohanboniface** [comment] 2016-04-02 10:46
@perliedman can you just have a quick look with IE11 to see if the issue is still present, and if then we should close, fixed during today sprint, keep as 1.0 fix or move to 1.1? :)

**Comment by perliedman** [comment] 2016-04-02 11:10
Example to test this out using latest Leaflet-dev: https://playground-leaflet.rhcloud.com/rul/edit?html,output

**Comment by perliedman** [comment] 2016-04-02 11:33
This is still a problem on IE11. I'm going for implementing that changes suggested by @danzel in https://github.com/Leaflet/Leaflet/issues/2699#issuecomment-44219069 and https://github.com/Leaflet/Leaflet/issues/2699#issuecomment-44222633.

**Comment by perliedman** [comment] 2016-04-02 12:30
`L.DomEvent.disableClickPropagation` stops propagation of `touchstart` for touch devices; for the `select` element, this unfortunately prevents it from opening on touch (at least in IE11, still works in Chrome). So it looks like modifying and using `disableClickPropagation´ is not an option, since it must disable `touchstart`.

**Comment by perliedman** [comment] 2016-04-18 09:09
Closed by #4371, we `preventDefault` on some form controls in IE.

**Closed by perliedman** 2016-04-18 09:09 UTC
Labels: accepted, bug, help wanted
