### ISSUE TITLE
Marker gets dropped without releasing the mouse button when trying to drag it fast

### ISSUE THREAD

**Issue by jperelli** [Leaflet/Leaflet#5916] opened 2017-11-15 01:29 UTC
## How to reproduce

- Leaflet version I'm using:  1.2.0+Detached: 1ac320ba232cb85b73ac81f3d82780c9d07f0d4e.1ac320b
- Browser (with version) I'm using: chrome 63.0.3239.40 (Official Build) beta (64-bit)
- OS/Platform (with version) I'm using: Linux Ubuntu 17.10
- add a marker to the map, make it draggable
- add some processing to the drag event
- as a user, drag the marker around

## What behaviour I'm expecting and which behaviour I'm seeing

When dragging the marker without releasing the mouse button, I'm expecting the marker not to drop.
The behaviour I'm seeing is that when I move the marker slowly, it works just fine, but when I move it around a little faster, the marker just drops, without releasing the mouse button. 

Repro link https://plnkr.co/edit/8TkncJ8oLCTJ2jxVMufu?p=preview

**Comment by ghybs** [comment] 2017-11-15 02:43
Hi,

Please share enough data and code so that we can reproduce your issue.

I am unable to get the behaviour you describe with Leaflet 1.2.0 on Chromium 62 and Firefox 56 (Kubuntu 16.04):
https://plnkr.co/edit/lW1PSp5aGyrZhjeIRLHf?p=preview

**Comment by jperelli** [comment] 2017-11-15 03:37
Ok, I found the root of the problem, It might be not a Leaflet issue after all...
this is the simplest repro I could make https://plnkr.co/edit/8TkncJ8oLCTJ2jxVMufu?p=preview

It seems that it happens when I try to change the icon when hovering. Should I do that in some other way?

**Comment by ghybs** [comment] 2017-11-15 11:47
When you drag and move the mouse fast, it easily happens that the DOM element (marker icon) does not follow quickly enough, therefore firing a `"mouseout"` event.

When this happens, your code dynamically changes the marker icon.
This sounds to me like a duplicate of https://github.com/Leaflet/Leaflet/issues/4484.

Several other issues are related and have been fixed, I am not exactly sure why that one could not be fixed yet.
It might be due to this part of Marker code:
https://github.com/Leaflet/Leaflet/blob/1ac320ba232cb85b73ac81f3d82780c9d07f0d4e/src/layer/marker/Marker.js#L295-L305

In your case, it seems like the workaround proposed in https://github.com/Leaflet/Leaflet/issues/561#issuecomment-17659859 could work for you:
```javascript
marker._icon.src = newImageUrl;
```
https://plnkr.co/edit/6zPzzTP5FKufmmTzTPfi?p=preview

Pushing further this trick to modify the already existing DOM element (in case you need to adjust other options like size, anchor, etc.) without using `marker.setIcon` should enable you doing most of what you need.

Therefore I am going to close this in favour of https://github.com/Leaflet/Leaflet/issues/4484.
Please feel free to comment further on that issue, or re-open here if you think your issue is different.

**Closed by ghybs** 2017-11-15 11:47 UTC
Labels: needs more info

**Comment by jperelli** [comment] 2017-11-15 17:53
Thanks! really helpful. And you are right, it is a duplicate of #4484.
