### ISSUE TITLE
Bearing, rotating, pitch, tilt, angle

### ISSUE THREAD

**Issue by josuelmm** [Leaflet/Leaflet#9158] opened 2023-11-04 18:09 UTC
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Good day, it is possible in the near future to add the option of Bearing, rotating, pitch, tilt, angle. 
Examples:
https://maplibre.org/maplibre-gl-js/docs/examples/set-perspective/
https://docs.mapbox.com/mapbox-gl-js/example/set-perspective/
https://developers.google.com/maps/documentation/javascript/webgl/tilt-rotation?hl=es-419

### Suggested solution

Add option in map

**Comment by Falke-Design** [comment] 2023-11-04 18:26
Duplicate of #268

**Closed by Falke-Design** 2023-11-04 18:26 UTC
Labels: feature, needs triage
