### ISSUE TITLE
A mouse click on Safari generates two events, and the second is always 'click' even using right mouse button

### ISSUE THREAD

**Issue by paulatthehug** [Leaflet/Leaflet#7887] opened 2022-01-03 20:57 UTC
**Steps to reproduce**

- Go to https://plnkr.co/edit/PmzoUQD7cNUbcbIb?preview
- Make sure you have the Javascript console open
- left click on the map
- right click on the map

**Expected behaviour**

Based on the documentation I'd expect each click to produce a single event and in the log you should see "left mouse click" generated by map.on('click') and then "right mouse click" generated by map.on('contextmenu').

**Current behaviour**

This all works as expected with Firefox and Chrome. I should mention in passing, as you will see, that the events are triggered on button up for left mouse and button down for right mouse.

However if you do this on Safari then for the left click you get **two** left click events - one on button down, another on button up - and for right click you get a right click event on button down and then a **left** click event on button up.

**Some thoughts on a fix**

In the code where I first discovered this I have a work around which I'm using for now and the example illustrates how this can be made to work. With Safari the event has a property originalEvent.webkitForce (which I'm displaying in the console log). If, in your left click event handler, you ignore any left click event where it was a value of zero then you can get behaviour consistent with Firefox or Chrome so it occurs to me that this might be a simple way to fix this within Leaflet itself ...

**Environment**

- Leaflet version: 1.7.1
- Browser: Safari 15.2 (15612.3.6.1.8, 15612)
- OS/Platform: MacOS Catalina

**Comment by paulatthehug** [comment] 2022-01-03 21:47
It occurs to me that I didn't mention a key fact which is that I'm not a Mac user, and never have been. I'm running MacOS in a Virtualbox VM on Linux which is why I have a two button mouse (with a scroll wheel) ... but I gather from Googling about that some Mac users do use two button mice so this issue will presumably apply there too, and even with a one button mouse two .on('click') events for each mouse click is not as per the documentation.

**Comment by IvanSanchez** [comment] 2022-01-04 03:20
Duplicate of https://github.com/Leaflet/Leaflet/issues/7255

**Closed by IvanSanchez** 2022-01-04 03:20 UTC
