### ISSUE TITLE
Marker (in LayerGroup in Pane) not placed in the expected order

### ISSUE THREAD

**Issue by cintek** [Leaflet/Leaflet#8971] opened 2023-05-25 09:24 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Place one circle in a Pane with index 821
2. Place another circle in a Layergroup which was added to a different pane with index 850

### Expected behavior

Expected the orange circle to be on top of the red circle because the orange circle belongs to the LayerGroup `orangeGroup` which is in the Pane `orange` which has a higher z-index than Pane `red` with the red circle.

### Current behavior

The red circle is on top of the orange circle.

I'm not 100% sure if this is not expected but I didn't find a hint in the docs that it should work like this.

### Minimal example reproducing the issue

https://plnkr.co/edit/MN6JUsDJfhwW3htm?preview

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Firefox 113.0.1
- OS/Platform (with version): Zorin OS 16

**Comment by IvanSanchez** [comment] 2023-05-25 11:06
Duplicate of https://github.com/Leaflet/Leaflet/issues/8958

`L.Path`s (including `L.Circle`s) are added to a `L.Renderer`, not to a map pane.

**Closed by IvanSanchez** 2023-05-25 11:06 UTC
Labels: bug, needs triage
