### ISSUE TITLE
0.8-dev L.circle with tiny radius renders wrong

### ISSUE THREAD

**Issue by johnwillyn** [Leaflet/Leaflet#2425] opened 2014-01-30 14:21 UTC
When creating a circle with a very small radius of 0.01 (m), Leaflet 0.8-dev renders it incorrectly.  I tracked this down to the calculation of lngR in L.Circle._project an patched my version to use the old version of this calculation.  I have not had a chance to debug the new calculation.

Here is the line and my patch to the old code:

                            lat2 = map.unproject(p).lat;
			    //var lngR = latR / Math.cos(Math.PI / 180 * lat); //old way
			    lngR = Math.acos((Math.cos(latR * d) - Math.sin(lat * d) * Math.sin(lat2 * d)) /
			            (Math.cos(lat * d) * Math.cos(lat2 * d))) / d;

And here is what it renders like in 0.8-dev:
![screen shot 2014-01-30 at 9 20 04 am](https://f.cloud.github.com/assets/2018351/2040629/a6051e72-89b9-11e3-865c-67a8887252a9.png)

I am doing testing of hi-precision GPS devices and this is how I test for 'cm' accuracy, so use these tiny radius circles to test results.

**Comment by IvanSanchez** [comment] 2015-06-05 14:49
Already fixed as part of #2345 in https://github.com/Leaflet/Leaflet/pull/2345/files#diff-e63d205690b47d6a456c0d77565b55c5R47

**Comment by mourner** [comment] 2015-06-05 15:29
@IvanSanchez the issue was created after the pull request got merged, so probably not.

**Comment by yohanboniface** [comment] 2015-10-12 13:03
@johnwillyn can you by chance try with latest master to see if issue is still there? If yes, can you set up a minimal test case on http://playground-leaflet.rhcloud.com/ to demonstrate the issue? Thanks!

**Comment by Eschon** [comment] 2015-10-14 11:06
I've seen this at least in 1.0 beta1 but I never managed to make a minimal test case. I'll check it again the next days when I have the time.

**Comment by johnwillyn** [comment] 2015-10-14 23:26
Hi Guys,
I don't use Leaflet vector drawing in this manner any longer.  I replaced it with my own vector layer.  I will try to dig up some old code to create a test case.
John

**Comment by Eschon** [comment] 2015-10-15 12:45
Ok I don't know why I had problems reproducing [this fiddle](http://jsfiddle.net/Eschon/drcjcwya/1/) shows it perfectly well on leaflet 1.0-beta3.

Reproduces on:
* Safari 9.0
* Firefox 41.0.1
* Firefox 43.0a2 (2015-10-13)

On latest Chrome it seems to work.

**Comment by IvanSanchez** [comment] 2015-10-15 12:56
@Eschon beta3 doesn't exist yet :-P

**Comment by Eschon** [comment] 2015-10-15 12:57
:sweat_smile: I mean beta2 of course

**Comment by mourner** [comment] 2015-10-15 13:03
@Eschon thanks for looking into this!

**Comment by yohanboniface** [comment] 2015-10-20 07:28
Humm, at this stage I'm not even sure what do we mean by "renders wrong". I can see that the radius is smaller in 1.0beta than in 0.7.x, but nothing says it was "correct" in 0.7.x: if I move the circle to [0, 0] and set the path weight like it was in 0.7.x (5, while it's now 3 by default) both seems equal to me: http://playground-leaflet.rhcloud.com/len/1/edit?html,output

The image in the description of this ticket shows a distorted radius that looks like a line, but now I can only see a normal circle:

![screenshot from 2015-10-20 09 23 24](https://cloud.githubusercontent.com/assets/146023/10600615/3f0e9454-770c-11e5-9868-b4e03c7fa2eb.png)

@Eschon can you be a bit more precise on what's wrong and what you are expecting instead?

**Comment by mourner** [comment] 2015-10-20 09:27
@yohanboniface I assume it was rendering as shown in the screenshot at the top, stretched vertically.

**Comment by yohanboniface** [comment] 2015-10-20 09:28
@mourner but is it still the case? That's my question ;)

**Comment by Eschon** [comment] 2015-10-21 10:22
@yohanboniface have your tried my fiddle in Firefox or Safari?
There it should be clearly visible.

In Chrome it looks like your screenshot for me too.

**Comment by IvanSanchez** [comment] 2016-01-08 13:34
I'm having a look at this. Apparently, the calculations for the `lngR` variable drop to zero when the circle radius is approx > 0.1. This makes the circle x-radius to be zero plus line width.

**Comment by IvanSanchez** [comment] 2016-01-08 13:53
Ultimately a precision issue - the "new" calculations using `acos(cos-sin*sin/(cos-cos))` run into the 32-bit float number precision limit much much faster than the "old" one.

#4133 can work around this by falling back to the older calculation, which is more precise but produces a worse shape in some scenarios (less accurate).

**Closed** 2016-01-08 16:35 UTC
Labels: bug, in progress
