### ISSUE TITLE
White lines with maptiles

### ISSUE THREAD

**Issue by hhhc** [Leaflet/Leaflet#8408] opened 2022-08-20 09:54 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

When zooming into a map, white lines show up.
This behaviour is app independant and can also be seen on the demo pages, for example: https://leafletjs.com/examples/wms/wms.html

Screenshot from above demo pages with latest Chrome:
<img width="1062" alt="Chrome" src="https://user-images.githubusercontent.com/961087/185739847-b4ff4517-1d32-4dde-bc6a-4504d959edb1.png">

### Expected behavior

No white lines should appear.

### Current behavior

When zooming into a map, white lines show up.

### Minimal example reproducing the issue

https://leafletjs.com/examples/wms/wms.html

### Environment

- Leaflet version: 1.7 and 1.8
- Browser (with version): On Desktop basically all browsers, Safari Version 15.6 (17613.3.9.1.5), Chrome 104.0.5112.101
- OS/Platform (with version): Mac

**Comment by IvanSanchez** [comment] 2022-08-20 11:30
Duplicate of #3575

**Closed by IvanSanchez** 2022-08-20 11:30 UTC
Labels: bug, needs triage
