### ISSUE TITLE
freezing on marker drag

### ISSUE THREAD

**Issue by Dexus** [Leaflet/Leaflet#5079] opened 2016-11-07 17:32 UTC
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.1
- Browser (with version) I'm using: Chrome latest stable
- OS/Platform (with version) I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing

I expect that i can drag the marker in the same way as with 0.7.x.

But if i click and start drag the map/marker freeze and dont let me drag. The cursor icon stil hangs as drag but now i cant do nothing...

## Minimal example reproducing the issue

https://jsfiddle.net/b1m0o085/

**Comment by IvanSanchez** [comment] 2016-11-07 17:35
Duplicate of https://github.com/Leaflet/Leaflet.markercluster/issues/685

**Closed by IvanSanchez** 2016-11-07 17:35 UTC
