### ISSUE TITLE
Mouseout event triggered on removed L.Path throws TypeError

### ISSUE THREAD

**Issue by sambernet** [Leaflet/Leaflet#3844] opened 2015-09-15 15:07 UTC
**Description:**
If a Path is removed from the map while in 'mouseover state' (the mouse is still over the element - the mouseover event has been triggered but the mouseout event not yet), then the next mousemove event will trigger a mouseout event on the Path. As the path has been removed from the map when this event is triggered, the this._map property has already been nulled and the event throws an uncaught TypeError in _fireMouseEvent. 

**Stack trace:**
Uncaught TypeError: Cannot read property 'mouseEventToContainerPoint' of null
o.Path.o.Path.extend._fireMouseEvent @ leaflet.js:7
o.DomEvent.addListener.t.(anonymous function).s @ leaflet.js:8

**Test case:**
Minimal jsFiddle test case can be found here:
http://jsfiddle.net/Ldp25Lf4/

**Affected Versions:**
Note that this happens on *0.75 / stable* only, but *not on 1.0.0-beta.1 / master* (due to major refactorings in that part of the code).

**Browser:**
Tested on Firefox 40.x and Chrome 45.x

**Comment by yohanboniface** [comment] 2015-09-15 15:11
Duplicate of #3829

**Closed by yohanboniface** 2015-09-15 15:11 UTC
