### ISSUE TITLE
Canvas mouse move events not fired when another canvas put over top.

### ISSUE THREAD

**Issue by Spaction** [Leaflet/Leaflet#6205] opened 2018-06-22 21:28 UTC
Fiddle with very simple example below.
Note the left side has the simple Canvas over top the polygon, while the right does not and is interactable
[https://jsfiddle.net/9zy64frx/12/](https://jsfiddle.net/9zy64frx/12/)

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Chrome 67.0.3396.87, IE Edge 41.16299.402.0, Firefox 60.0.2
- OS/Platform (with version) I'm using: Win 10

When having preferCanvas enabled and drawing a Polygon, the Canvas object binds events to the Canvas object itself. If any 3rd party plug-in wants to also use a Canvas, depending on the order the two canvas's are added to the DOM, the Leaflet Canvas will not have the events fired when the other canvas is on top as the mouse is not interactive with the canvas below the other.

Without adding every object that can be created into the canvas, simply moving the binding for events from the Leaflet Canvas onto the Map itself should eliminate the issue.

**Comment by jbccollins** [comment] 2018-06-26 13:19
Add the CSS rule
```
pointer-events: none;
```
to the canvas that you are overlaying. Your mouse events should now propagate through.

Here's an updated fiddle
https://jsfiddle.net/9zy64frx/14/

**Comment by Spaction** [comment] 2018-06-26 16:12
@jbccollins 

This assumes the canvas you are creating does not want to be interacted with. If the canvas is made a little more complex, such as adding any type of interactivity, then the canvas you put over top will not be able to function due to this CSS.

**Comment by jbccollins** [comment] 2018-06-26 16:50
Well. IMO handling mouse interactions with third party overlays (canvas or otherwise) is outside the scope of Leaflet core.

I personally use https://github.com/Sumbera/gLayers.Leaflet which extends Leaflet to give you a built in L.canvasLayer that plays nicely with other Leaflet elements.

```
const lat = 0;
const lng = 0;
L.canvasLayer().delegate({
      onDrawLayer: info => {
        // Draw whatever you need to draw right here
        var ctx = info.canvas.getContext('2d');
        ctx.clearRect(0, 0, info.canvas.width, info.canvas.height);
        const dot = info.layer._map.latLngToContainerPoint([lat, lng]);
        ctx.beginPath();
        ctx.arc(dot.x, dot.y, 5, 0, Math.PI * 2);
        ctx.fill();
        ctx.closePath();
      }
    });
```

And if you happen to be using React I can give you the React wrapper component I use for that as well :)

**Comment by Spaction** [comment] 2018-06-26 20:13
Please stop referencing or pointing to projects which have no interactivity on the canvas you are adding, this is arguing apples to oranges. If you want to know where this is coming from, it is with https://github.com/eJuke/Leaflet.Canvas-Markers project. This fulfills a gap in Leaflets implementation of canvas for allowing actual Markers (not Circle Markers) to be created in a canvas, with the implementation of everything that comes with markers.

Simply put, changing the bindings of Leaflet's canvas implementation to the map and stopping propagation when an element is "hit" will allow for other canvas's to interact with the map as well and not just Leaflets.

As a work around is to insure all Canvas implementations which are wanted to have interactions are pushed to the back of the Dom and is created in the overlay pane. This requires adding
`L.DomUtil.toBack(this._container);`
after the containers add to the Pane.

**Comment by jbccollins** [comment] 2018-06-26 21:38
If you want to make a PR to Leaflet core that does this then go for it. I think it's unlikely to get merged but it can't hurt to try I guess.

In the meantime...

You could try using color masking hit detection for events drawn on a canvas to achieve interactivity.

Here's a working demo:
https://jsfiddle.net/uyhzx2qd/52/

Try clicking on the shapes

There are some drawbacks to doing that but I get the feeling that you won't be interested in this option so /shrug

**Comment by Spaction** [comment] 2018-06-26 22:18
I don't think we are on the same page...

It is not that I cannot get interactivity. It is the fact that when preferCanvas is enabled and anything is drawn on the Canvas (such as an L.polygon), you can not interact with the canvas when you draw over top it.

Taking your example: enabling preferCanvas & adding a Polygon before the adding of your canvas, prevents any interaction with the Blue polygon behind.

https://jsfiddle.net/uyhzx2qd/59/

This is also not an issue with Leaflet Core (Sorry, I did not realize Leaflet was split in this manor), it is dealing specifically with layer/vector/Canvas

**Comment by danwild** [comment] 2018-09-10 04:49
Related to: #5739, #5752

This is definitely an issue.
Adding any kind of canvas layer blocks events to any other layers below it in the stack 😞

There is an event forwarding PR (#6012) that was previously considered but needs further work.

**Comment by perliedman** [comment] 2018-09-11 08:28
As @danwild says, this is a duplicate of #5739, so I'm going to close this; there are workarounds, although not nice.

#5752 is an attempt to address the issue, but it's not complete and it seems the author lost interest in finishing it (don't be fooled by the PR saying "Merged" - I accidentally merged it, but then reverted it, so it's still not in any release Leaflet version).

**Closed by perliedman** 2018-09-11 08:28 UTC

**Comment by danwild** [comment] 2018-09-12 04:29
Hi @perliedman, given that this issue and #5739 are both closed, are we saying this is not an issue (IMO it is, given that canvas is supported by leaflet now)?

If not, at the very least it should probably be noted in the docs, that - when using a canvas layer, interaction with any other layers below it in the stack will be void.

I'd imagine many would think twice before using canvas if they were aware of this major limitation.

The only current [forewarning in then docs](https://leafletjs.com/reference-1.3.4.html#canvas) are for `IE8`, and that "overlapping geometries might not display properly in some edge cases"

**Comment by perliedman** [comment] 2018-09-12 15:01
@danwild This is a quite fundamental difference between SVG and Canvas: Canvas is a solid layer that you can either disable pointer events entirely for, or it will catch all events. We could work around this fact with hacks (like #5752 attempts), but it will be _hacks_ to emulate events passing through the layer. You can also work around it with the hack I linked to in #5739: https://gist.github.com/perliedman/84ce01954a1a43252d1b917ec925b3dd - I've used that in a Leaflet app with multiple Canvas / VectorGrid layers, it worked out ok.

I would agree that a word of warning in the docs would be nice, help in the form of a PR would be great. Perhaps finishing #5752, or even better turning it into a plugin, would also be a nice solution, IMO. Having said that, for a lot of common use cases, this is not an issue though, since interaction is with overlays that will all be in the canvas.

**Comment by danwild** [comment] 2018-09-13 02:42
I understand the challenges introduced by canvas elements not existing in the dom as with other layers, but think that given leaflet supports multiple overlays, and is by it's own definition:

> an open-source JavaScript library
for mobile-friendly <strong><em>interactive</em></strong> maps

Suggests (to me anyway) that it should handle interaction for more than one overlay at a time, but yes - I accept in reality any solution is going to be a hack (.."event emulation" sounds nicer? 😉).

Regardless - thanks for the additional info and gist, I will look a little closer and think about how a plugin might work (I'd like `mousemove` events so might be dreaming..).

I also understand a generic solution might be tricky given layers can be nested arbitrarily in [panes..](https://leafletjs.com/reference-1.3.4.html#map-pane)

**Comment by danwild** [comment] 2018-09-16 22:59
Just a quick note - I went ahead and hacked [a plugin](https://github.com/danwild/leaflet-event-forwarder) together, it is based pretty heavily on the approach in your gist @perliedman.

Plugin is a little crude but pretty much achieves what I need.

Cheers,
Dan
