### ISSUE TITLE
Animated setView causes grid on Chrome

### ISSUE THREAD

**Issue by ultimate-tester** [Leaflet/Leaflet#6696] opened 2019-06-13 09:41 UTC
Hi, this issue is the same as described in #6101.
When moving the map with the mouse everything is fine but when using animated setView, it causes the grid described in #6101.

Is this a known issue and is it on the backlog to fix? Otherwise I'm willing to create a pull request but seeing there's 95 pull requests already I'm not sure if it will be picked up. Just want to check.

**Comment by IvanSanchez** [comment] 2019-06-13 09:58
Yes, that's a duplicate of #6101 and the answer is still the same: debug https://github.com/Leaflet/Leaflet.TileLayer.NoGap , see that it doesn't introduce any regressions *at all*, decide with other maintainers whether to include it in core leaflet or not.

**Closed by IvanSanchez** 2019-06-13 09:58 UTC

**Comment by ultimate-tester** [comment] 2019-06-13 10:06
That's fine, but I was able to solve this by rounding the _step in the animation. There's a flag unspecified in the Animation object, which I think was overseen. This causes the animation steps not to be rounded off and therefore it starts glitching with the tiles. I'm asking why is the round flag not set for the Step in the animation? I can't see any visual change to the animation itself. The grid is gone, it seems like a full fix for the problem....
