### ISSUE TITLE
Disappearing vectors

### ISSUE THREAD

**Issue by Mappavini** [Leaflet/Leaflet#6864] opened 2019-10-18 10:01 UTC
Hi,

We created a cartographic tool about wine in different regions. We have discovered a problem of displaying vectors, whatever the region and which seems to come from the leaflet engine...
During navigation (essentially pan) vectors disappear partially or totally. It can be seen following several pan to the north.

Here is a link to a map: [https://mappavini.com/vignoble/valais](url)
Try several pan to the north and see the result:

![image](https://user-images.githubusercontent.com/13860016/67085233-be385380-f19e-11e9-9834-0738fdab7a82.png)

![image](https://user-images.githubusercontent.com/13860016/67085186-a791fc80-f19e-11e9-9104-7924ba332a15.png)

We did not find this problem among the issues.

However the introduction of code in the console temporarily fixes the problem:
`mapavini.map._resetView(mapavini.map.getCenter(), mapavini.getZoom())
`

Comparable experiences? Sustainable solution?

Thanks in advance!

**Comment by ghybs** [comment] 2019-10-18 20:59
Duplicate of #2814

**Closed by ghybs** 2019-10-18 20:59 UTC

**Comment by Mappavini** [comment] 2019-10-19 10:41
Hi @ghybs 
It is not at all a duplicate of #2814 !
Not surprisingly, the proposed solution does not work.
You could reproduce the event for you with the link that is included in my message ?
Cheers
Laurent

**Comment by ghybs** [comment] 2019-10-19 11:34
Hi @Mappavini,

If you think you have a different issue, please make sure to provide all the requested information from the issue template, and in particular a minimal reproduction example.

> the proposed solution does not work.

It would tremendously help supporting your statement if you can provide an example with your issue and the proposed solution not solving it.

I will be happy to re-open once there is enough details.
