### ISSUE TITLE
wrap method on newest leaflet not working

### ISSUE THREAD

**Issue by RhezaBoge** [Leaflet/Leaflet#4999] opened 2016-10-03 07:30 UTC
i'm sorry for my english.
there is a function that i found on leaflet 0.7.7 ("wrap" Conversion Methods). it has made me solved a problem like #82 with some additional code.

but i can't run this function again on the newest leaflet (currently 1.0.1). i don't know why.. so for a while, i just use leaflet 1.0.1 but i change little bit code on "wrap function" (use leaflet 0.7.7 code). let me know if I missed anything or had some incorrect code for "wrap" methods on the newest leaflet. or maybe "wrap" methods has been changed? 

Thanks and i'm sorry if i missed something, let me know that ;)

**Comment by IvanSanchez** [comment] 2016-10-03 07:31
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by RhezaBoge** [comment] 2016-10-03 08:01
this is an example i use wrap on leaflet 0.7.7 
[jsfiddle-wrap-on-leaflet-0.7.7](https://jsfiddle.net/rhezaboge/18auLnf3/) 
it has worked and the coordinate has changed

and this is an example i use wrap on leaflet 1.0.1
[jsfiddle-wrap-on-leaflet-1.0.1](https://jsfiddle.net/rhezaboge/18auLnf3/)
it has not worked and the coordinate has not changed. Did I miss something??

**Comment by IvanSanchez** [comment] 2016-10-03 08:08
The `LatLng` will not wrap around, as the longitude is between `-180` and `-180`. 

[This is the expected, documented behaviour in 1.0.0](http://leafletjs.com/reference-1.0.0.html#latlng-wrap). The method will always wrap between `-180` and `+180`.

Please note that the [behaviour in 0.7.x is different](http://leafletjs.com/reference.html#latlng-wrap): the `L.LatLng.wrap` method accepted extra parameters.

Use [`L.Util.wrapNum()`](http://leafletjs.com/reference-1.0.0.html#util-wrapnum) manually on the latitude if you need to. You might need to manually instantiate the wrapped `LatLng` in this way.

Documented behaviour → not a bug → closing.

**Closed by IvanSanchez** 2016-10-03 08:08 UTC
Labels: needs more info
