### ISSUE TITLE
Allow zindex option for L.ImageOverlay

### ISSUE THREAD

**Issue by patrickarlt** [Leaflet/Leaflet#2132] opened 2013-10-28 22:24 UTC
In the process of developing Esri Leaflet i have had users request the ability to maintain a very specific ordering of `DynamicMapLayer` (`ImageOverlay`). See https://github.com/Esri/esri-leaflet/issues/149 and https://github.com/Esri/esri-leaflet/issues/129

The reason this is an issue with that `ImageOverlay` uses `appendChild` which means that the last added layer is always on top. This means that when working with many layers (like in a `L.Control.Layers`) the last activated or added layer is always on top.

While I could implement a `zindex` option in Esri Leaflet I wanted to explore the idea of solving this issue in Leaflet itself.

```js
L.ImageOverlay(url, bounds, {
  zindex: 1000 // zindex:1000; in CSS
}).addTo(map);
```

This would mean that the `bringToFront` and `bringToBack` method on `ImageOverlay` would also have to set an absurdly high/low `zindex` when they are called.

Is there any interest in this? I can start working on it if there is.

**Comment by mourner** [comment] 2015-07-21 12:25
ImageOverlay now has `bringToBack` and `bringToFront` methods. If they're invoked immediately after adding to the map, there's no performance overhead as it happens in one JS tick. So I think we can close this for now.

**Closed by mourner** 2015-07-21 12:25 UTC
Labels: feature

**Comment by ekalaya** [comment] 2017-09-28 06:14
# @> # _**_`[](url)`_**_
Duplicate of #
