### ISSUE TITLE
Leaflet Map is not able to rotate in mobile devices

### ISSUE THREAD

**Issue by pravinmitta** [Leaflet/Leaflet#6818] opened 2019-09-24 07:44 UTC
i've assigned the map overlay id to the element and tried with hammerjs

document.getElementsByClassName('leaflet-map-pane')[0].setAttribute('id', 'stage2')
    var stage = document.getElementById('stage2');
    var mc = new Hammer.Manager(stage);

    var rotate = new Hammer.Rotate();
    var pinch = new Hammer.Pinch();
    var pan = new Hammer.Pan();

    mc.add([pinch, rotate]);
    mc.get('pinch').set({ enable: true })
    mc.get('rotate').set({ enable: true })

    var adjustScale = 1;
    var currentScale = null;
    var currentRotation = null;
    var adjustRotation = 0;

    var adjustDeltaX = 0;
    var adjustDeltaY = 0;
    var currentDeltaX = null;
    var currentDeltaY = null;

    mc.on("pinch rotate", function (e) {
      var transforms = [];
      // var rotation = currentRotation + Math.round(e.rotation);

      currentRotation = adjustRotation + Math.round(e.rotation);
      currentScale = adjustScale * e.scale;
      currentDeltaX = adjustDeltaX + (e.deltaX / currentScale);
      currentDeltaY = adjustDeltaY + (e.deltaY / currentScale);

      // transforms.push('scale(' + currentScale + ')');
      transforms.push('translate(' + currentDeltaX + 'px,' + currentDeltaY + 'px)');
      transforms.push('rotate(' + currentRotation + 'deg)');
      stage.style.transform = transforms.join(' ');

    })

    mc.on(" pinchend rotateend", function (e) {
      adjustScale = currentScale;
      adjustRotation = currentRotation;
      adjustDeltaX = currentDeltaX;
      adjustDeltaY = currentDeltaY;

    })

When i used this var stage = document.getElementById('map'); as element entire div is rotating or if i updated to var stage = document.getElementById('stage2'); this nothing is happening.
i've tried with this reference still it's not working 
https://github.com/Leaflet/Leaflet/issues/2342

**Comment by IvanSanchez** [comment] 2019-09-24 10:17
Duplicate of #6811.

Asking twice won't get you any further. If you want to check out the `rotate` branch and try to forward-port to 1.5 and fix #268, go ahead.

**Closed by IvanSanchez** 2019-09-24 10:17 UTC
