### ISSUE TITLE
Map.ZoomAnimation 'moveend' event fired twice on zoom in or zoom out

### ISSUE THREAD

**Issue by alekzonder** [Leaflet/Leaflet#4220] opened 2016-02-11 12:56 UTC
bug is reproduce randomly

```js
   //...
   // Work around webkit not firing 'transitionend', see https://github.com/Leaflet/Leaflet/issues/3689, 2693
    this line `setTimeout(L.bind(this._onZoomTransitionEnd, this), 250);`: 
},
```
https://github.com/Leaflet/Leaflet/blob/master/src/map/anim/Map.ZoomAnimation.js#L109

issues #3689 and #2693 closed 

moveend fired twice randlomly this example with leaflet-1.0.0-rc.2: https://jsfiddle.net/alekzonder/x0w9yo8q/

- click zoom control buttons
- wait 1 second (log clear) 
- zoom in or zoom out 
- randomly got two '!moveend!' in log

like on this [screenshot](http://10125.selcdn.com/js/twice-moveend.png)

here example, where i comment `setTimeout` (leaflet-1.0.0-rc.2)

http://jsfiddle.net/alekzonder/y26Lay52/

it works without this bug

**Comment by IvanSanchez** [comment] 2016-02-11 13:00
Duplicate of #4023. @alekzonder, read the comments there.

**Closed by IvanSanchez** 2016-02-11 13:00 UTC
