### ISSUE TITLE
leaflet-src.js missing from dist directory

### ISSUE THREAD

**Issue by aprilb** [Leaflet/Leaflet#5288] opened 2017-01-30 19:32 UTC
I am getting errors because references to dist/leaflet-src.js which simply isn't there:
https://github.com/Leaflet/Leaflet/blob/master/package.json#L30

**Comment by danzel** [comment] 2017-01-31 00:03
We only ship the built files in release tags, like:
https://github.com/Leaflet/Leaflet/tree/v1.0.3
(And npm packages etc)
They got out of date too soon in master, so they weren't really useful.

How did you obtain leaflet?

**Comment by pke** [comment] 2017-02-13 12:00
I can confirm, that `npm install leaflet` will install a package that references `dist/leaftlet-src.js`.
When using `import L from "leaflet` that drags in the source file instead of the minimized variant.

@IvanSanchez How is the package supposed to work in a webpack build scenario.

**Comment by IvanSanchez** [comment] 2017-02-13 13:31
@pke Webpack *et al* are supposed to handle unminified files with their sourcemaps. I'm using Leaflet in a number of Rollup-based projects, and the bundling Just Works™.

@aprilb This bug seems like a duplicate of https://github.com/Leaflet/Leaflet/issues/5326 / #5186, and as @danzel points out, this is just a matter of downloading a release instead of the `master` branch.

If you are *really* sure that this is a bug in leaflet, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html), like e.g. https://github.com/Leaflet/Leaflet/issues/5124. I'll reopen it in that case.

**Closed by IvanSanchez** 2017-02-13 13:31 UTC
Labels: needs more info

**Comment by pke** [comment] 2017-02-13 13:53
@IvanSanchez not sure if that is a webpack issue: `import L from "leaflet/dist/leaflet"` imports the mimimized version directly and the bundle size shrinks dramatically.
`import L from "leaflet"` imports the wrong file "dist/leafleft-src.js"
U think that's a webpack bug and should be filed over there?

**Comment by IvanSanchez** [comment] 2017-02-13 13:58
@pke No, Webpack is not supposed to minify by default, and that's fine. See https://webpack.js.org/guides/production-build/ if you expect minified bundles.

**Comment by pke** [comment] 2017-02-14 11:42
I know how to build production bundles. However, even in production mode webpack uses `leaflet-src.js` as the source for minimisation. The end result is a bigger bundle than when I'd import the already minified version of leaflet. Maybe its a webpack bug.

**Comment by amalshehu** [comment] 2017-06-01 16:16
I'm getting this error on rollup build using angular seed minko.
@pke Can anyone help?
```
'map' is not exported by 'node_modules/leaflet/dist/leaflet-src.js'
```
