### ISSUE TITLE
No interaction with layer below another one if i set panes and option "PreferCanvas"

### ISSUE THREAD

**Issue by Jonibigoud** [Leaflet/Leaflet#6797] opened 2019-09-11 07:10 UTC
I'm facing the following problem:

If i enable "preferCanvas" option on L.Map and if i set panes on two distinct polygons, i cannot interact with the polygon below the other (that is to say the layer with zIndex pane smaller than other layer's).
If i disable preferCanvas, i don't face the problem anymore.
if i disable panes  i don't face the problem anymore..

Here is an example (based on angular):

[https://stackblitz.com/edit/leaflet-prefercanvasenabled](url)

**Comment by Jonibigoud** [comment] 2019-09-18 05:45
When using "panes" with "preferCanvas:true", the DOM shows that multiple "canvas" are created and put into each <div> with the corresponding pane class. This way interaction is possible with the  above canvas 
When not using panes, only one canvas is created, it includes every elements, which you can interact with.
So it seemes that the principle of ordering layers when using canvas is not possible in leaflet.
Am i correct?
Any workaround for this?

**Comment by perliedman** [comment] 2019-09-18 06:54
Hi, this is more or less a duplicate of #6205 (and I think a couple of other issues). Please look at the discussion there, there are some workarounds but at the core, the issue is that a canvas will catch the mouse events and propagating them to underlying layers will be some kind of hack.

**Closed by perliedman** 2019-09-18 06:54 UTC

**Comment by perliedman** [comment] 2019-09-18 06:56
Sorry, #5739 appears to be the original issue; the one I referenced was closed as duplicate as well.
