### ISSUE TITLE
Broken "WMS and TMS" and "Showing video files" tutorials

### ISSUE THREAD

**Issue by dwiyatci** [Leaflet/Leaflet#5583] opened 2017-06-26 13:37 UTC
## How to reproduce

- Leaflet version I'm using: latest
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Ubuntu 16.04
- Go to http://leafletjs.com/examples/wms/wms.html
- Go to http://leafletjs.com/examples/video-overlay/

## What behaviour I'm expecting and which behaviour I'm seeing
**Expected:**
Maps should display correctly and behave as the examples describe.

**Actual:**
Most of the maps aren't displayed and expose broken behaviour.

## Minimal example reproducing the issue

- [ ] http://leafletjs.com/examples/wms/wms.html
- [ ] http://leafletjs.com/examples/video-overlay/

**Comment by IvanSanchez** [comment] 2017-06-26 13:46
Duplicate of #5540. We'll tackle the video example when 1.1.0 is released.

**Closed by IvanSanchez** 2017-06-26 13:46 UTC
