### ISSUE TITLE
iOS pinch zoom not getting right position.

### ISSUE THREAD

**Issue by stripathix** [Leaflet/Leaflet#5700] opened 2017-08-09 06:35 UTC
Using leaflet version 1.1.0 on doing a pinch dot drawn by d3 are misaligned but get correctly positioned on pinch release.
 
```
  function update() {
        feature.attr("transform", function (d) {
            var x = map.latLngToLayerPoint(d.LatLng).x;
            var y = map.latLngToLayerPoint(d.LatLng).y;
            return "translate(" + x + "," + y + ")";
        });
    }
   map.on("zoom", update);
   update();
```

![ezgif-4-cf68356787](https://user-images.githubusercontent.com/8480351/29107917-219b51aa-7cfa-11e7-8b7e-f9fef9fd7823.gif)

This is working right on version 0.7.7 where I was using: 

`map.on(viewreset")`

**Comment by perliedman** [comment] 2017-08-09 09:05
Hi, can you add a test case which reproduces this together with an explanation on what you expect to happen? I honestly have a bit of a hard time understanding what I'm seeing in that animation.

**Comment by stripathix** [comment] 2017-08-09 09:51
For example in the previous gif look at the green dot at Lynchburg.

**On PinchIn:** That dot is going away from Lynchburg

**On PinchOut:** That dot is going closer to Lynchburg

But on releasing the pinch then that green dot goes and settles right near to gray area beneath Lynchburg text. 

Expected behavior from v(0.7.7) is like this. 
![ezgif-4-14a09cfe1e](https://user-images.githubusercontent.com/8480351/29115692-22aafb7e-7d16-11e7-8686-bd194cc84497.gif)
That dot always stays near to that Lynchburg airport:

**Comment by stripathix** [comment] 2017-08-09 09:57
This is with version leaflet 0.7.7, running on iOS simulator:
![ezgif-4-8c3b220370](https://user-images.githubusercontent.com/8480351/29115964-020d2936-7d17-11e7-8406-2ef7c3fd5783.gif)

That green dot sticks to right position at Lynchburg airport. But in latest leaflet that green dots moves on pinch while pinching

**Comment by perliedman** [comment] 2017-08-09 11:19
Ok, think I get it. It sounds like this might be the same issue as #5181; I also seem to remember another issue which had the same problem, but can't find it now.

The problem, IIRC, lies in that `latLngToLayerPoint` does not correctly compensate for the fact that the map layers are translated and scaled while a pinch zoom is happening.

**Comment by perliedman** [comment] 2017-08-09 11:24
It would still be _very_ helpful to have a runnable example (on http://playground-leaflet.rhcloud.com/?html,output, for example) to debug this, if you could make one.

**Comment by stripathix** [comment] 2017-08-09 11:28
Sure I will create that and post a link

**Comment by perliedman** [comment] 2017-08-29 07:37
I'm closing this since we have nothing to act on here. This might be a Leaflet issue, or it might be an issue in this app, but right now we can't investigate further.

Happy to reopen if we get a reproducible test case!

**Closed by perliedman** 2017-08-29 07:37 UTC
Labels: needs more info
