### ISSUE TITLE
Suddenly I'm getting this error message: Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by raphael10-collab** [Leaflet/Leaflet#8139] opened 2022-04-13 16:45 UTC
Suddently I'm getting this error message,  strange  to me since I haven't been touching the map part :  

    Failed to load resource: the server responded with a status of 403 ()

Searching for a clue I found this outdated info: 
https://ninio.ninarski.com/2014/06/18/leaflet-tiles-failed-to-load-resource-the-server-responded-with-a-status-of-403-forbidden/

But I'm aleady using `openstreetmap` as tiles provider : 

    <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />

Other info:

    "@types/leaflet": "^1.7.9",
    "leaflet": "^1.7.1",
    "react-leaflet": "^3.2.5",
    "react-leaflet-fullscreen": "^2.0.2",
    "react-leaflet-textpath": "^2.1.1",
    node : v16.13.0
    O.S.: Ubuntu 20.04 Desktop

How to solve the problem?

**Comment by mourner** [comment] 2022-04-13 17:36
We're not able help, because you haven't provided us with a reproducible live test case. Generally it seems to be a server-side issue, not anything to do with Leaflet, so closing.

**Closed by mourner** 2022-04-13 17:36 UTC

**Comment by IvanSanchez** [comment] 2022-04-13 17:51
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by raphael10-collab** [comment] 2022-04-14 08:31
@IvanSanchez  I filled my post with all related code. Please feel free to have a look at it, and give me your feedback : 
https://stackoverflow.com/questions/71861153/leaflet-suddenly-im-getting-this-error-message-failed-to-load-resource-the
