### ISSUE TITLE
Invalid map bounds accepted, then not displayed if multiple points exist... let me explain

### ISSUE THREAD

**Issue by andrewhodel** [Leaflet/Leaflet#7582] opened 2021-05-25 17:23 UTC
Version 1.7.1

If I add a marker at `40.479084344656535 -2266.0515721227716` it will render on the map in Colorado.

If I then add another marker near the shown point with normal earth coordinates, the map will not render either markers and provide no error.

**Comment by IvanSanchez** [comment] 2021-05-25 17:57
Closing as a duplicate of https://github.com/Leaflet/Leaflet/issues/6172.

If this is about markers only, see the "RepeatedMarkers" plugin.

**Closed by IvanSanchez** 2021-05-25 17:57 UTC
