### ISSUE TITLE
Why tiles seem to be loaded again upon dragging?

### ISSUE THREAD

**Issue by wesbyte** [Leaflet/Leaflet#6669] opened 2019-05-19 11:39 UTC
Firstly thank you for your great job!

My question:
If you drag the map to the right and left, then drag again to see the same tiles in both directions, the tiles appear with the gray background first then get filled with the images while it's supposed they are loaded before and should appear directly without showing the gray background first!
Is there a way to fix this.
Thanks in advance.

**Comment by IvanSanchez** [comment] 2019-05-19 12:09
Expected behaviour due to memory usage concerns. See https://leafletjs.com/reference-1.4.0.html#gridlayer-keepbuffer

Not a bug, closing.

**Comment by IvanSanchez** [comment] 2019-05-19 12:09
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Closed by IvanSanchez** 2019-05-19 12:09 UTC

**Comment by wesbyte** [comment] 2019-05-22 05:47
Thanks, Ivan, I think this should be considered as a bug, if you take a look at Google maps, the tiles are loaded normally when dragging the previously loaded tiles which I am looking to get it done in leaflet!
Would that be possible?

**Comment by wesbyte** [comment] 2019-05-22 05:54
Hi Ivan,
keepbuffer seems to solve the issue, many thanks.
Do you recommend a maximum number for it if it's going to work in a mobile app?
