### ISSUE TITLE
Destroy map trouble

### ISSUE THREAD

**Issue by sergeantklin** [Leaflet/Leaflet#2718] opened 2014-06-02 04:31 UTC
I use several maps at a time. They can be created and deleted dynamically. But when I destroy a map using map.remove() there is a memory leak and "Detached DOM trees" appears in Chrome Dev Tools.

Working example here http://84.53.192.170/patyi/index.html

How to destroy maps properly?

**Comment by IvanSanchez** [comment] 2015-06-04 14:24
First, `map.remove()` should remove all layers. If not, these layers keep a dangling reference to `this._map` and cannot be added to any other map instance afterwards.

Second, I've found a non-completely-clean way of triggering `map.remove()` when the map container is removed from the DOM (#3514). See https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver , which seems to be the only way to do it.

**Comment by mourner** [comment] 2015-06-04 14:26
@IvanSanchez lets not use mutation observers since we want Leaflet to work reliably in older browser (it's not supported in IE up to 10)

**Comment by IvanSanchez** [comment] 2015-06-04 14:32
@mourner I'm surprised you still have hopes for *anything* to work reliably on IE8 :-P

**Comment by mourner** [comment] 2015-06-04 14:50
I just don't like _adding_ code that's not strongly necessary and not working everywhere. :)

**Comment by mourner** [comment] 2015-06-04 22:18
Merged.

**Closed by mourner** 2015-06-04 22:18 UTC
Labels: bug, help wanted, needs investigation

**Comment by foodaka** [comment] 2017-07-17 03:43
Hi there. Im also having trouble removing the map. Im using react with a bootstrap modal to render the map. see the removeMap function below.

```
class NeabySpot extends React.Component {

    constructor(props) {
        super(props);
        this.state = { showModal: false };
    }


    componentDidUpdate(prevProps, prevState){
        if(prevProps.selectedSpot !== this.props.selectedSpot) {
            const lat = this.props.selectedSpot.getIn(['gpsLocation', 'lat']);
            const lng = this.props.selectedSpot.getIn(['gpsLocation', 'lng']);

            this.drawMap(lat, lng)
        }
    }


    drawMap(lat, lng) {


        if (!this.map) {
            this.map = L.map("map-nearby");
            L.tileLayer("http://{s}.tile.osm.org/{z}/{x}/{y}.png", {
                attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(this.map);
            this.markers = new L.FeatureGroup();
            this.map.addLayer(this.markers);
        }
        this.map.setView([lat, lng], 3);
        this.mapIcon = L.icon({
            iconUrl,
            iconRetinaUrl,
            shadowUrl,
            iconSize: [25, 41],
            iconAnchor: [12, 41],
            popupAnchor: [1, -34],
            tooltipAnchor: [16, -28],
            shadowSize: [41, 41]
        });

        const marker = L.marker([lat, lng], {
            icon: this.mapIcon
        });

        this.markers.clearLayers();
        this.markers.addLayer(marker);
    }

    removeMap() {
        this.map.remove();
        this.map.off();
        //the remove function is not working with leaflet. issue creatd on git for now
        delete this.map;

    }


    render() {
        const showModal = this.props.showModal;
        const lat = this.props.urlspot.getIn(['gpsLocation', 'lat']);
        const lng = this.props.urlspot.getIn(['gpsLocation', 'lng']);
        return (
            <div>
                <Modal show={ showModal } onHide={ this.props.close } onExiting={ () => this.removeMap() } >
                    <Modal.Header closeButton>
                        <Modal.Title style={{display: 'flex', justifyContent:'center'}}>Compare Nearby Spot</Modal.Title>
                    </Modal.Header>
                    <Modal.Body>
                        <div  style={{ height: 300 }} id="map-nearby"></div>

                    </Modal.Body>
                    <Modal.Footer>
                        <div>
                        </div>

                    </Modal.Footer>
                </Modal>

            </div>
        )
    }
}

export default NearbyDiveSpotsModal;
```

**Comment by perliedman** [comment] 2017-08-06 16:15
@foodaka can you explain what you mean when you say the `remove` function "does not destroy the map instance"? What is it that is not being destroyed?

**Comment by jpatel3** [comment] 2017-09-12 17:55
Even after removal of the map by `.remove()`, the various events still end up calling leaflet functions and end up with errors like `Cannot read property  '_leaflet_pos' of undefined`. So it doesn't really remove the map entirely, as it seems like the div element on which map was rendered, still holding few events without actual map object.

**Comment by perliedman** [comment] 2017-09-13 06:32
@jpatel3 ok, thanks for reporting. Could you please open a new issue with an example that reproduces this problem? It's not likely the problem you're seeing is related to the one discussed in this three year old issue.
