### ISSUE TITLE
CDN over http

### ISSUE THREAD

**Issue by Profpatsch** [Leaflet/Leaflet#4080] opened 2015-12-10 13:07 UTC
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />

http://leafletjs.com/examples/quick-start.html

Disclaimer: I love leaflet and you are my heroes. But omg.

**Comment by Profpatsch** [comment] 2015-12-10 13:07
Moreover, using https gives a cert error.

**Comment by IvanSanchez** [comment] 2015-12-10 13:10
Duplicate of #2944, #4059, #1824, #3337 and #2649. So yeah, this has been already discussed.

If you need Leaflet over HTTPS *right now*, we encourage you to download a copy and host it yourself.

**Closed by IvanSanchez** 2015-12-10 13:10 UTC

**Comment by IvanSanchez** [comment] 2015-12-10 13:16
> I love leaflet and you are my heroes. But omg.

As long as you don't call us crazy and then delete that comment because you realized it was a mistake, it's OK. We love our users too ;-)

**Comment by Profpatsch** [comment] 2015-12-10 15:49
> As long as you don't call us crazy and then delete that comment because you realized it was a mistake, it's OK. We love our users too ;-)

Got me. Need to work on my “get over the first schock before you write” skill. :)

**Comment by mourner** [comment] 2015-12-10 16:42
Use https://npmcdn.com/ if you need https now. We may switch to it at some point.

**Comment by eric-tucker** [comment] 2015-12-17 14:23
The response from the leaflet team regarding requests for a CDN providing https seems rather puzzling up until this point.

With the Let's Encrypt project there's not really any excuse to still not provide https.  What is the issue?  Anything not supporting SNI is dead and should be forgotten / not supported.

**Comment by perliedman** [comment] 2015-12-17 16:00
@eric-tucker the issue is finding a free CDN that supports HTTPS. While Let's encrypt is great, it doesn't help in this case, since we don't manage, and don't want to manage, the CDN ourselves.

**Comment by Profpatsch** [comment] 2015-12-17 16:04
@perliedman How about just dropping the CDN? Probably a pure HTTP CDN (where you serve executable code over a trivially manipulable connection) is a lot worse than no CDN.

**Comment by eric-tucker** [comment] 2015-12-17 16:05
Agreed.  With http eventually going away (browsers will stop supporting it) any CDN that isn't getting off its arse and supporting https should just no longer be used.  I'd remove it from a list of CDNs you publish to and discourage anyone from using it going forward.

**Comment by IvanSanchez** [comment] 2015-12-17 16:15
@eric-tucker [Talk is cheap. Show me the code.](https://lkml.org/lkml/2000/8/25/132) (Or, in this case, a CDN with HTTPS that *you* are willing to take care of).

@Profpatsch No, because plain a HTTP CDN helps with testing and adoption, which I consider beneficial.

**Comment by eric-tucker** [comment] 2015-12-17 16:22
@IvanSanchez that's a ridiculous response.  This has nothing to do with code.  You're being asked to  stop publishing to a CDN that only supports HTTP.  "Go host it yourself" (your first response paraphrased) is a terrible suggestion.  Why even bother with CDNs if that's your solution to a problem that nearly everyone will experience?

Hell, if you look through the other duplicate issues there have been other suggestions already made.  cloudfare, cdnjs, npmcdn (in this thread), etc.

How does HTTP CDN help with testing and adoption?  You can run http locally and include https links without issue.  It's the reverse (https site including http links) that does not work.

**Comment by IvanSanchez** [comment] 2015-12-17 16:28
> You're being asked to stop publishing to a CDN that only supports HTTP.

And I'm asking you to do something proactive about it instead of just ranting. If you're willing to spend time and sweat on the issue and maintain some CDN links, welcome. If not, we have better things to do.

**Comment by mourner** [comment] 2015-12-17 21:21
@eric-tucker we are consider dropping CDN hosting alltogether (because of CloudFront pains) and switching to https://npmcdn.com/ which is free, has HTTPS and requires no setup. 

No need to be harsh and call everything ridiculous like we owe you something. This is open source. Let's be polite and considerate to each other. If you want to contribute, do it with a pull request, not with a rant blaming maintainers. e.g. a PR to the website, adding a link to npmcdn with a clarifying note.
