### ISSUE TITLE
horizontal polyline - mouseover

### ISSUE THREAD

**Issue by karuit** [Leaflet/Leaflet#4286] opened 2016-02-29 12:05 UTC
It looks like hovering over some clickable polylines is not correctly recognized, which makes them really hard to click on.
It also seems to be only an issue with nearly horizontal lines. Alll other lines behave correctly.
There's a [fiddle](http://jsfiddle.net/FranceImage/9dggfhnc/) on http://stackoverflow.com/questions/32882523/how-to-apply-css-on-polylines-leaflet where you can see the problem:
If you hover over the top line the cursor doesn't always change to 'pointer'. Hovering over the two bottom lines works fine, though.

Any idea how to fix this?

**Comment by IvanSanchez** [comment] 2016-02-29 13:23
Can't reproduce the bug on either firefox or chrome. Hovering over horizontal SVG lines works just as expected, as fas as I can see.

Do you have any specific environment this is reproducible in? If not, it's unlikely we'll accept this as a bug.

**Comment by karuit** [comment] 2016-02-29 14:16
Nope, no specific environment.
If you won't mind you could try the same [fiddle ](http://jsfiddle.net/FranceImage/9dggfhnc/) and change the css to:

#map { height: 300px; }

.my_polyline { 
 stroke: green;
  fill: none;
  stroke-width: 50;  
}

as it's more apparent with thicker lines, escpecially when hovering in from the top.
Here's a screenshot:
![hover](https://cloud.githubusercontent.com/assets/17545734/13396811/ec113d6c-def6-11e5-8921-31054517c0e3.png)

But if it's not reproducable on your side, then I suppose it might not have been leaflet.

**Comment by IvanSanchez** [comment] 2016-02-29 14:20
With a thickness of 50 px it still behaves as expected on my side.

What browser are you using, anyway?

**Comment by karuit** [comment] 2016-02-29 14:23
I only has the issue on firefox 38.6.1.
Just tested IE11 and it's working fine.

**Comment by IvanSanchez** [comment] 2016-02-29 14:31
My advice then is to upgrade your Firefox up to v44.

We do care for outdated browsers, but this seems like just a glitch and not a breaking bug, not really worth the time to research and fix it. It might as well be a (now fixed) upstream SVG bug.

**Closed by IvanSanchez** 2016-02-29 14:31 UTC
Labels: needs more info
