### ISSUE TITLE
Leaflet is not opening popup bindend to markers on Safari

### ISSUE THREAD

**Issue by irafunesta** [Leaflet/Leaflet#7542] opened 2021-04-06 08:37 UTC
### How to reproduce
Go to the site https://leafletjs.com/index.html with Safari
Close the popup in the example map, then try to open it by clicking on the marker

Leaflet version I'm using: 1.7.1
Browser (with version) I'm using: Safari Version 13.1.3 (15609.4.1)
OS/Platform (with version) I'm using: Mac Catalina and iOS 10.15.7 (19H2)

**What behaviour I'm expecting and which behaviour I'm seeing**

Once closed the popup can't be opened, i'm expecting that the popup from markers have the same behavior both on
Chrome and Safari. If you click and drag the marker sometimes the popup become visible.

**Comment by johnd0e** [comment] 2021-04-06 09:36
Duplicate of #7255

**Closed by johnd0e** 2021-04-06 09:36 UTC
