### ISSUE TITLE
autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated

### ISSUE THREAD

**Issue by mohammed-gehad** [Leaflet/Leaflet#8319] opened 2022-07-01 09:07 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

using leaflet with autoprefixer 10.4.7
and getting error autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated

### Expected behavior

using  print-color-adjust instead of color-adjust in leaflet css file

### Current behavior

deprecated color-adjust is being used in leaflet css.

### Environment

- Leaflet version: 1.8.0
- Browser (with version):  
- OS/Platform (with version):

**Comment by Malvoz** [comment] 2022-07-01 09:11
Duplicate of https://github.com/Leaflet/Leaflet/issues/8268.

> Leaflet v1.8.0 was released [2022-04-18](https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md#180-2022-04-18) and [`color-adjust` was changed](https://github.com/Leaflet/Leaflet/pull/8211) afterwards. The change will be available in the latest stable version once v1.9.0 has been released.

**Closed by Malvoz** 2022-07-01 09:11 UTC
Labels: bug, needs triage
