### ISSUE TITLE
The map has white graticule lines   leaflet1.20

### ISSUE THREAD

**Issue by langfengac** [Leaflet/Leaflet#5972] opened 2017-12-18 03:50 UTC
System: windows 10 Enterprise Edition
Browser chrome: version 63.0.3239.84 (official version) (64-bit)
If the monitor is enlarged to 125%
There will be white grid lines on the map
The 1.2 version will have a white line of checkered lines
The 0.77 version does not have white line grid lines

System:macOS Sierra 10.12.6
Browser chrome: version 65.0.32294.5 (official version) (64-bit)
Some Apple computers also have problems
There will be white grid lines on the map
The 1.2 version will have a white line of checkered lines
The 0.77 version does not have white line grid lines

But using this tile there is no white grid lines https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk .eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw
Other third-party maps will have, such as the world map, Google maps, high Germany map, Baidu map, mapbox maps, etc. will have a white grid lines
For example: http://t{s}.tianditu.cn/ter_w/wmts?service=wmts&request=GetTile&version=1.0.0&LAYER=ter&tileMatrixSet=w&TileMatrix={z}&TileRow={y}&TileCol={x}&style=default&format=tiles
![_20171218113224](https://user-images.githubusercontent.com/6505148/34089175-639ca350-e3e9-11e7-868a-fd0147e479dc.png)
![_20171218113715](https://user-images.githubusercontent.com/6505148/34089177-63e26f70-e3e9-11e7-8236-a2f9e4429b3f.png)

If you set "zoomDelta" and "zoomSnap"
Then any time chrome will appear white line
Help！
Thanks !

**Comment by cherniavskii** [comment] 2017-12-21 12:44
Duplicate of #3575

**Closed by cherniavskii** 2017-12-21 12:44 UTC
