### ISSUE TITLE
Map locks up while waiting for tiles to load

### ISSUE THREAD

**Issue by bsudekum** [Leaflet/Leaflet#3689] opened 2015-07-29 19:46 UTC
Specs: scrolling with mouse wheel, Chrome Version 44.0.2403.107 (64-bit)

After zooming, the map locks up and I am not able to pan. No errors in the console.
![gif](https://cloud.githubusercontent.com/assets/1058624/8968000/953684a8-35ef-11e5-8831-6766aadb1549.gif)

/cc @mourner @tmcw

**Comment by mourner** [comment] 2015-07-29 19:47
Is this reproducible in stock Leaflet, or only mapbox.js? How about Leaflet 1.0b1 and master?

**Comment by IvanSanchez** [comment] 2015-07-29 19:47
Duplicate of #3685

**Comment by mourner** [comment] 2015-08-26 15:41
Turns out it's a different issue, and is not fixed by #3692 in master. The original cause is a regression in Chrome which is still being worked on https://code.google.com/p/chromium/issues/detail?id=513206

Meanwhile I'll see if I can find a way to fix it in stable.

**Comment by mourner** [comment] 2015-08-26 16:04
@IvanSanchez the bug was fixed in master indirectly by https://github.com/Leaflet/Leaflet/commit/bbf32ebfcdb0d24d187dbb54eecbea367fd7b72d by @jfirebaugh.

The issue here seems to be that due to recent Chrome bug `transitionend` doesn't fire after transform until all tiles have been loaded. We either need to add a horrible but working hack and force it on timeout for the duration of the transition, or find a less obtrusive fix.

**Comment by mourner** [comment] 2015-08-26 16:55
@danzel I'm now seriously considering just putting setTimeout and ditch all reliance on transitionend in master. It's just so freaking unreliable.

**Comment by danzel** [comment] 2015-08-26 21:40
Wow :(
Yeah, I agree.

It looks like we've got part way there already, using requestAnimFrame for the ZoomAnimation.
Maybe we could abstract the animation timer part of L.PosAnimation out and then implement PosAnimation and ZoomAnimation based on that?

**Comment by IvanSanchez** [comment] 2015-08-26 22:13
@danzel Sounds right to me, but it's way overkill for 1.0.

**Comment by danzel** [comment] 2015-08-26 22:14
True, we already have way too many changes in 1.0 ;)

**Comment by mourner** [comment] 2015-08-27 01:12
@danzel the idea to switch zoom animations to reqAnimFrame-based animation was floating around for a long time already, and @jfirebaugh is especially rooting for it. I was resisting it over the years because the performance of animating a large number of objects is much worse, which I demonstrated with a demo (somewhere among my bl.ocks). Although we might eventually just say "screw it" and drop performance, just not recommending ever putting too many markers on the page and always using something like marker cluster.

**Comment by danzel** [comment] 2015-08-27 01:17
Yeah, I actually thought it had gone in, must have been dreaming (or is zoomPanTo reqAnimFrame powered?)

Maybe the browser gods will keep transitionend stable and we can all move on with our lives? :(

**Comment by mourner** [comment] 2015-08-27 01:26
@danzel yes, `flyTo` (renamed) is reqAnimFrame-based because there's no way to animate transform along a curve with a transition. :) Map moving on pinch-zoom on mobile is also frame-by-frame. So maybe we should consolidate everything eventually and not pay attention to performance.

**Comment by mourner** [comment] 2015-08-27 01:27
One huge advantage of reqAnimFrame-based zoom animations is that you can stop them any time, and you can change them in the middle. With transitions it's huge pain in the ass. Maybe this alone will overweight the performance drop.

**Comment by danzel** [comment] 2015-08-27 01:29
Perf is a pretty important feature though. Maybe time to wheel out the old tests and see what the difference is in modern browsers again.

**Comment by mourner** [comment] 2015-08-27 01:33
@danzel found the test http://bl.ocks.org/mourner/4336d03f18c1938df5d9 — frame-by-frame still pretty horrible in Chrome but smooth with transitions. In Firefox, there's no difference — perf is horrible in both cases lol. :)

**Closed** 2015-08-31 09:35 UTC
Labels: blocker
