### ISSUE TITLE
using zoom and drag the map renders wrong in the container

### ISSUE THREAD

**Issue by jabaren** [Leaflet/Leaflet#4069] opened 2015-12-03 22:47 UTC
Hello,

I'm not sure if this a bug, but sometimes when I'm dragging and scrolling (with mouse wheel) the the map  sometimes doesn't render in the correct way, e.i :

![graygapinmap](https://cloud.githubusercontent.com/assets/9442532/11574765/2868f6c4-99d3-11e5-8926-ec1ae64a6e07.gif)

At the end the map is shown in this way:

![mapbadloading](https://cloud.githubusercontent.com/assets/9442532/11574832/80bca0f0-99d3-11e5-8ec6-1d2fa2fbee5b.png)

the url https://otile1-s.mqcdn.com/tiles/1.0.0/map/18/70026/123550.jpg response with 504 (it can't be my connection).

This happen in http://leafletjs.com/index.html:

![samebugleaflet](https://cloud.githubusercontent.com/assets/9442532/11575215/726e25e4-99d5-11e5-84e8-5eee42f33dd1.png)

I couldn't find the reason why is this happening and I don't know if it's a race condition between drag and zoom.

**Comment by IvanSanchez** [comment] 2015-12-03 22:55
I'm not able to reproduce. Can you be more specific in the sequence of actions that trigger the bug?

Does this happen in a particular browser? Does it happen using 1.0.0-betas?

**Comment by jabaren** [comment] 2015-12-04 14:29
I'm using : 

Leaflet version 0.7.3.
https://open.mapquestapi.com/sdk/leaflet/v1.s/mq-geocoding.js
https://open.mapquestapi.com/sdk/leaflet/v1.s/mq-map.js

Chrome Version 43.0.2357.81
FireFox Version 42.0

Steps:
1.-Drag the map
2.-While the map is moving by the inertia, use the mouse wheel to zoom in or zoom out the map.
3.-Stop moving the map.

**Comment by IvanSanchez** [comment] 2015-12-04 14:30
We don't maintain 0.7.3 anymore. Is the bug reproducible with 0.7.7?

**Comment by jabaren** [comment] 2015-12-04 14:31
Ok, I'll check it

**Comment by jabaren** [comment] 2015-12-04 15:53
It happens on version 0.7.7 (http://jsfiddle.net/ga7155bn/3/)

I think is an error on css translate3d(5307px, -336px, 0px);

![fiddlemapbadposition](https://cloud.githubusercontent.com/assets/9442532/11593872/58912ae4-9a6c-11e5-9f0b-f4c3489947c7.png)

the correct position should be translate3d(5167px, -336px, 0px);

![fiddlemapcorrectposition](https://cloud.githubusercontent.com/assets/9442532/11593947/c65559d8-9a6c-11e5-85be-7644a7dd8cf3.png)

**Comment by IvanSanchez** [comment] 2015-12-04 15:59
I think this is a duplicate of #2360. @mourner, are you still interested in cherry-picking the changes and backporting to 0.7.x?

**Comment by jabaren** [comment] 2015-12-04 16:12
Yes, I think it's a nice UX, Thanks. Cheers

**Comment by mourner** [comment] 2015-12-04 22:53
@IvanSanchez yes, looks very likely, let's try cherry-picking this and seeing if it fixes this.

**Comment by alex-marin-sv** [comment] 2016-02-11 14:36
Hello.
Any updates on this ? I am running into the same issue. Try this on 0.7.2 and 0.7.7. still same error. It happens when you move the map and zoom or zoom in at the same time. I reproduced this on the demo map on leaflet.com. (image below). Thank you!

![leaflet issue](https://cloud.githubusercontent.com/assets/17179183/12979054/742aa2ec-d0dd-11e5-907b-4cae5c44c5f2.PNG)

**Comment by JPustkuchen** [comment] 2016-06-10 16:01
I can confirm this problem still exists in rc1.

**Comment by mourner** [comment] 2016-09-27 14:16
Can you confirm that it exists in 1.0.0 final?

**Comment by perliedman** [comment] 2017-08-09 08:21
Since we've had no updates and no reproducible test case for more than a year, I'm going to close this for now.

Happy to re-open if this is still an issue that can be reprodcued.

**Closed by perliedman** 2017-08-09 08:21 UTC
Labels: help wanted, needs more info
