### ISSUE TITLE
JavaFX Webview - dragging problem - Leaflet issue?

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7825] opened 2021-11-29 07:17 UTC
I had a meeting with a developer, which used JavaFX and Webview to display a Leaflet map. 
After upgrading to `JDK1.8.0_291` (or greater then 291) the map dragging doesn't work anymore.
First I thought it is only a Java problem but it looks like the `mouse`-events are correctly passed to the html.

We found out
1. that dragging the map works if we use Leaflet 0.7.7
2. if we hold down on the zoom control button and then move the pressed mouse to the map, and then release it -> the map is moving / dragging until we click again
![javafx_control_drag](https://user-images.githubusercontent.com/19800037/143824123-c37fb87d-45a1-4dc4-be2e-97b96ef9af3a.gif)

Have we some JavaFX experts here?
I have following questions:
1. Can you confirm this issue?
2. Is it possible to debug the Javascript in the WebView?
3. Is this a JavaFX problem or is this a problem of Leaflet?

I suggest to let this Issue open until 2022 and if no one can confirm this we close it.

**Comment by johnd0e** [comment] 2021-11-29 07:28
Have you tried `master` version?

**Comment by Falke-Design** [comment] 2021-11-29 07:46
Yes (with the new Tab Handler), also checked if `tab: false` is changing something in 1.7.1

**Comment by jonkoops** [comment] 2021-11-30 13:06
Do we want to support think kind of browser? It looks like JavaFX is using some fork of Webkit we cannot realistically test on.

**Comment by Falke-Design** [comment] 2021-11-30 13:13
I would not force it but if someone has time to take a look into it and maybe find an easy solution then I think that we should fix it. If it needs some bigger additions I would say it should be a plugin. And if we don't find a solution until 2022 it is no problem.

**Comment by jonkoops** [comment] 2021-11-30 16:12
I agree, it would be fine if someone finds a fix for this to merge it. However since this browser is not listed in the official browser support and we have no way of realistically testing this I am not a fan of keeping another issue open in our already massive backlog.

**Comment by jonkoops** [comment] 2021-12-01 11:25
Closing this issue as this browser is not in our support target. If anyone has the time to debug this an create a fix that is always welcome.

**Closed by jonkoops** 2021-12-01 11:25 UTC
Labels: help wanted, compatibility

**Comment by PrimosK** [comment] 2021-12-10 07:05
It would be great if Leaflet would support JavaFx WebView (WebKit) but I totally understand your POV as debugging of it is rather no trivial (i.e. there are no debugging facilities one could use). 

After investigating this issue further, it seems to actually be JavaFX WebView (WebKit) regression. More info and workaround can be found in:
https://stackoverflow.com/questions/69872483/leaflet-does-not-work-in-webengine-after-javafx-17/70300669#70300669

**Comment by Falke-Design** [comment] 2021-12-10 07:14
> In Leaflet 1.7.1. it's actually this if expression which consequently causes map to not be moved (because PointerEvent.buttons is wrongfully set to 0 by Java FX 17): https://github.com/Leaflet/Leaflet/blob/bd88f73e8ddb90eb945a28bc1de9eb07f7386118/src/dom/DomEvent.Pointer.js#L104

nice catch! I think this should be fixed in JavaFX

**Comment by Falke-Design** [comment] 2021-12-10 07:26
@PrimosK I don't think that `buttons === 0` is the full problem. Because in the current master we have removed the `e.buttons` check and it was still not working:
https://github.com/Leaflet/Leaflet/blob/e3719a317ab325ed091fbbc6bfd34640fe19e13e/src/dom/DomEvent.Pointer.js#L79

I think the problem is that the `pointerType` is `mouse`, can you check this?

**Comment by Falke-Design** [comment] 2021-12-10 07:28
You can use this url to use the newest master: https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet-src.js

**Comment by PrimosK** [comment] 2021-12-10 07:35
I can confirm that `pointerType` is set to `mouse` but I guess this is expected/correct behavior.

I will try to do some more experimenting also with the latest master (in the following days)...

**Comment by PrimosK** [comment] 2021-12-10 07:49
I did a quick check.

The good news is that with the latest master the issue is gone! :)

Side question:
Are there any estimations of when new Leaflet version (based on the latest master) will be out?

**Comment by Falke-Design** [comment] 2021-12-10 07:58
I tested it too with the newest master and it didn't worked, maybe i have not used the correct build and / or the fix was not merged at this moment.
There is still a `button !== 1` check in the code. But you had no problems with moveing the map and markers correct?
`L.marker(map.getCenter(), {draggable: true}).addTo(map)`
https://github.com/Leaflet/Leaflet/blob/e3719a317ab325ed091fbbc6bfd34640fe19e13e/src/dom/Draggable.js#L83

We want to release 1.8. as fast as possible but I think it will take minimum 2 months.

-----

Can you please check if this code is a workaround for Leaflet 1.7.1, because I don't think it is a problem with DomEvent.Pointer, this is only needed if touch is used.
```
var _onDownOriginal = L.Draggable.prototype._onDown;
L.Draggable.include({
	_onDown: function (e) {
		e.button = 1;
		_onDownOriginal.call(this, e);
	}
});

// .... create map, etc.
var map = L.map('map')
map.setView([50.5, 30.51], 15)
```

**Comment by PrimosK** [comment] 2021-12-10 08:15
WRT `e.button !== 1` check - note that it's not the check that was causing the issues. I was actually `e.buttons` property (plural) which seems to not be used anymore in the current master.

The code you've provided as a workaround for 1.7.1. doesn't help with it.

**Comment by Falke-Design** [comment] 2021-12-10 08:16
> WRT e.button !== 1 check - note that it's not the check that was causing the issues. I was actually e.buttons property (plural) which seems to not be used anymore in the current master.
Ou yes sorry

**Comment by carldea** [comment] 2022-01-19 04:15
@Falke-Design and @PrimosK,

I did run into the same issue. When using leaftlet 1.7.1 and webview using JavaFX 16 it works, but when using JavaFX 17.0.x or 18 ea (early access release) the dragging doesn't seem to work. Is there a simple test you could create to send to the GluonHQ who often will help fix this issues in WebView component.

I don't know the internals of Leaflet to know what you are expecting in terms of mouse events.

**Comment by Falke-Design** [comment] 2022-01-19 05:38
@carldea If you use the current master it should work: https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet-src.js

A simple demo to test the current master: http://falke-design.bplaced.net/leaflet/master.html

**Comment by schajuli** [comment] 2024-07-08 09:39
I think I have a similiar issue https://imgur.com/bphKERS
Is there a way to resolve this or a way how Leaflet can be properly used within a Java Application?

**Comment by jonkoops** [comment] 2024-07-09 10:30
I am going to go ahead and lock the discussion here. We do not offer support for JavaFX WebView, nor do we intent to add support for it. If you are looking for support making Leaflet work with JavaFX WebView I would recommend that you open a compatibility issue on that project.
