### ISSUE TITLE
Add data to `L.geoJSON` layer using `addData` fails with 1.9.1

### ISSUE THREAD

**Issue by moosetraveller** [Leaflet/Leaflet#8490] opened 2022-09-28 19:11 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Create a `L.geoJSON` layer with no data
2. Add data using `.addData(features)`

Source Code see section `Current Behaviour`

### Expected behavior

Data should be successfully added and displayed (as it is when using Leaflet 1.8)

### Current behavior

**Error 1** (when initializing)
![image](https://user-images.githubusercontent.com/3456293/192866885-fcd9a0f2-a58d-4c00-929e-b348ef164234.png)

**Error 2** (when showing tooltip)
![image](https://user-images.githubusercontent.com/3456293/192867112-c64ac40e-4414-4632-a4aa-aa4fd0c6bdaa.png)

**JSFiddle for Reproduction**
<https://jsfiddle.net/moosetraveller/3sqoaywv/47/>

**Source Code for Reproduction**
```html
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Leaflet Issue</title>
  
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.1/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.9.1/dist/leaflet.js"></script>
  
  <!-- <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.8/dist/leaflet.js"></script> -->
  
</head>
<body>
    
  <div id="map" style="height: calc(100vh - 1rem);"></div>

  <script>
    const map = L.map('map')
	    .setView([44.6475, -63.580278], 11);
    
    const basemap = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '© OpenStreetMap',
    });
    
    const pane = map.createPane('washrooms-overlay');
    const canvas = L.canvas({
      padding: 0.5,
      pane: pane,
    });
    
    const markerOptions = {
      radius: 6,
      color: '#b70000',
      weight: 1,
      opacity: 0.8,
      fillColor: '#b70000',
      fillOpacity: 0.5,
      renderer: canvas,
    };
    
    const layer = L.geoJSON([], {
      pointToLayer: (feature, latlng) => {
        return L.circleMarker(latlng, markerOptions)
          .on('click', event => console.log(event))
          .bindTooltip(layer => {
      	    return layer.feature.properties.FAC_NAME;
          });
      },
      attribution: 'Halifax Regional Municipality',
    });
    
    basemap.addTo(map);
    layer.addTo(map);
    
    fetch('https://services2.arcgis.com/11XBiaBYA9Ep0yNJ/arcgis/rest/services/HRM_Public_Washrooms/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson')
      .then(response => response.json())
      .then(features => {
        layer.addData(features);
      });
  </script>

</body>
</html>
```

**Result with Leaflet 1.9.1**
![image](https://user-images.githubusercontent.com/3456293/192867305-02877e8c-db1b-40cd-9db0-cd78e2209847.png)
(errors see screenshot above, only 1 washroom is shown, tooltip not working)

**Result with Leaflet 1.8**
![image](https://user-images.githubusercontent.com/3456293/192867432-a765c044-9b66-49a6-a875-eb6f1d7a1764.png)
(and no errors)

-----

This is a minimal example above, in my real project, I get a slightly different error when doing the above. I couldn't reproduce the exact same error, but it seems it's all located somewhere in `_addFocusListenersOnLayer`:

![image](https://user-images.githubusercontent.com/3456293/192868405-1cafcd80-2560-4a0f-8f83-15d0c84626c1.png)

The different error may be because I am using `leaflet-src.esm.js` in my project?

### Minimal example reproducing the issue

https://jsfiddle.net/moosetraveller/3sqoaywv/47/

### Environment

- Leaflet version: 1.9.1
- Browser (with version): Firefox 105.0.1
- OS/Platform (with version): Windows 10

**Comment by moosetraveller** [comment] 2022-09-28 19:24
Looks like `_addFocusListenersOnLayer` was introduced with #8247.

**Comment by jonkoops** [comment] 2022-09-29 11:18
Duplicate of #8490

**Closed by jonkoops** 2022-09-29 11:18 UTC
Labels: bug, needs triage
