### ISSUE TITLE
Angular2 Issues

### ISSUE THREAD

**Issue by TheVoxell** [Leaflet/Leaflet#4750] opened 2016-07-25 11:27 UTC
Hi, 

I have a couple of problems with leaflet 1 rc1 and rc2 on angular 2. Lealet 0.77 is working fine.

1. : When moving the map it often returns to the start position of the map when you start dragging.

2. : When starting to drag on the map it starts firing events and wont stop. on leaflet 0.7.7 it stops when you dont move your cursor anymore but on leaflet 1 it doesnt stop firing events.....

I have tests online. With debugging to the console when firing events. 

http://jelledevos.nl/maps/leaflet100/
http://jelledevos.nl/maps/leaflet77/

Regards,
Jelle

**Comment by kaynz** [comment] 2016-07-25 11:37
Hi,

this is a duplicate of  #4588.

This will be fixed with the next release of zone.js.

**Comment by IvanSanchez** [comment] 2016-08-09 08:52
Closing as duplicate.

**Closed by IvanSanchez** 2016-08-09 08:52 UTC
