### ISSUE TITLE
A element with dragging=true in Microsoft Edge breaks drag functionality of map

### ISSUE THREAD

**Issue by kozy4324** [Leaflet/Leaflet#5619] opened 2017-07-10 08:21 UTC
## How to reproduce

- Leaflet version I'm using: 1.1.0 and 1.0.3
- Browser (with version) I'm using: Microsoft Edge 38.14393.1066.0
- OS/Platform (with version) I'm using: Windows 10
- step
  1. Put a element that has `draggable="true"` with a Leaflet map.
  2. Drag the element.

## What behaviour I'm expecting and which behaviour I'm seeing

After dragging the element once, a dragging map with single tap changes into like a dragging map with double tap.
After dragging the element twice, a dragging map does not work.

## Minimal example reproducing the issue

https://kozy4324.github.io/leaflet-dragging-error-at-ms-edge/

**Comment by perliedman** [comment] 2017-10-27 11:11
Hi,

sorry for a very late reply. It's not clear to me exactly how to reproduce the problem from your example, it looks like it's just showing a default map. Is it panning the map that doesn't work for you in Edge, or what?

**Comment by kozy4324** [comment] 2017-11-02 06:13
@perliedman 

Thank you for your reply. I tried to reproduce the problem with **Microsoft Edge 40.15063.674.0** (current stable version), but it did not happen. Perhaps it may be fixed by updating.

If there is no problem, please close this issue. Thanks.

**Comment by perliedman** [comment] 2017-11-02 07:24
Ok, thanks for the update! I'm closing this for now, but feel free to add more information in case you see the issue again, and we'll re-open.

**Closed by perliedman** 2017-11-02 07:24 UTC
Labels: needs more info
