### ISSUE TITLE
[longitude, latitude]-order geo-coordinates 

### ISSUE THREAD

**Issue by kkdd** [Leaflet/Leaflet#4169] opened 2016-01-23 17:44 UTC
Do you have a plan to switch to [longitude, latitude]-order geo-coordinates or not?
At this time, as far as I know,

[longitude, latitude]-order: OpenLayers, MapboxGL, KML, GeoJSON, PostGIS, MongoDB, MySQL,
[latitude, longitude]-order: Leaflet, Google Maps API, ArangoDB.

**Comment by yohanboniface** [comment] 2016-01-23 17:56
Duplicate of #1455.

**Closed by yohanboniface** 2016-01-23 17:56 UTC
