### ISSUE TITLE
L.Marker.setIcon re-inits 'draggable' option

### ISSUE THREAD

**Issue by chupikk** [Leaflet/Leaflet#3807] opened 2015-09-04 10:10 UTC
See http://jsfiddle.net/VPzu4/721/
Create a marker with initial option 'draggable': true.
Change it to false: marker.dragging.disable()
Change marker icon: marker.setIcon(...) - it looks like on this step initial marker options are used to re-initialize the marker, so it again becomes draggable.

**Comment by snkashis** [comment] 2015-09-05 15:20
You are aware this fiddle uses Leaflet 0.5.1, right? It was released more than 2 years ago. Have you checked with a more recent version?

**Comment by snkashis** [comment] 2015-09-05 15:23
If I had to guess, this was fixed by https://github.com/Leaflet/Leaflet/commit/c6dea37d86cb5935d0f69f7e921cd40c7cd8c6fc in 1.0.0b1

**Comment by IvanSanchez** [comment] 2015-09-05 18:46
Yeah, this looks like a duplicate of #2578, already fixed.

**Closed by IvanSanchez** 2015-09-05 18:46 UTC

**Comment by chupikk** [comment] 2015-09-07 10:03
Regarding 0.5.1 - yes, I was aware, just forgot to mention (sorry) that I was testing this on the latest stable release 0.7.5 as well, and it is still present there. Don't you merge fixes to the stable version?

**Comment by mourner** [comment] 2015-09-07 10:08
Generally we only merge critical fixes. Looks like there's an easy workaround, right? `marker.dragging.disable()`

**Comment by chupikk** [comment] 2015-09-07 10:10
Sure there is, thanks for clarifications :)
