### ISSUE TITLE
2 Finger zoom on Mobile does not work if 2 fingers placed at same time (Tested on Android + Firefox 79.0.5)

### ISSUE THREAD

**Issue by FinduschkaLi** [Leaflet/Leaflet#7246] opened 2020-08-26 05:56 UTC
- Zooming on map works only, if 2 fingers are placed on screen one after another. 
- if both fingers are placed on screen at the same time, no pinch-zoom is possible.
- If i place first 1 and then the second finger and pinch to zoom / dezoom it works just fine.
- Double-tab zoom works normally

VERSIONS
Firefox mobile 79.0.5
Android 10 on Motorola Power
Leaflet 0.1.6 (see example code below)
Code where tested: https://leafletjs.com/examples/quick-start/example.html

REPRODUCE
Go to https://leafletjs.com/examples/quick-start/example.html on device, place both fingers simultaneously on the map and try to zoom -> should not work
Place first finger 1 and then finger 2 and try to zoom --> should work

FURTHER INFO:
Pinch zoom is not working at all on Windows 10 / Firefox 79, 64bit / Lenovo Yoga 520 with touch screen.

**Comment by IvanSanchez** [comment] 2020-08-26 12:43
Possible duplicate of #7206. Also could be put under the umbrella of #7200.

**Comment by Yarjk32** [comment] 2020-08-27 11:06
I have the same problem at Firefox for Android 79.0.5 (Build #2015758619). But I have Android 5.1 (Flyme 6.3.2.0G) on Meizu M3s. Before this Firefox version, I don't notice this problem.

**Comment by FinduschkaLi** [comment] 2020-08-27 11:13
I am also almost certain, that this worked before the update to FFox 
79...

**Comment by doconnoronca** [comment] 2020-09-05 15:22
I used pinch to zoom the maps on my website https://www.transsee.ca/routemap?a=ttc&r=501 and after the recent major update of Firefox Mobile it no longer works.

**Comment by andwaal** [comment] 2020-10-02 09:07
Same issues on FF 81.1.1 @ Android 10.0

**Comment by arggh** [comment] 2020-10-05 10:28
Same issue on iPad (7th generation), iOS 13.3, Safari.

**Comment by arggh** [comment] 2020-10-05 11:24
...and I seem to have solved my iPad issue by setting a CSS property `touch-action: none;` on my map container element.

**Comment by Yarjk32** [comment] 2020-10-27 19:51
In the last Firefox update, Mozilla had fixed this issue. More info [here](https://github.com/mozilla-mobile/fenix/issues/14285).

**Comment by IvanSanchez** [comment] 2020-10-27 22:07
So this was being caused by an upstream bug that has already been fixed... closing this one, then.

Kudos to the Mozilla folks (i.e. @staktrace)

**Closed by IvanSanchez** 2020-10-27 22:07 UTC
Labels: needs investigation
