### ISSUE TITLE
After panning with mouse shows outline in every tile

### ISSUE THREAD

**Issue by Jinkwon** [Leaflet/Leaflet#6471] opened 2019-01-11 06:13 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
After panning the map, it shows ugly grid in tile outline.
I found it translated final coordinates was float value.
translate3d(5194.22px, -58.4258px, 0px):
if coordinates was int, it not shows.

**Expected behavior**
No outline in tiles.

**Current behavior**
show outline in every tiles.

**Environment**
- Leaflet version: Latest version
- Browser (with version): Chrome Latest version

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

- OS/Platform (with version): MacOS

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

<img width="490" alt="2019-01-11 3 06 50" src="https://user-images.githubusercontent.com/1798916/51016149-8d454580-15b2-11e9-8994-a9dcf0fbbc6f.png">
<img width="487" alt="2019-01-11 3 06 54" src="https://user-images.githubusercontent.com/1798916/51016150-8ddddc00-15b2-11e9-9977-8907b68ffdbf.png">

**Comment by IvanSanchez** [comment] 2019-01-11 11:00
Duplicate of #3575 (Note that the gap happens not only on fractional zoom levels but also on panning inertia)

**Closed by IvanSanchez** 2019-01-11 11:00 UTC
