### ISSUE TITLE
In Canvas mousedown event not called after dragging map

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7775] opened 2021-11-13 16:53 UTC
While useing `preferCanvas: true` and adding `mousedown` listener on a layer, the event is not fired correctly.
Tested on Firefox and Chrome.

Hard to reproduce and a very special usecase:
1. mousedown and move on the layer -> `mousedown` on the layer fired & map is moveing / dragging
2. drag the map outside of the layer
3. mousedown and move on the layer -> `mousedown` on the layer is not fired

```
		var circle = L.circle(map.getCenter(), {radius: 500}).addTo(map);
		circle.on('mousedown',(e)=>{
			console.log('Circle mousedown');
		});
		L.DomEvent.on(map.getContainer(),'mousedown',(e)=>{
			console.log('Map mousedown','');
		})
```

After clicking somewhere on the map, it is working again and possible to fire `mousedown` on the layer.

I found out that this happens because `moved()` is `true`:
https://github.com/Leaflet/Leaflet/blob/a37f0297afd1e547e94d5ae4e217f7cef1d696c8/src/map/handler/Map.Drag.js#L88-L90

The stacktrace:
https://github.com/Leaflet/Leaflet/blob/a37f0297afd1e547e94d5ae4e217f7cef1d696c8/src/layer/vector/Canvas.js#L353
https://github.com/Leaflet/Leaflet/blob/a37f0297afd1e547e94d5ae4e217f7cef1d696c8/src/map/Map.js#L1448-L1450

Demo: https://plnkr.co/edit/RZBfMbG3UERW1FB2

@johnd0e the problem occured since the commit https://github.com/Leaflet/Leaflet/commit/f2d625fcad8b5bf01bd7e98293ea0607c9d4fff7 -> PR #7059

![map_mousedown](https://user-images.githubusercontent.com/19800037/141651830-d9f3e8f8-d68b-45e2-b702-b06fc75ddc5b.gif)

**Comment by johnd0e** [comment] 2021-11-13 17:33
> I created no plunker because it only happens in the newest master version

https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet-src.js

**Comment by Falke-Design** [comment] 2021-11-13 17:39
Thanks searched for this but didn't found!

**Comment by johnd0e** [comment] 2021-11-13 18:44
Do you have automated test for this case?

**Comment by Falke-Design** [comment] 2021-11-13 18:55
Yes here:
```
it("does fire mousedown on layer after dragging map", function (done) {
			map = new L.Map(container, {
				preferCanvas: true,
				center: [0, 0],
				zoom: 15,
			});

			var spy = sinon.spy();
			var circle = L.circle(map.getCenter(), 300).addTo(map);
			circle.on('mousedown', spy);

			var hand = new Hand({
				timing: 'fastframe',
				onStop: function () {
					expect(spy.callCount).to.eql(2); // No drag event should have been fired.
					done();
				}
			});
			var mouse = hand.growFinger('mouse');

			mouse.wait(100)
				.moveTo(300, 300, 0).down().moveBy(5, 0, 20).up()
				.moveTo(100, 100, 0).down().moveBy(5, 0, 20).up()
				.moveTo(300, 300, 0).down().moveBy(5, 0, 20).up()
		});
```

Can be tested when you overwrite return to `false`:
https://github.com/Leaflet/Leaflet/blob/a37f0297afd1e547e94d5ae4e217f7cef1d696c8/src/map/handler/Map.Drag.js#L88-L90

**Comment by johnd0e** [comment] 2021-11-13 19:11
What if you revert #7439

**Comment by Falke-Design** [comment] 2021-11-13 19:42
No change. I also tried to use the commit before #7439 but is still failing

**Comment by johnd0e** [comment] 2021-11-14 11:44
> Can be tested when you overwrite return to `false`:

But then it fails another test:
https://github.com/Leaflet/Leaflet/blob/a37f0297afd1e547e94d5ae4e217f7cef1d696c8/spec/suites/layer/vector/CanvasSpec.js#L113

**Comment by johnd0e** [comment] 2021-11-14 13:03
BTW, this seems to be duplicate of #7007.

**Comment by johnd0e** [comment] 2021-11-15 08:53
@Falke-Design 
Could you give this issue more specific name?

**Comment by Falke-Design** [comment] 2021-11-15 08:55
Not realy 😁 Because I don't know from where the issue comes. `In Canvas mousedown event not called after dragging map`?

**Comment by johnd0e** [comment] 2021-11-15 09:05
Yeah, sort of.

**Closed** 2021-11-15 22:48 UTC
