### ISSUE TITLE
Strange behaviour on L.Control.Layers<._addLayer

### ISSUE THREAD

**Issue by rburone** [Leaflet/Leaflet#5076] opened 2016-11-03 16:36 UTC
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce
If i use a Array.prototype.someThing definitions, the layers dont´work and report the error: 
  _Error: layer.on is not a function
  L.Control.Layers<._addLayer@http://localhost/leaflet/lib/leaflet-src.js:12307:4
  L.Control.Layers<.initialize@http://localhost/leaflet/lib/leaflet-src.js:12169:4
  L.Class.extend/NewClass@http://localhost/leaflet/lib/leaflet-src.js:310:4
  L.control.layers@http://localhost/leaflet/lib/leaflet-src.js:12487:9_

```
addLayer: function (layer, name, overlay) {
		console.log(layer); ---> __function Array.prototype.someThing()_;
```
when i delete de Array.prototypes definitions. The layers started to work.
I patched putting a condition:

```
_addLayer: function (layer, name, overlay) {
      if (typeof layer == 'object') {
          ....
      }
```
then worked.

- Leaflet version I'm using: 2.0.0
- Browser (with version) I'm using: Firefox and Chrome.
- OS/Platform (with version) I'm using: Windows 8.

I´m using AngularJS 1.5.5 and the ui-leaflet.js library.

**Comment by IvanSanchez** [comment] 2016-11-03 17:46
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by IvanSanchez** [comment] 2016-11-03 17:47
> Leaflet version I'm using: 2.0.0

This is very doubtful, given that the latest version of Leaflet is 1.0.1.

> I´m using AngularJS 1.5.5 and the ui-leaflet.js library.

You are aware you checked the box next to « I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)», right?

**Comment by rburone** [comment] 2016-11-04 17:44
I'm very sorry, the ui-left.js is 2.0.0 version and leaflet is 1.0.1.

In my humble opinion, i think that´s may be a leaflet issue because the function acepted a wrong type data.

I'm not sure what happened, but I could analyze that everything happens when it goes through the initialization function of the layer.

Lines 1268~1270

```
for (var i in baseLayers) {
			console.log(typeof baseLayers);    ----> Object
			console.log(typeof baseLayers[i]); ----> Function and "i" is a name of function in prototype of the Array.
			this._addLayer(baseLayers[i], i);
		}

```
And this happends when i use Array.prototype....
Angular collections some times was like arrays and some times like as objects.
It's very probably there a messy with that.

I´m very sorry not be more helpful.

**Comment by yohanboniface** [comment] 2016-11-04 18:56
@rburone please provide a minimal test case without any dependencies (with http://playground-leaflet.rhcloud.com/), or open an issue to those dependencies first.
I'm closing because not action is needed on our part. Feel free to reopen once you have a test case, and feel free to continue the discussion.

**Closed by yohanboniface** 2016-11-04 18:56 UTC

**Comment by grischard** [comment] 2016-11-22 16:43
I think I've reproduced it:

https://playground-leaflet.rhcloud.com/kovu/edit?html,console,output
