### ISSUE TITLE
L.Browser.touch value is `true` on chrome windows 10 x64 bit

### ISSUE THREAD

**Issue by msschl** [Leaflet/Leaflet#7275] opened 2020-09-14 14:42 UTC
Up to leaflet v1.6.0 `L.Browser.touch` returned `false` on chrome. After the [change](https://github.com/Leaflet/Leaflet/pull/7010/files#diff-bc4c02f919ba9f4e3259e37fa12927a7L96) in PR #7010 in leaflet v1.7.1 this returns `true`, which messes up some styles for leaflet plugins e.g. `https://github.com/pelias/leaflet-plugin/`

Is this behavior intended?

**Environment**
- Leaflet version: v1.7.1
- Browser (with version):
- OS/Platform (with version):
```
Google Chrome | 85.0.4183.102 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Windows 10 OS Version 1903 (Build 18362.1082)
```

**Comment by IvanSanchez** [comment] 2020-09-14 15:11
Paging @johnd0e

**Comment by johnd0e** [comment] 2020-09-14 15:25
Nothing wrong is here.

See docs:
https://github.com/Leaflet/Leaflet/blob/dda26ba96d7dc79213818d1bcc0565b6ac3c69c4/src/core/Browser.js#L98-L102

**Comment by johnd0e** [comment] 2020-09-14 15:27
Close as duplicate of #5266

**Closed by johnd0e** 2020-09-14 15:27 UTC
Labels: bug, compatibility
