### ISSUE TITLE
Switch to a ES6 module system with Rollup

### ISSUE THREAD

**Issue by olanod** [Leaflet/Leaflet#3229] opened 2015-02-12 21:20 UTC
Have a version of leaflet which plays nice with SystemJs(and jspm) loader so we can import Leaflet components form ES6 code.
E.g.

```
import {Map, LatLng} form 'leaflet';
/*
var map = new Map({
  center: new LatLng(0,0)
})
*/
var map = Map({
  center: LatLng(0,0)
});
```

**Comment by mylen** [comment] 2015-03-30 09:02
:+1:

**Comment by tmcw** [comment] 2015-05-08 14:45
Have you confirmed that this doesn't work already?

```js
var { Map } = require('leaflet');
```

This code already works with [babel](https://babeljs.io/)

**Comment by mourner** [comment] 2015-05-08 15:00
@tmcw this is CommonJS, — I guess ES6-style modules would need some additional treatment.

@olanod do you know what changes would be required on the Leaflet side if we assume this needs to be supported?

**Comment by mourner** [comment] 2015-05-12 17:24
@patrickarlt any update?

**Comment by patrickarlt** [comment] 2015-05-12 23:42
@mourner doing a little bit more digging on this in the context of Leaflet. I'll post my finding and what I decided to do for Esri Leaflet here tomorrow.

**Comment by patrickarlt** [comment] 2015-05-13 00:16
Decided to just wrap this up now.

The sample that @tmcw  posted is just destructuring not a named import.

```js
var { Map } = require('leaflet');
```

Run through browserify + babelify just requires all of Leaflet and destructures the object to just pull out map.

What @olanod wants is for everything to be authored in an ES 6 format first. For whatever reason JSPM/SystemJS cannot do this if Leaflet is a CommonJS module. The sample below fails with "undefined is not a function" on `new Map`

```
import {Map, TileLayer} from 'leaflet';

var map = new Map('map').setView([37.75, -122.23], 10);

var tiles = new TileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
```

However this works because Leaflet is published as a CommonJS module.

```js
import L from 'leaflet';

var map = new L.Map('map').setView([37.75, -122.23], 10);

var tiles = new L.TileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
```

I took a look at the compiled code for both samples and concluded that named imports from CommonJS module was just a missing feature. Luckly JSPM and SystemJS are already ahead of us https://github.com/jspm/jspm-cli/issues/736 and https://github.com/systemjs/systemjs/issues/334.

---

So while we can just wait for SystemJS and JSPM to play cacthup on this and solve this exact issue (named exports from Leaflet) there are some other benifits of switching to the ES 2015 syntax that I explored in https://github.com/Esri/esri-leaflet/issues/525:

* Doing a named import like `import {Map, TileLayer} from 'leaflet';` will still import the all of Leaflet unless you use ES 2015 modules. Writing Leaflet with ES 2015 modules at the source level would mean that only the things required for `Map` and `TileLayer` are imported making the build smaller.
* You can eliminate the [deps.js](https://github.com/Leaflet/Leaflet/blob/master/build/deps.js) file to manage which files are required for other files and manage concatenation order.
* Once everything is written in ES 6 you could use browserify + babelify to build things for distribution. Browserify ships with support for standalone build with Global and UMD support so the build command would look like this. `browserify ./src/leaflet.js --standalone L -t [ babelify ]`. If you are only using modules you don't need a polyfill for ES 5 features but still carries a penalty in terms of file size.

**Comment by mourner** [comment] 2015-05-13 16:24
@patrickarlt thanks for a very thorough response!

I think this is something that we should keep an eye on for Leaflet core, but put off until we've dealt with more pressing issues like everything related to 1.0 release. 

It also seems too much hassle to switch to transpiler-based workflow just for the module system, which is not as useful in the Leaflet core itself - we'd rather start using more ES6 features at the same time to get more benefits to justify the switch.

**Comment by patrickarlt** [comment] 2015-06-23 05:17
@olanod Just so you know it looks like this should be working in SystemJS 0.17.0 it also looks there are some breaking changes in that release too, but thought you might like to know.

**Comment by patrickarlt** [comment] 2015-07-09 17:24
It took me most of yesterday but I did an experimental 1st draft of this working on the [ES6 branch](https://github.com/Esri/esri-leaflet/tree/es6) in Esri Leaflet and thought I would share a few pros and cons here.

###### Pros

* Massively simplified build system
* 1st class support for Browserify, JSPM and WebPack based projects
* Better support for AMD
* Still exposes a global

###### Cons

* Using ES 6 modules via Babel requires an `Object.defineProperty` polyfill for IE 8
* All of the module wrapping adds 4k (gzipped) to the file size
* Complicates testing infrastructure
* Complicates development workflow though could probably leverage JSPM to do everything on the fly though

**Comment by mourner** [comment] 2015-07-10 14:22
@patrickarlt thanks for sharing, pretty cool! 

I also just discovered https://github.com/rollup/rollup, which [d3 is switching to](https://twitter.com/mbostock/status/604339652506472449) for small custom builds — might be worth checking out.

Cons are probably too much at this point to consider ES6 modules for Leaflet core, but it's the future, so we'll have to make the switch eventually.

**Comment by patrickarlt** [comment] 2015-07-10 14:54
Also just realized because of #2364 you can't guarantee that `window.L` will be available if you want to do a partial import like

```js
import tileLayer from "leaflet/src/.../TileLayer"
import map from "leaflet/src/.../Map"

// no window.L here because the main leaflet file was never imported
```

So something like a rollup based bundler would probably be the way to do in the future for a custom Leaflet build with ES 6 modules.

>  but it's the future, so we'll have to make the switch eventually.

Pretty much sums it up for me. I might mess around with a custom builder for Esri Leaflet (since it is highly useful there) and see what could be adapted for use in Leaflet core.

**Comment by patrickarlt** [comment] 2015-07-11 23:36
After @mourner's tip above I started looking at [Rollup](https://github.com/rollup/rollup) and [Esperanto](https://github.com/esperantojs/esperanto). I would defiantly recommend using Esperanto or Rollup over Babel to bundle and package modules. It looks like there was discussion on [merging Babel and Esperanto](https://github.com/babel/babel/issues/1118) and it was generally agreed that babel should do transpiring and Esperanto should do module bundling.

After switching to Esperanto there was **ZERO** file size bloat (Esperanto just does straight concatenation) and the resulting code is compatible with IE 8 without a polyfill. This negates the major cons from my investigations above and could in theory allow us to move to ES 6 modules use Esperanto to replace the current build process.

I'm going to continue to pursue this approach for building/bundling In Esri Leaflet since I can take a hit rethinking the testing and development workflows and have wanted to redo the build toolchain anyway and keep posting what I find back here.

**Comment by mourner** [comment] 2015-07-15 13:12
@patrickarlt Great to hear that Esperanto worked so well! 
Is there anything actionable in Leaflet related to ES6 modules (other than switching to Esperanto with it)? If not, I think we can close this for now and reconsider in future.

**Comment by mourner** [comment] 2016-09-27 17:09
Let's reconsider now. I've started https://github.com/Leaflet/Leaflet/pull/4952 to make this easier.

**Comment by mourner** [comment] 2016-09-29 16:09
Another reason to switch to a proper bundler sooner rather than later: http://blog.dareboost.com/en/2016/09/avoid-using-document-write-scripts-injection/ (tl;dr we won't be able to use the current debug pages starting with Chrome 54)

**Closed** 2017-01-30 10:35 UTC
Labels: feature, in progress

**Comment by nyurik** [comment] 2017-06-29 01:11
@mourner is there a guide on how leaflet plugins should now be structured?  Ideally, please refactor one of the existing plugins to be a "best practices" guide on using leaflet 1.1 w/ rollup & es6. Thanks!

**Comment by IvanSanchez** [comment] 2017-06-29 07:57
@nyurik I've been working on refactoring one of my plugins so it's coded in ES2015, but it's still not finished: https://gitlab.com/IvanSanchez/Leaflet.GLMarkers/commit/4a1e64f4f1dbc20b8f729c280b98bcf0b0083c6a

I'm trying to find/create a good pattern for writing ES2015 code that can work with ES5 Leaflet code, but it's not being the easiest thing.
