### ISSUE TITLE
Leaflet tries to get negative value images or images that don't exist

### ISSUE THREAD

**Issue by donaldallen** [Leaflet/Leaflet#2981] opened 2014-10-28 16:17 UTC
Here is my Leaflet config:

```javascript
function init() {
    var mapMinZoom = 2;
    var mapMaxZoom = 5;
    var map = L.map('map', {
        maxZoom: mapMaxZoom,
        minZoom: mapMinZoom,
        crs: L.CRS.Simple
    }).setView([0, 0], mapMaxZoom);

    var mapBounds = new L.LatLngBounds(
        map.unproject([0, 4352], mapMaxZoom),
        map.unproject([2048, 0], mapMaxZoom));

    map.fitBounds(mapBounds);
    L.tileLayer('/assets/themes/sec/img/tiles/{z}/{x}/{y}.png', {
        minZoom: mapMinZoom,
        maxZoom: mapMaxZoom,
        bounds: mapBounds,
        noWrap: true,
        continuousWorld: true
    }).addTo(map);

    var store_marker = L.marker([0, 0]).addTo(map);
}
```

Everything works, but I get a lot of "resource not found" in my console whenever I zoom or pan:

```console
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (0.png, line 0)
http://localhost:3000/assets/themes/sec/img/tiles/2/-1/0.png

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (0.png, line 0)
http://localhost:3000/assets/themes/sec/img/tiles/2/1/0.png

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1.png, line 0)
http://localhost:3000/assets/themes/sec/img/tiles/2/-1/1.png

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1.png, line 0)
http://localhost:3000/assets/themes/sec/img/tiles/2/1/1.png
```

I have no negative numbered tiles. The files referenced here don't exist. Yet everything looks fine on the map. I used MapTiler to build the map. Anything I can do to fix this?

**Comment by SundialServices** [comment] 2015-05-19 20:16
I don't know exactly what Rob meant when he said, "add 1 to all the coordinates."  Anyhow, there are definitely problems with setBounds, setMaxBounds and fitBounds in the 0.7 release.  For my map, which is 1164x700 pixels (tiled from upper-left), I get a slew of (always negative ...) URL requests coming out of the back-end, and maps that, although they do "bounce back," are neither correctly positioned (centered) on the screen, nor of the proper size, if "fitBounds()" is used at all.

**Comment by xPaw** [comment] 2015-05-30 21:38
Looks like bounds are simply checked incorrectly, adding 1 pixel to lower bounds, and removing 1 pixel from upper bounds fixes the issue.

**Comment by Eschon** [comment] 2015-06-02 08:54
@xPaw can you explain what you mean by lower/upper bounds?

Do you mean changing
```JavaScript
var mapBounds = new L.LatLngBounds(
map.unproject([0, 4352], mapMaxZoom),
map.unproject([2048, 0], mapMaxZoom));
```
to 
```JavaScript
var mapBounds = new L.LatLngBounds(
map.unproject([1, 4351], mapMaxZoom),
map.unproject([2047, 1], mapMaxZoom));
```

**Comment by xPaw** [comment] 2015-06-02 08:56
@Eschon Yep, that's what I mean.

**Comment by IvanSanchez** [comment] 2015-06-02 09:11
I *think* that the problem resides in the difference between [this bit of code](https://github.com/Leaflet/Leaflet/blob/stable/src/layer/tile/TileLayer.js#L296) in 0.7.x:

```js
		var tileBounds = L.bounds(
		        bounds.min.divideBy(tileSize)._floor(),
		        bounds.max.divideBy(tileSize)._floor());
```

And [this bit of code](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L621) in master:

```js
		return new L.Bounds(
			bounds.min.divideBy(this._tileSize).floor(),
			bounds.max.divideBy(this._tileSize).ceil().subtract([1, 1]));
```

@xPaw Does your problem happen in 0.7.x, master, or both? If using 0.7.x, can you set up a breakpoint in the javascript code I've referred to and see if the values are offset by one?

**Comment by xPaw** [comment] 2015-06-02 09:13
It's both 0.7 and master.

**Comment by IvanSanchez** [comment] 2015-06-02 09:41
Hm. I think I was wrong in my previous note. See [this line here](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L465):

```js
	return L.latLngBounds(this.options.bounds).intersects(tileBounds);
```

A tile will be loaded if its bounds **intersect** the layer bounds. This is true for overlapping edges.

Maybe it's time to break open the books on spatial operators and see if `bounds.contains()` will work or not.

**Comment by Eschon** [comment] 2015-06-02 09:48
@xPaw's workaround doesn't work for me. I guess I'll stick to my workaround by adding 1x1 transparent dummy tiles until this gets fixed.

**Comment by IvanSanchez** [comment] 2015-06-02 10:43
OK, folks, #3508 needs some love (and testing of that branch) to see if it solves the problem gracefully.

**Comment by mourner** [comment] 2015-06-04 10:15
@Eschon @xPaw @robkovacs @SundialServices @donaldallen guys, could you try the PR above and see if it works as expected?

**Comment by donaldallen** [comment] 2015-06-04 12:11
Works perfectly for me. Thank you so much!

**Closed** 2015-06-04 12:24 UTC
Labels: bug, in progress, projections

**Comment by mikila85** [comment] 2017-02-06 08:18
i downloaded the latest:
Leaflet 1.0.3 and i still see this 404 when i zoom out of map with noWrap because of 0 and negative numbers in the x y z.
anyone knows how to solve this?

**Comment by IvanSanchez** [comment] 2017-02-06 09:02
@mikila85 If this bug is still reproducible in 1.0.3, please publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour.

**Comment by mikila85** [comment] 2017-02-07 08:10
it is still reproducible but adding bounds: [[-90, -180], [90, 180]] solved the problem. thx <3

**Comment by josephrocca** [comment] 2017-05-03 07:09
@IvanSanchez I'm having the same problem - still reproducible in 1.0.3: http://jsbin.com/tiducorejo/edit?html,output

**Comment by IvanSanchez** [comment] 2017-05-03 08:20
@josephrocca If you specify the `noWrap` option, and not the `bounds` option for the tilelayer, then this is behaviour **as expected**.

**Comment by josephrocca** [comment] 2017-05-03 10:31
Ahh thanks - sorry for the trouble!

**Comment by timgavin** [comment] 2022-11-04 17:31
For anybody else that comes across this issue my solution was to change the map bounds from 0 to 1

original
```javascript
L.tileLayer('/map/map/{z}/{x}/{y}.jpg', {
    minZoom: 1,
    maxZoom: 6,
    noWrap: true,
    bounds: [
        [-85.675, -675],
        [85.622, 675]
],
     crs: L.CRS.Simple
}).addTo(map);

let mapSW = [0, 16384];
let mapNE = [16384, 0];

map.setMaxBounds(new L.LatLngBounds(map.unproject(mapSW, map.getMaxZoom()),map.unproject(mapNE, map.getMaxZoom())));
```

changed 0 to 1 and now no more 404 errors!
```javascript
let mapSW = [1, 16384];
let mapNE = [16384, 1];
```
