### ISSUE TITLE
Map freeze problem, but unlocks after marker click

### ISSUE THREAD

**Issue by iandeherdt** [Leaflet/Leaflet#2693] opened 2014-05-21 09:34 UTC
Hello

I'm using leaflet 0.7.2 in a windows RT application, developed with the use of the WinJS library. I'm also using angularjs as the basis for the application. The map freezes 1/20 times when i zoom in or out. When i press a marker on the map, the map unfreezes and becomes responsive once more. When i use the leaflet-src and debug the problem i notice, that when the problem occurs the "_catchTransitionEnd"  isn't called. When i press a marker the "_catchTransitionEnd" is called and the map unfreezes. Does anyone know what is causing this problem, and better still how to fix it? a quick workaround would be great, because of the deadline i'm on.

Any help would be greatly appreciated.

Thanks in advance

Ian

**Comment by mourner** [comment] 2015-03-03 13:08
Guys, could you please test if things got better after #3270?

**Comment by fnicollet** [comment] 2015-03-04 23:58
Hello,
This bug is a pain to reproduce. Even removing the previous workaround, I can't reproduce it after a few dozens tries.
But the commit looks like it would solve the issue tracked down by @fab1an, hopefully he has better luck than I did to reproduce it!

Fabien

**Comment by dagjomar** [comment] 2015-10-03 21:18
I can confirm that this bug is still present in the beta version of leaflet 1.0

I can easily reproduce this bug in Safari on an iOS device
http://g.recordit.co/HKvKPEDhFn.gif

For me, it happens in a special case where I try to zoom past the maxZoom limit. The map wants to animate the zoom back to the "same" beforeZoom property, but still the transitionEnd event is not fired :(

http://g.recordit.co/HKvKPEDhFn.gif

**Comment by IvanSanchez** [comment] 2015-10-05 11:51
Still reproducible - particularly when using a touchscreen to zoom past `maxZoom` with `bounceAtZoomLimits=true` on iOS devices. (I think it depends on some other factors so unfortunately cannot provide a clean test case)

The fix @dagjomar refers to is firing a synthetic `_catchTransitionEnd` via `debounce`: https://github.com/Leaflet/Leaflet/issues/1759#issuecomment-55228732 - this is not exactly the timer solution that @mourner would prefer, but would do the job.

**Comment by dagjomar** [comment] 2015-10-06 08:27
Yeah, like @IvanSanchez says, it's zooming past maxZoom which has triggered the bug most consistently.


This is the setup I use to reproduce the bug

http://jsbin.com/huyisorufo/edit?html
View on mobile device: http://jsbin.com/huyisorufo/

**Comment by fab1an** [comment] 2015-10-06 08:56
@mourner Your patch might not catch all occasion where this occurs.

Whoever is affected by this: please add a logging line in DomUtil to see if they same transform-value is still being applied.

I think the way to fix this is store the last transform value for per element in DomUtil. It takes some memory, but it frees us from adding patch code everywhere.

**Comment by IvanSanchez** [comment] 2015-10-07 11:19
Closed via #3894

**Comment by narrowtux** [comment] 2015-10-23 13:31
Just a heads up, this issue is not closed although the last comment says it would be.

**Comment by yohanboniface** [comment] 2015-10-23 13:47
Thanks :)

**Closed by yohanboniface** 2015-10-23 13:47 UTC
Labels: blocker, in progress

**Comment by dagjomar** [comment] 2015-10-26 15:06
Well, should it really be closed? Will no-one find a better workaround than the current one?

**Comment by narrowtux** [comment] 2015-10-28 12:01
Update to this: I changed my project around a bit so I am not using angular-mapbox in any way, just the normal Mapbox 2.2.2 Javascript library. The bug still persists, weirdly only for the `click` event.
