### ISSUE TITLE
maxBounds and map.invalidateSize cause imageOverlay to flicker

### ISSUE THREAD

**Issue by adgoncal** [Leaflet/Leaflet#3197] opened 2015-02-04 23:20 UTC
I have the issue using Windows 7, Leaflet 0.7.3, Firefox 34.0.5, Chrome 40.0.2214.93 m and Internet Explorer 11.

[jsfiddle: Leaflet 0.7.3](http://jsfiddle.net/8zr3d9hn/13/)
[jsfiddle: Leaflet 0.8-dev](http://jsfiddle.net/8zr3d9hn/15/)

The image starts flickering, or rather "dancing" on certain zoom levels when the bounds do not take up the whole container and panInsideBounds is called immediately following a call to map.invalidateSize. The "dance" is simply the css transform: translate() property getting updated indefinitely with 1px difference between updates. 

When it is "dancing" you lose the ability to pan or zoom and it logs the following error:
"TypeError: point is undefined on leaflet-src.js (line 1050, col 2)
  return open + point.x + 'px,' + point.y + 'px' + close;"

This error occurs on L.DomUtil.getTranslateString. I investigated the function call and the undefined point comes from L.Map.panInsideBounds.

@mourner, do you have any idea why this is happening and what I can do to fix it?

I have seen the "dance" occur in both horizontal and vertical directions, but not both at the same time. However, it seems more common on the horizontal direction. Additionally, I have seen this issue in multiple computers, and at least 3 different-sized monitors, all of which were using 1920x1080 resolution. I had some difficulty replicating the issue on jsfiddle and found that width: 1900px and height: 1041px worked often with zoom set to 29 in my custom CRS, but the issue is not limited to these values. 

I am currently investigating leaflet's source looking for a way to fix the issue, but any help is greatly appreciated. 
![dancingimageoverlay](https://cloud.githubusercontent.com/assets/10856791/6051927/9343077c-ac9a-11e4-84df-ed367c267c45.gif)
Above gif shows the dancing as I see it on my computer in case you are not able to replicate using the jsfiddle.

Update: I added a jsfiddle using Leaflet 0.8, which has the same issue.

**Comment by adgoncal** [comment] 2015-02-09 16:48
Adding a log in panInsideBounds, not only does the translate string change by 1px back and forth, the map center changes back and forth as well:

```
{
	center: { 
		lat: 1424.8275862068963, 
		lng: 2135.1724137931033
	}, newCenter: { 
		lat: 1423.4482758620688, 
		lng: 2136.5517241379307
	}
}

{
	center: {
		lat: 1424.8275862068963, 
		lng: 2137.931034482758
	}, newCenter: { 
		lat: 1423.4482758620688, 
		lng: 2136.5517241379303
	}
}

{
	center: { 
		lat: 1424.8275862068963, 
		lng: 2135.1724137931033
	}, newCenter: { 
		lat: 1423.4482758620688, 
		lng: 2136.5517241379307
	}
}

{
	center: { 
		lat: 1424.8275862068963, 
		lng: 2137.931034482758
	}, newCenter: {
		lat: 1423.4482758620688, 
		lng: 2136.5517241379303
	}
}
...
```

**Comment by adgoncal** [comment] 2015-02-09 21:55
I have just figured out how to replicate the issue consistently, by calling invalidateSize on map followed by panning the imageOverlay:
[jsfiddle](http://jsfiddle.net/8zr3d9hn/13/)

**Comment by adgoncal** [comment] 2015-05-14 17:21
I found that the following worked for my project, though I am not sure whether this would work as a general solution to the problem:

```javascript
L.Map.extend({
	panInsideBounds = function (bounds, options) {
		var center = this.getCenter(),
			newCenter = this._limitCenter(center, this._zoom, bounds);

		// Override the portion that checks whether center and newCenter are equal, using a custom number for the margin of error
		var margin = Math.max(
		Math.abs(center.lat - newCenter.lat),
		Math.abs(center.lng - newCenter.lng));

		if (margin <= 1 / this.options.crs.scale(this._zoom)) {
			return this;
		}

		return this.panTo(newCenter, options);
	}
});
```

**Comment by Eschon** [comment] 2015-09-29 06:48
I have a similar issue where my map starts to flicker. 
I use a map with L.CRS.Simple to display a tiled image. The maxBounds are set to fit the image. I use getScaleZoom to calculate a Zoom so that the map size fits the window size as close as possible. For certain window/map sizes the map starts "dancing" like in @adgoncal's fiddle.

For additional information: I'm using the leaflet 1.0 beta1 and so far I have seen this in latest Safari and Chrome.

**Comment by Eschon** [comment] 2015-09-29 07:32
@adgoncal's workaround doesn't work for me when I use L.Map.extend, but it works when I add it to the Leaflet src and build a new version.

**Comment by Eschon** [comment] 2016-04-20 09:10
The issue hasn't happened for me since I started testing with the 1.0 release candidate without the workaround but it seems it is still present with @adgoncal's fiddle. Here's a version with the updated leaflet: http://jsfiddle.net/Eschon/muv8eyju/

But contrary to his description zooming and panning now works and sometimes fixes the "dancing".

**Comment by jonkoops** [comment] 2022-07-24 11:46
Can anyone verify this is still an issue that occurs?

**Comment by Malvoz** [comment] 2022-10-29 09:34
Can reproduce in v1.9.2, but it is fixed on the `main` branch, probably per https://github.com/Leaflet/Leaflet/pull/8534.

**Closed by Malvoz** 2022-10-29 09:34 UTC
Labels: bug, accepted, help wanted

**Comment by jonkoops** [comment] 2022-10-31 16:49
Thanks @Malvoz!
