### ISSUE TITLE
source map not working in 1.0rc1

### ISSUE THREAD

**Issue by neothemachine** [Leaflet/Leaflet#4631] opened 2016-06-08 12:12 UTC
I'm trying out the 1.0 rc1 and noticed that I can't put breakpoints into leaflet code in Chrome. As soon as I try to set a break point on a line it jumps to the corresponding source module file and puts the breakpoint at the first line of that, not the line I wanted. And then the debugging doesn't work. If I manually set a breakpoint in the module file, the debugger doesn't stop there, so I assume somewhere the association is lost.

**Comment by IvanSanchez** [comment] 2016-06-08 12:15
Duplicate of #4455, fixed in the master branch already.

**Closed by IvanSanchez** 2016-06-08 12:15 UTC
