### ISSUE TITLE
GridLayer's _tileZoom can be null instead of undefined

### ISSUE THREAD

**Issue by kikuchan** [Leaflet/Leaflet#5871] opened 2017-10-26 02:49 UTC
Hi, I've just found a bug while trying to implement my own CRS.

https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L644
Sometimes `this._tileZoom` can be `null` instead of `undefined` here, set by `_invalidateAll()` for example.
Due to the bug, the code run into `undefined`/`null`/`NaN` calculations.
It calls CRS's `scale()` function with `null`, and if the `scale()` returns `NaN` or something, causes `Attempted to load an infinite number of tiles` exception, in my case.

Simply add `|| this._tileZoom === null` solves the issue.

Thank you.

**Comment by cherniavskii** [comment] 2017-10-26 07:09
I think `_invalidateAll` should set `this._tileZoom` to `undefined` instead of `null`.

**Comment by cherniavskii** [comment] 2017-10-26 07:12
@kikuchan would you like to submit a PR?

**Comment by kikuchan** [comment] 2017-10-27 17:15
Uh, sorry, no. I'm not so familiar with PR...
I confirmed that changing the code to `this._tileZoom = undefined;` in `_invalidateAll` and `onRemove` solves the issue.
Thank you.

**Comment by mariobro** [comment] 2017-11-03 20:06
Hi, it seems this issue was solved by iH8, but it's still open - was there another complication that came up?

**Comment by cherniavskii** [comment] 2017-11-04 13:40
@mariobro reviewer requested adding a test https://github.com/Leaflet/Leaflet/pull/5888#issuecomment-341759441

**Comment by cherniavskii** [comment] 2017-11-05 19:30
Hi @kikuchan,
could you set up a minimal example which reproduces this issue? Because I'm not able to reproduce it

**Comment by kikuchan** [comment] 2017-11-06 02:18
Here you are.
[leaflet-gridlayer-null-scale.zip](https://github.com/Leaflet/Leaflet/files/1444732/leaflet-gridlayer-null-scale.zip)

Click a button, and you'll get "Error: Attempted to load an infinite number of tiles" on console.

**Comment by cherniavskii** [comment] 2017-11-13 17:02
Closed by #5888

**Closed by cherniavskii** 2017-11-13 17:02 UTC
Labels: good first issue
