### ISSUE TITLE
New Chrome 55 Support - contextMenu

### ISSUE THREAD

**Issue by markyme21** [Leaflet/Leaflet#5220] opened 2016-12-27 14:46 UTC
Leaftlet 1.0.2
Google Chrome 55.0.2883.87 (64bit)
Ubuntu/Mac

Context menu won't open.
Does work on same configuration/code with Chrome  54.0.2840.71 (64-bit)

**Comment by perliedman** [comment] 2017-01-03 10:56
Hi there @markyme21,
could you provide an example where this happens? Which context menu do you mean? Right clicking on the Leaflet map on the Leaflet home page brings up the context menu for me in Chrome 55 on Ubuntu, but perhaps you're talking about a custom context menu, or some other use case?

**Comment by markyme21** [comment] 2017-01-03 11:09
Hey,
I might have opened the issue in the wrong place :)

Indeed i was talking about a custom context menu.

(https://github.com/aratcliffe/Leaflet.contextmenu)

**Comment by perliedman** [comment] 2017-01-03 13:38
@markyme21 alright, no worries! :smile: It sounds like this might be a duplicate of #5194.

**Closed by perliedman** 2017-01-03 13:38 UTC
