### ISSUE TITLE
IE 11 SVG zoom issue

### ISSUE THREAD

**Issue by ktyminski** [Leaflet/Leaflet#6306] opened 2018-08-22 11:02 UTC
- Leaflet version I'm using: 1.3.4
- Browser (with version) I'm using: IE11
- OS/Platform (with version) I'm using: W10

## What behaviour I'm expecting and which behaviour I'm seeing:
The issue I came across occures in IE11. I am using imageOverlay with SVG file, but when no viewBox property in svg is declared, zoom don't act properly. In chrome it works totally fine. I also tried to find a way to render it as a vector layer but it didn't work. Is it any possible workaround to make this work on IE ?

## Minimal example reproducing the issue
```javascript
var map = L.map('map', {
  crs: L.CRS.Simple,
});

var bounds = [[0,0], [1000,1000]];

var image = L.imageOverlay('./image.svg', bounds).addTo(map);
map.fitBounds(bounds);
```

**Comment by IvanSanchez** [comment] 2018-08-22 11:09
I think this is a duplicate of https://github.com/Leaflet/Leaflet/issues/5756 (or at least very related to #5756). Because `L.ImageOverlay` uses `<img>` instead of `<svg>`, some behaviour of SVG is not supported (or fails in IE).

Implementations of `L.SvgOverlay` in the form of pull requests will be welcome.

**Comment by mourner** [comment] 2018-10-05 11:56
@IvanSanchez I don't think we need another overlay type in the core. Maybe we could go by with just the `DivOverlay` for this case?

**Comment by jonkoops** [comment] 2022-07-24 11:44
Closing this issue as we have decided to drop support for Internet Explorer in a future version of Leaflet (see #6136).

**Closed by jonkoops** 2022-07-24 11:44 UTC
Labels: feature, needs solution, ie
