### ISSUE TITLE
Use Leaflet as node.js library

### ISSUE THREAD

**Issue by NtsDK** [Leaflet/Leaflet#7351] opened 2020-11-25 01:25 UTC
**Is your feature request related to a problem? Please describe.**
I want to use the same code both in browser and node.
Leaflet provides nice primitives for geo operations.
In my project I use LatLngBounds to get polygon bounds.

**Describe the solution you'd like**
I tried to import LatLngBounds but deeply inside it uses window object.
It will be awesome if it will not require to have window.

**Describe alternatives you've considered**
I apply a fictive hack - introduce `global.window = {};`
But unfortunately it breaks Dropbox library in node.js environment.
I improved this hack to fix Dropbox problem but I will prefer to avoid hacks.

```
import 'leafletWindow'; // global.window = {};
import { LatLngBounds } from 'leaflet/src/geo/LatLngBounds';
import 'leafletUnwindow'; // delete global.window;
```

**Comment by IvanSanchez** [comment] 2020-11-25 03:18
Closing as a duplicate of https://github.com/Leaflet/Leaflet/pull/6715

**Closed by IvanSanchez** 2020-11-25 03:18 UTC
