### ISSUE TITLE
L.Icon.Default(options) icon retina override

### ISSUE THREAD

**Issue by jonenst** [Leaflet/Leaflet#3696] opened 2015-07-30 17:32 UTC
Hi,
With leaflet 0.7.3 and current master, the Default icon allows to override the iconUrl and shadowUrl but not the iconRetinaUrl. See http://jsfiddle.net/vcbvzr55/2/ (note: you can test the retina mode by zooming in firefox)

The attached patch fixes the behavior for icon2 while maintaining the "degradation to normal icon" behavior of icon3, feel free to use it in any way you like. I noticed @mourner and @danzel worked on this part of the code.
- jsfiddle top line: current behavior:
  - icon1 (left): OK: uses retina icons
  - icon2 (middle): NOK: doesn't use the supplied retina icon
  - icon3 (right): OK: correctly uses the default icon even in retina mode because iconRetinaUrl is not defined but iconUrl is defined
- jsfiddle bottom line: after patch:
  - icon5 (middle): OK: uses retina icons

It might be useful to also update the docs:
Change

> L.Icon.Default extends L.Icon and is the blue icon Leaflet uses for markers by default.

To

> L.Icon.Default extends L.Icon and is the blue icon Leaflet uses for markers by default. The constructor accepts the same options as L.Icon except it ignores 'shadowRetinaUrl'. You can use the L.Icon.Default.imagePath property to use your additional images from leaflet's default folder, for example:
> 
> ``` javascript
> new L.Icon.Default({
>     iconUrl: L.Icon.Default.imagePath + "/marker-icon-green.png",
>     iconRetinaUrl: L.Icon.Default.imagePath + "/marker-icon-green-2x.png"
> });
> ```

patch:

``` diff
--- /tmp/Icon.Default.js        2015-07-30 17:38:54.504167213 +0200
+++ /tmp/Icon.Default-retina.js 2015-07-30 17:44:33.844183175 +0200
@@ -13,6 +13,14 @@

        _getIconUrl: function (name) {
                var key = name + 'Url';
+               var isRetinaIcon = L.Browser.retina && name === 'icon';
+
+               if (isRetinaIcon) {
+                       var Retinakey = name + 'RetinaUrl';
+                       if (this.options[Retinakey]) {
+                               return this.options[Retinakey];
+                       }
+               }

                if (this.options[key]) {
                        return this.options[key];
@@ -24,7 +32,7 @@
                        throw new Error('Couldn\'t autodetect L.Icon.Default.imagePath, set it manually.');
                }

-               return path + '/marker-' + name + (L.Browser.retina && name === 'icon' ? '-2x' : '') + '.png';
+               return path + '/marker-' + name + (isRetinaIcon ? '-2x' : '') + '.png';
        }
 });

```

Finally, I wonder if the behavior of ignoring 'shadowRetinaUrl' is useful or if it should be used if passed to the constructor. If so, the `+               if (isRetinaIcon) {` line can be changed to `+               if (L.Browser.retina) {`

**Comment by johnd0e** [comment] 2020-04-14 06:58
As I can see the issue is resolved in 1.x versions. 
And as nobody is going to port it back to 0.7.x, I close the issue.

**Closed by johnd0e** 2020-04-14 06:58 UTC
