### ISSUE TITLE
adding nautical miles to Control.scale

### ISSUE THREAD

**Issue by Pomax** [Leaflet/Leaflet#8864] opened 2023-02-25 17:34 UTC
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

When using leaflet for things like sailing or flight sims, or shipping/flight visualisation, distances use nautical miles, abbreviated as NM, which is slightly longer than the imperial mile. It would be great if the `Control.Scale` options could be extended to

options | type | default | description
-- | -- | -- | --
metric | Boolean | True | Whether to show the metric scale line (km/m).
imperial | Boolean | True | Whether to show the imperial scale line (mi/ft).
nautical | Boolean | True | Whether to show the nautical scale line (nm/ft).

(technically aviation uses `NM` instead of `nm`, but that's an irrelevant difference)

Also note that this table reverses the order for `metric` to be `km` first, `m` second, so that all three use the same "main/secondary" format.

### Suggested solution

The nautical mile is exactly 1852km, so should hopefully be fairly easy to implement .

### Alternatives considered

there isn't really an alternative in this case.

**Comment by Falke-Design** [comment] 2023-02-26 15:16
Duplicate of #7788. This a perfect usecase for a plugin.

Maybe this helps you: https://github.com/PowerPan/leaflet.nauticscale

**Closed by Falke-Design** 2023-02-26 15:16 UTC
Labels: feature, needs triage

**Comment by Pomax** [comment] 2023-02-27 00:26
cheers
