### ISSUE TITLE
Path - setStyle() not working with classes

### ISSUE THREAD

**Issue by slaven3kopic** [Leaflet/Leaflet#6083] opened 2018-03-06 11:55 UTC
- Leaflet version I'm using: 0.7.7
- Browser I'm using: Google Chrome (64.0.3282.186)
- OS I'm using: Windows 10 Version 1607 (OS Build 14393.2068)
- Create Polyline with specific className
- Try to update Polyline className using function setStyle
- updated className is not assigned to Polyline-s path

## What behaviour I'm expecting and which behaviour I'm seeing

Updated className should be added to Polyline path

## Minimal example reproducing the issue

https://plnkr.co/edit/xhZRLd

**Comment by perliedman** [comment] 2018-03-06 17:49
Hi!

This is indeed true, `setStyle` does not consider the `className` option. However, this is a duplicate of #2662, see that issue for an in depth discussion of the issue.

BTW, please consider upgrading your Leaflet version, 0.7.7 is starting to get quite old, and we do not actively maintain 0.7 - so even if this issue would be fixed, you would not benifit from it.

**Closed by perliedman** 2018-03-06 17:49 UTC
