### ISSUE TITLE
Map gets stuck if a marker is removed while dragging it

### ISSUE THREAD

**Issue by jessenic** [Leaflet/Leaflet#5638] opened 2017-07-17 14:06 UTC
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using: Chrome 59 + Edge 40
- OS/Platform (with version) I'm using: Windows 10 Creators Update
- Create a marker and bind to dragstart event, remove marker when event fires.
- Move marker --> map gets stuck

## What behaviour I'm expecting and which behaviour I'm seeing
Map should not get stuck if the dragged marker gets removed. This happens with 1.1.0, but not with 1.0.3.

## Minimal example reproducing the issue

Start dragging the marker in these:
1.1.0: https://jsfiddle.net/3v7hd2vx/345/
1.0.3: https://jsfiddle.net/3v7hd2vx/346/

- [ x ] this example is as simple as possible
- [ x ] this example does not rely on any third party code

**Comment by Ceremony64** [comment] 2017-07-19 13:27
I can confirm this issue and it also applies for the events mousedown and contextmenu (on mobile for certain browsers).

**Comment by SethGreylyn** [comment] 2017-07-21 21:12
I've noticed this problem too, in the context of removing the pin when it is dragged beyond the map's bounding box. I've confirmed that the issue does not occur in 1.0.3. This is a fairly substantial bug for my application, possibly worth downgrading my Leaflet version for (unless I want to make an expensive check for the marker's location every time it's dragged).

**Comment by codeofsumit** [comment] 2017-07-26 07:16
This happens also when you simply remove a marker with a rightclick `contextmenu` event.

Here's the fiddle:
https://jsfiddle.net/3v7hd2vx/353/

Both markers are draggable. Remove one with a right click and the map plus markers become non-draggable.

This currently breaks the leaflet.pm plugin

**Comment by perliedman** [comment] 2017-07-26 10:20
Did a git bisect for this, which was a little tricky since we've changed the build system in 1.1.0 and 1.0.3, but it ended up showing 703ae02aa8cbd0b87be5b01e77754b83ad732267, which is our big ES6 refactor, as the breaking commit. Don't have time to investigate further, so I'll have to dig into this at some later point, but any help would be greatly appreciated.

**Comment by seethemhigh** [comment] 2017-08-03 13:22
Looks like it's been fixed, at least it work as of 50705e1f0d179a53229965393adc3da0f861d8b6.
Tested on Safari 10 and Chrome 59.

**Comment by perliedman** [comment] 2017-08-03 13:46
@seethemhigh hm, it does indeed appear that this is working with latest master: https://jsfiddle.net/y93r80x9/

@Ceremony64 @codeofsumit @SethGreylyn could you verify if this is also resolved for you in latest?

**Comment by SethGreylyn** [comment] 2017-08-04 04:36
@perliedman The issue seems to be resolved in the code from https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet-src.js, but not (yet?) on the CDN at https://unpkg.com/leaflet@1.1.0/dist/leaflet.js, which my project is using as its Leaflet source. Should I update the source, or wait until the latest changes are pushed to the CDN?

**Comment by codeofsumit** [comment] 2017-08-04 06:48
@SethGreylyn this will not get pushed to 1.1.0. They'll release a new version with the fix. To test it, you should include the master version in your project to test it.

**Comment by jjimenezshaw** [comment] 2017-08-04 09:27
Using `git bisect` I found that it was fixed in 748f65f119, in the file `src/dom/Draggable.js`.
The changes to move into ES6 style forgot this one, and `L.Draggable._dragging` is now `undefined`.
v1.0.3 was before all those changes.

Now it is clear how it was broken, and fixed ;)

**Comment by codeofsumit** [comment] 2017-08-04 09:42
@jjimenezshaw awesome! Any estimation about a patch release?

**Comment by perliedman** [comment] 2017-08-05 12:06
Thanks folks, great to hear this is fixed!

I hope that we can make a release in the coming week but can't unfortunately promise anything.

**Closed by perliedman** 2017-08-05 12:06 UTC
