### ISSUE TITLE
A way to distinguish between programmatic and user-originated view changes

### ISSUE THREAD

**Issue by jczaplew** [Leaflet/Leaflet#2267] opened 2013-12-05 22:12 UTC
Recently I have been using ````event.hard```` to distinguish between zoom and pan events that originate with the user, and ones generated internally. For example, 

````
map.on('zoomend', function(event) {
  if (event.hard) {
    console.log("From code");
  } else {
    console.log("From interaction");
  }
});
````

Although I haven't been able to find any documentation related to this method, it seems to work fairly well and is very handy for manually setting the map state without other listeners firing. In Firefox, Safari, and Chrome, ````event.hard```` will only be true when manually manipulating the map, say, with ````map.setView(...```` or with boxZoom. In IE9, it is true on every zoom event.

What this boils down to is:

1. If ````event.hard```` is intended to distinguish between user-based and code-based map interaction, it should not be true on boxZoom or on all zoom events in IE9.

2. If it is not, a method should exist on all map events that indicates whether the event originates with the user or code.

Any and all assistance is greatly appreciated, and if I can help fix/improve this let me know!

**Comment by IvanSanchez** [comment] 2016-09-26 13:00
Closing as duplicate of #2934

**Closed by IvanSanchez** 2016-09-26 13:00 UTC
Labels: feature
