### ISSUE TITLE
Make Map.getScaleZoom aware of CRS

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3808] opened 2015-09-04 12:04 UTC
Right now `getScaleZoom` is using `log2`, whereas `getZoomScale` uses `crs.scale()`.

It looks like we should edit `getScaleZoom` to use CRSs also. And make unit tests.

This looks like an easy task, so if there's any non-core-developer who wants to give it a shot, I'd love to see it happen :-)

**Comment by perliedman** [comment] 2015-09-07 07:07
I think this is a duplicate of #2990, but possibly more clearly stated :)

**Comment by mourner** [comment] 2015-09-07 10:08
Yes, let's close as duplicate.

**Closed by mourner** 2015-09-07 10:08 UTC
Labels: bug, easy fix, help wanted
