### ISSUE TITLE
Leaflet.Routing was not found in 'leaflet'

### ISSUE THREAD

**Issue by RRGT19** [Leaflet/Leaflet#8467] opened 2022-09-23 14:17 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Update leaflet to 1.9.0 or 1.9.1.

Also, I have:

- @types/leaflet
- leaflet-routing-machine
- @types/leaflet-routing-machine

### Expected behavior

This worked before 1.9.0:

```typescript
import {
  Routing,
} from 'leaflet';

import 'leaflet-routing-machine';

private routingControl: Routing.Control;
```

### Current behavior

```typescript
import {
  Routing
} from 'leaflet';
import 'leaflet-routing-machine';
```

Error:
`export 'Routing' (imported as 'Routing') was not found in 'leaflet' (possible exports: Bounds, Browser, CRS, Canvas, Circle, CircleMarker, Class, Control, DivIcon, DivOverlay, DomEvent, DomUtil, Draggable, Evented, FeatureGroup, GeoJSON, GridLayer, Handler, Icon, ImageOverlay, LatLng, LatLngBounds, Layer, LayerGroup, LineUtil, Map, Marker, Mixin, Path, Point, PolyUtil, Polygon, Polyline, Popup, PosAnimation, Projection, Rectangle, Renderer, SVG, SVGOverlay, TileLayer, Tooltip, Transformation, Util, VideoOverlay, bind, bounds, canvas, circle, circleMarker, control, default, divIcon, extend, featureGroup, geoJSON, geoJson, gridLayer, icon, imageOverlay, latLng, latLngBounds, layerGroup, map, marker, noConflict, point, polygon, polyline, popup, rectangle, setOptions, stamp, svg, svgOverlay, tileLayer, tooltip, transformation, version, videoOverlay)`

I have tried:

```typescript
import * as L from 'leaflet';
import 'leaflet-routing-machine';
```

Error:
` export 'Routing' (imported as 'L') was not found in 'leaflet' (possible exports: Bounds, Browser, CRS, Canvas, Circle, CircleMarker, Class, Control, DivIcon, DivOverlay, DomEvent, DomUtil, Draggable, Evented, FeatureGroup, GeoJSON, GridLayer, Handler, Icon, ImageOverlay, LatLng, LatLngBounds, Layer, LayerGroup, LineUtil, Map, Marker, Mixin, Path, Point, PolyUtil, Polygon, Polyline, Popup, PosAnimation, Projection, Rectangle, Renderer, SVG, SVGOverlay, TileLayer, Tooltip, Transformation, Util, VideoOverlay, bind, bounds, canvas, circle, circleMarker, control, default, divIcon, extend, featureGroup, geoJSON, geoJson, gridLayer, icon, imageOverlay, latLng, latLngBounds, layerGroup, map, marker, noConflict, point, polygon, polyline, popup, rectangle, setOptions, stamp, svg, svgOverlay, tileLayer, tooltip, transformation, version, videoOverlay)`

I have tried:

`import L from 'leaflet';`

Error:
`Module '"node_modules/@types/leaflet/index"' has no default export.`

### Environment

- Leaflet version: 1.9.1
- Browser (with version): All
- OS/Platform (with version): All

**Comment by jonkoops** [comment] 2022-09-23 14:32
Duplicate of #8451. The reason why `import L from 'leaflet'` is not working is probably because the TypeScript definitions (which we don't maintain) haven't been updated yet. You might want to try to enable [`allowSyntheticDefaultImports`](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports), it could solve that issue.

**Comment by jonkoops** [comment] 2022-09-23 14:32
Duplicate of #8451.

**Closed by jonkoops** 2022-09-23 14:32 UTC
Labels: bug, needs triage

**Comment by natBizitza** [comment] 2022-09-27 18:05
> Duplicate of #8451. The reason why `import L from 'leaflet'` is not working is probably because the TypeScript definitions (which we don't maintain) haven't been updated yet. You might want to try to enable [`allowSyntheticDefaultImports`](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports), it could solve that issue.


For some reason, this doesn't work for me. I installed leaflet@v1.9.1

**Comment by DesarrolloLocalizamos** [comment] 2024-09-13 14:41
Hola, muy buenos días. 
Esto teniendo un problema muy similar- Estoy usando  leaflet version
leaflet-routing-machine version
leaflet-draw version
leaflet.markercluster version
con las ultimas versiones. 
En un entorno local funciona todo, pero cuando compilo y subo a producción me da el siguiente error
TypeError: Cannot read properties of undefined (reading 'control')
    at r.reporteRuta (chunk-B3YYFBNG.js:379:309)
    at Object.next (chunk-B3YYFBNG.js:309:11212)
    at Q_.next (chunk-B3YYFBNG.js:172:3112)
    at Gh._next (chunk-B3YYFBNG.js:172:2795)
    at Gh.next (chunk-B3YYFBNG.js:172:2522)
    at chunk-B3YYFBNG.js:172:7401
    at qh (chunk-B3YYFBNG.js:172:2214)
    at gr.next (chunk-B3YYFBNG.js:172:7240)
    at gr.next (chunk-B3YYFBNG.js:172:9229)
    at r.setReporteRutaData (chunk-B3YYFBNG.js:274:3520)
    
    Estoy usando Angular 17, y compilo de la siguiente forma ng build --configuration production
    
    ¿Qué puede estar pasando?, ¿Cómo lo solucionaron ?
