### ISSUE TITLE
The `translate3d` of CSS causes popup to become blurred in some cases.

### ISSUE THREAD

**Issue by sytana** [Leaflet/Leaflet#6861] opened 2019-10-14 08:28 UTC
So, I tried to cancel `translate3d(x, y, z)` and use `translate(x, y)` ...

1. This is a failure because it disables CSS3.
```html
<script>L_NO_TOUCH = true;</script>
<script src="leaflet.js"></script>
```

2. This doesn't look like it works ...
```js
L.Browser.any3d = false
L.Browser.ie3d = false
L.Browser.webkit3d = false
L.Browser.gecko3d = false
L.Browser.mobileWebkit3d = false

let map = L.map(...)
```
![image](https://user-images.githubusercontent.com/11701135/66737765-6dbfae00-ee9f-11e9-8153-63645b2d6e86.png)
---
![image](https://user-images.githubusercontent.com/11701135/66737794-7ca66080-ee9f-11e9-846a-1d45e8fc9a65.png)

So what should I do?

**Comment by Malvoz** [comment] 2022-02-05 11:30
> `<script>L_NO_TOUCH = true;</script>`

@sytana You want to use [`L_DISABLE_3D`](https://leafletjs.com/reference#:~:text=L_DISABLE_3D).

Duplicate of https://github.com/Leaflet/Leaflet/issues/6232.

**Closed by Malvoz** 2022-02-05 11:30 UTC
