### ISSUE TITLE
leaflet.css alert in line 535 and 40

### ISSUE THREAD

**Issue by alan-morais** [Leaflet/Leaflet#7311] opened 2020-10-14 16:57 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
- step 2
- ...

**Expected behavior**

**Current behavior**

**Environment**
- Leaflet version:
- Browser (with version): Chrome Version 86.0.4240.75 (Official version) 64 bits
- OS/Platform (with version): Windows 10 home 64bits

**Additional context**
line 40 Also define the standard property 'transform-origin' for compatibility.
line 535 Also define the standard property 'zoom' for compatibility

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment] 2020-10-14 20:32
You missed the Leaflet version. At least some of this is already fixed by https://github.com/Leaflet/Leaflet/commit/0603741cf7322599a5bd4520eaf3ef90e00e9ada (see #6960).

Also, you're missing the exact error/warning messages.

Closing as invalid, since it's not (fully) reproducible in the latest release.

**Closed by IvanSanchez** 2020-10-14 20:32 UTC
