### ISSUE TITLE
zIndexOffset difference of 40000 does not place marker visibly above/on top of another marker that is 10 degrees lower vertically on the cartesian map

### ISSUE THREAD

**Issue by andrewhodel** [Leaflet/Leaflet#7980] opened 2022-02-07 12:37 UTC
**Steps to reproduce**

https://plnkr.co/edit/hyWro1sGgmjbeDPk

**Expected behavior**

The Google logo should be visually above (per z-index) the Yandex logo.

**Current behavior**

The Yandex logo is shown as on top of the google logo.

**Environment**
- Leaflet version: latest
- Browser (with version): Chrome 98.0.4758.80 (Official Build) (x86_64)
- OS/Platform (with version): MacOS 12.1

**Minimal example reproducing the issue**

https://plnkr.co/edit/hyWro1sGgmjbeDPk

**Comment by Malvoz** [comment] 2022-02-07 12:40
Duplicate of https://github.com/Leaflet/Leaflet/issues/5560.

**Closed by Malvoz** 2022-02-07 12:40 UTC
