### ISSUE TITLE
map.openTooltip() fails because no tooltip anchor

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#4827] opened 2016-08-18 11:45 UTC
Running `map.openTooltip(text, latlng);` fails with an error like `Uncaught TypeError: Cannot read property '_getTooltipAnchor' of undefined` in https://github.com/Leaflet/Leaflet/blob/master/src/layer/Tooltip.js#L175 - the code expects the `L.Tooltip` to have an `_anchor`, but this is not true when it's created via `map.openTooltip`.

Playground showing the issue: https://playground-leaflet.rhcloud.com/xay/1/edit?html,output

cc @yohanboniface

**Comment by snkashis** [comment] 2016-08-18 14:17
So I guess the fix for this is not as simple as what I thought, which is add a `this.source` check
```
	_getAnchor: function () {
		// Where should we anchor the tooltip on the source layer?
		return L.point(this.source && this._source._getTooltipAnchor && !this.options.sticky ? this._source._getTooltipAnchor() : [0, 0]);
	}
```
because after I did that, three tests fail, _Tooltip can be forced on left direction, Tooltip honours offset on left direction & Tooltip can be forced on center_. 

I'm trying to get more familiar with `L.Tooltip` as I am looking forward to using them extensively.

**Comment by yohanboniface** [comment] 2016-08-18 20:47
I sort of remember a discussion where we decided that a tooltip had to be on a feature, not directly on the map.
But it seems suboptimal. I'll have a look. @snkashis ping me on gitter if you want to pair on this.

**Comment by yohanboniface** [comment] 2016-08-22 17:46
> because after I did that, three tests fail, Tooltip can be forced on left direction, Tooltip honours offset on left direction & Tooltip can be forced on center. 

Humm, I just did that too and tests passe, that's weird.

**Comment by snkashis** [comment] 2016-08-22 18:58
Yeah, weird huh. I get the below, not that it helps much I think

> PhantomJS 2.1.1 (Mac OS X 0.0.0) Tooltip can be forced on left direction FAILED
	expected false to equal true
	assert@/Users/steve/Code/Leaflet/spec/expect.js:99:38
	equal@/Users/steve/Code/Leaflet/spec/expect.js:200:16
	/Users/steve/Code/Leaflet/spec/expect.js:73:29
	/Users/steve/Code/Leaflet/spec/suites/layer/TooltipSpec.js:82:31
PhantomJS 2.1.1 (Mac OS X 0.0.0) Tooltip honours offset on left direction FAILED
	expected true to equal false
	assert@/Users/steve/Code/Leaflet/spec/expect.js:99:38
	equal@/Users/steve/Code/Leaflet/spec/expect.js:200:16
	/Users/steve/Code/Leaflet/spec/expect.js:73:29
	/Users/steve/Code/Leaflet/spec/suites/layer/TooltipSpec.js:93:31
....
PhantomJS 2.1.1 (Mac OS X 0.0.0) Tooltip can be forced on center FAILED
	expected false to equal true
	assert@/Users/steve/Code/Leaflet/spec/expect.js:99:38
	equal@/Users/steve/Code/Leaflet/spec/expect.js:200:16
	/Users/steve/Code/Leaflet/spec/expect.js:73:29
	/Users/steve/Code/Leaflet/spec/suites/layer/TooltipSpec.js:153:31

**Comment by yohanboniface** [comment] 2016-08-22 19:04
You sure those tests passe without the fix, right? :)

**Comment by yohanboniface** [comment] 2016-08-22 19:06
One possible explanation of those failures is that Phantom may not be loading the CSS.
But no clue why that would happen specifically on your computer.

**Comment by snkashis** [comment] 2016-08-22 19:47
yes, confirmed again, works fine without my `source` check.

**Comment by yohanboniface** [comment] 2016-08-23 08:22
Quite hard to debug remotely.
Can you try switching from `L.marker` to `L.circleMarker` on those tests (because the image of the marker is not loaded in Phantom), and make a screenshot before the failure?

```
takeScreenshot();
```

This will create a `screenshot.png` file.

**Closed** 2016-08-25 13:29 UTC
Labels: bug, in progress
