### ISSUE TITLE
Example on leafletjs.com not working

### ISSUE THREAD

**Issue by HeyStenson** [Leaflet/Leaflet#6765] opened 2019-08-12 17:18 UTC
The example on the main leafletjs.com is not loading. This has been an issue since at least 8/9/19.

![Screen Shot 2019-08-12 at 10 17 17 AM](https://user-images.githubusercontent.com/8186438/62884046-6c7cd400-bcea-11e9-8900-766ca38c3831.png)

- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
- step 2
- ...

**Expected behavior**

**Current behavior**

**Environment**
- Leaflet version:
- Browser (with version):
- OS/Platform (with version):

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by jazdw** [comment] 2019-08-14 16:10
I think this is caused by the OpenStreetMap tile server timing out, I have seen this as well.

**Comment by ghybs** [comment] 2019-10-02 18:12
Hi,

Indeed, looks like a temporary issue with OSM tiles.
Working now, and there is little we can do about OSM tiles availability, so I m going to close this.

**Closed by ghybs** 2019-10-02 18:12 UTC
