### ISSUE TITLE
Leaflet 1.7.1 causes map elements (such as the zoom control) to be selected on long-press on iOS 14

### ISSUE THREAD

**Issue by samcrawford** [Leaflet/Leaflet#7394] opened 2020-12-31 10:52 UTC
Leaflet 1.7.1 causes map elements (such as the zoom control) to be selected on long-press on iOS 14.  This results in the user seeing a popup for copy/paste/select-all on whatever elements are on the page (the zoom control is the best example in a default map).

**Steps to reproduce**

* Setup a basic map, with all defaults
* Add a contextmenu event handler on the map to call alert('...')
* Observe that when long-pressing on iOS 14 the zoom control is selected (and you get the copy/paste/select-all popup) when a long-press occurs on the map. You still get the contextmenu event too, sometimes.

Note that I can also reproduce the issue by just visiting https://leafletjs.com/examples/quick-start/ on iOS 14 too and long-pressing on the map. The issue does not occur on Leaflet 1.6.0 or on iOS 12.5.

**Expected behaviour**

The copy/paste/select-all popup should not appear and nothing should be selected on a long-press on the map. The contextmenu event should fire when a long press occurs on the map reliably.

**Current behaviour**

Leaflet 1.7.1 causes map elements (such as the zoom control) to be selected on long-press on iOS 14, and the user sees a copy/paste/select-all popup. For example:

![example](https://user-images.githubusercontent.com/988733/103408168-46630880-4b59-11eb-9529-8f2fc39f7963.png)

Note that the issue _only_ appears on iOS 14 with Leaflet 1.7.1 (or Leaflet master branch).

The issue does not appear with:

* Leaflet 1.6.0 on iOS 14
* Leaflet 1.6.0 on iOS 12.5
* Leaflet 1.7.1 on iOS 12.5
* Leaflet 1.7.1 on any other OS/browser combination I have tested.

I do not have access to an iOS 13.x device to test with.

**Environment**

* Leaflet 1.7.1 (also appears with master)
* Browser: Safari (whatever version comes with iOS 14.3)
* OS: iOS 14.3 (latest)

**Additional context**

Having read https://github.com/Leaflet/Leaflet/issues/6865, I tried adding the following CSS:

    * { -webkit-touch-callout: none; -webkit-user-select: none; }

This successfully stopped the issue, but of course it prevented users from selecting any text as well (which is actually quite important to my application), so I wouldn't consider this a fix.

Having read https://github.com/Leaflet/Leaflet/issues/7255 I also tried the master branch, but saw no difference in behaviour from 1.7.1.

**Minimal example reproducing the issue**

Leaflet 1.7.1: https://jsfiddle.net/ut3bg82e/ - Reproduces the issue on iOS 14.3
Leaflet master: https://jsfiddle.net/s68q4da7/ - Reproduces the issue on iOS 14.3
Leaflet 1.6.0: https://jsfiddle.net/qer82o9w/ - Works fine on iOS 14.3

**Comment by johnd0e** [comment] 2020-12-31 11:00
Not sure that it is related, but try to disable `tap` handler: https://leafletjs.com/reference-1.7.1.html#map-tap

**Comment by samcrawford** [comment] 2020-12-31 11:05
> Not sure that it is related, but try to disable `tap` handler: https://leafletjs.com/reference-1.7.1.html#map-tap

Thanks for the suggestion. Unfortunately, that makes the situation worse. With 1.7.1 we now have:

iOS 14.3: Select text popup still appears, and contextmenu event no longer fires.
iOS 12.5: Select text popup now appears. Contextmenu event no longer fires.

**Comment by johnd0e** [comment] 2020-12-31 11:14
> Contextmenu event no longer fires.

Yeah, that is expected.
I just trying to figure out what exact change in leaflet should we blame for this behavior.

Here is the list: https://github.com/Leaflet/Leaflet/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc

**Comment by samcrawford** [comment] 2020-12-31 12:37
Okay, I've tracked down the commit and the specific line that seems to have caused it: https://github.com/Leaflet/Leaflet/commit/95c436638180efff57e50d6356062be96925fcee#diff-5c529ba8a005e494ea6280599f5e7a70576a7544ec825327efc4c77f2213c5fdL96

If I reintroduce the `!webkit && ` then it works as it did in 1.6.0.

**Comment by johnd0e** [comment] 2020-12-31 14:03
Thank you for this addition.
I believe that here you run into #7077.

**Comment by samcrawford** [comment] 2021-01-01 12:29
Confirmed - the fix proposed in https://github.com/Leaflet/Leaflet/pull/7029 resolves the issue.

**Comment by johnd0e** [comment] 2021-03-08 21:58
@samcrawford 
Please test again, with these two pages:

[test (tap:false)](https://gist.githack.com/johnd0e/3ad393c73b12b24af7e947711a87b7a4/raw/test.html)

[test (tap:true)](https://gist.githack.com/johnd0e/3ad393c73b12b24af7e947711a87b7a4/raw/test_tap_true.html)

**Comment by johnd0e** [comment] 2021-03-09 11:17
Duplicate of #6872

**Closed by johnd0e** 2021-03-09 11:17 UTC
Labels: bug, mobile
