### ISSUE TITLE
Disable dragging not working correctly in IE, FF

### ISSUE THREAD

**Issue by amir-infsoft** [Leaflet/Leaflet#4157] opened 2016-01-18 13:54 UTC
In my case I need to disable map panning when user clicks on map and re-enable it when mouse click is released.

(I am using current Leaflet v0.7.7)

I implement this with:  
```
//disable
map.on('mousedown', function (e) {
           console.log('mousemove');
           map.dragging.disable();
            return false;
        });

//in meanwhile I am monitoring mouse and intend to do some drawing 
//(that is why map has to stay fixed)
map.on('mousemove', function (e) {
            console.log('mousemove');
            //some drawing
        });

//re-enable
map.on('mouseup mouseout', function (e) {          
            map.dragging.enable();
            console.log('mouse up');
            return false;
        });
```
It works correctly in Chrome (testing in v47).

Interenet explorer (testing in v11): 
In IE it does not disable dragging. Actually it does disable dragging but later, when mouse press is released.

Firefox (testing in v43.0.4).
In Firefox panning is disabled, but then dragging images (default browser behavior) is enabled. I tried to disable it, but it does not work. Any other solution to disable image dragging here?
```
//works to disable other images dragging but not with leaflet tile images
$(document).on("dragstart", "img", function() {
            return false;
        });
```
Also if there is some other/better approach to get map fixed for drawing, please let me know...

Thanks for any help,
Amir

**Comment by IvanSanchez** [comment] 2016-01-18 13:55
Which versions of Leaflet, IE, Chrome, Firefox?

**Comment by amir-infsoft** [comment] 2016-01-18 14:02
I have updated post with version details

**Comment by IvanSanchez** [comment] 2016-01-18 14:06
Maybe the issue is just the order of the `mousedown` events: `map.on('mousedown', ...)` might be running *after* the map dragging logic fires up - different browsers are known to fire events in different orders. So the right way to do it should be to always disable map dragging, before any potentially-dragging event takes place.

Otherwise, I advise you to upgrade to some of the 1.0.0 betas - right now it's unlikely we'll spend the time tracking down a bug like this one in the 0.7.x series.

**Comment by amir-infsoft** [comment] 2016-01-18 15:36
I tested with new Leaflet version 1.0 beta2 and issue is same.

IE is not setting dragging disabled until mouse press is released. 

Even if I add 'dragging.disable()' to move event: I get e.g. 50 'mousemove' events logged in console, but dragging is not disabled.

```
map.on('mousemove', function (e) {
            console.log('mousemove');
            map.dragging.disable();
            //some drawing
        });
```

**Comment by IvanSanchez** [comment] 2016-01-18 15:41
Duplicate of #3666.

**Closed by IvanSanchez** 2016-01-18 15:41 UTC
