### ISSUE TITLE
Outdated marker location for 46.80782,-92.06189

### ISSUE THREAD

**Issue by katieragusa** [Leaflet/Leaflet#7288] opened 2020-09-23 16:04 UTC
The credit union business referenced in the leaflet map is outdated and a new business has occupied the space.

Leaflet's outdated business name: https://drops.tribus.com/Kouwxrx8
For 46.80782,-92.06189

Here's how Google displays the building now: https://drops.tribus.com/NQu1Lg8k, which is correct (https://www.google.com/maps/place/2516+London+Rd,+Duluth,+MN+55812/@46.8077689,-92.0624793,19z/data=!4m13!1m7!3m6!1s0x52afaccca16f0271:0x6d742e0623d9371!2s2516+London+Rd,+Duluth,+MN+55812!3b1!8m2!3d46.8077689!4d-92.0619321!3m4!1s0x52afaccca16f0271:0x6d742e0623d9371!8m2!3d46.8077689!4d-92.0619321)

Google lists it as un-named, but the actual latest occupant is RE/MAX Results

**Comment by IvanSanchez** [comment] 2020-09-23 16:12
Duplicate of #3896 (and #7004, #6989, #6925, #4661, #4332, #4819, #5056, and #6284).

**Closed by IvanSanchez** 2020-09-23 16:12 UTC
