### ISSUE TITLE
Change icon on popup-close and drag causes unwanted behavior

### ISSUE THREAD

**Issue by HarelM** [Leaflet/Leaflet#6226] opened 2018-07-06 21:53 UTC
## How to reproduce

- Leaflet version I'm using: 1.3.0
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Windows
1. Create marker with popup
2. Bind close event to marker icon change
3. Click to open popup
4. Drag click while popup is open

## What behaviour I'm expecting and which behaviour I'm seeing
Expected: Popup should close, icon should change, mouse icon should be return to regular state when stop dragging.
Actual: Popup closes, Icon changes, marker does not get dragged and mouse icon stays as "close hand" when dragging is stopped.
## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

https://plnkr.co/edit/Sek0ISvwfDiST76h26Qy?p=preview

The idea behind this issue is the following:
Popup window allow the user to change the icon of the marker. when the user closes the popup the changes are applied to the marker and so the icon needs to be changed. this is a draggable marker and so the user should be able to drag is while the popup is open (doesn't mean the popup needs to stay open though).

**Comment by Falke-Design** [comment] 2022-04-08 04:37
Duplicate of #4484

**Closed by Falke-Design** 2022-04-08 04:37 UTC
