### ISSUE TITLE
Add entrypoint for ES modules to package

### ISSUE THREAD

**Issue by rjackson** [Leaflet/Leaflet#7055] opened 2020-03-28 18:55 UTC
Hi folks,

I've been digging around today trying to figure out why Webpack's tree shaking magic did not appear to be working on Leaflet's code. Digging back through the history here, I see the following historic PRs:

* February 2018: #6021 adds ES6 Module support, and unlocking all the goodies that come alongside
* March 2018: Leaflet/Leaflet.markercluster#874 is broken due to the lack of a global `L`
* July 2018: #6239 was a hotfix removing support for ES6 modules due to the above

In the removal hotfix, there was a comment that "people who want to take advantage of tree shaking can opt-in by adding custom rules resolving Leaflet to `dist/leaflet-src.esm.js`." I'll freely admit that I'm struggling to figure out how to do that (it may be pretty clear to be fair; I'm really not up to date with the modern Javascript ecosystem.)

Ever since that hotfix, [there's been a few PRs attempting to reintroduce module support](https://github.com/Leaflet/Leaflet/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aunmerged+esm+) but they've all been closed with a link back to the removal hotfix, and no further discussion.

The Leaflet/Leaflet.markercluster#874 issue remains open, with recent (January this year) comments floating the ideas of:

* A new major version release of Leaflet to enforce the removal of the `L` global variable
* Updating plugins to automatically resolve `L` to the `leaflet` module, rather than requiring Leaflet to expose `L` as a global variable.

Beyond this chatter on the Markercluster repo, I haven't seen any other discussion on how the Leaflet community is feeling about the lack of ES6 module support and the widespread (?) dependence on a global `L`. If I may, I'd like to be the one to bring these up for discussion.

Do we know what the remaining blockers are for:

* Removing the global `L`
* Bringing back ES6 module support?

And is there anything we can do make progress on these?

Thanks all,
Rob

**Comment by bennypowers** [comment] 2020-06-11 17:49
It would be great to just add the "module" field to package.json

**Comment by ogdenstudios** [comment] 2020-06-24 17:52
Hey everyone, I'm new to the project. Working with a team, considering migrating from Mapbox to Leaflet to save on performance. Would really really the ability to import at an ES6 module. Threw me for a loop this morning that I could not.

**Comment by bennypowers** [comment] 2020-09-06 15:55
You can import from `/dist/leaflet-src.esm.js`, but if your toolchain relies on the `module` field in package.json, as most tools do at the moment, you will be out of luck.

your options are to rewrite the imports at build/run time, or to patch the `package.json` under `node_modules/leaflet` to include the line

```json
"module": "dist/leaflet-src.esm.js"
``` 

Hopefully our good maintainers will merge my PR soon and we won't have to resort to `patch-package` shenanigans anymore

**Comment by bennypowers** [comment] 2020-09-06 16:01
In the mean time, put this in `scripts/fix-leaflet.mjs`

```js
// @ts-check
import pkgJson from '../node_modules/leaflet/package.json';

import { writeFileSync } from 'fs';

writeFileSync(
  './node_modules/leaflet/package.json',
  JSON.stringify({
    ...pkgJson,
    module: 'dist/leaflet-src.esm.js',
  }, null, 2));
```

then add this to your postinstall:
```json
"postinstall": "node --experimental-json-modules scripts/fix-leaflet.mjs"
```

**Comment by ebrensi** [comment] 2020-09-25 21:07
Parcel as of 2.0.0-beta.1 seems not to use the `module` field in `package.json` anyway, so I just go ahead and 
```
import { stuff } from "{mypath}/node_modules/leaflet/dist/leaflet-src.esm.js"
```
A bigger problem IMO is that if you use any plugins, which pretty much everyone does, most of them are expecting Leaflet's `L` namespace to extend.

I guess a clever patch for one of those plugins would be to replace every `L.obj` with `obj` and prepend 
`import { obj1, obj2, ... } from .../leaflet-src.esm.js`
in the plugin's code, and set `L` to a dummy-value.

**Comment by nwsw** [comment] 2020-10-18 10:22
I added a default `index.js` to the root of the Leaflet package. With this in place, I can just add the raw Leaflet repos to a project (where the `dist` folder contains only `css` files). Node automatically falls back to the main source, since the `main` entry point from `package.json` does not exist.

valdese-net/Leaflet@ade00ec59dbc494ea9f6b48cba403299d8415971

**Comment by ebrensi** [comment] 2020-11-13 22:24
For anyone who might come upon this from a web search, I have a setup that works pretty well using Parcel v2.  I suppose it would work for any bundler.

What I do is have my own module `myLeaflet.js` where I import only what is required by my own code and the plugins I use.

Example `myLeaflet.js`:
```javascript
import {
  Control,
  DomEvent,
  DomUtil,
  Evented,
  LatLng,
  LatLngBounds,
  Layer,
  Map
} from "../../node_modules/leaflet/dist/leaflet-src.esm.js"

export {
  Control,
  DomEvent,
  DomUtil,
  Evented,
  LatLng,
  LatLngBounds,
  Layer,
  Map
}

/*
 * The global namespace L is required by a few plugins.  We provide one,
 * with the bare minimum content that they require.
 */
window.L = {
  Control,
  DomEvent,
  DomUtil
}
```
In my own code I import what I need from `myLeaflet.js` rather than `leaflet`.  For the plugins that require the `L` namespace, a minimal one there for them.  Some leaflet plugins modify an existing Leaflet class and some create their own. As an example of two that have a `npm` repository I do
```javascript
import "thePlugin"
import "theOtherPlugin"

const thePlugin = window.L.thePlugin
const theOtherPlugin = new window.L.Control
```

So there is some pollution of the global namespace with `L` but not much, and full tree-shaking is enabled.

**Comment by ogdenstudios** [comment] 2020-11-14 18:56
I think @ebrensi has a really good approach. If Leaflet doesn't pursue ES6 module support in the future and someone finds this thread looking for a good solution, I just want to endorse that idea. Despite relying too much on the global `L`, it still does a great job of encapsulating the Leaflet code and managing it. This kind of interface between 3rd party libraries and your own code is a responsible way to do things (and ES6 modules kind of solve the problem for us, but without them, a custom solution like this is as good as anything).

**Comment by mathe42** [comment] 2021-02-01 13:21
Solution for rollup: https://www.npmjs.com/package/@ec-nordbund/rollup-plugin-leaflet

**Comment by keul** [comment] 2021-06-23 11:30
Another missing piece for a fully three-shakable use in webpack is the missing of `sideEffects` package.json entry.

**Comment by mathe42** [comment] 2021-06-23 12:06
You can try https://www.npmjs.com/package/@ec-nordbund/leaflet it is fully tree-shakeable and because of some little code I inject you can even require it in node (not use it but require it). This helps with some workarounds with serverSideRendering

**Comment by keul** [comment] 2021-06-23 13:29
@mathe42 I like the approach, but I have to inject some stuff in a global `L` because of outdated plugins.

**Comment by mathe42** [comment] 2021-06-23 13:42
You can just use like above:
```ts
/* myLeaflet.js */  
import {
  Control,
  DomEvent,
  DomUtil,
} from "@ec-nordbund/leaflet"

window.L = {
  Control,
  DomEvent,
  DomUtil
}
```

And add in your bundler a rewrite for `leaflet` to `@ec-nordbund/leaflet`. It is easy in rollup and webpack. other build tools should be simple too.

**Comment by keul** [comment] 2021-06-23 16:03
@mathe42 thanks for the idea, it worth a try.
I'm able to reach a 95% of my target.

- I'm also able to fake the `react-leaflet` import saving 10Kb of bundle just using the [webpack resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias).
- I'm able to import pretty everything, also problematic add-ons like proj4leaflet…

Still, the window.L (or just a `export default L`) is not working in the way some deprecated addons works.
It seems that the global `L` can't be accessed for writing, or at least stuff inserted there is lost.

The only plugin that is not working for me is [Leaflet.TimeDimension](https://github.com/socib/Leaflet.TimeDimension). I'm forced to rely on the global `L` there due to an [issue of exported stuff](https://github.com/socib/Leaflet.TimeDimension/issues/191).

**Comment by mathe42** [comment] 2021-06-23 16:39
Just a idea (with a quick look at Leaflet.TimeDimension):

1. Create a copy of it (fork it)
2. Rewrite all access of `L.[...]`
  1. Access from L rewrite to import
  2. New Properties as a export

Did this with a small Leaflet plugin. I think there are many plugins that have this problem so I will have a look to write some build script that does those transforms automaticly... Thinking about a esbuild plugin wanted to try to write one. 

I will work on this in the same repro as for the leaflet builder: https://github.com/EC-Nordbund/leaflet-builder

**Comment by backspaces** [comment] 2021-06-25 22:52
My team has an extension/plugin to ImageOverlay which allows any DOM element to be overlayed on a map.
In addition, all our code is es6 modules.

Importing L works fine:
```
import * as L from 'https://unpkg.com/leaflet/dist/leaflet-src.esm.js'
```
But as we're discussing here, any plugin fails due to assignments to L:
```
import * as L from 'https://unpkg.com/leaflet/dist/leaflet-src.esm.js'
L.ElementOverlay = L.ImageOverlay.extend({...})   <==  fails
```

The simplest solution for our own module is to simply export the extension:
```
const ElementOverlay = L.ImageOverlay.extend({})
export default ElementOverlay
```
The user of the plugin has to use:
```
const layer = new ElementOverlay(...).addTo(map)
```
I believe this will work in general, but no longer having the plugin nicely added to L, making it difficult for those used to the nice plugin style.

The hybrid solution, scripts and modules, is to use:
```
        <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
        <script src="path/to/elementOverlay.js"></script>
        ...
        <script type="module">
           use L.elementOverlay(...) as usual
        </script>
```
..where elementOverlay.js now retains the older style:
```
L.ElementOverlay = L.ImageOverlay.extend({})
L.elementOverlay = function (...) {
    return new L.ElementOverlay(...)
}
```
Unfortunately, I can see no other simple solution yet, but I suspect using rollup just might work.

Is that the consensus of the rest of us?

Three.js had to deal with similar issues with their extensions/examples and ended up having two branches within the Three repo, one with examples using modules, the other not.

**Comment by backspaces** [comment] 2021-06-26 18:12
There is a solution for storing new methods etc in Leaflet.
Modules cannot be assigned to directly. BUT if you simply have an object defined in L:
```
export const plugins = {}
```
..then the plugins can easily be added. Instead of:
```
L.MyPlugin = ...
```
... you use:
```
L.Plugins.MyPlugin = ...
```

This simply shows how to add new things to a module. We may prefer a slightly different approach, more "Leaflet-y". But, yes, there is absolutely no problem "adding" to a module, but indirectly to an object.

**Comment by backspaces** [comment] 2021-07-05 19:40
So I'm curious about strategy.

Three.js had huge issues with their examples, converting them to imports. But they eventually solved the problem, and naturally Three itself has an esm version as well.

The strategy issue is how to go about converting the plugins. I think Three's experience may be that we need a separate subtree of all the plugins which are converted to the examples above.

Also see #7055 as well. TypeScript & esm. Strange bedfellows, but if we do esm first, the TS issues can be solved outside of the Leaflet repo. Apparently we can easily solve the types file problem with jsDocs?

**Comment by backspaces** [comment] 2021-07-12 18:13
Update: we've converted from using an import of leaflet within the ElementOverlay plugin to "dependency injection", i.e. handing L to the ElementOverlay. This insures we do not import different versions of Leaflet, one in the HTML "app", and a different one in the plugin.

It looks like this:
```
export default function (L) {
    const ElementOverlay = L.ImageOverlay.extend({
    ...
    })
    return ElementOverlay
}
```

And is used like this:
```
import * as L from 'https://unpkg.com/leaflet/dist/leaflet-src.esm.js'
import elementOverlay from 'https://unpkg.com/@redfish/leafletelementoverlay?module'
const ElementOverlay = elementOverlay(L)
...
const layer = new ElementOverlay(canvas, bounds).addTo(map)
```
If we standardize on converting plugins to esm, I'd recommend the dependency injection approach. It is more like the usual use of L in window and avoids one of the major problems with esm .. i.e. import maps

**Comment by mathe42** [comment] 2021-07-12 20:02
I don't like this approach as it doesn't support treeshaking.  This is one of the important things I want to fix with #7615 / #7614

**Comment by backspaces** [comment] 2021-07-12 22:29
@mathe42: I hear you! But the main issue we face is simply so few of us appear to care! 

And we need to state our goals really well. Is it modules primarily? Or also TypeScript? Running in node or deno? Treeshaking implies awkward workflow, which I Will Not Use for example, all my work is Write and Run with no compiles etc. But making it possible is fine .. if you like workflow.

If we could work out the architectural details of what needs to be done, we'd be in better shape. 

I've mentioned several alternatives that fit in nicely with Leaflet. Dependency injection matches well with L usage. We're NOT going to get Leaflet itself to change much. And Leaflet is already esm, whew! Nicely done.

And honestly, I think a lot of esm issue arise from how badly they were thought out and cursed us with horrible workflow trying to babelize static module paths away. Import maps might work but then the entire esm community would have to change to use them! 

And then there is TypeScript! JavaScript has become so weird an ecology that I am really sympathetic with those unwilling to deal with it all.

**Comment by mathe42** [comment] 2021-07-13 05:48
Just reading your comment again and now understanding your problem .

Solution: 
1. Use a build tool or
2. Use `import {} from 'leflet'` in Plugins and the cdn unpkg. unpkg auto rewrite the imports. See for example https://unpkg.com/vue@3.1.4/dist/vue.runtime.esm-bundler.js?module

Other CDN are not so nice...

But I think if you are in the situation that you have 2 versions of leaflet in your code - just use a build tool (maybe even not for all of your code but only for the libarys)

**Comment by joelhickok** [comment] 2021-07-13 23:39
The primary reason I have been struggling with Leaflet in the last year is the treeshaking, and the fact that Leaflet is imported as over *400 KB* when using many bundlers.  This is all because of the import problem.  Don't get me wrong, I still love Leaflet as I did 10 years ago, but even with the latest heavyweight releases from the likes of ArcGIS JS API, you can import the exact module.

```js 
{Map} from 'leaflet'
 
// versus

{Map} from 'leaflet/src/map/'
```

It's totally absured to make claims that Leaflet is still 'lightweight' when it could be so much more lightweight on page loads if you could just use what you need for the project, for example, GeoJSON, Map, and BasemapLayer.  When your bundler is importing the whole Leaflet package, it's obvious to me that the codebase could definitely benefit from some restructuring.

**Comment by mathe42** [comment] 2021-07-14 06:17
> It's totally absured to make claims that Leaflet is still 'lightweight' when it could be so much more lightweight on page loads if you could just use what you need for the project, for example, GeoJSON, Map, and BasemapLayer. When your bundler is importing the whole Leaflet package, it's obvious to me that the codebase could definitely benefit from some restructuring.

To extend this - I think the Problem is with the structure of Leaflet in a few Places:

1. `Map.mergeOptions`
2. `Map.addInitHook`
3. `Map.include`

(Near) all Websites that use Leaflet use the Map. Now the Zoom control has some code:
```ts
Map.addInitHook(function () {
	if (this.options.zoomControl) {
		// @section Controls
		// @property zoomControl: Control.Zoom
		// The default zoom control (only available if the
		// [`zoomControl` option](#map-zoomcontrol) was `true` when creating the map).
		this.zoomControl = new Zoom();
		this.addControl(this.zoomControl);
	}
});
```

So Map has a direct refrence to the Zoom class. This means, that there is no way to treeshake this class away - In this case this might be good as the Zoom Control is used by most maps but if we change this code to.

```ts
export function useZoomControl() {
    Map.addInitHook(function () {
	if (this.options.zoomControl) {
		// @section Controls
		// @property zoomControl: Control.Zoom
		// The default zoom control (only available if the
		// [`zoomControl` option](#map-zoomcontrol) was `true` when creating the map).
		this.zoomControl = new Zoom();
		this.addControl(this.zoomControl);
	}
    });
}
```
This gets treeshakeable!
 
Same with the other functions above.

And here we see that the main problem is the non standard class syntax.

And if we look for example at vue3 (they had 0 treeshake support in vue2) we now have a 113.76KB Bundle with a minimal example treeshaking down to 43.09kb and that is a full framework! - There is a reason why I don't test my webpage with lighthouse CI on pages with maps...

**Comment by joelhickok** [comment] 2021-07-14 11:47
Thanks @mathe42 for pointing these specific concerns out.  I agree!  I look forward to the day that Leaflet codebase can be revised with some more forethought in place.  It has been wonderful over the years, but in 2021, it is unacceptable to ignore this, although I recognize that it may take some time.

**Comment by joelhickok** [comment] 2021-07-14 11:53
@backspaces, a well-written codespace can be used cleanly and efficiently using ES6 imports and treeshaking, AND by importing the entire library, or your "Write and Run" approach.  Just look at something like Lodash.

**Comment by mathe42** [comment] 2021-07-19 06:35
I had a look at the last Problem and I created a new entryfile without the problem https://github.com/leaftypes/Leaflet/blob/feat/better_exports/src/Leaflet.js This has breaking changes but the "nice" type as you can search and replace most of it:


For example `Control.Zoom` -> `Zoom` or `Control_Zoom`.

I think know it is a lot more treeshakeable as before. (Will try it out.)

**Comment by jonkoops** [comment] 2022-06-22 08:31
I am not against introducing this in the v2 milestone, it's a good moment to introduce changes that might be breaking (see #6239 why this is a breaking change).

@mourner How would you feel about including this one? I think it makes sense to batch some of these breaking changes together.

**Comment by septatrix** [comment] 2022-06-22 09:51
> Perhaps we can provide a separate entry-point to expose the globals of Leaflet in ESM mode? Something like:
> 
> ```js
> import 'leaflet/globals';
> import 'some-legacy-plugin';
> ```

I like this approach. `leaflet/globals` or (legacy, or compat, or whatever name) could probably be as simple as:

```js
// import all the things
import foo from 'leaflet/foo';
import bar from 'leaflet/bar';
...
globalThis.L = { foo, bar, ... };
```

This should still be backwards compatible.

**Comment by joelhickok** [comment] 2022-06-22 14:38
> 

I am not a contributor on this project, so I know I may not hold weight here.  You have to remove the global L at some point to move forward.  Whatever the solution is, I'm sure the talented people here can figure something out.  I realize the plugin issue, but in my own dev world, Leaflet is one of the few libraries out there keeping my development and build pipelines 10 years behind.  

And, actually, MANY of the Leaflet plugins I use these days (or the build tools) allow one to import the core objects/classes directly.

**Comment by jonkoops** [comment] 2022-06-27 14:33
I have a some work in progress on the [`export-esm`](https://github.com/Leaflet/Leaflet/compare/export-esm) branch. It adds the proper entry-points to the package and exposes the globals without any breaking changes.

However, strangely enough it looks like I managed to actually break Rollup with this one as all of the outputs end up in a single file instead of separated files.

Perhaps I can get a second pair of eyes on this to confirm that this might be a Rollup issue and not a silly mistake on my side.

**Comment by septatrix** [comment] 2022-07-06 11:12
It definitely would be nice if this could be implemented in a backwards compatible manner. Nevertheless I think that for v2 the global `L` should be considered for removal as this encourages plugins to be more modular and not modify global stuff.

**Comment by jonkoops** [comment] 2022-07-06 15:11
I think we want to drop UMD builds and the global at some point (whether that's 2.0 or some other future version). To maintain backwards compatibility we can provide a dedicated `leaflet/globals` import to restore the behavior.

Personally I'd like to work Leaflet towards an 'ESM first' library so that it can simply be imported directly from a web browser. New standards such as [Import Maps](https://github.com/WICG/import-maps) will make this even easier.

**Closed** 2022-07-20 20:18 UTC
Labels: compatibility, breaking, needs decision
