### ISSUE TITLE
Uncaught TypeError when using the downloaded version of Leaflet

### ISSUE THREAD

**Issue by kwankong** [Leaflet/Leaflet#8983] opened 2023-06-08 22:07 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

I am not sure who I turn to about this error that appeared only when I used the downloaded version of Leaflet (both v1.9.4 and v1.8.0) from https://leafletjs.com/download.html
<link rel="stylesheet" href="/path/to/leaflet.css" />
<script src="/path/to/leaflet.js"></script>

Uncaught TypeError: Cannot use 'in' operator to search for '_leaflet_id' in undefined

When I switched back to the hosted version as indicated on https://leafletjs.com/download.html, the error went away.
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin="">
</script>

The reason I wanted to use the download Leaflet version rather than the hosted version was that I needed to specify the tile coordinates {z}{y}{x} with padded 0s rather than regular numbers (i.e. 001 vs 1).  I thought I would need to modify TileLayer.js to accomplish that.

Any idea on what went wrong?  Thanks!

### Expected behavior

(No errors)

### Current behavior

![Radar WMS archive Leaflet version - Google Chrome 6_8_2023 5_49_57 PM](https://github.com/Leaflet/Leaflet/assets/20267052/e2cb26ce-870f-42c5-8627-2d6c7d29716e)

### Environment

- Leaflet version:  v1.9.4
- Browser (with version): Chrome Version 114.0.5735.110
- OS/Platform (with version): Windows 10

**Comment by IvanSanchez** [comment] 2023-06-09 08:26
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by kwankong** [comment] 2023-06-09 15:31
Hmm...I could not reproduce this error using the Leaflet quick-start example (https://leafletjs.com/examples/quick-start/example.html).

**Comment by Falke-Design** [comment] 2023-06-10 11:00
I compared the source code of unpkg and the downloaded version of `leaflet.js` and they are exactly the same.
I will close this until a reproduceable example will be shared.

**Closed by Falke-Design** 2023-06-10 11:00 UTC
Labels: bug, needs more info

**Comment by nielsbom** [comment] 2025-01-16 17:13
I have a strong suspicion this is related: https://github.com/vue-leaflet/vue-leaflet/issues/399

**Comment by nielsbom** [comment] 2025-01-28 11:51
I debugged [my problem](https://github.com/vue-leaflet/vue-leaflet/issues/399) some more and came to the conclusion that, in my case, the error was caused because I was asking Leaflet to add and remove a couple hundreds of layers in quick succession.
