### ISSUE TITLE
Closing Leaflet pop-up in map in a page whose html head contains <base target="_blank"/> opens new map page

### ISSUE THREAD

**Issue by eggertj** [Leaflet/Leaflet#8209] opened 2022-05-02 18:58 UTC
- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Make an html page with this in the <head> element:
      <base target="_blank"/>
- Embed a Leaflet-based map with marker popups in that page
- Open the page in a browser
- Open a popup (if not already open)
- Close the popup using the x in the popup

**Expected behavior**

I expect the popup to close and nothing else to happen.

**Current behavior**

The popup closes, but a new page also opens with the same URL but with the suffix #close.

**Environment**
- Leaflet version: 1.8.0
- Browser (with version): Safari 15.4 (17613.1.17.1.13)
- User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
- OS/Platform (with version): macOS Monterey 12.3.1 (21E258)

Also tested on same platform with
- Browser: Firefox 99.0.1 (64-bit)

**Additional context**

This didn't happen with LeafletJS 1.7.1.

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code
See
https://www.aegilops.com/pedigreemv5b.html

Compare with same page with Leaflet 1.7.1:
https://www.aegilops.com/pedigreem.html

**Comment by IvanSanchez** [comment] 2022-05-02 19:09
Duplicate of https://github.com/Leaflet/Leaflet/issues/8159

**Closed by IvanSanchez** 2022-05-02 19:09 UTC
