### ISSUE TITLE
Spacing between tiles when printing

### ISSUE THREAD

**Issue by boris-arkenaar** [Leaflet/Leaflet#5551] opened 2017-06-07 09:08 UTC
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Firefox 53.0.3 (64-bit) and Chromium 58.0.3029.110
- OS/Platform (with version) I'm using: Ubuntu 17.04 (64-bit)
- step 1: Go to http://leafletjs.com/examples/quick-start/example.html
- step 2: Print the page to a PDF file
- step 3: Open the PDF file and zoom in very far (383,71%)

## What behaviour I'm expecting and which behaviour I'm seeing

I see small white lines between the tiles of the map which i don't expect. Since you need to zoom in very far it doesn't seem like a problem. However, when printing to paper you see the lines unfortunately.

**Comment by IvanSanchez** [comment] 2017-06-07 09:10
Duplicate of #3575

**Closed by IvanSanchez** 2017-06-07 09:10 UTC

**Comment by boris-arkenaar** [comment] 2017-06-07 09:21
@IvanSanchez Ah yes. This is only visible when printing though, not on screen in the browser.

**Comment by IvanSanchez** [comment] 2017-06-07 09:23
It's the same thing, tho. Fixing this involves the same fix as #3575: join tiles together in a `<canvas>` with https://github.com/Leaflet/Leaflet.TileLayer.NoGap

**Comment by boris-arkenaar** [comment] 2017-06-07 09:28
I see. Thanks!
