### ISSUE TITLE
Map Loads Unexpectedly Into 0x0 Container

### ISSUE THREAD

**Issue by miqrogroove** [Leaflet/Leaflet#7153] opened 2020-05-20 15:35 UTC
I've got a thread going over at https://github.com/fisharebest/webtrees/issues/3255

Apparently something is happening with the tabbed layout of a page where switching in-page tabs breaks the map feature on some connection types but not others.

With just my amateur look in DevTools, I've determined that the expected tile requests are not even showing up when connected to my home network, unless I refresh the page, and then it works fine.  Either way, I'm seeing no errors.

Any better way to troubleshoot this?

**Comment by miqrogroove** [comment] 2020-05-23 23:37
It's starting to look like the problem is here:

https://github.com/Leaflet/Leaflet/blob/0d06c4256f4312a7122c23626c8bd36e14269d01/src/map/Map.js#L907

Maybe that script needs to throw a helpful error if the container is not dimensioned.  Otherwise, it ends up displaying an unexpected tile and not much else.

**Comment by Malvoz** [comment] 2022-02-21 14:37
Related / potentially duplicate of https://github.com/Leaflet/Leaflet/issues/4200.

**Comment by Malvoz** [comment] 2022-06-19 13:52
> I've got a thread going over at https://github.com/fisharebest/webtrees/issues/3255

@miqrogroove Looks like it was a timing issue, closing in favor of #4200.

**Closed by Malvoz** 2022-06-19 13:52 UTC
