### ISSUE TITLE
Browser.touch is true on desktop IE (Internet Explorer)

### ISSUE THREAD

**Issue by ilyapro** [Leaflet/Leaflet#4325] opened 2016-03-17 08:31 UTC
L.Browser.touch property returns true on desktop IE browsers.
This causes some IE bugs in my application.
(src/core/Browser.js)

**Comment by IvanSanchez** [comment] 2016-03-17 08:33
Duplicate of #3944

**Closed by IvanSanchez** 2016-03-17 08:33 UTC
