### ISSUE TITLE
a mouse wheel problem when zooming

### ISSUE THREAD

**Issue by zjlhope** [Leaflet/Leaflet#5973] opened 2017-12-19 03:23 UTC
**I have a problem when use leaflet1.2.**
I zoom the map by mouse wheel,if slowly,It has no problem,but if quickly,the zoom of the map is wrong.
sometime it skep from 11 to 13,sometime skep from 4 to 6 etc, Thus results in a white area and no smooth feeling,like jumping!
but It has no problem in leaflet 0.7-*

**Comment by ghybs** [comment] 2017-12-19 19:37
Sounds like a duplicate of https://github.com/Leaflet/Leaflet/issues/5622.

If that is not your case, please provide steps to reproduce and a live example so that we can investigate, as specified in the issue template.

**Closed by ghybs** 2017-12-19 19:37 UTC

**Comment by zjlhope** [comment] 2017-12-20 04:09
no complex step,just create a small project.
var  map=L.map({}).
var tileLayer=L.tileLayer('url',{}).addTo(map).

then run it and zoom the map by mouse wheel slowly and quickly,you can find it.
