### ISSUE TITLE
Zooming occasionally causes layer to temporarily slip off the map

### ISSUE THREAD

**Issue by brienna** [Leaflet/Leaflet#7680] opened 2021-09-25 20:02 UTC
I've built a map with a GeoJSON layer that shows some countries of the world as filled-in polygons. 

[![enter image description here][1]][1]

Everything is working fine, except that when you zoom into the map, the layer sometimes moves separately from the map. The problem is more pronounced on mobile, and my gifs below are from mobile. 

[![enter image description here][2]][2]

Related questions I've looked at but don't quite apply to this case: 
- https://stackoverflow.com/questions/64890232/leaflet-shapes-move-when-zooming
- https://stackoverflow.com/questions/17875438/leafletjs-markers-move-on-zoom

There are also related issues in the Leaflet GitHub ([Map content moves when zooming](https://github.com/Leaflet/Leaflet/issues/4053) and [Strange zooming behaviour with vector (extended L.geoJson) layers on 1.0.0](https://github.com/Leaflet/Leaflet/issues/4247)), but the solution to that problem was to update the CSS file so that its version was in sync with the JS file. I'm using [react-leaflet][3] with the CSS from [leaflet](https://www.npmjs.com/package/leaflet) which are in sync to the best of my knowledge.

I also see this problem happening on [the GeoJSON example](https://leafletjs.com/examples/geojson) on the Leaflet website:

[![enter image description here][4]][4]

Reproducible code is at https://leafletjs.com/examples/geojson/. The more things there are on the layer, the greater this slippage. Sometimes when zooming I accidentally grab onto the layer with one finger and it stays underneath that finger as the map gets panned. It is not limited to GeoJSON - it occurs with CircleMarkers as well ([example site I found online where it occurs](https://cymraeg.ling.cam.ac.uk/?map=6)). 

Is there a way to prevent this slipping effect and make the features more "anchored" like on Google Maps? 

  [1]: https://i.stack.imgur.com/Y3YvA.png
  [2]: https://i.stack.imgur.com/lVBme.gif
  [3]: https://www.npmjs.com/package/react-leaflet
  [4]: https://i.stack.imgur.com/pqi8d.gif

**Comment by ghybs** [comment] 2021-09-26 02:33
Originally posted on StackOverflow: https://stackoverflow.com/questions/69329278/leaflet-layer-moves-separately-from-map-when-zooming

- Strangely visible only the 1st time in Leaflet version 1.6.0: https://plnkr.co/edit/bHjrrQxycoaJOyBw
- Same since version 1.0.0-beta.1: https://plnkr.co/edit/nwj6IIknhAlfTyPk
- Symptom slightly different on version 0.7.7 https://plnkr.co/edit/W9TWjIcQQUJXZBRM (slip during zoom only)

**Comment by ghybs** [comment] 2021-09-26 03:00
Duplicate of https://github.com/Leaflet/Leaflet/issues/6395

**Closed by ghybs** 2021-09-26 03:00 UTC
