### ISSUE TITLE
Unexpected behavior of panInside

### ISSUE THREAD

**Issue by user073** [Leaflet/Leaflet#7445] opened 2021-02-01 03:25 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**

Please see the unexpected behavior of [panInside](https://leafletjs.com/reference-1.7.1.html#map-paninside) the CodeSandbox below. The bottom padding passed to panInside in map2 is only 1px greater than the bottom padding passed to panInside in map1 but map2 pans the marker all the way to the top while map1 does not pan at all.

**Expected behavior**

map2 should only pan up one pixel, as this is the minimum amount to make marker2 visible within the padding.

**Current behavior**

map2 pans so that marker2 is at the top of the map.

**Environment**
- Leaflet version: ^1.7.1
- Browser (with version): Chrome 88.0.4324.96 
- OS/Platform (with version): macOS High Sierra 10.13.6

**Additional context**

**Minimal example reproducing the issue**

[![Edit quirky-frost-946z7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-frost-946z7?fontsize=14&hidenavigation=1&theme=dark)

Please see this screen recording: 

https://user-images.githubusercontent.com/63527968/106411334-e8e10680-63f9-11eb-8671-7a7ddd3fb899.mov

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by user073** [comment] 2021-02-08 06:15
@daverayment Is this a bug?

**Comment by daverayment** [comment] 2021-02-09 11:50
@user073 Thanks for reporting this and for the clear example. This is definitely not intended behaviour. The map should pan the smallest amount so the marker is within the padded bounds.

I have a lot on at the moment, but I'll try to track down the root cause soon.

**Comment by daverayment** [comment] 2021-02-09 21:59
The calculations currently depend on the padding taking up less than half the bounds, otherwise the movement offset created is reversed, i.e. a Y scroll of 1 pixel down from the top of the bounds instead of 1 pixel up from the bottom. I'll attempt to correct this soon.

**Comment by user073** [comment] 2021-02-10 07:41
@daverayment You’re welcome. OK. Please consider converting [paddedBounds](https://github.com/Leaflet/Leaflet/blob/620bc3e9c5d282090f429ac21d28d00fbffdb3db/src/map/Map.js#L530) to a [LatLngBounds](https://leafletjs.com/reference-1.7.1.html#latlngbounds) object and passing the LatLngBounds object to [panInsideBounds](https://leafletjs.com/reference-1.7.1.html#map-paninsidebounds). The Point objects in `paddedBounds` may be able to be converted to LatLng objects with [layerPointToLatLng](https://leafletjs.com/reference-1.7.1.html#map-layerpointtolatlng).

**Comment by daverayment** [comment] 2021-02-18 14:16
@user073 This should be fixed in a future release by PR #7469. Thanks again for the report.

**Comment by user073** [comment] 2021-02-21 08:27
@daverayment OK. You're welcome.

**Comment by Malvoz** [comment] 2022-04-19 10:28
Looks like this was fixed in https://github.com/Leaflet/Leaflet/pull/7469.

**Closed by Malvoz** 2022-04-19 10:28 UTC
Labels: bug
