### ISSUE TITLE
data-urls in L.Icon.Default

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#6496] opened 2019-01-29 13:04 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**

```
  var myIcon = L.Icon.Default.extend({options: {
    iconUrl: 'data:image/png;base64,iVBORw...'
  }});
```
**Expected behavior**
There is nothing special in [data url](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), so I expect this code to work flawlessly.

**Current behavior**
Unfortunately there is path-guessing magic in code (#4605) which fails to deal with data-url.

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): Google Chrome Version 71.0.3578.98 (Official Build) (32-bit)
- OS/Platform (with version): Windows 8.1 (32-bit)

**Additional context**
Current workaround:
```
  L.Icon.Default.imagePath = ' ';
```
But better to improve magic to take into account data-urls here:
https://github.com/Leaflet/Leaflet/blob/61ef1776ac3c7afc5dec5ce4dfab8986ff9f5376/src/layer/marker/Icon.Default.js#L45-L59

Or here:
https://github.com/Leaflet/Leaflet/blob/61ef1776ac3c7afc5dec5ce4dfab8986ff9f5376/src/layer/marker/Icon.Default.js#L33-L43

**Minimal example reproducing the issue**

I haven't got simple example, but will make if it will be necessary.

**Comment by cherniavskii** [comment] 2019-01-29 13:10
> L.Icon.Default extends L.Icon and is the blue icon Leaflet uses for markers by default.

Did you try [`L.Icon`](https://leafletjs.com/reference-1.4.0.html#icon) instead of `L.Icon.Default`?

**Comment by johnd0e** [comment] 2019-01-29 13:18
> Did you try `L.Icon` instead of `L.Icon.Default`?

Well, it's obvious that `L.Icon` does not suffer from such issue.
But just I use `L.Icon.Default` because of it's default options.

May be I am wrong in understanding of real purpose of `L.Icon.Default`?

**Comment by cherniavskii** [comment] 2019-01-29 13:32
`L.Icon.Default` detects icon's path, which is not needed when using data-urls.
If you want to reuse default icon options - you can always extract them from `L.Icon.Default.prototype.options` and pass to your custom icon

**Comment by johnd0e** [comment] 2019-01-29 14:37
Sure, this is also working.

But see, there is also `L.Marker` dependent from `L.Icon.Default`.
So in fact we have two option.
* Let things as they is, but make addition into docs.
I suppose there should be explicit warning saying that `L.Icon.Default` doesn't work with data-urls, as long as some recommendation for this case (extend `L.Icon` **and** also override the `L.Marker.prototype.options.icon` with it).
* Or we just make small corrections in `IconDefault` private methods, and all works out of-the-box.

**Comment by jaythomas** [comment] 2019-08-26 06:37
Using webpack's file-loader (as the convention with Vue and React) the url's in the css are replaced with inline data URL's, however the library is appending `")marker-icon-2x.png` to the data url as seen in the inspector:

![Screenshot from 2019-08-26 02-21-59](https://user-images.githubusercontent.com/2344456/63669772-eb711280-c7a8-11e9-82c5-89055c3bd1f2.png)

I am not overriding default markers or anything, just trying to set up a very basic and vanilla map.

**Comment by ghybs** [comment] 2019-10-02 18:02
Hi @jaythomas,

The situation you describe is  duplicate of #4968.

**Comment by jaythomas** [comment] 2019-10-09 02:12
@ghybs I originally tried all the suggestions on that thread but couldn't comment because the thread was locked. With my code verbatim to the code snippet suggested:

```js
import L from 'leaflet';
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png'),
});
```

The icon url strings are being mutated after being passed to the options objects. The only solution I didn't try was the leaflet-defaulticon-compatibility third-party library and was exploring other possible solutions first.

Thanks.

**Closed** 2021-12-05 10:32 UTC
