### ISSUE TITLE
Internet explorer scroll jump on map click

### ISSUE THREAD

**Issue by McGern** [Leaflet/Leaflet#2463] opened 2014-02-14 11:58 UTC
Hi,

This is similar (sorry if it is the same) to issue 1228, but am seeing similar behaviour in IE8 through 10 (not tested on IE11) on windows 7.

It seems that if a portion of the map is outside the window viewport (i.e. above or below the viewable area) random clicks on the map will cause the page to "jump" very quickly to an undetermined point on the page (perhaps the top or bottom of the map?) and back to the original position.

Not sure if this is an IE only issue or if other browsers are faster at rendering, but have only noticed in IE.

To replicate:
- using IE10, 9 or 8 go to http://leafletjs.com/ (assume latest version?)
- scroll the page so a portion of the first demo map is offscreen
- Continually click on the map to cause the flicker. Doesn't matter if it is fast, slow, doubleclick, same spot or different spots, it will usually happen between 5 and 10 clicks.
- the issue is happening on mousedown.

Temp hack:
This code snippet from issue 1228 fixed it for me (which I assumes blocks/removes a mousedown event attached to a keyboard event?) but am not sure of the adverse effects.

```
L.Map.addInitHook(function () {
        return L.DomEvent.off(this._container, "mousedown", this.keyboard._onMouseDown);
    });
```

Thanks,
Jarrod

**Comment by IvanSanchez** [comment] 2020-02-15 23:49
Duplicate of #6229

**Closed by IvanSanchez** 2020-02-15 23:49 UTC
Labels: bug
