### ISSUE TITLE
Documentation request: How to add featureGroups to custom panes

### ISSUE THREAD

**Issue by livemixlove** [Leaflet/Leaflet#3705] opened 2015-08-03 18:54 UTC
Hi There,
I couldn't find documentation for this anywhere.  I want to do something like the following:

var highlightPane = map.createPane('highlight');
var highlightLayerGroup = L.featureGroup({pane:highlightPane});
var geojsonLayer = L.geoJson(geojson, {pane:highlightPane});
highlightLayerGroup.addTo(map);

This doesn't work.  Is there a way to do this?

Thanks!

**Comment by yohanboniface** [comment] 2015-09-28 12:19
Discussions and example on #1742 may help.

cc @Jakobud so we need more documentation on new pane management?

**Comment by Jakobud** [comment] 2015-09-28 21:18
Okay I'll put together something soon.

**Comment by IvanSanchez** [comment] 2016-04-02 19:28
Is this not covered in the panes tutorial? Maybe a section on how to create renderers with panes is needed.

**Comment by IvanSanchez** [comment] 2016-04-19 10:55
Closing as a duplicate of #4277

**Closed by IvanSanchez** 2016-04-19 10:55 UTC
Labels: docs
