### ISSUE TITLE
Absolute URLs to marker icons not working?

### ISSUE THREAD

**Issue by gerdint** [Leaflet/Leaflet#9216] opened 2024-01-15 09:13 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Create marker with custom icon(s) option
2. Add marker to map

### Expected behavior

The marker's icons should show up

### Current behavior

The absolute URL:s to marker icons are relative to the CDN CSS file path and are thus not found, i.e: 

`https://unpkg.com/leaflet@1.9.4/dist/images/https://pushpal.mindheartconsulting.se/css/images/red-marker-icon-2x.png`

### Minimal example reproducing the issue

https://plnkr.co/edit/9JzO0qBE9HF21kXu

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Firefox 121 (also tried Safari and Chrome with same result)
- OS/Platform (with version): macOS BIg Sur

**Comment by IvanSanchez** [comment] 2024-01-15 12:25
So you're doing `class UserMarkerIcon extends L.Icon.Default {`. If I replace that class with the standard `L.Icon`, eerything works as expected.

Leaflet classes were made waaaaaaaay before the ES `class` keyword and therefore have quite a lot of legacy and should be fixed. In fact, this bug report is technically a duplicate of https://github.com/Leaflet/Leaflet/issues/9066 .

You'll have to resort to "the Leaflet way" of class inheritance. Do read https://leafletjs.com/examples/extending/extending-1-classes.html .

**Closed by IvanSanchez** 2024-01-15 12:25 UTC
Labels: bug, needs triage

**Comment by gerdint** [comment] 2024-01-15 13:29
@IvanSanchez Thanks for looking into this. I wanted to inherit L.Icon.Default in order to get the shadow* properties for free. It indeed seems to work when extending L.Icon, but then there is no shadow.
Not related to this issue, but do you have any pointers on how to extend L.Icon.Default?

**Comment by IvanSanchez** [comment] 2024-01-15 14:15
> Not related to this issue, but do you have any pointers on how to extend L.Icon.Default?

Inherit from `L.Icon` instead, providing your own URL (and size, and anchor) for the shadow. Read https://leafletjs.com/reference.html#icon-option and https://github.com/Leaflet/Leaflet/blob/main/src/layer/marker/Icon.Default.js .

**Comment by gerdint** [comment] 2024-01-15 15:24
@IvanSanchez Yeah, that works. Thanks for a super-nice library!
