### ISSUE TITLE
[Leaflet] Update marker's popUp content without rewriting all HTML

### ISSUE THREAD

**Issue by DanielShinken** [Leaflet/Leaflet#3988] opened 2015-11-06 18:59 UTC
Hi, I would like to know if there's a way to change the content of a marker's popUp without having to rewrite all the html that is already there, I mean, I would like to toggle a class of one of the element inside of the popUp, it appears that the class exist in the DOM, and it toggles right, but after I close the popUp of the markers, returns to it's previous state, as If toggle hasn't applied, I believe is because I need to change the initial HTML of the popUp, I would like to do this without having to rewrite all the html I already built, and since is a pretty heavy html, is complicated to rewrite everything, I tried using update() method, but is not working, hope somebody can help me,

```js
 var objeto = Layerpints._layers;
      for(r in objeto){
        var html = Layerpints._layers[r]._popup._content;
        var html_parse = $.parseHTML(html);
        var up_tick    = $(html_parse).find('.up_tick');
      }
      $(up_tick).each(function(e){
          var id_pint_name = $(this).attr('name');
          if(id == id_pint_name){
            if($(this).hasClass('text-info')){
              console.log("remove class");
              $(this).removeClass('text-info');
              //Layerpints._layers[r]._popup.update();
            }else{
              console.log("add Class");
              $(this).addClass('text-info');
              //Layerpints._layers[r]._popup.update();
            }
          }else{
            console.log("do nothing");
          }
      });
```

this is the code I'm trying to use hope someone could help, thanks and greetings!

**Comment by DanielShinken** [comment] 2015-11-06 20:08
Somehow I managed to fixed it by changing the update() method to setContent() method like this

var objeto = Layerpints._layers;
  for(r in objeto){
    var html = Layerpints._layers[r]._popup._content;
    var html_parse = $.parseHTML(html);
    var up_tick    = $(html_parse).find('.up_tick');
  }
  $(up_tick).each(function(e){
    var id_pint_name = $(this).attr('name');
      if(id == id_pint_name){
        if($(this).hasClass('text-info')){
          $(this).removeClass('text-info');
          Layerpints._layers[r]._popup.setContent();
        }else{
          $(this).addClass('text-info');
          Layerpints._layers[r]._popup.setContent();
        }
      }else{
        console.log("do nothing");
      }
  });
the truth is I don't know why this is working since I believed setContent() will empty my popUp but it didn't, perhaps someone could explain further, thanks

**Comment by IvanSanchez** [comment] 2015-11-16 15:41
> Somehow I managed to fixed it

Seems like the problem is gone, so closing this.

> I believed setContent() will empty my popUp but it didn't

And it doesn't when there was no content passed, check the [source code](https://github.com/Leaflet/Leaflet/blob/master/src/layer/Popup.js#L195).

Otherwise, remember that you can use instances of HTMLElement instead of strings containing HTML for the popup contents - using those will allow you to keep their state around.

**Closed by IvanSanchez** 2015-11-16 15:41 UTC
