### ISSUE TITLE
Firefox warning: MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead.

### ISSUE THREAD

**Issue by kngai** [Leaflet/Leaflet#7078] opened 2020-04-09 18:48 UTC
Hello. I've noticed this Firefox warning for a long time but I couldn't find an exact issue matching this.  Not a ground breaking issue, but it's there for Firefox users.

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1: With Firefox browser, visit page with any [Leaflet map](https://plnkr.co/plunk/Ub3MyucTh28OAiFk)
- step 2: Open F12 developer tools
- step 3: Pan the Leaflet map

**Expected behavior**
Compared to Chrome or Edge, no event warnings appear.

**Current behavior**
In console, notice the Firefox warning:
```
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead.
```

**Environment**
- Leaflet version: 1.5.1+
- Browser (with version): Firefox (74.0)
- OS/Platform (with version): Windows 10 64-bit

**Additional context**
Doesn't seem to affect anything major, but it's a warning that has persisted in Firefox for a very long time. Perhaps it's related to https://github.com/Leaflet/Leaflet/issues/3943 ?

**Minimal example reproducing the issue**
Visit https://plnkr.co/plunk/Ub3MyucTh28OAiFk and perform the steps

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment] 2020-04-09 19:05
Very much a duplicate of #3943. There's no ill effect.

**Closed by IvanSanchez** 2020-04-09 19:05 UTC

**Comment by jzabate** [comment] 2024-03-01 10:26
This issue still appears on **tinymce 6.7.0** on **Firefox 123.0 (64 bit)**
`MouseEvent.mozInputSource is deprecated. Use PointerEvent.pointerType instead.`
