### ISSUE TITLE
MouseEvent.mozPressure is no longer supported. Please use PointerEvent.pressure instead.

### ISSUE THREAD

**Issue by JatGitHub** [Leaflet/Leaflet#8991] opened 2023-06-19 17:49 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Click anywhere on the map.

### Expected behavior

The click event is caught and the icon can be moved

### Current behavior

Nothing

### Minimal example reproducing the issue

https://plnkr.co/edit/SvJu6rdizSTn9D0t

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Firefox
- OS/Platform (with version): Windows 10

The issue has been reported as a warning, now it is not supported and the click is not caught anymore.

 leaflet.js:5:319

Might want to check also 
'webkitMovementX' is deprecated. Please use 'movementX' instead.
leaflet-src.js:49. Haven't seen the error yet.

Thanks in advance

**Comment by IvanSanchez** [comment] 2023-06-19 17:57
Duplicate of https://github.com/Leaflet/Leaflet/issues/7078.

**Closed by IvanSanchez** 2023-06-19 17:57 UTC
Labels: bug, needs triage
