### ISSUE TITLE
Bug while removing a marker with opened popup

### ISSUE THREAD

**Issue by bullgare** [Leaflet/Leaflet#2762] opened 2014-06-27 14:45 UTC
There's a bug in leaflet.js: "popupclose" event is fired before "remove" event is fired but after the marker is actually removed.
That occurs when there are markers on the map with one opened popup and we want to remove them all.
That's a solution I went to

```
marker
    .setPopupContent(html)
    .openPopup()
    .on('popupclose', function () {
        if (marker._icon) {
            marker.setOpacity(1);
        }
        marker.off('popupclose');
    })
    .on('remove', function () {
        marker.off('popupclose');
    });
```

But this workaround (**if (marker._icon)**) I don't like.

The possible solutions are:
- to fire "remove" event before "popupclose"
- check for **if (marker._icon)** in method marker.setOpacity()
- fire "popupclose" event before marker is removed

I can make a pull request, but I have to understand, which way to go.

**Comment by IvanSanchez** [comment] 2016-09-26 12:09
@bullgare Can you please check if the bug is still reproducible with Leaflet 1.0.0?

**Comment by perliedman** [comment] 2017-08-09 08:32
While I can understand the reasoning about event order presented here, I don't think this is something we will change at this point, given the likeliness it will break existing code relying on the current order of events.

Also, nothing new on this in a loooong while, so I'm closing for now. If you think this is still a problem and have a constructive suggestion on how to improve this, I'm happy to reopen!

**Closed by perliedman** 2017-08-09 08:32 UTC
Labels: bug, needs more info

**Comment by bullgare** [comment] 2017-08-09 09:25
Fine for me cause I don't use Leaflet for about two years now.
If someone will run into it - good luck :)
