### ISSUE TITLE
progid:DXImageTransform causes error on ios

### ISSUE THREAD

**Issue by tuvokki** [Leaflet/Leaflet#5066] opened 2016-10-31 14:43 UTC
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported
There is a pull request that fixes this issue, but it has been closed without merge: https://github.com/Leaflet/Leaflet/pull/4122/commits/0a2a736d57eee2308922d1a4cfdd57984c87add8

----

## How to reproduce

- Leaflet version I'm using: 1.0.1
- Browser (with version) I'm using: Safari on ios (9.3)
- OS/Platform (with version) I'm using: ios (9.3)
- include a map in an ios build. In this case it is an ionic application
- open to see the following:
![screen shot 2016-10-31 at 15 40 09](https://cloud.githubusercontent.com/assets/181719/19858068/693d16ae-9f80-11e6-963f-843a5c01f640.png)

## What behaviour I'm expecting and which behaviour I'm seeing
No warnings

The above pullrequest fixes it.

**Comment by IvanSanchez** [comment] 2016-10-31 14:47
Duplicate of https://github.com/Leaflet/Leaflet/pull/4977, https://github.com/Leaflet/Leaflet/pull/4122. 

Besides, that's an error, not a warning. Compatibility for old IEs is more important than warnings in Safari.

**Closed by IvanSanchez** 2016-10-31 14:47 UTC

**Comment by tuvokki** [comment] 2016-10-31 16:09
Does quoting the line break anything?

**Comment by IvanSanchez** [comment] 2016-10-31 16:32
Yes. See #4977.

**Comment by tuvokki** [comment] 2016-11-01 07:21
Clear. I only read (and referenced) #4122 thanks for clearing this up.
