### ISSUE TITLE
calling fitBounds() right after setZoom() (with animation enabled) does not work

### ISSUE THREAD

**Issue by pakro** [Leaflet/Leaflet#5853] opened 2017-10-19 15:43 UTC
**System**
- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Firefox 56 / Chrome 62
- OS/Platform (with version) I'm using: Ubuntu 16.04

**Current behaviour**
calling fitBounds right after a setZoom (with animation enabled) does not show the bounds on the map (at least visually not -- the map pane does not get updated)

**Expected behaviour**
calling fitBounds right after a setZoom does show the map pane containing the bounds (animated or not)

**minimal reproducible example snippet (with commented workaround)**
https://jsfiddle.net/83cyhnaw/

Thanks to @w0m who actually found that issue!

**Comment by VictorVelarde** [comment] 2017-10-23 06:29
~~___ _ ~~

**Comment by perliedman** [comment] 2017-10-23 08:06
Hi, thanks for reporting. This sounds like a duplicate of #3249, so I'm closing this for now.

**Closed by perliedman** 2017-10-23 08:06 UTC
