### ISSUE TITLE
Tooltip bug: tooltip doesn't close when mouse leaves the feature ( canvas rendered )

### ISSUE THREAD

**Issue by balciseri** [Leaflet/Leaflet#4828] opened 2016-08-19 06:13 UTC
Here an example:
https://playground-leaflet.rhcloud.com/wule/edit?html,js,console,output

There are 3 overlapping circles. 
http://puu.sh/otXdv/88fe99f2bb.jpg

- Now with your cursor start on the most left and keep moving the mouse to the right.
You can see the tooltips are showing for each canvas circle but they are not closing when you leave that circle and pass to the next one.

- Now do the opposite: start from the most right circle and go to the left.
This time the tooltips are closing.

Can this be related to: https://github.com/Leaflet/Leaflet/issues/4495

I'm not sure how this amazing new feature is beeing handled but it would be awesome to be possible to use these tooltips on maps where many markers are beeing rendered via the cavans ( using the canvas because the normal markers are not an option: too Many dom's elements make it laggy ).

**Comment by IvanSanchez** [comment] 2016-08-19 07:43
Yeah, this is a perfect duplicate of #4495 - the tooltip functionality is working as expected, but the canvas circle markers' events are not.

**Closed by IvanSanchez** 2016-08-19 07:43 UTC
