### ISSUE TITLE
Polygon tooltip out of place (after zooming in) when map in initialized with a low zoom level

### ISSUE THREAD

**Issue by nevaan9** [Leaflet/Leaflet#7492] opened 2021-03-04 19:50 UTC
**Steps to reproduce**
- Initialize a map with a low zoom level (1, 2, or 3)
- Add a few polygons close to each other, that spans across a city somewhere in the world
- Add a **permanent** tooltip to the polygons (issue seems to be with permanent tooltips)
- Now zoom down to the polygons to see all of them
- You will see the tooltips are out of place
![image](https://user-images.githubusercontent.com/20254162/110021126-5d101200-7cf8-11eb-9ac8-dcda7456d3e6.png)

**Expected behavior**
The tooltips should be inside the polygon bounds

**Current behavior**
They are not within the body/bounds of the polygon

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome Version 88.0.4324.192
- OS/Platform (with version): Mac 10.15.7

**Minimal example reproducing the issue**
https://codesandbox.io/s/friendly-solomon-s71um?file=/src/App.vue

**Comment by johnd0e** [comment] 2021-04-04 14:51
Duplicate of #5216

**Closed by johnd0e** 2021-04-04 14:51 UTC
Labels: bug, good first issue, help wanted
