### ISSUE TITLE
Pop-ups Don't Open in Microsoft Legacy Edge

### ISSUE THREAD

**Issue by pmacMaps** [Leaflet/Leaflet#7262] opened 2020-09-09 11:21 UTC
**Steps to reproduce**
- visit https://gis.ccpa.net/labs/edge-legacy-leaflet/ in Microsoft Legacy Edge (44.18362.449.0)
- click on the map marker to open the pop-up (does not work)
- visit above link in a different web browser
- click on the map marker to open the pop-up (does work)

**Expected behavior**
The pop-up should open when clicking on it.

**Current behavior**
The pop-up does not open when clicking on it using Microsoft Legacy Edge.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Microsoft Legacy Edge (44.18362.449.0)
- OS/Platform (with version): Windows 10

**Minimal example reproducing the issue**
https://gis.ccpa.net/labs/edge-legacy-leaflet/

**Comment by jgravois** [comment] 2020-09-09 15:44
FWIW, i'm not seeing the popup display in your minimal demo in Safari either.

besides the fact that it displays initially, the behavior is the same in https://leafletjs.com/examples/quick-start/

![output](https://user-images.githubusercontent.com/3011734/92621378-994a4480-f278-11ea-8d4a-2fe00d14057a.gif)

**Comment by IvanSanchez** [comment] 2020-09-09 17:40
If this happens on Safari as well, it might be a duplicate of #7255. Please try reproducing using a build from the `master` branch, as detailed in https://github.com/Leaflet/Leaflet/issues/7255#issuecomment-689562115

**Comment by johnd0e** [comment] 2020-09-10 07:01
> If this happens on Safari as well

But this also happens on Edge (confirmed).
So definitely that is not fixed in `master`.

**Closed** 2020-09-11 09:36 UTC
