### ISSUE TITLE
mousedown and click events interfere with each other

### ISSUE THREAD

**Issue by da-mkay** [Leaflet/Leaflet#4328] opened 2016-03-17 18:41 UTC
When using `.on('mousedown', ...)` and `.on('click', ...)` on a `Rectangle` the on-click event may not always fire when the `Rectangle` is clicked. Consider the following example:

    <div id="map" class="map"></div>
    <script>
    var map = L.map('map').setView([42.383901, 4.744117], 5)
      , tileLayer = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png').addTo(map)
      , rectLayer = L.layerGroup().addTo(map)

    var rect = L.rectangle([[43.683901, 3.444117], [41.083901, 6.044117]]).addTo(rectLayer)

    rect.on('mousedown', function (e) {
        console.log('I was DOWNED :P')
        // NOTE: no stopPropagation() here!
    })

    rect.on('click', function (e) {
        console.log('I was CLICKED')
    })
    </script>

If you click on the `Rectangle` right after the page was loaded, both the `mousedown`- and `click`-handler are called. You can click on it multiple times and each time both handlers are called.... until you drag the map a bit around. After dragging/repositioning the map, often only the `mousedown`-handler is called when the `Rectangle` is clicked. You can then try to drag the map around and if you're  lucky both handlers will be called again. Looks like a bug to me :-) Maybe propagation of mouse events is mistakenly stopped somewhere.

EDIT: Leaflet v0.7.7

**Comment by IvanSanchez** [comment] 2016-03-17 18:59
I made a [playground here](http://playground-leaflet.rhcloud.com/pehu/edit?html,console,output). I'm unable to reproduce the problem.

**Comment by iH8** [comment] 2016-03-17 19:18
Can reproduce, Windows, Edge 25, Chrome 49 and Firefox 44, without the layerGroup, with polylines, polygons and rectangles. Also in Safara 9 on OSX, no problems with Chrome 48.
![click](https://cloud.githubusercontent.com/assets/692063/13857862/1ffec788-ec7c-11e5-93b5-bceeb625861e.gif)

**Comment by IvanSanchez** [comment] 2016-03-17 20:14
This must check with both canvas and SVG (but I forgot how to do that with 0.7.x already)

**Comment by iH8** [comment] 2016-03-18 14:36
Set `L_PREFER_CANVAS` to true before loading the libary you mean? Canvas is not affected, at least, for me it doesn't even fire the mousedown event?

**Comment by nmccready** [comment] 2016-09-01 20:28
I am seeing this problem as well when two polygons are layered on top of each other.

**Comment by nmccready** [comment] 2016-09-01 20:33
One thing to note is `mousedown` is caught and fired where `click` is not.

**Comment by mourner** [comment] 2016-09-27 14:14
Closing because we just released 1.0 and minor issues in 0.7.x are unlikely to be fixed.

**Closed by mourner** 2016-09-27 14:14 UTC
Labels: 0.7.x, needs investigation
