### ISSUE TITLE
DOM generation of leaflet

### ISSUE THREAD

**Issue by Sven74Muc** [Leaflet/Leaflet#5484] opened 2017-04-26 15:28 UTC
I'm using MapMarker Pro which is using Leaflet and having an issue. MapsMarkers Pro support assumes that it is an Leaflet DOM issue because it happens only on the first click on a marker and they are only using internal leaflet parameter. 

You can see the issue at maps.sven-esser.de/bikemap or in full screen at http://maps.sven-esser.de/maps/fullscreen/layer/1/ 

Clossing the marker and opening another or the same marker again the issues is gone. After reloading the page the issue is back.

I did the following:

    1. Setup a new subdomain under maps.sven-esser.de
    2. Setup an entire new Wordpress
    4. Setup a fresh MapsPro installation
    5. Setup one layer (100% with, 600px hight) and one marker (map size 100% with, 600px hight)
    6. Create a site with the layer included maps.sven-esser.de/bikemap

For CSS of the marker pop-up I set
maxWidth (px): 600 maxHeight (px): 300 CSS for images in popups: max-width:234px !important; height:auto; width:auto !important;

Result Fault_a: Popup is too much on the top of the map
![fault_a](https://cloud.githubusercontent.com/assets/27951109/25442541/9c916ac2-2aa5-11e7-99c5-b19af4d686c6.gif)

Changed CSS
max-width:234px !important; height:auto; width:auto !important;
to
max-width:600px !important; height:auto; width:auto !important;

Result Fault_b: Pobup is too much on the top of the map AND popup is to small for image
![fault_b](https://cloud.githubusercontent.com/assets/27951109/25442563/aa5eb5b0-2aa5-11e7-9b05-05c89f794c5d.gif)

**As written it's just the first marker click in a map, after this everything is working till I reload the page.**

**Comment by Sven74Muc** [comment] 2017-04-26 15:34
I'm reporting a bug, not asking for help
I've looked at the [documentation]
I'm sure this is a Leaflet code issue because MapsMarker Pro is only using internal leaflet parameter

**Comment by ghybs** [comment] 2017-04-26 16:08
See:
- [SO: Adding an image inside popup content with Leaflet](https://stackoverflow.com/questions/34561725/adding-an-image-inside-popup-content-with-leaflet/34561788#34561788)
- [SO: Leaflet: adjust popup to picture size](https://stackoverflow.com/questions/38170366/leaflet-adjust-popup-to-picture-size/38172374#38172374)

**Comment by perliedman** [comment] 2017-04-26 18:20
Thanks @ghybs, those are to good questions and answers. You are correct, the problem is that Leaflet doesn't know the size of the image until it's loaded.

You can either specify the image size directly if you know it beforehand, or you can listen for the image's `load` event and call the popup's [`update()`](http://leafletjs.com/reference-1.0.3.html#popup-update) method once it has loaded.

Given that Leaflet allows arbitrary content in popups, it can't know when its size changes, so this needs to be handled by the code creating the content. I'm going to close this, since I do not believe it's a bug in Leaflet, but that should be handled by the application, in this particular case MapMarker Pro.

**Closed by perliedman** 2017-04-26 18:20 UTC

**Comment by Sven74Muc** [comment] 2017-04-27 15:08
Thanks so much @perliedman !!! load event and update() methode is the solution... and so easy I think

**Comment by Sven74Muc** [comment] 2017-05-07 07:48
Ok, unfortunately "Leaflet MapsMarker Pro" doesn't look that they get it solved. They talk about side effects...

However, I think what perlidman described couldn't be so difficult. It sounds it is very easy for a programmer... unfortunately I'm not a programmer. 
It's Sunday and I have time :-) Is here anyone who can help me that I can do the changes by my own without the plugin provider?

Just try to find out where the procedure for opening the pop-up is placed. Think that's the first step.

**Comment by Sven74Muc** [comment] 2017-05-07 07:55
Here's teh js part which opens a popup. Am I right that there needs something to be placed at the beginning? My understanding is that right now 1. is the click and then the popup opens. This needs to be changed to 1. click 2. load event & update() method needs to be called and then the popup opens. Right?

//info: open popup when clicking on icon or marker name in list of markers; also needed for JS Event API so no check if $listmarkers == 1
	if (!empty($layer)) {
		//info: JS API function to open popup
		$lmmjs_out .= PHP_EOL . "function listmarkers_openpopup_" . $mapname_js . "(id) {".PHP_EOL;
		if($lmm_options['defaults_layer_listmarkers_link_action_zoom'] == 'marker-zoom'){
			if($filter_details || $clustering == '1'){
				$lmmjs_out .= '	setTimeout(function(){ '.PHP_EOL;
				$lmmjs_out .= "	var newlocation = markerID_" . $mapname_js . "[id].getLatLng();".PHP_EOL;
				$lmmjs_out .= 		$mapname_js.".setView(newlocation,markerID_" . $mapname_js . "[id].feature.properties.zoom);".PHP_EOL;
				$lmmjs_out .= '	setTimeout(function(){ '.PHP_EOL;
				if($clustering == '1'){
					$lmmjs_out .= ' 	if( markercluster_'.$mapname_js.'.getVisibleParent(markerID_'.$mapname_js.'[id]) != null){ '.PHP_EOL;
					$lmmjs_out .= ' 		if(typeof markercluster_'.$mapname_js.'.getVisibleParent(markerID_'.$mapname_js.'[id]).spiderfy == "function"){ '.PHP_EOL;
					$lmmjs_out .= '				markercluster_'.$mapname_js.'.getVisibleParent(markerID_'.$mapname_js.'[id]).spiderfy();'.PHP_EOL;
					$lmmjs_out .= '			}'.PHP_EOL;
					$lmmjs_out .= '		}'.PHP_EOL;
				}
				if ($lmm_options['defaults_layer_listmarkers_link_action'] == 'setview-open') {
					$lmmjs_out .= '		markerID_' . $mapname_js . '[id].openPopup();'.PHP_EOL;
				}
				$lmmjs_out .= '},1000);'.PHP_EOL;
				$lmmjs_out .= '	 }, 300);'.PHP_EOL;
			} else {
				if ($lmm_options['defaults_layer_listmarkers_link_action'] == 'setview-open') {
					$lmmjs_out .= "	" . $mapname_js.".setZoom( markerID_" . $mapname_js . "[id].feature.properties.zoom );" . PHP_EOL;
					$lmmjs_out .= "	markerID_" . $mapname_js . "[id].openPopup();".PHP_EOL;
				}
			}
		} else {
			if ($lmm_options['defaults_layer_listmarkers_link_action'] == 'setview-open') {
			$lmmjs_out .= "	markerID_" . $mapname_js . "[id].openPopup();".PHP_EOL;
			}
			if($clustering == '1'){
				$lmmjs_out .= '	setTimeout(function(){ '.PHP_EOL;
				$lmmjs_out .= "	var newlocation = markerID_" . $mapname_js . "[id].getLatLng();".PHP_EOL;
				$lmmjs_out .= $mapname_js.".setView(newlocation," . $mapname_js . ".getZoom());".PHP_EOL;
				$lmmjs_out .= 'if( markercluster_'.$mapname_js.'.getVisibleParent(markerID_'.$mapname_js.'[id]) != null){ '.PHP_EOL;
				$lmmjs_out .= '		if(typeof markercluster_'.$mapname_js.'.getVisibleParent(markerID_'.$mapname_js.'[id]).spiderfy == "function"){ '.PHP_EOL;
				$lmmjs_out .= '			markercluster_'.$mapname_js.'.getVisibleParent(markerID_'.$mapname_js.'[id]).spiderfy();'.PHP_EOL;
				$lmmjs_out .= '		}'.PHP_EOL;
				$lmmjs_out .= '}'.PHP_EOL;
				if ($lmm_options['defaults_layer_listmarkers_link_action'] == 'setview-open') {
					$lmmjs_out .= "	markerID_" . $mapname_js . "[id].openPopup();".PHP_EOL;
				}
				$lmmjs_out .= '},1000);'.PHP_EOL;
			}else{
				$lmmjs_out .= "	var newlocation = markerID_" . $mapname_js . "[id].getLatLng();".PHP_EOL;
				$lmmjs_out .= "	" . $mapname_js.".setView(newlocation," . $mapname_js . ".getZoom());".PHP_EOL;
			}
		}
		//info: jump to top/map
		$lmmjs_out .= '	window.location.href = "#lmm_'.$uid.'"'.PHP_EOL;
		//info: change url for permalinks (not supported in IE8+9)
		$lmmjs_out .= '	if (history.pushState) {'.PHP_EOL;
		$lmmjs_out .= '		window.history.pushState(null, null, "?highlightmarker="+[id]);'.PHP_EOL;
		$lmmjs_out .= '	}'.PHP_EOL;
		$lmmjs_out .= "}";
	}

**Comment by Sven74Muc** [comment] 2017-05-07 07:57
Ok, here the js is better readable

![js](https://cloud.githubusercontent.com/assets/27951109/25778885/95be1a88-330b-11e7-8df5-15217d6cd013.jpg)

**Comment by Sven74Muc** [comment] 2017-05-07 08:07
Here's the entire file

[showmap.zip](https://github.com/Leaflet/Leaflet/files/981387/showmap.zip)

**Comment by Sven74Muc** [comment] 2017-05-07 09:22
The entire file you can download here:

https://www.mapsmarker.com/docs/how-to-install-the-plugin/

...its inc/showmap.php within the downloadable pro version (zip file)

**Comment by robertharm** [comment] 2017-05-08 06:06
@ghybs @perliedman thanks for helping one of our plugin users, although this is not your job. 

We try to handle all plugin related questions and issues in our internal helpdesk & only open leaflet issues ourselves if we are 100% sure that it is not caused by our code (and can be reproduced with a native Jsfiddle setup).

**Comment by ghybs** [comment] 2017-05-08 18:25
Hi @robertharm,

Sorry I do not know this plugin and I do not know how to play with it.

However it seems to me that this type of issue could be addressed for good by globally capturing the `<IMG>`'s `"load"` event on all popups and forcing them to `update()` every time…

```javascript
document.querySelector(".leaflet-popup-pane").addEventListener("load", function (event) {
  var tagName = event.target.tagName,
      popup = map._popup;
  
  if (tagName === "IMG" && popup) {
    popup.update();
  }
}, true); // Capture the load event, because it does not bubble.
```

Example: https://jsfiddle.net/3v7hd2vx/277/

**Comment by ghybs** [comment] 2018-08-03 06:47
Other similar issues: https://github.com/Leaflet/Leaflet/issues/250, https://github.com/Leaflet/Leaflet/issues/2458
