### ISSUE TITLE
"export 'markerClusterGroup' (imported as 'L') was not found in 'leaflet'"

### ISSUE THREAD

**Issue by krabouilleur** [Leaflet/Leaflet#8495] opened 2022-09-29 12:45 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

On "ng build" the following error : 
"export 'markerClusterGroup' (imported as 'L') was not found in 'leaflet'"

the package.json :  
```
"dependencies": {
    "@angular/animations": "^14.2.4",
    "@angular/cdk": "^14.2.3",
    "@angular/common": "^14.2.4",
    "@angular/compiler": "^14.2.4",
    "@angular/core": "^14.2.4",
    "@angular/forms": "^14.2.4",
    "@angular/material": "^14.2.3",
    "@angular/platform-browser": "^14.2.4",
    "@angular/platform-browser-dynamic": "^14.2.4",
    "@angular/router": "^14.2.4",
    "@asymmetrik/ngx-leaflet": "^14.0.1",
    "@asymmetrik/ngx-leaflet-markercluster": "^14.0.1",
    "@fortawesome/angular-fontawesome": "~0.11.1",
    "@fortawesome/fontawesome-svg-core": "^6.2.0",
    "@fortawesome/free-solid-svg-icons": "^6.2.0",
    "@juggle/resize-observer": "^3.4.0",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@turf/turf": "^6.5.0",
    "@types/echarts": "^4.9.16",
    "@types/file-saver": "^2.0.5",
    "@types/leaflet": "^1.8.0",
    "@types/leaflet.markercluster": "^1.5.1",
    "angular-oauth2-oidc": "^13.0.1",
    "crypto-js": "^4.1.1",
    "echarts": "^5.4.0",
    "file-saver": "^2.0.5",
    "jwt-decode": "^3.1.2",
    "leaflet": "^1.9.1",
    "leaflet.markercluster": "^1.5.3",
    "material-design-icons-iconfont": "^6.7.0",
    "moment": "^2.29.4",
    "ng-swagger-gen": "^2.3.1",
    "ngx-echarts": "^14.0.0",
    "ngx-mat-select-search": "^4.2.1",
    "npm-check-updates": "^16.3.3",
    "rxjs": "~7.5.7",
    "tslib": "^2.4.0",
    "zone.js": "~0.11.8"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.4",
    "@angular/cli": "^14.2.4",
    "@angular/compiler-cli": "^14.2.4",
    "@types/crypto-js": "^4.1.1",
    "@types/jasmine": "~4.3.0",
    "@types/node": "^18.7.23",
    "crypto-browserify": "^3.12.0",
    "jasmine-core": "^4.4.0",
    "karma": "^6.4.1",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "ng-openapi-gen": "^0.23.0",
    "stream-browserify": "^3.0.0",
    "typescript": "~4.8.4"
  }
```

### Expected behavior

no build error

### Current behavior

Error on ng build

### Environment

- Leaflet version: 1.9.1

**Comment by Falke-Design** [comment] 2022-09-29 12:47
Duplicate of #8451

**Closed by Falke-Design** 2022-09-29 12:47 UTC
Labels: bug, needs triage
