### ISSUE TITLE
accessibility : L.control disappear when focus on an off-screen marker using TAB key

### ISSUE THREAD

**Issue by remilev** [Leaflet/Leaflet#3363] opened 2015-04-09 13:06 UTC
I'm using leaflet stable 0.7.3 
Issue tested on firefox 37 and chrome 41. 
Can be test on the map at http://leafletjs.com/ :
 1 - drag the map to make the demo marker disappear
 2 - hit TAB key
 -> The map will move so the demo marker will show and gain focus, which is expected.
      But zoom control will <b>disappear</b>

I think leaflet isn't firing any panning/dragging code (like when dragging with mouse or touch) in this case : the .leaflet-map-pane css style <code>transform: translate(-XXpx, XXpx);</code> won't update as expected. The absolute positioning of L.controls make them follow the map -> they move off-screen.

As a workaround, positioning .leaflet-top, right, bottom, left and top with <code>position: fixed;</code> will fix this issue. But maybe you don't use "fixed" because it can lead to problems on some browsers (on IPAD maybe?) ?

**Comment by mourner** [comment] 2015-04-09 14:27
Duplicate of #3333 which has been fixed just recently.

**Closed by mourner** 2015-04-09 14:27 UTC
