### ISSUE TITLE
Z-index bugs on Android 3/4

### ISSUE THREAD

**Issue by Savvkin** [Leaflet/Leaflet#335] opened 2011-10-16 09:03 UTC
Not only zoom control is hidden, but any div with position:absolute and any z-index is drawing behind tiles.
Screenshot from Samsung Galaxy Tab 10.1 @ Android 3.1:
http://dl.dropbox.com/u/17131034/SC20111016-124937.jpg
Screenshot illustrates that zoom control is actually there, but behind tile pane and you can see it while you move map away, buy tiles are not yet loaded.
Issue persist in native browser and Dolphin browser. Mobile Firefox is OK.

Also, div it is not visible, but actually it works. You can click-thru and events dispatched.

Device is updated to latest firmware and software.
Everything is fine on Android 2.3.4 phone and on Desktop (IE, FF, Safari).

**Comment by yohanboniface** [comment] 2015-10-12 12:14
Can someone confirm this issue is still in latest master? And if yes create a minimal small test case to demonstrate it using http://playground-leaflet.rhcloud.com/ or similar service? Thanks :)

**Comment by mourner** [comment] 2016-02-12 14:39
No reaction so closing.

**Closed by mourner** 2016-02-12 14:39 UTC
Labels: android, blocker, help wanted, mobile, needs solution

**Comment by petitlen** [comment] 2017-04-19 06:11
when leaflet in iscroll5, the control pane show right in pc(safari,chrome);but the control pane could't show in mobile(ios,android).
until i drag the map , the control pane behide the map can show on mobile!

**Comment by petitlen** [comment] 2017-04-19 06:14
my version is leaflet 1.0.3

**Comment by perliedman** [comment] 2017-04-19 08:28
@petitlen since you're seeing this on iOS as well as Android, this is hardly the same issue (which only happens on Android 3/4, as stated in the title).

Also, please note that we _do not_ fix issues caused by interaction with specific libraries and frameworks, in this case iScroll 5. If you can create a minimal example that reproduces the issue without other libraries, please open a new issue.

**Comment by petitlen** [comment] 2017-04-19 11:38
thank for reply. becase iscroll5 is popular, so if you can make leaflet and iscroll5 compatibility, it's very very good to us. thank you.

**Comment by perliedman** [comment] 2017-04-19 12:00
@petitlen Leaflet already works with iScroll, that is not the issue (see http://playground-leaflet.rhcloud.com/bejeh/edit?html,output).

This is an issue tracker, for problems and features related to Leaflet. You either need to:

1. make sure this is  _a Leaflet issue_ (an issue that occurs with _only_ Leaflet, not together with other frameworks or libraries); in this case, open a new issue
2. go to a forum for support questions, like Stackoverflow
