### ISSUE TITLE
Multipolygon shape cause invalid GeoJSON

### ISSUE THREAD

**Issue by DanFaudemer** [Leaflet/Leaflet#7627] opened 2021-07-27 09:58 UTC
## Description

An unbalanced multipolygon shape will generate an invalid GeoJSON with null coordinates

## Steps to reproduce

Create an unbalanced Multipolygon shape and call toGeoJson:

```javascript
const poly = L.polygon([[[
		[51.509, -0.08],
		[51.503, -0.06],
		[51.51, -0.046]
	],
        [
		[51.508, -0.06],
		[51.504, -0.06],
		[51.509, -0.05]
	]
     ], [
           [51.499, -0.08],
	   [51.493, -0.06],
	   [51.48, -0.046]
        ]])

console.log(poly.toGeoJSON().geometry.coordinates)
``` 
Returns:
```json
[
    [
        [
            [
                -0.08,
                51.509
            ],
            [
                -0.06,
                51.503
            ],
            [
                -0.046,
                51.51
            ],
            [
                -0.08,
                51.509
            ]
        ],
        [
            [
                -0.06,
                51.508
            ],
            [
                -0.06,
                51.504
            ],
            [
                -0.05,
                51.509
            ],
            [
                -0.06,
                51.508
            ]
        ]
    ],
    [
        [
            null
        ],
        [
            null
        ],
        [
            null
        ]
    ]
]
```

## Environment
Leaflet version : 1.7.1

## Minimal example reproducing the issue

Please see https://plnkr.co/edit/h7neyNZ5M8sLId7s and click on the polygon

**Comment by Malvoz** [comment] 2022-04-21 11:26
Duplicate of #5446?

**Closed** 2022-08-28 20:33 UTC
Labels: bug
