### ISSUE TITLE
When you zoom and move the map is lost KML layer

### ISSUE THREAD

**Issue by alexgubanow** [Leaflet/Leaflet#4775] opened 2016-08-01 08:37 UTC
I have leafletjs 1.0.0-rc.1 (6ea195a), and leaflet-plugins kml by shramov(with my changes). When you zoom and move the map is lost KML layer. Video demonstration of a bug https://youtu.be/tPPmb3vbrus.
my code kml and working with map: [code.zip](https://github.com/Leaflet/Leaflet/files/393262/code.zip)

UPDATE:
I have only leafletjs v1.0.0-beta.2, blue areas is multipolygon layer, his lost when you fast max zoom, move and zoom out to min.
code http://playground-leaflet.rhcloud.com/govu/1/edit?html,js,output

**Comment by yohanboniface** [comment] 2016-08-03 09:23
Hi,

You should either try to reproduce the issue without any third party plugin or lib (and demonstrate in a http://playground-leaflet.rhcloud.com/ for example), or open an issue in the plugin itself.

**Comment by alexgubanow** [comment] 2016-08-03 16:17
ok, http://playground-leaflet.rhcloud.com/ledi/edit?html,js,output
for reproduce bug, you need fast max zoom, move and zoom out to min.

**Comment by yohanboniface** [comment] 2016-08-03 16:34
Not able to reproduce.
I see the playground uses beta2, can you reproduce with latest master by the way?
Which browser are you using? Are you able to reproduce with another browser?

**Comment by alexgubanow** [comment] 2016-08-03 16:39
i change to latest master, bug is still there))
in my app i'm use awesomium .Net, but i try opera and microsoft edge.
you get it reproduce?

**Comment by alexgubanow** [comment] 2016-08-03 16:46
Video demonstration of a bug https://www.youtube.com/watch?v=nzbIjPqubaw

**Comment by perliedman** [comment] 2017-08-09 07:45
Can't reproduce in the playground example, video is gone. Need more information to proceed on this, so closing for now.

**Closed by perliedman** 2017-08-09 07:45 UTC
Labels: needs more info
