### ISSUE TITLE
geolocation shortcuts failing

### ISSUE THREAD

**Issue by drgottjr** [Leaflet/Leaflet#3384] opened 2015-04-17 16:04 UTC
within the past couple days (following a google update to webview, i believe) leaflet's geolocation shortcuts are now broken.  if i replace the shortcuts with "standard" browser geolocation functions, the functionality of the app returns, as before.

i've left a similar - more detailed - post on a google leaflet forum, but i'm not seeing much interest there.  i'm reluctant to start posting duplicates, but the issue may be of concern.

-go

**Comment by mourner** [comment] 2015-04-17 18:22
Do you know what could go wrong? The geolocation code in Leaflet is very easy, just a simple wrapper around the standard methods: https://github.com/Leaflet/Leaflet/blob/master/src/map/ext/Map.Geolocation.js

Also, what browsers / versions / OS are affected?

**Comment by drgottjr** [comment] 2015-04-17 19:31
i was hoping this would catch your eye.  did you happen to look at my post athttps://groups.google.com/forum/#!forum/leaflet-jsit answers some of your questions. i looked at the leaflet source and saw that the geolocation shortcuts were apparently just wrappers around the standard browser functions. not sure where to start, so let me just spill it:i have a mapping app running on android.  the code is usually ironed out on an emulator.  some basic stuff is first done on my windows 7 chrome (latest) browser for convenience.as mentioned in my other post, i have 3 android devices - all kept up to date by google whenever i turn them on.  they are currently running android 4.2, 5.0 (which was upgraded from 4.4 by google) and 5.0.2 on a motorola e lte.   the app was running fine on all 3.  it was running fine on the first 2 for about a year (whenever leaftlet was last updated).  the motorola is a recent purchase, but it ran on it fine.  the geolocation calls have been unchanged for a year.  i can send them to you; otherwise, take my word that they worked as expected. what i mean by "as expected" is outlined in my other post: "fine positioning" is used, so i get gps, wifi and cell towers (as supplied by google).  error checking and timeouts are used.  so you know, android's webview is used, not a browser.  you feed it javascript and html, and it acts pretty much like a browser. my user can choose to locate his position once or to watch his position as he moves around.  since geolocation relies on whatever the browser uses for positioning, some kind of network connection is needed.  with this in mind, my app also allows the user to select gps only.  geolocation functions would be unused in that case. so everything is fine until a couple days ago when i noticed that using geolocation inside (where i'm usually sitting in front of my terminal) wasn't working.  it's always worked in the past:  the cell tower/wifi positioning normally reports a location almost immediately.  then, a few seconds later, the gps kicks in with a more accurate position.  if no position is found within 15 seconds, the thing times out and you get an error alert.  now, no position is reported and there is no timeout.  i go outside to test.  no position, no timeout.  (if i choose gps only, that still works.  but that's not using leaflet.) i remember that google updated webview a few days ago.  it did some other updates as well, but since i'm so dependent on webview, it stood out.  i haven't started "googling" what the update involved.  i assumed that geolocation "failures" would start appearing on leaflet-related forums.   in the meantime, i happened to remember i had another app that used geolocation.  it's not a mapping app, so it didn't use leaflet.  it used the standard browser geolocation functions (but still in a webview context.)  i ran it, and got the "coarse" positioning immediately.  so i stripped the leaflet shortcuts out of my mapping app and replaced them with the standard browser calls, and geolocation ran perfectly.  on all 3 devices. i understand this is still vague in the scheme of things.  i really thought i couldn't be the only one this was happening to, and that you would have been deluged with cries for help.  i don't know what else to tell you.  my workaround is to not use the leaflet shortcuts (even though they just wrap my workaround!)  for my sake, and if anyone else experiences this, i hope they can explain it to you better. thanks for your time.  and for leaflet!-george ott

**Comment by sindre** [comment] 2015-04-27 07:36
I can only reproduce the Error in latest Firefox on Android 5.1 - simple html5 geolocation works - leaflet wrapper not.

**Comment by IvanSanchez** [comment] 2015-04-27 08:19
I just tried http://leafletjs.com/examples/mobile-example.html in Firefox 37.0 on Android 5.0.1, and works just fine.

**Comment by sindre** [comment] 2015-04-27 12:08
Tracked the error down to "maximumAge" geolocation option. So guess no leaflet problem.

**Comment by mourner** [comment] 2015-04-27 15:59
Closing unless we find a test case that reproduces the problem.

**Closed by mourner** 2015-04-27 15:59 UTC
Labels: bug

**Comment by wolfmuc** [comment] 2015-06-22 09:44
In Feb 2015 leafletjs geolocation worked fine. Now failing on Android 4.1.1. HTC Sense 4+, Chrome 43.0.2357.93 and Firefox 26.0.1. HTML5 Geolocation works fine in Chrome and Firefox. Since Feb I updated both browsers. Same on colleague´s Android. 
Regards Wolf

**Comment by wolfmuc** [comment] 2015-06-22 16:15
Tested, updated and reinstalled the whole day. Seems to be a bug on my HTC. At the moment Chrome does not accept raw HTML5 Geolocation and Leafletjs geolocation.

**Comment by explorob** [comment] 2016-02-02 02:46
I'm seeing geolocation failure too on WebChromeClient webview in my Android app on Android 5.1.1.

Webview has appropriate android.permission.INTERNET and android.permission.ACCESS_FINE_LOCATION permissions.  I also tried the Mapbox alternative Locate control at https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js with no luck. Seems to be timing out in finding location.  The HTML finds location on desktop browsers and also in Firefox and Chrome mobile browsers.

**Comment by hyperknot** [comment] 2016-02-02 08:47
Geolocation is very unreliable in browsers, it works randomly, and Leaflet has nothing to do with it.

There are two things which helped me:
- catch the error and restart location finding from within the error handling code with a limiter. So you implement retries this way.
-  `enableHighAccuracy: true` enables the GPS receiver on mobile phones (unless disabled by security), so eventually it'll find location, not depending on Google's servers, etc.

**Comment by drgottjr** [comment] 2016-02-02 16:16
i ditto that emotion.  it isn't leaflet.  leaflet just re-wraps the underlying geolocation code as supplied by the browser.  
you (we and leaflet) are at the mercy of that underlying code. plus whatever restrictions may be enforced by the device or your network operator (thus causing a timeout).  plus you could have a quirky gps or even a problem with your code.
what i did to convince myself that i couldn't blame it on leaflet (in spite of mourner himself telling me it wasn't) was to use the standard geolocation calls instead of leaflet's to see if that made a difference.  you don't have to use the leaflet geolocation routines.  you can find geolocation code online or this will get you started: http://www.w3schools.com/html/html5_geolocation.asp.  you can also see the same calls in the leaflet source.  it probably doesn't solve your problem, but it's important to eliminate leaflet as the cause.
timing out also doesn't sound like a coding issue.  you're down to hardware, a device setting or network or network provider issue.

**Comment by hyperknot** [comment] 2016-02-02 17:00
Also, I found out that when you are developing and calling a lot of geolocation calls, Google's servers are more likely to return an error, so I suspect they rate-limit geo-location requests. If I waited a minute they always started working again.

**Comment by explorob** [comment] 2016-02-02 20:27
Thanks for these ideas and info.  

So for use with Leaflet on a webview, you're recommending writing my own code with longer timeout values than the ones the Locate plugin uses as well as changing the desired accuracy value.

This alternative plugin seems to offer the functionality being suggested:
https://github.com/M165437/Leaflet.AccuratePosition

I haven't tried it yet but will try it.

**Comment by hyperknot** [comment] 2016-02-02 21:38
@explorob you don't need to use any plugins or custom code for that, Leaflet supports the required parameters (in 1.0 at least, I haven't checked 0.7). 

Here is a snippet:

```
map.on('locationfound', onLocationFound);
map.on('locationerror', onLocationError);

function getLocation() {
   tries += 1;
    map.locate({
        setView: true,
        maxZoom: 16,
        timeout: 5000,
        enableHighAccuracy: true
    });
}

function onLocationFound(e) {...}

function onLocationError(e) {...
    if (tries < 10) {
        getLocation();
    }
}
```

**Comment by drgottjr** [comment] 2016-02-02 22:18
no custom code necessary.  leaflet handles it.  

the plugin is a wrapper around the standard html5 geolocation calls, just like leaflet itself is.  the author has a theory about the accuracy of getCurrentPosition() which you can read once you figure out why you can't get a reading at all.  it has to do with forcing the gps to update itself (which may not be happening unless you goose it.)  i only took a quick look at the code but the main difference between it and regular leaflet seems to be that it prefers watchPosition().  this is the battery drainer.  watchPosition() will run until you turn it off or error out.  i think he inserts a time out so that
it turns itself off after massaging the gps for a more accurate reading.

if your browser uses a third party to resolve your location, either that party hears the call or it doesn't.  (in the case of chrome, google is third party listening for geolocation calls, and it has its own database
of things it uses to position you.)  the third party - if there is one - may answer or not.  none of this is under your control.  if you have the fine access setting on, and your gps isn't blocked or non-functioning, the geolocation call is supposed to turn the gps on.  you can see a symbol of some sort indicating it's on.  if you use the gps in a new location or in a "bad" location, it may take several minutes to find and coordinate the satellites.  if it succeeds at all.  normally, you get an approximate
location (depending on how your browser handles that) quickly, and then (if the fine access setting is on) you should get a gps reading almost immediately after that.  in the case of google, you can see this when you get a dot showing your location and then a few seconds later you're located on the other side of town!  the first dot is the fuzzy fix (based on wifi or cell tower).  the second location is the gps (or possibly a better wifi fix.  things depend on how your browser handles geolocation.)

your version of android is probably not the issue either.  i've got a number of them going for testing.
there are free apps to test your gps.  eliminating that aspect is helpful
