### ISSUE TITLE
leaflet-src.js file missing

### ISSUE THREAD

**Issue by Yasaa** [Leaflet/Leaflet#5840] opened 2017-10-14 08:52 UTC
I was going through this Leaflet github repository but found that dist/leaflet-src.js file is missing,its a big deal since the package.json file says that leaflet-src.js is the main entry point.

**Comment by cherniavskii** [comment] 2017-10-14 12:24
Duplicate of #5288

**Closed** 2017-10-14 12:24 UTC
