### ISSUE TITLE
Blurry tooltips due to unrounded CSS translation

### ISSUE THREAD

**Issue by futuretechmag** [Leaflet/Leaflet#4813] opened 2016-08-12 01:47 UTC
leaflet.js version: "1.0.0-rc.3+27f05a2"

Tooltips were drawing half-pixel digits for the pos.x position (at least the only one it was doing it for me) so:

transform: translate3d(1024.5px, 359px, 0px); - was blurry
transform: translate3d(1024px, 359px, 0px); - was perfect (same with if I made it 1025px)

So, I hacked it (as in most likely not correct) line 1464 from:

'translate3d(' + pos.x + 'px,' + pos.y + 'px,0)') +

-to- 

'translate3d(' + Math.round(pos.x) + 'px,' + Math.round(pos.y) + 'px,0)') +

And everything with my tooltips has been perfect.

**Comment by perliedman** [comment] 2016-08-15 19:08
Hi and thanks for reporting. Can you make JSFiddle or playground example that illustrates the problem? Which browser/OS do you use when you see this?

**Comment by sisou** [comment] 2016-08-19 13:13
Linux: blurry with half values in Chrome (y coordinate for me), but sharp in Firefox (but also shows half pixels in Dev Tools, just renders only full pixels).

**Comment by yohanboniface** [comment] 2016-08-19 13:25
@sisou thanks for those infos.
Sounds like a rounding issue. But more a browser issue than a Leaflet one, but we may workaround it.
Anyway, what would really help is:
- a jsfiddle (http://playground-leaflet.rhcloud.com/ is a good place for that) that reproduces the issue
- a screencast that shows the issue

**Comment by futuretechmag** [comment] 2016-08-19 14:22
Can you explain (honestly, not being rude) why we need a fiddle? In my case, I've shown the line that caused the issue, with the replace line that fixes the issue.

**Comment by yohanboniface** [comment] 2016-08-19 14:39
> Can you explain (honestly, not being rude) why we need a fiddle?

Because the time of your beloved library maintainers is rare. So if you want them to help you, start by helping them.
Reporting an issue is nice. Reporting it with all the needed info for understanding it and fixing it is better. Doing a PR is even better.
See https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs
We have *dozen* of examples of bug being reported being at then an issue on the user side (JS conflict, CSS conflict, buggish browser plugin, bad usage, etc.). I'm not saying that is the case here, but to be fair it's up to you to make the demonstration.
Remember that we are at most five active maintainers, while people reporting issues are hundreds.

> In my case, I've shown the line that caused the issue, with the replace line that fixes the issue.

That is not a fix. A fix is made in the src, not in the distributed files; tests should be ran without failures (and sometimes added); and a PR should be made.
BTW, the line you are touching is impacting all Leaflet code, and adding a Math.round there is not without impact on performances, and can have a lot of side effects. The proper fix very luckily somewhere else (*if* this is an issue at all).

Side note: writing "blurry bug again…" in an issue title *is* being rude.

**Comment by sisou** [comment] 2016-08-19 14:53
I found the issue and will send a PR when I'm home in an hour.

**Comment by futuretechmag** [comment] 2016-08-19 15:14
I labeled it "blurry bug again..." because I found a few other issues from 6+ months ago that had this same problem where it wasn't rounding. Didn't know that'd be construed as rude, so I'm sorry for that.

Secondly, to show you the broken and fixed line of code, to where the broken line of code causes blurry text because it's placing them on half-pixel pos.x and pos.y and my fixed line makes each pos.x and pos.y land on a whole number and the tooltip text isn't blurry, how could you even question "if this is an issue at all".

Personally, I don't care at this point if you guys fix it in the src, I'll just keep fixing it in the dist code. I just wanted to be nice and show the broken line and the fixed line for when others run across (as they have before according to a search on here) this problem.

**Comment by sisou** [comment] 2016-08-19 15:18
http://playground-leaflet.rhcloud.com/yol/edit?html,css,output

One of the two tooltips will be blurry, because the height of the tooltip is an uneven number. That uneven height is then halved in the calculation for the tooltip position.

AFAIK, this affects Webkit-based browsers. MS Edge/IE and Firefox do not render DOM elements at half pixels.

(PR incoming)

**Comment by IvanSanchez** [comment] 2016-08-19 15:29
@futuretechmag: And your effort is appreciated (this is an above-average bug report), but @yohanboniface's points still stand - pointing to a line in the code of a build is not pointing to a line in the source, unbuilt code; and rounding up CSS transforms affects other functionalities.

So it's nice that you could locate the source of the problem, but you got to understand that the way we work is different (and for a reason!). It's not that we don't trust your word, is that we *need* to *see* the problem. When applying changes, we need to see things for ourselves, and we ask of bug reporters to make it easy for us.

> how could you even question "if this is an issue at all".

Because your priorities are not our priorities. Because this particular behaviour impacts other functionality. Because this wouldn't be the first time that we haven't fixed something not really that important in order to not break other more important features.

You've detected a bug, and hacked in a fix, and shared your hack/fix. And that's great!! It's just that you're experiencing some resistance at the project management layer, as you're bypassing the usual commit/pr/test procedures that we keep in place in order to not go insane.

It's just a bug. Go outside, enjoy the weekend, relax.

**Comment by IvanSanchez** [comment] 2016-08-19 15:36
@sisou Can you please check that fractional zoom (and `flyTo` animation) works fine with your branch? I do expect some problems there if all the translated coordinates are rounded up. Check `debug/map/zoom-delta.html` and `debug/map/zoompan.html` if you haven't already.

**Comment by futuretechmag** [comment] 2016-08-19 16:38
@IvanSanchez @yohanboniface I would like to first apologize for coming across as brash, I was having a moment. 

I understand what you mean in terms of my problem isn't everyone's problem, so a fix may not be worth it.

I mainly just wanted to apologize for my earlier behavior. :)

**Comment by yohanboniface** [comment] 2016-08-19 16:39
@futuretechmag ♥

**Comment by perliedman** [comment] 2017-08-09 07:20
Closing, since this appears to have been fixed by the already merged #5089.

**Closed by perliedman** 2017-08-09 07:20 UTC
Labels: needs more info
