### ISSUE TITLE
Latest Chrome introduced 1px tile borders to integer zooms

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#6101] opened 2018-03-22 02:13 UTC
<img width="468" alt="half dome via mist trail by hyperknot maphub 2018-03-22 03-08-01" src="https://user-images.githubusercontent.com/494223/37747189-48512b14-2d7e-11e8-9af7-3cb86c025a17.png">

## How to reproduce
- Leaflet version I'm using: 1.3.1 (but same with 1.0.3)
- Browser (with version) I'm using: Chrome Stable and Chrome Canary
- OS/Platform (with version) I'm using: macOS 10.13.3

1. Use a map with a darker background colors, like Dark Matter.
2. Pan around and you'll see the 1px grey tile borders.
3. This was the biggest issue with fractional zooms in Chrome, now it's happening with integer zooms as well!

Safari and Firefox is still fine.

@IvanSanchez any chance of getting back the examples from:
https://github.com/Leaflet/Leaflet/issues/3575

cc: @perliedman @yohanboniface @mourner 

What should we do now? Open issues in Chromium and just hope for the best?

**Comment by hyperknot** [comment] 2018-03-22 02:59
Created a CodeSandbox and a screen capture GIF:
[![Edit ql1ymyr0n6](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ql1ymyr0n6)

![leaflet](https://user-images.githubusercontent.com/494223/37748784-696a5760-2d85-11e8-8f21-448a7d3c87b8.gif)

It happens in non-Retina resolutions as well.

**Comment by perliedman** [comment] 2018-03-22 08:18
😭

Can just confirm that I can reproduce this on Windows with Chrome 65.0.3325.181.

I seem to remember setting `L_DISABLE_3D` fixed the old issue with tile borders, but this does not appear to make any difference in the example you linked above.

**Comment by IvanSanchez** [comment] 2018-03-22 08:35
I can reproduce on Chromium 65.0.3325.146 on linux.

At first sight this seems to be due to non-integer offsets when doing inertia panning.

**Comment by perliedman** [comment] 2018-03-22 08:35
On a further update, I'm still seeing a lot of `translate3d` when I inspect the map in the DOM, even after setting `window.L_DISABLE_3D = true`, so maybe something else going on there.

Anyway, I'd say we should report this as an issue to the Chrome team. IIRC, they were at least sort of helpful last time we did that, even though it didn't fix the issue in the end.

**Comment by IvanSanchez** [comment] 2018-03-22 08:37
https://github.com/Leaflet/Leaflet/blob/8a009fa662fd42efc3d720ab60d878c245f6e681/src/map/handler/Map.Drag.js#L212

Wait, the inertia offset is already rounded up. WTF?! :confused:

**Comment by IvanSanchez** [comment] 2018-03-22 08:40
![image](https://user-images.githubusercontent.com/1125786/37759779-ef6295a6-2db4-11e8-851d-f61c9de931e2.png)

If the inertia offset is rounded up, why are the `translate3d` transforms fractional?! :confused:

**Comment by perliedman** [comment] 2018-03-22 08:41
@IvanSanchez weird, but at least that look like something _we_ can work on!

**Comment by IvanSanchez** [comment] 2018-03-22 08:48
The rounded-up calls are called just once. I've traced the problem down to 

https://github.com/Leaflet/Leaflet/blob/8a009fa662fd42efc3d720ab60d878c245f6e681/src/dom/PosAnimation.js#L77

The fix would be to somehow pass an option to `PosAnimation` to round the coordinates on every animation frame.

**Comment by Widdershin** [comment] 2018-03-26 04:30
Rounding is not necessarily an ideal solution, because on a retina display you actually have twice the number of physical pixels as what the browser reports, so `translate(0.5px)` will actually have a visual and useful consequence on retina. 

I was able to create a minimal reproducer without using Leaflet.js, so it looks like it's actually a bug in Blink.

I've opened an issue over on the Chromium tracker so hopefully we can get it resolved there:

https://bugs.chromium.org/p/chromium/issues/detail?id=825711&can=2&q=subpixel%20image&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

If you'd like to see this bug resolved I think they like people to star issues to reflect that.

**Comment by Widdershin** [comment] 2018-03-26 04:33
Additionally, I think this issue actually spans beyond zooms, I think it's about any subpixel translation.

I can reproduce this consistently:

1) Open this demo: https://esri.github.io/esri-leaflet/examples/switching-basemaps.html
2) Switch the basemap to "Imagery" to increase the contrast
3) Pan the map to the east. If you finish such that the pan is not a whole number, you'll see gray lines between the basemaps.

**Comment by feature7** [comment] 2018-03-27 09:39
For consideration, the borders even though I don't see them on panning in Firefox 59.0.1 (rpm) they show during the animation on every zoom-operation.

@Widdershin Hi, for retina the physical pixels are calculated to CSS-pixels, and treated as such, so why would you need to take the actual physical pixels into account for the layout? I think that is irrelevant. If `translate(0.5px)` have a visual effect for you is it not because it has been rounded by the layout engine to display as 1 CSS-pixel? https://www.w3.org/TR/css3-values/#absolute-lengths

**Comment by hyperknot** [comment] 2018-03-27 12:02
@Widdershin zoom is only important here, because it's been like this forever for fractional zoom levels. Now this introduced the same bug to integer zoom levels as well.

**Comment by hyperknot** [comment] 2018-03-27 16:18
Hi everyone, I've also commented on the Chrome bug (@Widdershin thanks for reporting), the Chromium team seems to be interested in resolving it, and are asking which was the first version which produces it. Can you help with this? I cannot install old versions of Chrome on macOS, and in a Parallels Virtual Machine the issue is not present.

If you are on a different OS, maybe you can try portable Chrome or something similar to find out which version introduced it. Can you help finding this out?

**Comment by feature7** [comment] 2018-03-28 14:47
@hyperknot 
Hello, sorry I don't know the first version, I downgraded and checked Chromium 61.0.3163.100-1.fc27 and the borders show there too if I do a quick pan and release the mouse button, they show until the animation has ended.

**Comment by Widdershin** [comment] 2018-03-28 21:48
> For consideration, the borders even though I don't see them on panning in Firefox 59.0.1 (rpm) they show during the animation on every zoom-operation.

Sounds like the zoom bug is actually different from the pan bug I reported to the chromium team, sorry for taking over this issue!

**Comment by Widdershin** [comment] 2018-05-01 03:58
Related/possible duplicate of #3575.

Also see the Chromium issue that was raised as a result of that issue.

https://bugs.chromium.org/p/chromium/issues/detail?id=600120

**Comment by lapo-luchini** [comment] 2018-05-01 06:17
Mhh, they upped the priority on July… let's hope.

**Comment by oliverheilig** [comment] 2018-05-05 12:36
What's most frustrating: You see these grid lines in Chrome even together with **Google** maps, and nobody seems to be bothered by this. Just a scaling > 100% for the Windows desktop or the browser and open

https://www.google.de/maps/@54.3061614,2.0559393,5z
![grid lines](https://lh3.googleusercontent.com/_tvEG85GHaWsxg0yxxk15iI_1EMnS2a4y5_BbXgEJc6VG5xBvOWRqbymQK3s8efMv2ElISGDR0X0wo0m-eFsvrYhq7tLg5TGclK7ExCRyMcD1dgX5g2L5ED0BIMQzfbj5V8RXmAQxQ=w2400 "grid lines")

Maybe we are just too pedantic, but a dark theme renders Leaflet almost unusable with Chrome. Switch to the base map 'blackmarble' here

https://ptv-logistics.github.io/xserverjs/boilerplate/Leaflet.1.0.html

This problem doesn't occur with LL0.7 btw

https://ptv-logistics.github.io/xserverjs/boilerplate/Leaflet.0.7.html

So after years of suffering from this issue the only options i see:

1. Make the map background black/dark for dark base maps
```css
.leaflet-container {
    background: #000;
}  
```
2. Use FireFox or Edge 
3. Use Leaflet 0.7

**Comment by hyperknot** [comment] 2018-07-18 11:36
I can confirm that @oliverheilig's example is right, the 1px lines only appear in the 1.0 version, not in 0.7. So it seem that there is a way to solve this Leaflet side. If someone has the energy to find what causes Chrome to introduce the 1px lines in 1.0 and not in 0.7, it might allow a fix.

**Comment by Widdershin** [comment] 2018-08-14 00:12
Latest update to that Chrome issue confirms they have no intention of fixing the issue anytime soon.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/398365/44064694-8ffa37e0-9fba-11e8-850d-f7dff405448c.png">

If anyone wants to fix this, I would recommend running a `git bisect` manually to find the issue.

**Comment by oliverheilig** [comment] 2018-08-23 13:07
I've compared the code of 0.7 and 1.x. For me it looks like 1.x uses nested CSS transforms, which Chrome doesn't handle correctly. I guess this was introduced with the fractional zoom in LL. I'm afraid this can only be resolved by a complete rewrite of the tile-stitching using canvas, like OL does: 

https://ptv-logistics.github.io/xserverjs/boilerplate/OpenLayers3.html

**Comment by perliedman** [comment] 2018-08-27 10:50
There is already a plugin for tile stitching on canvas: https://github.com/Leaflet/Leaflet.TileLayer.NoGap (might or might not be updated to work with latest Leaflet, but it worked at some point).

**Comment by oliverheilig** [comment] 2018-09-23 15:57
Now we have this "experience" also on Firefox (62.0.2) great! So currently the only flawless browsers are IE and edge!

![image](https://user-images.githubusercontent.com/958768/45930012-da48d180-bf59-11e8-8b66-8a45ea1c0c9b.png)

**Comment by meawoppl** [comment] 2019-02-06 21:17
Gross, has any progress been made on this, and/or is there a workaround that is the accepted approach that people are using?

**Comment by oliverheilig** [comment] 2019-03-26 11:28
Looks like we all have to live with it. And also the new chromium-based Edge will inherit this issue. 
![image](https://user-images.githubusercontent.com/958768/54993260-b37b5e80-4fc1-11e9-8818-814c28f17dca.png)

**Comment by oijkn** [comment] 2019-04-07 14:06
From [cmulders](https://github.com/Leaflet/Leaflet/issues/3575#issuecomment-150544739) "hack" here is a good workaround to make the tiles 1 pixel larger, with the side effect that they overlap by 1 px. Besides that the tiles will be slightly enlarged and scaled (by 1px).

```javascript
/* 
 * Workaround for 1px lines appearing in some browsers due to fractional transforms
 * and resulting anti-aliasing.
 * https://github.com/Leaflet/Leaflet/issues/3575
 */
(function(){
    var originalInitTile = L.GridLayer.prototype._initTile
    L.GridLayer.include({
        _initTile: function (tile) {
            originalInitTile.call(this, tile);

            var tileSize = this.getTileSize();

            tile.style.width = tileSize.x + 1 + 'px';
            tile.style.height = tileSize.y + 1 + 'px';
        }
    });
})()
```

**Comment by shodge17** [comment] 2019-11-08 15:41
Just want to say that Oijkn's function above works.  I just copied and pasted it in my code and the white grid lines are gone.  Thanks Oijkn!

**Comment by ebrensi** [comment] 2020-03-03 02:28
The fix works for me too. Thanks @oijkn !  I want to stay posted on this issue though, in case it gets fixed in a future release of Leaflet so I can get rid of that hack.

**Comment by zdila** [comment] 2020-11-06 14:03
I can reproduce this issue on Debian Linux, XFCE, after upgrading to HDPI monitor (4k 32"). Reproducible on Chrome, not in FF.

Sample: https://www.freemap.sk/?map=15/48.687986/20.446608&layers=Z

![2020-11-06_14-54](https://user-images.githubusercontent.com/636095/98374564-232c4900-2041-11eb-8eb5-05c9865dc64b.png)

**Comment by brgrz** [comment] 2021-03-22 17:18
At the moment I only experience this issue on 4K displays with Chrome based browsers. FF seems fine. 

Under same conditions (4K, Chromium browsers) other mapping solution do not seem to suffer from this issue: Google Maps, OL, Mapbox.

So I guess we should be expecting Leaflet to fix this?

**Comment by Widdershin** [comment] 2021-03-26 01:29
Looks like there might be a bit more hope of getting this resolved in Chrome:

 https://bugs.chromium.org/p/chromium/issues/detail?id=600120

<img width="922" alt="Screen Shot 2021-03-26 at 2 28 37 PM" src="https://user-images.githubusercontent.com/398365/112564142-993e1a80-8e3f-11eb-97af-f53175f79125.png">

**Comment by GeomaticaNet** [comment] 2021-07-23 00:19
Any solution?

**Comment by dravnic** [comment] 2022-04-03 08:52
here is a workaround we did based on the idea of increasing tile size. this workaround increase tile size only during animations, so while map is at rest there are no visual glitches due to the minor tile overlap.

for 256px tiles:
`
.leaflet-pan-anim .leaflet-tile,
.leaflet-zoom-anim .leaflet-tile {
    width: 256.5px !important;
    height: 256.5px !important;
}
`

for 512px tiles:
`
.leaflet-pan-anim .leaflet-tile,
.leaflet-zoom-anim .leaflet-tile {
    width: 512.5px !important;
    height: 512.5px !important;
}
`

as tile size is set during layer initialization maybe a general solution would be to setup such css animation override per layer during its initialization?

**Comment by Falke-Design** [comment] 2022-04-03 09:24
I close this because it is a duplicate of #3575.

@dravnic the animation workaround is a good idea, can you please post it in #3575 again.

**Closed by Falke-Design** 2022-04-03 09:24 UTC
Labels: bug

**Comment by moshanghuage** [comment] 2023-07-24 08:28
> .leaflet-pan-anim .leaflet-tile,
> .leaflet-zoom-anim .leaflet-tile {
>     width: 256.5px !important;
>     height: 256.5px !important;
> }

This method actually increases the gap on the Edge browser
