### ISSUE TITLE
Cannot drag panorama viewer <canvas> inside popup

### ISSUE THREAD

**Issue by helmi03** [Leaflet/Leaflet#4960] opened 2016-09-28 00:59 UTC
## How to reproduce
- Leaflet version I'm using: 1.0.0
- Browser (with version) I'm using: Google Chrome 53.0.2785.116
- OS/Platform (with version) I'm using: macOS Sierra
- step 1: open http://playground-leaflet.rhcloud.com/yuq/edit?html,output
- step 2: drag panorama image inside popup
## What behaviour I'm expecting and which behaviour I'm seeing

Can drag panorama viewer. It works perfectly for leafletjs 0.7.7.
## Minimal example reproducing the issue

http://playground-leaflet.rhcloud.com/yuq/edit?html,output

**Comment by perliedman** [comment] 2016-09-28 05:55
The linked playground example loads some resources (https://www.marzipano.net/demos/common/requestAnimationFrame.js, for example) with HTTPS/cert problems, so they refuse to load for me. This unfortunately makes it impossible to see the issue.

**Comment by IvanSanchez** [comment] 2016-09-28 07:30
OK, after browsing to https://www.marzipano.net manually and temporarily accepting the cert (which applies to a different domain name), I can see the bug.

Apparently dragging on the `<canvas>` does not work, but dragging *from* the empty region of the popup container does. Weird.

**Comment by IvanSanchez** [comment] 2016-09-28 07:47
This seems to be caused by calling `L.DomEvent.disableClickPropagation()`  [in `L.Popup._initLayout()`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/Popup.js#L176).

Now we have to see why we did that, and why disabling click propagation *from* the popup container *to the map pane* also disables propagation from children elements under whatever circumstances.

**Comment by IvanSanchez** [comment] 2016-09-28 08:10
We need to check that pointer interactions *inside* popups work well. A better/simpler test case than the panorama scenario might be setting up some [dragula](https://github.com/bevacqua/dragula) examples inside a popup.

**Comment by johnd0e** [comment] 2020-04-13 13:58
Seems like duplicate of #6044.

**Closed by johnd0e** 2020-04-13 13:59 UTC
Labels: bug, needs solution
