### ISSUE TITLE
Add an option CRS to L.TileLayer

### ISSUE THREAD

**Issue by molokovskikh** [Leaflet/Leaflet#3343] opened 2015-03-31 16:34 UTC
Example code:
```js
var map = new L.map("map").setView([55,37], 10); 
L.control.layers(
{
    'Yandex': L.tileLayer('http://{s}.pvec.maps.yandex.net/?l=pmap&x={x}&y={y}&z={z}',{
        crs:L.CRS.EPSG3395,//that's what I would like to
        subdomains:['00','01','02','03','04'],
        attribution: '&copy; <a href="http://yandex.ru/copyright">Яндекс</a>'
    }), 

    'OpenStreetMap':L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a>'
    }).addTo(map)
}).addTo(map);
```
There is a difference between the base layers when switching. 
You need to add functionality presumably L.GridLayer (_reset, _update), so to have a tile layer was binding to the CRS option TileLayer.

**Comment by danzel** [comment] 2015-04-01 02:04
Have formatted your code.
Sort of a dupe of #2553
I have a feeling this was going to be hard to support but can't find the bug I was thinking about. @perliedman should know :)

**Comment by molokovskikh** [comment] 2015-04-01 03:49
I have a <a href='http://jsfiddle.net/yk6nkwqu/5/'>solution</a> to this problem, but I would like to make this functionality was already in the engine without hacks. Preparing a pull-request.

**Comment by perliedman** [comment] 2015-04-01 07:05
Also see #2927 and #3002, which are also discussion of this issue.

While there might be a few use cases for this, in general it's not a good idea to switch CRS on a map, and I have a hard to visualizing how it would work with a single tilelayer having a different CRS.

**Closed** 2015-04-23 10:49 UTC
