### ISSUE TITLE
"Leaflet Quick Start Guide" should offer a simpler Tile Provider

### ISSUE THREAD

**Issue by brunob** [Leaflet/Leaflet#6336] opened 2018-09-07 17:53 UTC
Hi, i've just read someone saying that quick start doesn't work since it use MB tiles with no accessToken defined. See also #6280 & #6268 and as @IvanSanchez said : 

> apparently the mapbox tokens are confusing more people.

I propose to change the base tiles on this example, and maybe it would be better to apply this everywhere MapBox tiles are used in examples pages. Any thought about it ?

**Comment by Shizen** [comment] 2018-09-07 21:30
Serendipitously I happened to be looking at your Quickstart documentation right at this moment, and been having trouble getting it to do anything at all.  I am working in JSFiddle for convenience, which makes this easy to share.  The code doesn't seem to make it past the `L.map('mapid')` call, really.

[JSFiddle of Quickstart](https://jsfiddle.net/0pyvtsob/29/)

I've tried a few different places to work around the access token requirements, since I was just looking to see how hard it was to get leaflet up and running.  Your example also sets options for `id` and `accessToken` passed into the `L.tileLayer()` call, which are not listed in the API docs for [tileLayer](https://leafletjs.com/reference-1.3.4.html#tilelayer).  (`maxZoom` and `attribution` are though).

**Comment by brunob** [comment] 2018-09-08 17:43
PR proposed, i see that others examples using MB tiles could also use other tilesets : mobile, geojson, layers-control, choropleth. Video-overlay can stick on MB tiles i think. Any thought about it ? Should i push in the same PR or in a separate one for each example ?

**Comment by ghybs** [comment] 2018-10-25 03:44
Hi @brunob,

We appreciate your contributions, both the issue and the PR.

I think we all agree about the potential advantages of using OSM tiles in Leaflet code snippets: simplify code (no more `id`, `accessToken` undocumented keys…), less friction (works as-is, not directing to external service, not having to realize that one can change the tile source and having to look for such sources…), etc.

Now my personal view on this is that we face 2 difficulties in switching the Tile provider from Mapbox to OSM:
1. OSM tiles should be used only for testing / small scale usage.
2. Mapbox "implicitly sponsors" Leaflet.

**1. OSM tiles should be used only for testing / small scale usage.**

As [pointed out](https://github.com/Leaflet/Leaflet/issues/6280#issuecomment-412511601) by @perliedman:

> […] as long as it's for testing / small scale usage (see [Tile Usage Policy](https://operations.osmfoundation.org/policies/tiles/)).

And in [switch2osm](https://switch2osm.org/using-tiles/):

> Apart from very limited testing purposes, you should not use the tiles supplied by OpenStreetMap.org itself.

Unfortunately, we all know we are lazy and no longer care once we have a working technical solution:
people forget any associated administrative / legal restriction when upscaling / deploying.

The mere fact that your PR also uses OSM tiles in live examples illustrates this situation:
you may not realize the high traffic on Leaflet pages, which could be considered a "heavy use".

Furthermore:

> Do not hardcode any URL at tile.openstreetmap.org into an app

…so even providing OSM tiles URL in Leaflet website code snippets could be interpreted as a violation.

**2. Mapbox "implicitly sponsors" Leaflet.**

While not explicitly written, Leaflet main author is employed by Mapbox.
Somehow they "agree" that he spends some of his energy (whether at work or free time) on this Open Source project.

Besides, Mapbox provides an access token for Leaflet website live examples, so switching those to OSM is unnecessary (and could be considered a violation of OSM Tile Usage Policy, as already explained above).

**Comment by ghybs** [comment] 2018-10-25 03:48
All that being said, I still understand that the current code snippets give more friction to newcomers than it should be.

@matkoniecz's [proposal](https://github.com/Leaflet/Leaflet/issues/6268#issue-347851810) to use CartoDB basemaps instead sounds a reasonable approach to simplify code (no need for `id` and `accessToken`) while still providing a compliant solution.

**Comment by brunob** [comment] 2018-10-25 09:19
@ghybs just for the "fun" about the high traffic on Leaflet page, you may have seen that https://leafletjs.com/ home page use tile.openstreetmap.org tiles ;)

**Comment by matkoniecz** [comment] 2018-10-25 09:36
PR "Fix #6336 : use openstreetmap tiles in quickstart guide: (#6337) was rejected.

I am not sure why @ghybs kept this issue open.

**Comment by ghybs** [comment] 2018-10-26 02:53
> https://leafletjs.com/ home page use tile.openstreetmap.org tiles ;)

Lol nice catch! :sweat_smile:

> i was proposing osm tiles because _it's not_ a commercial provider, in order to stay neutral […]

I think we all agree as well on this, but the issue is that…

> to promote OSM project

…it is difficult to say we are helping OSM by increasing (directly and indirectly through recommendation) the load on their Tile Servers, whereas they explicitly request not to do so.
By using Mapbox or CartoDB tiles, we are still crediting OSM.

**Comment by matkoniecz** [comment] 2018-10-26 07:49
@ghybs Given that #6337 was rejected for reasons that are unfixable - maybe also close this issue as WONTFIX?

**Comment by ghybs** [comment] 2018-10-28 05:09
Hi @matkoniecz,

Indeed that is the idea, but there is still the point of trying to provide an easier example in quick start tutorial.

Maybe provide several examples with a few providers (Mapbox and CartoDB?), in order to show that Leaflet is provider agnostic and have a simpler example (CartoDB), while still maintaining a reference to Mapbox?

I see that you have also created issue #6383 for the point of using another tile provider on Leaflet home page, thanks!

By curiosity, are you affiliated with OSM?

**Comment by matkoniecz** [comment] 2018-10-28 05:34
> By curiosity, are you affiliated with OSM?

I am active as mapper, in discussions on mailing lists and in some projects like https://github.com/westnordost/StreetComplete or https://github.com/gravitystorm/openstreetmap-carto/

**Comment by brunob** [comment] 2018-10-28 10:45
'k should i take some time to propose another PR adapted to use cartodb tiles or should i just forget about it ?

**Comment by brunob** [comment] 2018-10-28 11:30
FTR as said in https://github.com/CartoDB/basemap-styles

> Limitations: free usage for up to 75,000 mapviews per month, none-commercial services only.

**Comment by ghybs** [comment] 2018-10-29 02:12
Hi @brunob,

> should i take some time to propose another PR adapted to use cartodb tiles

Sure!
What I could imagine for now would be a kind of tabbed examples, with Mapbox by default and CartoDB next.
That way the default display still uses the Mapbox token for Leaflet, but the tutorial provides an alternative for a more simple scheme.
What do you think?

**Comment by brunob** [comment] 2018-10-29 07:43
@ghybs i think we should make it simple, showing mapbox by default will not prevent mistake like #6280

**Comment by johnd0e** [comment] 2021-11-09 13:52
@mourner 
Should we reopen #6337?

**Comment by simonpoole** [comment] 2021-11-28 10:40
> So we may start our "not so heavy" use, and wait for a shrug if what we do is considered as an abuse ? :)

To avoid misunderstandings: reality is that there is no such thing as permission for heavy use, the application will simply be blocked if it is deemed to use too many resources. The "asking for permission" bit was probably intended so that users that were going to be blocked in any case could be informed of the errors of their ways in advance and be pointed to commercial services, as @tomhughes points out that just doesn't work in real life.

**Comment by brunob** [comment] 2021-12-05 18:02
Another case of someone trapped by it on #7817 :\

**Comment by johnd0e** [comment] 2021-12-05 20:38
Tile service is not free. Even OSM. Everyone should understand it.

**Closed** 2022-05-27 08:33 UTC
Labels: docs
