### ISSUE TITLE
DomEvent.off() not working correctly when called with one parameter

### ISSUE THREAD

**Issue by cdawi** [Leaflet/Leaflet#6013] opened 2018-01-18 14:36 UTC
## How to reproduce

- Leaflet version I'm using: 1.3.0
- Browser (with version) I'm using: Chome 63.0.3239.132
- OS/Platform (with version) I'm using: Linux
- Assing event handler on an element using DomEvent.on(element, 'eventType', callback) 
- Remove all event handlers from element using DomEvent.off(element)
- Expect that after firing event, the callback will not be executed. (It is not working)

## Minimal example reproducing the issue

```
var div = document.getElementById('leaflet');
var eventHandler = function(){
  alert('Handler fired!');
}
L.DomEvent.on(div, 'click', eventHandler);
L.DomEvent.off(div);
//now manually click on div element -> alert is shown
```
https://plnkr.co/edit/yQ1GzAFD9oDNqnV0Nhok?p=preview

## Possible solution
I think that problem is in DomEvent.js
```
export function off(obj, types, fn, context) {
(...)
	} else {
		for (var j in obj[eventsKey]) {
                        //this does nothing cause j variable is not parsed
			removeOne(obj, j, obj[eventsKey][j]);
		}
		delete obj[eventsKey];
	}
(...)
```
In this case `j` is a key which isn't event type. It is a event handler id (e.g. resize37_35)
In order to fix it, `j= j.replace(/[^a-z]/g, '')` or something similar.

**Comment by IvanSanchez** [comment] 2018-01-18 14:43
The first parameter to `L.DomEvent.on()` and `L.DomEvent.off()` **must** be an instance of `HTMLElement`. In your case, it's an instance of `L.Map`.

I think you should use `map.on(...)` instead of `L.DomEvent.on(map, ...)`. Or, if deemed necessary, `L.ComEvent.on(map.getContainer(), ... )`. Note how, according to the documentation, the return type of `getContainer` is an `HTMLElement`.

**Comment by cdawi** [comment] 2018-01-19 09:10
I think you are wrong. I've updated plunker to add eventListener on click on div element. Removing all listeners from this div element is not working correctly.
```
var div = document.getElementById('leaflet');
var eventHandler = function(){
  alert('Handler fired!');
}
L.DomEvent.on(div, 'click', eventHandler);
L.DomEvent.off(div);
//now manually click on div element -> alert is shown
```
https://plnkr.co/edit/yQ1GzAFD9oDNqnV0Nhok?p=preview

**Comment by IvanSanchez** [comment] 2018-01-19 09:39
You're right, that problem is now reproducible. New plunker = we can see the problem = :tada:

---

I've looked at this for a couple of minutes, and it seems `addOne()` is storing a reference to the *wrapper* of the event handler 

https://github.com/Leaflet/Leaflet/blob/bb0884873455d01c557a29c34fa03f5f6b1f89e0/src/dom/DomEvent.js#L77

https://github.com/Leaflet/Leaflet/blob/bb0884873455d01c557a29c34fa03f5f6b1f89e0/src/dom/DomEvent.js#L121

...so then `removeOne()` tries to stamp the wrapper **instead** of the original handler...

https://github.com/Leaflet/Leaflet/blob/bb0884873455d01c557a29c34fa03f5f6b1f89e0/src/dom/DomEvent.js#L126

...that causes a double numerical ID at `type`.

That's one part of the problem. The other is that the `off()` takes the *key* of the registered events...

https://github.com/Leaflet/Leaflet/blob/bb0884873455d01c557a29c34fa03f5f6b1f89e0/src/dom/DomEvent.js#L64

...but that key `j` is the event type **plus** a numerical ID. That should be either stripped out, or have some kind of mapping so the code can discern the original event type.

---

This sounds doable, but not completely trivial, and I don't have the time for taking this right now. Any takers.

**Comment by perliedman** [comment] 2018-10-28 11:14
I'm going to close this, since no one seems interested in implementing it, and the docs no longer claim this is possible.

**Comment by johnd0e** [comment] 2020-05-05 09:36
> the docs no longer claim this is possible.

But our code still has some code trying to handle this case: https://github.com/Leaflet/Leaflet/blob/ec35ab52f66c191f7c855583354722c40dcdf239/src/dom/DomEvent.js#L30-L36

As mentioned by @IvanSanchez this code fails.
So we need either to remove it completely, or fix it (which is easy too).

**Closed** 2021-11-05 12:18 UTC
Labels: bug
