### ISSUE TITLE
GridLayer opacity does not work in non-3D environments

### ISSUE THREAD

**Issue by Mr0grog** [Leaflet/Leaflet#4254] opened 2016-02-17 01:04 UTC
This is a pretty similar issue to #4211. When 3D support is disabled (by setting `L_DISABLE_3D` or by running in environments where that's off, such as PhantomJS, where I'm hitting this), GridLayer's `_updateOpacity()` method bails out immediately and never actually sets opacity:

```js
_updateOpacity: function () {
  if (!this._map) { return; }

  // IE doesn't inherit filter opacity properly, so we're forced to set it on tiles
  if (L.Browser.ielt9 || !this._map._fadeAnimated) {
    return;
  }

  L.DomUtil.setOpacity(this._container, this.options.opacity);
  ...
```

Since `_fadeAnimated` is `false` (because of no 3D support), it never gets to setting the opacity. The problem is mainly that `_updateOpacity()` conflates a static opacity with a lot of animation logic.

My naive fix is to move the `_fadeAnimated` check after the initial setting of opacity, separating out the parts that are about the layer's overall opacity from the parts about fading the tiles in:

```js
_updateOpacity: function () {
  if (!this._map) { return; }

  // IE doesn't inherit filter opacity properly, so we're forced to set it on tiles
  if (L.Browser.ielt9) {
    return;
  }
  
  L.DomUtil.setOpacity(this._container, this.options.opacity);

  if (!this._map._fadeAnimated) {
    return;
  }
  
  ...
```

But it certainly seems like a smarter fix would be pull the logic related to fading tiles in out of this method altogether. I think I'd have to spend more time understanding the overall mechanism to figure out the right way to do that, though.

**Comment by IvanSanchez** [comment] 2016-02-17 08:28
@Mr0grog This is an exact duplicate of #4068.

I made #4228 as a fix, but that mysteriously makes the unit tests about opacity fail in PhantomJS :angry:

**Closed by IvanSanchez** 2016-02-17 08:28 UTC

**Comment by Mr0grog** [comment] 2016-02-17 14:37
Oh, wow, I thought I'd looked but completely missed that one. Sorry!

**Comment by IvanSanchez** [comment] 2016-02-17 14:39
@Mr0grog Nevermind ;-)

**Comment by Mr0grog** [comment] 2016-02-17 18:44
@IvanSanchez are you sure that failure's not spurious? The same code is passing on the PR test, just not the one triggered by the push.
