### ISSUE TITLE
GeoJSON Layers are not rendered properly on Map Panning

### ISSUE THREAD

**Issue by ferminarellano** [Leaflet/Leaflet#4771] opened 2016-07-31 06:44 UTC
You can reproduce this problem on your [Interactive Cloropleth](http://leafletjs.com/examples/choropleth.html) example. 

For example you click on Colorado state and drag it all the way to the right border of the map. You release the mouse and then click and drag all the way to the left and half of the overlay dissapears. 

This is only happening when you pan with a click and drag of the mouse. 
![proof](https://cloud.githubusercontent.com/assets/17556629/17275063/d92e915c-56b7-11e6-8b7c-32eca3dbb2fb.PNG)

**Comment by ferminarellano** [comment] 2016-07-31 07:34
I wrote a hack on which I remove my GeoJSON layer and add it again after the dragend event. 
```
map.on("dragend", function (e) {
	mygeojsonlayer.clearLayers();
	mygeojsonlayer = L.geoJson(my_geojson_data);
	mygeojsonlayer.addTo(map);
});
```
I guess this is a small bug easily fixable.

**Comment by yohanboniface** [comment] 2016-07-31 08:22
Duplicate of #4743

**Closed by yohanboniface** 2016-07-31 08:22 UTC
