### ISSUE TITLE
Vectors on SVG renderer not draggable in mobile Safari

### ISSUE THREAD

**Issue by kad3nce** [Leaflet/Leaflet#4070] opened 2015-12-04 04:21 UTC
I've implemented a draggable circle using a combination of mousedown, mousemove, and mouseup events. Of course, these events don't fire on mobile devices. Is it possible to make a Circle draggable on a mobile device?

**Comment by IvanSanchez** [comment] 2015-12-04 08:14
> Of course, [mousedown, mousemove, mouseup] events don't fire on mobile devices.

[Yes they do](https://www.youtube.com/watch?v=wwffqMAS8K8)

**Comment by kad3nce** [comment] 2015-12-09 03:42
@IvanSanchez, does Leaflet fire those events on mobile? I'm using [react-leaflet](https://github.com/PaulLeCam/react-leaflet) and they are firing on desktop browsers, but not on iOS 9 Safari. I'm trying to narrow down if the issue lies in Leaflet or react-leaflet. Thanks for the help!

**Comment by kad3nce** [comment] 2015-12-09 04:25
@IvanSanchez, I just noticed the `needs more info` tag and made [a CodePen](http://codepen.io/kad3nce/full/ZQYNrq/) to reproduce using vanilla Leaflet.

The CodePen loads a map and adds a circle. It binds `circle.on('mousedown', ...)` to show an alert (in my actual code, I'm using a combination of circle.on('mousedown'), map.on('mousemove'), and map.on('mouseup') to make the circle draggable). When clicking the circle in the CodePen on a desktop browser, the alert appears. When tapping the circle in Safari on iOS 9, or while using [Chrome's touch emulation](https://developers.google.com/web/tools/chrome-devtools/iterate/device-mode/device-input-and-sensors#test-touch-input), nothing happens.

I'm assuming that, on mobile, the map's zooming/dragging functionality is swallowing the event before it reaches the circle? Is this assumption correct and by design? If so, do you have any recommendations for working around it?

**Comment by RonnieRen** [comment] 2015-12-09 05:04
circle does not draggable on mobile device, at least, iOS does not.  if you'd like to make it be draggable, looks like you need to implement a similar CircleDrag like MarkerDrag

**Comment by IvanSanchez** [comment] 2015-12-09 08:51
OK, so turns out that Safari does indeed fire `mousedown` events, but **not** on SVG elements (thanks for the codepen, I was able to test easily in an iPad!!). See also https://patrickhlauke.github.io/touch/ and see the events fired when you tap on a `<button>`.

So I'm going to say this is a bug in Webkit. You might wanna try to use a Canvas renderer instead, or hack the events by firing synthetic `mousedown` events, doing something like:

```
var renderer = L.svg();

L.DomEvent.on(renderer._rootGroup, 'touchstart', function(ev) {
  var synth = L.Util.extend({}, ev);
  synth.type = 'mousedown';
  return this.dispatchEvent(synth);
});

var map = L.map({ renderer: renderer, .... });
```

It's very hacky, it has to be very specific (only on mobile Safari, only for SVG), and I really cannot think of a clean way to work around this in the leaflet core. @mourner @yohanboniface: any ideas?

**Comment by IvanSanchez** [comment] 2015-12-09 09:21
Damn, it's not a webkit bug - a minimal leaflet-less test case at https://jsfiddle.net/n3zLrwtf/1/ works as expected.

**Comment by IvanSanchez** [comment] 2015-12-09 09:22
@kad3nce Have you tried using Leaflet 1.0.0-beta? Event delegation there is revamped and it just *might* work.

**Comment by kad3nce** [comment] 2015-12-09 18:40
@IvanSanchez thanks a million for all your work on this! I'll give the beta a try tonight and report back.

**Comment by kad3nce** [comment] 2015-12-09 20:17
@IvanSanchez progress! The events fire on mobile when using 1.0.0 beta 2! I implemented the rest of the code to make the circle draggable. Sadly, the map is now dragged along with the circle. Can I call a method on the map in the circle's `mousedown` handler that will make the map undraggable? I tried `event.originalEvent.preventDefault()` as well as `return false` to no avail.

### [0.7.7 version](http://codepen.io/kad3nce/full/mVJOyd/)

- Works perfectly on desktop browsers (circle is draggable)
- Does not work on mobile (events don't fire for circle)

### [1.0.0 beta 2 version](http://codepen.io/kad3nce/full/bEdwOE/)

- Events fire as expected on both desktop and mobile (yay!)
- Unexpected behavior: Map is dragged along with the circle

**Comment by IvanSanchez** [comment] 2015-12-09 20:31
@kad3nce You're not aware of one of the biggest breaking changes in 1.0.0 from 0.7.x: events are now propagated from layers to the map (there is a mousedown on both the layer and the map). This is now expected behaviour.

It should be possible to stop propagation via `L.DomEvent.stop`, or even disable the map drag handler via `map.drag.disable()`.

**Comment by kad3nce** [comment] 2015-12-10 01:54
Hey @IvanSanchez, [`map.dragging.disable()/enable()` did the trick](http://codepen.io/kad3nce/full/bEdwOE/)! Thanks so much for the help.

Best,
-Jedidiah

**Comment by IvanSanchez** [comment] 2015-12-10 09:23
@kad3nce Nice! 

The issue is still there, but it's pretty complicated to fix and there is a workaround for it, so we probably won't worry about fixing it.

**Comment by kad3nce** [comment] 2015-12-13 20:05
@IvanSanchez I didn't notice it before, but there's still one issue with [the 1.0.0 Beta 2 CodePen](http://codepen.io/kad3nce/full/bEdwOE/). On mobile, or while using Chrome's emulated touch events, the first time you drag the circle, the map is dragged as well. The second time the circle is dragged, the map is not dragged (as expected). Is there something wrong with my code?

```javascript
var center = [51.505, -0.09];
var map = L.map('map').setView(center, 13);
var circle = L.circle(center, 1000).addTo(map);

circle.on('mousedown', function (event) {
  //L.DomEvent.stop(event);
  map.dragging.disable();
  let {lat: circleStartingLat, lng: circleStartingLng} = circle._latlng;
  let {lat: mouseStartingLat, lng: mouseStartingLng} = event.latlng;

  map.on('mousemove', event => {
    let {lat: mouseNewLat, lng: mouseNewLng} = event.latlng;
    let latDifference = mouseStartingLat - mouseNewLat;
    let lngDifference = mouseStartingLng - mouseNewLng;

    let center = [circleStartingLat-latDifference, circleStartingLng-lngDifference];
    circle.setLatLng(center);
  });
});

map.on('mouseup', () => { 
  map.dragging.enable();
  map.removeEventListener('mousemove');
});

L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
```

**Comment by johnd0e** [comment] 2020-04-08 18:44
`mousemove` should not be fired by touch. Except of case where ii is compatibility event fired along with click.

May be we should consider support of pointer* events.
Or at least touch* (#7044).

Perhaps we should close this issue.

**Closed** 2020-04-12 12:00 UTC
Labels: brainmelt, bug, mobile
