### ISSUE TITLE
Map is not visible since today 20.1.2021

### ISSUE THREAD

**Issue by rabbrobert** [Leaflet/Leaflet#7417] opened 2021-01-20 10:18 UTC
The map is not visible since today 20.1.2021

**Expected behavior**
The map should be visible 
**Current behavior**
The map is not visible in  Germany, Darmstadt.

**Environment**
- Leaflet version:  
- Browser (with version): Chrome  Version 86.0.4240.183,      Firefox 72.0.2 (64-bit
- OS/Platform (with version):  Windows 10,   Ubuntu 16.04

Thank you in advance,
Robert Rabb

**Comment by treziac** [comment] 2021-01-20 11:22
Same here

This seems to come from the tileLayer I am using

ihttps://api.tiles.mapbox.com/v4/mapbox.streets/1/1/1.png?access_token=XXX
was working before, but is now returning 

`{
"message": "Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"
}`

And using an other tileId as 
https://api.tiles.mapbox.com/v4/mapbox.mapbox-streets-v7/1/1/1.png?access_token=XXX

fixes the issue

**Comment by johnd0e** [comment] 2021-01-20 11:24
Duplicate of #7173.

**Closed by johnd0e** 2021-01-20 11:24 UTC
