### ISSUE TITLE
Click event not fired anymore after boxzoom

### ISSUE THREAD

**Issue by XellossT** [Leaflet/Leaflet#3208] opened 2015-02-06 13:38 UTC
Hi,

I have an application that use the boxzoom and the event _fireMouseEvent and after using the boxzoom the mouseEvent (in my case click element) is not fired anymore.

For now I found where the problem is : when leaflet start rendering the boxzoom element he is doing : 	this._moved = true; (line 7435)
But at the end of the boxzoom he never pass this option to false. (_finish: function)

So  at the end of the _finish function i added : 
```javascript
 var self = this;
     setTimeout(function() {self._moved = false;},0);
```
It works fine after.

**Comment by mourner** [comment] 2015-02-06 13:46
I remember a reported issue about the opposite — a click event after boxzoom was considered a bug. Would your use case be satisfied with a new `boxzoom` event? What's your use case specifically?

**Comment by XellossT** [comment] 2015-02-06 14:13
I will try to explain specifically my problem.

I have an object that allow the user to click on it to do something.
I also use the boxzoom to select element on the map.

At the begginning all is fine, the event Click works fine, but after I use a boxzoom on the map my object are not clickable anymore.

To test it put a console.log in _fireMouseEvent in Leaflet: 
```javascript
	_fireMouseEvent: function (obj, e, type, propagate, latlng) {
		type = type || e.type;

		if (L.DomEvent._skipped(e)) { return; }
		if (type === 'click') {
			if (!e._simulated && ((obj.dragging && obj.dragging.moved()) ||
			                      (this.boxZoom && this.boxZoom.moved()))) { return; }
			obj.fire('preclick');
                       console.log('preclick');
		}
```

At first when i click on the map the event (obj.fire('preclick')) is fired. After a boxzoom action, the event ('preclick') is not fired anymore.

**Comment by jfirebaugh** [comment] 2015-02-06 23:34
Duplicate of #3026.

**Closed by jfirebaugh** 2015-02-06 23:34 UTC
