### ISSUE TITLE
track the marker when tabbing through them on the map

### ISSUE THREAD

**Issue by adspuma** [Leaflet/Leaflet#3440] opened 2015-05-08 00:10 UTC
Hi experts

When I use the tab key on keyboard to tab through the markers on the map, how could I know which marker get focus and was tabbed into? What attribute I could track for that marker? Thanks for your answer!

**Comment by IvanSanchez** [comment] 2015-05-08 06:56
Duplicate of #3429. Just attach event handlers to each marker's icon.

**Closed by IvanSanchez** 2015-05-08 06:56 UTC

**Comment by adspuma** [comment] 2015-05-08 17:43
Hi Ivan
Thanks for your prompt reply! I am trying to do this job.
var geoJsonLayer = new L.GeoJSON(geoJsonData, {
				pointToLayer : function(feature, latlng) {
					marker = L.marker(latlng, {
						title : feature.properties.tooltip,
					});
					L.DomEvent.on(marker._icon, 'focus', function(ev) {
						alert(marker._leaflet_id);
					});
					return marker;
				}
			});
			map.addLayer(geoJsonLayer);
It didn`t work. It seems before adding the geoJsonLayer or a single marker to the map, we can`t attach event handlers to each marker`s icon. If like that, how could I iterate the geoJsonLayer after adding it to the map to retrieve each marker and attach the event handlers.

Thanks so much!

**Comment by IvanSanchez** [comment] 2015-05-08 19:58
```js
var layer = L.geoJson({}, {pointToLayer: ...} );
layer.addTo(map);
layer.addData(json);
```

**Comment by adspuma** [comment] 2015-05-08 20:54
Hi Ivan
Do you mean like this?

var layer = new L.GeoJSON(json, {
pointToLayer : function(feature, latlng) {
marker = L.marker(latlng, {
title : feature.properties.tooltip,
});
L.DomEvent.on(marker._icon, 'focus', function(ev) {
alert(marker._leaflet_id);
});
return marker;
}
});
layer.addTo(map);
layer.addData(json);

It doesn`t work.

**Comment by IvanSanchez** [comment] 2015-05-08 21:07
Create the geojson layer with *no data*, add it to the map, then add the data.

**Comment by adspuma** [comment] 2015-05-08 21:38
I am sorry, Ivan. It still doesn`t work. Below is my source code. Please let me know where is wrong.

	var layer = new L.GeoJSON({},{
				pointToLayer : function(feature, latlng) {
					marker = L.marker(latlng, {
						title : feature.properties.tooltip,
					});
					marker.on('click', function(e) {
						
					});
					L.DomEvent.on(marker._icon, 'focus', function(ev) {
						
					});
					return marker;
				},
				onEachFeature : function(feature, layer) {
					layer.bindPopup(feature.properties.popup);
				}
			});
			layer.addTo(map);
			layer.addData(json);
