### ISSUE TITLE
Slippy-map is blurry in Chrome on Linux

### ISSUE THREAD

**Issue by Brianetta** [Leaflet/Leaflet#3697] opened 2015-07-30 21:11 UTC
Previously logged on the OpenStreetmap tracker: https://trac.openstreetmap.org/ticket/5340

They sent me here, telling me it's probably a Leaflet bug. I don't know what Leaflet does specifically, but I'm happy to answer questions.

Using Chrome version 44.0.2403.107 (64-bit) on Ubuntu Linux.

When browsing the regular slippy map, the tiles appear blurry. When I change the zoom level, they are clear for a split second, but then it looks like anti-aliasing is performed, and the map blurs.

Here's an example of the blur:
![Screenshot](http://i.imgur.com/YWapoO4.png)
The left hand part of the image is the slippy map. The right hand part is that same tile, after a right click and "Open image in new tab". It is much clearer, despite appearing to be at the same scale.

The image is simply a cropped screenshot, with the tile's browser window being positioned above the slippy map on screen.

It doesn't matter which render I choose in the layers menu, they all behave like this. In Firefox, the slippy map's quality is much, much better.

**Comment by yohanboniface** [comment] 2015-07-30 21:14
Are you sure your browser is not zoomed in some way?

**Comment by mourner** [comment] 2015-07-30 21:14
Is this reproducible in Leaflet 1.0 b1?

**Comment by Brianetta** [comment] 2015-07-30 21:16
The browser is most definitely not zoomed in any way. Both halves of that screen shot are browser windows.

I was using OpenStreetmap.org - is there any way for me to attempt to reproduce this in a different version? I can visit another mapping application with my browser, if there is one.

**Comment by yohanboniface** [comment] 2015-07-30 21:20
Can you inspect the `img` element of one tile and check for the `width` attribute value in the computed style tab?

**Comment by Brianetta** [comment] 2015-07-30 21:21
I'll try.

**Comment by Brianetta** [comment] 2015-07-30 21:25
Here's the HTML element
```html
<img class="leaflet-tile leaflet-tile-loaded" 
src="http://a.tile.thunderforest.com/cycle/16/32478/20736.png"
 style="height: 256px; width: 256px; left: 527px; top: 59px;">
```

and here's the computed CSS:
```css
-webkit-user-drag: none;
-webkit-user-select: none;
border-bottom-color: rgb(34, 34, 34);
border-bottom-style: none;
border-bottom-width: 0px;
border-image-outset: 0px;
border-image-repeat: stretch;
border-image-slice: 100%;
border-image-source: none;
border-image-width: 1;
border-left-color: rgb(34, 34, 34);
border-left-style: none;
border-left-width: 0px;
border-right-color: rgb(34, 34, 34);
border-right-style: none;
border-right-width: 0px;
border-top-color: rgb(34, 34, 34);
border-top-style: none;
border-top-width: 0px;
box-sizing: border-box;
color: rgb(34, 34, 34);
cursor: -webkit-grab;
display: block;
filter: none;
font-family: 'Helvetica Neue', Arial, Helvetica, sans-serif;
font-size: 12px;
font-style: normal;
font-variant: normal;
font-weight: normal;
height: 256px;
left: 527px;
line-height: 18px;
max-width: none;
opacity: 1;
position: absolute;
text-align: left;
top: 59px;
transition-delay: 0s;
transition-duration: 0.2s;
transition-property: opacity;
transition-timing-function: linear;
visibility: visible;
width: 256px;
```

**Comment by yohanboniface** [comment] 2015-07-30 21:32
Can you load this jsfiddle which is running on master, and check if tiles are blurry too: http://jsfiddle.net/skalb/otwgyutn/3/

Also: same behaviour on Chromium? Can you check without any addon?

I've Chrome `Version 44.0.2403.125 (64-bit)` on Ubuntu but can't reproduce naively.

**Comment by Brianetta** [comment] 2015-07-30 21:36
That fiddle is nowhere near as blurry. I'm just installing Chromium.

**Comment by Brianetta** [comment] 2015-07-30 21:44
Chromium Version 43.0.2357.130 Ubuntu 14.04 (64-bit)

Same Google sign-in, same extensions loaded as a result. Looks loads better in that than Chrome 44.

**Comment by mourner** [comment] 2015-07-30 21:47
@Brianetta what's the computed transform value for the `map-pane` element in the blurry version?

**Comment by Brianetta** [comment] 2015-07-30 21:50
It's `transform: matrix(1, 0, 0, 1, -17, -40);`

**Comment by Brianetta** [comment] 2015-07-30 22:54
I've attempted to reset all of Chrome's settings by shutting it down and removing the .google-chrome directory. While it greeted me as a new user on the next start-up, the blurry effect in OpenStreetmap.org was still seen.

**Comment by Gp2mv3** [comment] 2015-09-25 07:55
I've the exact same problem with OpenStreetMap. The issue occures in my Cordova app and also in Chrome. My version of leaflet is v0.75.

**Comment by perliedman** [comment] 2015-09-25 13:12
Sounds awfully similar to #3297.

@Brianetta do you by any chance have multiple monitors with different DPI settings? I've seen similar issues in Chrome in those cases.

**Comment by perliedman** [comment] 2015-09-25 13:23
FWIW, I see blurry maps on Chrome/Ubuntu, but it's because of the display scale factor being set to 1.5 on one of my monitors (since it's high DPI/"retina"). I don't think there's much Leaflet can do about this, since I've more or less asked all applications to scale their content.

@Brianetta do you have any similar settings?

**Comment by Gp2mv3** [comment] 2015-09-25 13:27
I think it has nothing to do with the screen settings themselves as I have
the same issue on Android.

**Comment by perliedman** [comment] 2015-09-25 14:07
@Gp2mv3 is it possible that this is because you have a high DPI Android device and the tiles are scaled up? (Without scaling, text on low-dpi tiles appears very tiny).

On my Android/Chrome, openstreetmap.org does indeed appear a bit blurry, but I'm pretty certain it is because of scaling; using for example Mapbox's @2x tiles solves the problem.

You can check this with, for example:

```
alert(window.devicePixelRatio);
```

**Comment by Gp2mv3** [comment] 2015-09-25 14:59
Maybe you're right because it's a Nexus 5 and OpenStreetMap seems to have
the same behavior.

I'll check with Mapbox on Monday.

**Comment by Brianetta** [comment] 2015-09-25 15:04
I'll check out the DPI settings when I get home this evening. I'm not aware of such settings, and have never needed to customise them. I have only one monitor. Other applications don't share the issue, but I'll explore any avenue.

**Comment by perliedman** [comment] 2015-10-02 06:50
@Gp2mv3 @Brianetta any news on this?

**Comment by Gp2mv3** [comment] 2015-10-04 09:58
I switched to mapbox with 2x parameter and the map is not blurry anymore.
But why isn't the dpi detected by leaflet and then it calls the right
tiles?

It can be really convenient!

**Comment by perliedman** [comment] 2015-10-04 11:32
The `@2x` extension is a convention and not a spec that all tile services follow, so I don't think there's anything Leaflet can do automatically.

There is the [`detectRetina`](http://leafletjs.com/reference.html#tilelayer-detectretina) option for tile layers, which should also prevent blur and works for all tile sets, but doesn't as good results.

**Comment by mourner** [comment] 2015-10-04 16:45
One convenient thing Leaflet has is `{r}` token in the tile urls which gets replaces with `@2x` in case of retina, and otherwise an empty string.

**Comment by mourner** [comment] 2015-10-07 10:56
Are there any next actions for this issue on the Leaflet side?

**Comment by perliedman** [comment] 2015-10-07 12:13
Closing for now.

We should re-open if the map is still blurry when `window.devicePixelRatio` is 1 or when high-DPI tiles are used.

@Brianetta feel free to add more info if you still believe this is an issue in Leaflet!

**Closed by perliedman** 2015-10-07 12:13 UTC
Labels: bug, needs more info, stable

**Comment by Brianetta** [comment] 2015-10-07 12:17
Will do, but right now I don't feel that it really is.
