### ISSUE TITLE
White tiles overlay entire page after drawing ~200 markers

### ISSUE THREAD

**Issue by dvlahovski** [Leaflet/Leaflet#6132] opened 2018-04-10 13:49 UTC
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Chrome 63.0.3239.132 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: Ubuntu 14.04 64 bit
- step 1: Plot ~200 markers on the map.
- step 2: Hover mouse over the page. White tiles appear over the contents of the page.

## What behaviour I'm expecting and which behaviour I'm seeing
Expecting: Normal behaviour.
Seeing: White tiles appear over the contents of the page.
https://imgur.com/a/uoqcN - see first image.

## Minimal example reproducing the issue
https://plnkr.co/edit/KrgvoR3FxxMxRgUsyaMf?p=preview

## Research I've done so far
Looked though Leaflet bugs.
Looked (not thoroughly) through Chrome bugs.
Tested on other versions of Chrome:
60.0.3112.113 - reproduced.
63.0.3239.108 - not reproduced.
65.0.3325.181 - reproduced on Ubuntu 14.04, not reproduced on Windows 7, OS X, Ubuntu 14.04 (a different PC).
Tested on Firefox - not reproduced on any version I could get my hands on.
Turned-on Chrome rendering devtool:
https://imgur.com/a/uoqcN - see second image.
I think that the red color means OOM tiles, which sounds strange, because I have plenty (4 GB) of RAM free. (https://cs.chromium.org/chromium/src/cc/debug/debug_colors.cc?q=f:debug_colors.cc&sq=package:chromium&l=124)

**Comment by IvanSanchez** [comment] 2018-04-10 14:06
Cannot reproduce on Chromium 66.0.3359.26 on Debian (with a Nvidia GT graphics card). :neutral_face: 

BTW, what's your video hardware? It's a long shot, but this *might* be related to the GPU running out of GPU memory.

**Comment by dvlahovski** [comment] 2018-04-11 07:40
@IvanSanchez 
My CPU is:
> Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz

And I use the integrated GPU:
> 4th Generation Core Processor Family Integrated Graphics Controller

For the GPU memory - chrome can show how much GPU memory is allocated, and I didn't see it go past ~30 MB. See first photo - https://imgur.com/a/N1fbt.

@designgears 
After disabling hardware acceleration, the problem is still present.
See second and third photo - https://imgur.com/a/N1fbt.


BTW after disabling the hardware acceleration, Chrome needed to relaunch and it updated to 65.0.3325.181, and the problem is still present with and without hw accel.

**Comment by dvlahovski** [comment] 2018-05-17 11:14
Ping? :)

**Comment by mourner** [comment] 2018-07-27 14:46
Closing as it's likely a GPU/browser bug we have no control over.

**Closed by mourner** 2018-07-27 14:46 UTC
Labels: needs more info
