### ISSUE TITLE
getBounds() returns wrong longitudes at 0 zoom

### ISSUE THREAD

**Issue by Bobinhos** [Leaflet/Leaflet#4721] opened 2016-07-11 12:40 UTC
Hello! Version Leaflet 0.7.7 and Leaflet 1.0.0-rc1.

At 0 zoom scale and when the whole world can be seen, getBounds() returns wrong longitudes.

Expected: 
- southWestLng: **-180**
- northEastLng: **180**

[jsfiddle](https://jsfiddle.net/Lgp43vv8/1/) (just drag the map)

**Comment by IvanSanchez** [comment] 2016-07-11 12:47
[Same, in playground](http://playground-leaflet.rhcloud.com/zoq/edit?html,output)

I think this is the current behaviour is the expected one. You might want to intersect your bounds with the CRS limits manually. Having `LatLngBounds` intersect the CRS bounds automatically might create more problems (specially for stuff crossing the antimeridian).

**Comment by Bobinhos** [comment] 2016-07-11 13:16
According to [API Reference](http://leafletjs.com/reference.html#map-getbounds) it _returns the LatLngBounds of the current map view_. I see the whole world, so it's expectable to get **-90,-180** ; **90,180**.

I use server clustering and send getBounds() result to the server. How can I know, if the user wants to see the whole world?

Check google behavior on [jsfiddle](https://jsfiddle.net/h1xgz6a9/) (just drag the map)

**Comment by IvanSanchez** [comment] 2016-07-11 13:28
> it returns the LatLngBounds of the current map view. I see the whole world, so it's expectable to get -90,-180 ; 90,180.

Nope. The map wraps, so you're seeing *more* than the whole world.

**Comment by ghybs** [comment] 2016-07-11 13:40
Hi,

As a side note, notice that you will **never** reach -90 / +90 degrees latitude, because of the exponential term in the Web Mercator projection… :-)

This is also what you get in your JSFiddle with Google Maps.

**Comment by Bobinhos** [comment] 2016-07-11 13:44
> As a side note, notice that you will never reach -90 / +90 degrees latitude, because of the exponential term in the Web Mercator projection… :-)

Yeah, I know it. But this topic is about longitude ;-)

**Comment by Bobinhos** [comment] 2016-07-11 13:56
> Nope. The map wraps, so you're seeing more than the whole world.
If I see more, so why I never get the longitude limits? 

It's always less than maximum longitude, and always more than minimum one. And its not the little math error. Seeing the whole world I get longitudes like -163.828125 / 134.29687499999977, and according to this I can't see the huge piece of Earth.

**Comment by ghybs** [comment] 2016-07-11 15:43
> Seeing the whole world I get longitudes like -163.828125 / 134.29687499999977

I guess you are talking about the `wrap()` -ped longitude values in your JSFiddle?

In that case, it seems to me that it is also the expected behaviour of [`wrap()`](http://leafletjs.com/reference.html#latlng-wrap) method:
> Returns a new LatLng object with the longitude wrapped around left and right boundaries (-180 to 180 by default).

They are wrapped, not capped.

Besides, wrapping individually your `LatLng` variables does not guarantee that their order will be kept: notice how sometimes your wrapped West value is higher (i.e. more East) than the East one (i.e. more West)… Your Google Maps example exhibits a similar "bug" (go to zoom level 1).

You could imagine a workaround where you simply evaluate if you see more than an entire world (i.e. more than 360 degrees in longitude) and return [-180; 180] in that case.

Modified JSFiddle: http://jsfiddle.net/Lgp43vv8/2/

But you still may have longitudes outside [-180; 180], when you are above the International Date Line.
Or combine with `wrap()`, at the expense of possibly inverted West and East.

**Comment by IvanSanchez** [comment] 2016-08-09 09:03
Not really a bug (and Leaflet needs the values it's providing right now), so closing it. Developers are free to clamp/wrap the longitudes themselves.

**Closed by IvanSanchez** 2016-08-09 09:03 UTC
Labels: needs discussion
