### ISSUE TITLE
L.canvas() render forgets about zIndex

### ISSUE THREAD

**Issue by jockerfox** [Leaflet/Leaflet#8224] opened 2022-05-10 14:12 UTC
Hi all.
My application uses polygons and circles with the L.canvas() option enabled.
The polygons and circles are grouped in layerGroups. Each Layer has a different zIndex.
Finally the polygons are in a different Pane than the circles.

Example:

```
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css" integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js" integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ==" crossorigin=""></script>
  </head>
  <body style="margin:0; border: 0; padding:0; content: 0;">
  <div id="mapid" style="width: 100%; height: 666px;"></div>

  <script>
    var map = L.map('mapid', {}).setView([43.5, 11.5], 10);
    var LayMap = L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {zIndex:1, minZoom: 2, maxZoom: 18, zoom: 8, doubleClickZoom: false, id: 'mapbox/streets-v11', tileSize: 512, zoomOffset: -1, accessToken: 'YOUR-TOKEN'}).addTo(map);

    var myRenderer = L.canvas();
    map.createPane("PanPolyline").style.zIndex = 511;
    map.createPane("PanCircle").style.zIndex = 512;
    var LayerGroupPolyline = L.layerGroup();
    var LayerGroupCircle = L.layerGroup();

    L.polygon([[43,11],[44,11],[44,12],[43,12]], { renderer:myRenderer, pane:'PanPolyline' }).bindPopup("Polygon").addTo(LayerGroupPolyline);
    L.circleMarker([43.5,11.5], { renderer:myRenderer, pane:'PanCircle' }).bindPopup("Circle").addTo(LayerGroupCircle);

    map.addLayer(LayerGroupCircle);
    map.addLayer(LayerGroupPolyline); //<- HERE IS THE PROBLEM ! LayerGroupPolyline hides LayerGroupCircle despite zIndex saying otherwise !

  </script>
  </body>
</html>
```

I noticed that the mouse click event is received ONLY by the last added Layer (or better PanCircle) ! Hiding the ones below even though the zIndex is different.

Resuming the example, the Circle does not receive the click event because the Polygon (or better the PanCircle) blocks the click event and the circle remains hidden to the mouse events despite the PanCircle.zIndex > PanPolyline.zIndex !

I know about the existence of "eventForwarder" (https://github.com/danwild/leaflet-event-forwarder), but this PlugIn handles only one Layer, and I need many more Layers.

The problem with my application is that Layers will be added and removed at the user's discretion. This means that whenever the user hides or shows a Layer, my application has to remove ALL the Layers every time and add them again so that the zIndex I want is respected.

Will this problem be fixed in 1.8.1 ?
Or do we have to give up ?

Thanks.

Leaflet is a beautiful project!
;-)

**Comment by IvanSanchez** [comment] 2022-05-10 15:11
Duplicate of #6205 / #5739. Should be covered by  #6012 as well.

**Closed by IvanSanchez** 2022-05-10 15:11 UTC

**Comment by Falke-Design** [comment] 2022-05-10 17:24
@IvanSanchez should not one of the issues are open? Else we don't know that this bug ist still there

**Comment by IvanSanchez** [comment] 2022-05-10 18:08
> @IvanSanchez should not one of the issues are open? Else we don't know that this bug ist still there

I... guess? My understanding is that the old reports were closed as "won't fix", but it might be a good idea to file a clean new one and put it in the "2.0" bucket.
