### ISSUE TITLE
Map stuck until all tiles loaded

### ISSUE THREAD

**Issue by lxbarth** [Leaflet/Leaflet#3740] opened 2015-08-12 17:52 UTC
All map interaction is stuck as long as tiles are loading. I'm using the current version loading from `http://leafletjs.com/dist/leaflet.js`.

This bug is particularly prominent on `Chrome 44.0.2403.155 (64-bit) / Mac OS X` but I can also see some of this behavior on `Firefox 39.0.3 / Mac OS X`.

I can confirm the same behavior with Mapbox.js `v2.2.1`.

Here you can see how panning is stuck until all tiles load. Also zooming is stuck in such a situation.

![leafletstuck](https://cloud.githubusercontent.com/assets/98233/9231911/b72f8c80-40f8-11e5-8e10-549999ef7085.gif)

**Comment by IvanSanchez** [comment] 2015-08-12 17:54
Duplicate of #3685

**Closed by IvanSanchez** 2015-08-12 17:54 UTC

**Comment by lxbarth** [comment] 2015-08-12 17:56
:+1:
