### ISSUE TITLE
Page hangs when there are 1000's of layers

### ISSUE THREAD

**Issue by swaroop-invn** [Leaflet/Leaflet#8402] opened 2022-08-17 16:03 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Add 1000's of layers to the leaflet map
Page hang and not responsive - not able click, drag or anything.

Thanks for the help!

### Expected behavior

Page should not hang If there are N number of layers

### Current behavior

Page hangs when there are 1000's of layers in the map. As to add all the Features to the feature group I need to loop the geojson data.
Not able to click or drag the map because the page is hang.

### Minimal example reproducing the issue

It is internal Application, Sorry No link

### Environment

Leaflet version: 1.6.0
Browser: Chrome Version 104.0.5112.81
OS: Windows and Android

**Comment by IvanSanchez** [comment] 2022-08-17 16:21
Duplicate of https://github.com/Leaflet/Leaflet/issues/6314

**Closed by IvanSanchez** 2022-08-17 16:21 UTC
Labels: bug, needs triage
