### ISSUE TITLE
Problem opening popup on iOS

### ISSUE THREAD

**Issue by tikky** [Leaflet/Leaflet#7487] opened 2021-03-01 13:17 UTC
Hello,

I am experiencing a problem/bug with Leaflet 1.7.1 and iOS when trying to open a marker with popup.

**Steps to reproduce**
- create easy map with one marker and popup (closed popup)
- try to open map on iOS/iPhone and try to click on marker, then you can see the problem that popup is blinking and is hard to open it. After 2-3 click it is possible to open the marker properly

**Expected behavior**
- popup open

**Current behavior**
- popup open with blinking, need 2-3 click every time when page is opened/refreshed

Pls take a look at atached video - **keeps blinking when trying to open a popup**:
https://user-images.githubusercontent.com/546755/109501967-a6622680-7a98-11eb-9a9d-6d12c8860e4d.mp4

**Environment**
- Leaflet version: problem is visible on Leafle 1.7.1 and also on Leaflet 1.8-dev (as per 2021-03-01 13:00 UTC)
- Browser iOS Safari
- OS/Platform (iPhone 11):

**Additional context**
**Works fine on older Leaflet - for example 1.5.1 works fine, 1.6.1 works also ok**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ x] this example is as simple as possible
- [ x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment] 2021-03-01 15:24
Duplicate of #7430 / #7330 / #7255.

**Closed by IvanSanchez** 2021-03-01 15:24 UTC
