### ISSUE TITLE
custom image coordinate system issue

### ISSUE THREAD

**Issue by wouwei** [Leaflet/Leaflet#3787] opened 2015-08-28 11:52 UTC
Greetings Mourner and Perliedman,
First , thanks a lot for your great and elegant solution ! 

And since it is a great solution, i'm trying to push the limits of it . =)
I have a flat  image which makes around 360k X 385k. 
i did the basic implementation with LeaftLet 1.0 beta , that you can find a bit everywhere : 

```javascript
var map=L.map('main',{maxZoom :11,minZoom:4, crs: L.CRS.Simple} ).setView([0,0],11); 
var southWest = map.unproject([0,385981],map.getMaxZoom());
var northEast = map.unproject([361939,0],map.getMaxZoom());
map.setMaxBounds(new L.LatLngBounds(southWest,northEast));
L.tileLayer('quadtree/l{z}/{y}/{z}_{y}_{x}.jpg',{attribution:"test"}).addTo(map);
```

>A zooming  action will put you on the wrong coordinates . 

I noticed with these settings two things, with MAX zoom at start, and an expected view set to the top left of the image : 
1. reference point  in  lng/lat (0,0) is on the top left of the document, not the top/left of the first tile of the image. the first tile of the image have a margin-left and top of 300px , something like that.
2. lng/lat (-1,1) is fixed on the top left corner of your image , or your first tile .
3. zooming out will transform the coordinate system by 2^(zoom). The top left coordinate of the image will be lng/lat (-1,1), then (-2,2) then (-4,4) then (-8,8) , then 16 32 64... 

I'm digging up this issue since i really need both pixel and geo coordinates . I've got a few directions in mind  to explore , like : 
- basics : do i use the right RCS ? 
- in concept , does the global coordinate system is fixed at the top left corner of the tiled image ? 
- did i reversed the zoom ?

**Comment by mourner** [comment] 2015-08-28 12:07
cc @perliedman

**Comment by wouwei** [comment] 2015-08-28 12:23
images added to show : 
![zoommax](https://cloud.githubusercontent.com/assets/5656312/9546099/32ed616e-4d90-11e5-8470-b531892a363d.jpg)

![twotimeszoom](https://cloud.githubusercontent.com/assets/5656312/9546106/3b3dbd28-4d90-11e5-9aad-7d2b267abcf8.jpg)

**Comment by perliedman** [comment] 2015-08-28 14:51
I notice in your code you do `.setView([0,0],11)` - that sets the map's center to LatLng (0,0) - although a bit hard to tell from the screenshots, it look like that might be what you are seeing. Might that be the case?

I don't think you should worry too much about the `margin-left` etc., unless you really have to. If you are interested in pixel coordinates, you should use [`project`](http://leafletjs.com/reference.html#map-project), which will give you absolute pixel coordinates.

Does this help, or did I misunderstand the problem?

**Comment by wouwei** [comment] 2015-08-28 15:03
hi perliedman , i'll try ```project``` as you says and test with another ```.setView()```.
the pictures above are just what you see when you launch the app , and after clicking zoomout 2 times . 

what bugs me the most was this changing in lng/lat coordinates for a same point when you zoom .

Plus after restesting , full zoom out then full zoom in , i was expecting at least the same pixel ```e.layerpoint``` on mousemove  or geo coordinates ```e.latlng``` , but that was not the case. 

Anyway , have a good week end ! i'll come back on monday to tell you about the new tests. 
Regards,

**Comment by perliedman** [comment] 2015-08-28 20:54
Ok...

Looking a bit closer at this, the coordinates in your screenshots doesn't make sense to me: in the upper left corner, you've written (0,0), but in the image corner you've written a coordinate with a negative x-coordinate, implying that the x axis is directed to the left. Is this actually what you're seeing?

I guess you might not be able to publish your huge image, but a jsfiddle or similar example that shows of the problem would be of great help, I think.

**Comment by wouwei** [comment] 2015-08-31 10:32
so far this morning : 
correcting the coord issue : sorry i mismatched LNG/LAT ....
![zoommax2](https://cloud.githubusercontent.com/assets/5656312/9576731/effc93fa-4fda-11e5-8141-9485a9be0dfc.jpg)

this week end i tested with a mars topographic map ( .cub => preparing => .tif =>  GDAL2TILE => an Y axis flip => leaflet ) . the coordinates system works fine in leaflet !

now i see that the quadtree used in the example above have non regular tiles .. the tiles on the right side of the original image as the tiles on the bottom side of the original image have different sizes . 
I'm remaking the tiling of the quadtree in the same condition as for the mars map , to see if it passes. ( it just takes time, since the original image > 15Go ) .

**Comment by IvanSanchez** [comment] 2015-08-31 10:44
@wouwei Can you please try to use a [graticule](http://leafletjs.com/plugins.html#synthetic-overlays) on your map? It would make much easier to see what's going on.

**Comment by perliedman** [comment] 2015-08-31 11:11
I made a JSFiddle, trying to reproduce the problem: http://jsfiddle.net/dyn7s8c6/1/

I added a marker that starts at (0, 0), you can drag it and the marker's position will be logged, both latlng and pixel coordinate.

@wouwei I can't really see any obvious problem here, and it doesn't really look like the screenshots you've made - anything I'm missing here?

**Comment by perliedman** [comment] 2015-08-31 11:15
I made this fiddle to experiment, and it looks pretty much as I would expect: http://jsfiddle.net/dyn7s8c6/1/, both lat/lng and projected pixel coordinates.

@wouwei Looks like this is an issue with the tiles, no? Can we close this issue?

**Comment by wouwei** [comment] 2015-08-31 13:39
@perliedman yes , I think you can close the issue. I had exactly the same result as your fiddle with the mars map done this week end ... 
Sorry to have bothered you, and thanks a lot for the support !

By using IvanSanchez idea , ( see below ) , it seems like the quadtree given to me do not follow the normal pyramidal zoom logic , hence gibberish coordinates.

green leaf : coord (-3,3) lng/lat , Max zoom = 8;
orange leaf : coord(-6,6) lng/lat , zoom = 7;
red leaf : coord(-12,12) lng/lat , zoom = 6;
graticule interval : 1 .

![reticule_green](https://cloud.githubusercontent.com/assets/5656312/9579890/fb0c8c30-4ff5-11e5-96c3-48031a356bf1.png)
![reticule_orange](https://cloud.githubusercontent.com/assets/5656312/9579895/011b0e3a-4ff6-11e5-8887-9efb03520cb4.png)
![reticule_red](https://cloud.githubusercontent.com/assets/5656312/9579897/06d4445e-4ff6-11e5-8744-a9f5339f0f31.png)

**Closed** 2015-08-31 13:40 UTC
