### ISSUE TITLE
Removed Path with mouseout throws error

### ISSUE THREAD

**Issue by timwis** [Leaflet/Leaflet#3829] opened 2015-09-10 22:26 UTC
I've put together a test case that demonstrates what I'm attempting to do and the error that it causes: http://codepen.io/anon/pen/RWPyej?editors=001

To demonstrate, open the javascript console in Chrome then click on one of the polygons. It will remove the geojson layer entirely (desired) but when you move your mouse outside of where the polygon you clicked used to be, you'll get a console error: `Uncaught TypeError: Cannot read property 'mouseEventToContainerPoint' of null`

```javascript
    layer = L.geoJson(geojson, {
        onEachFeature: function(feature, layer) {
          layer.on({
            click: onClick
          });
        }
      }).addTo(map)

    function onClick(e) {
      map.removeLayer(layer);
    }
```

When a user clicks on a polygon, I'd like to replace the geojson layer with other geojson data. I can either do this by removing the layer from the map or clearing the layer and adding new data; it seems either route produces the same error.

I assume this has to do with the listeners for each polygon remaining after I've removed the layer, so I've tried to use `clearAllEventListeners()` to no avail.

@yohanboniface pointed out that it only seems to be occurring in Chrome and not Firefox or Safari. He also suggested I use leaflet.js from the master branch -- doing so stops the error and replaces it with a warning, `'webkitMovementX' is deprecated. Please use 'movementX' instead.`

Thanks for your help!

**Comment by IvanSanchez** [comment] 2015-09-11 07:37
I cannot reproduce with Chromium 44.0.2403.107-1 (no error messages at all after clicking a polygon then moving the mouse around).

Also, please note you're using the `master` branch javascript but the 0.7.5 CSS files in your codepen, which is causing graphical glitches when zooming.

**Comment by timwis** [comment] 2015-09-11 09:48
My apologies - I didn't realize swapping out the .js file to test master would save it on the codepen. I've switched it back to the stable 0.7.5 .js file. Can you give it another try? (Remember to move your mouse away from the area after clicking)

**Comment by IvanSanchez** [comment] 2015-09-11 10:13
Still cannot reproduce. :-/ Tried zomming and out and moving away out of the area or out of the map container, and still no errors in my Chromium console.

**Comment by secularkid** [comment] 2015-09-11 12:43
Hi. I just ran to the similar error today, and glady found this post. My workflow is not really the same but I'm able to reproduce error on @timwis codepen.

I've made a small capture from my screen, available there : http://www.filedropper.com/leafleterrorchrome (it's a .swf and I don't know how to host it directly here).

Indeed, this error only happens in Chrome (not Chromium), all other browsers are working fine.

**Comment by yohanboniface** [comment] 2015-09-12 03:47
> still no errors in my Chromium console.

@IvanSanchez I don't have the error in Chromium too, but do have it on Chrome, so the @secularkid suggestion that it's a Chrome update that make the error appear may be true

**Comment by ageblade** [comment] 2015-09-12 11:25
I really think this is a browser-specific issue.
I made this plunkr (http://plnkr.co/edit/xpa7OY5XdMTQ2m51UgvW?p=preview) to demonstrate it.

For some reason in Chrome for Windows version 45.0.2454.85 m (64-bit) it happens, and in Chrome for Linux version 44.0.2403.130 (64-bit) it doesn't.

I think it has something to do with the browser firing "mouseout" event after "click" event only in some versions.

**Comment by secularkid** [comment] 2015-09-12 14:14
The easy fix is to override _fireMouseEvent of L.Path via include method and add a !this._map int the first test. As this bug will be in my opinion quickly fixed by Google it does not require anything on Leaflet side. It also does not break anything in Leaflet.

**Comment by timwis** [comment] 2015-09-13 18:52
Thanks for investigating. Sounds like we'll just wait until Chrome updates then. Unless you have a suggestion on how to word a bug report to the Chrome team?

**Comment by sambernet** [comment] 2015-09-15 15:16
Sorry for opening a duplicate but I didn't find this issue with the old title and descriptions as it was far more specific.

What I can add from my analysis:
- the issue is NOT browser specific (tested on Firefox 40.x and Chrome 45.x)
- the problem has nothing to do with GeoJSON but happens for all L.Path instances

See simple test case here:
http://jsfiddle.net/Ldp25Lf4/

**Comment by mfc-julius** [comment] 2015-09-18 13:00
:+1:

**Comment by yohanboniface** [comment] 2015-09-28 10:13
Fixed by https://github.com/Leaflet/Leaflet/pull/3849 (but not yet released).

**Closed by yohanboniface** 2015-09-28 10:13 UTC
Labels: bug, needs more info, stable
