### ISSUE TITLE
Safari: Clicking on marker malfunction

### ISSUE THREAD

**Issue by QJjs** [Leaflet/Leaflet#7645] opened 2021-08-29 19:11 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Open Safari
- Go to https://leafletjs.com/examples/quick-start/
- Interact with the marker on the map of the first page

**Expected behavior**
As in other browsers (e.g. Firefox), clicking on the marker should toggle the visibility of its bound popup.

**Current behavior**
The behavior is very finicky, only getting the expected result by clicking and holding on the marker for ~1.5 seconds before releasing. Otherwise, the visibility of the popup does not toggle. (This is unlike clicking on the polygon or circle elements, which behave normally)

**Environment**
- Leaflet version: 1.7.1 (Personal) and whatever version leafletjs.com uses
- Browser (with version): Safari 14.1.2
- OS/Platform (with version): macOS Big Sur 11.5.2

**Additional context**
(This same behavior is also demonstrated on the iPhone and iPad through Safari)
Digging deeper into the issue, it looks like the marker is receiving two simultaneous click events (one real, one simulated) as seen in the following image (screenshot of Safari inspector console) and jsfiddle.
![image](https://user-images.githubusercontent.com/21070294/131262477-29ce526f-3b57-4cd7-8179-846fed5180b4.png)

**Minimal example reproducing the issue**
https://jsfiddle.net/6spr8vmt/4/

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment] 2021-08-29 19:23
Duplicate of https://github.com/Leaflet/Leaflet/issues/7255

**Closed by IvanSanchez** 2021-08-29 19:23 UTC
