### ISSUE TITLE
Popup sizing broken in 1.0rc1

### ISSUE THREAD

**Issue by neothemachine** [Leaflet/Leaflet#4640] opened 2016-06-10 17:12 UTC
0.7: http://jsfiddle.net/n6f7hk4t/
1.0rc1: http://jsfiddle.net/5dsac2bm/

What's going on here?

**Comment by jwoyame** [comment] 2016-06-12 15:47
Hi @neothemachine, this is a duplicate of #4575. There is a fix #4597 that is awaiting review/comment.

**Comment by nathancahill** [comment] 2016-06-12 20:28
Closing as duplicate.

**Closed by nathancahill** 2016-06-12 20:28 UTC
