### ISSUE TITLE
Marker popups not working in touch browsers

### ISSUE THREAD

**Issue by AbrahamArun** [Leaflet/Leaflet#3480] opened 2015-05-19 05:19 UTC
I am trying to add popups for markers. They work just perfect in the desktop browsers, but just does not seem to work in a mobile browser. An example taken out from the leaflet example as shown below does not work in a mobile browser:

<pre><code> L.marker([51.5, -0.09]).addTo(map)
			.bindPopup("<b>Hello world!</b><br />I am a popup.")
</code></pre>

As part of debugging this issue, I see that even events such as 'click' / 'touchstart' and 'touchend' does not get called. The only event that works is 'contextmenu'. Am I missing something? I am using mapbox version 2.1.9

Related to #3375

**Comment by mourner** [comment] 2015-05-19 06:48
Does it work on official Leaflet examples on the website? What mobile browser do you use? Can you set up a minimal JSFiddle test case reproducing the issue?

**Comment by AbrahamArun** [comment] 2015-05-19 07:22
The leaflet example works fine if I load it from the url in a mobile browser. But in my case, I have it integrated it in a cordova mobile app (using ionic framework), I am not sure how i could do a JS Fiddle for it. I am using a Galaxy Nexus phone with Android V 4.3.

**Comment by mourner** [comment] 2015-05-19 08:27
Duplicate of #3184

**Closed by mourner** 2015-05-19 08:27 UTC
Labels: bug, needs more info
