### ISSUE TITLE
Firefox: Mouse wheel scrolling results in 2 step zoom

### ISSUE THREAD

**Issue by KommX** [Leaflet/Leaflet#8016] opened 2022-02-21 19:25 UTC
- [X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Open Firefox (on Windows)
- Go to https://www.openstreetmap.org/
- Zoom by using the mouse wheel

**Expected behavior**

The zoom level should increase/decrease in steps of 1.

**Current behavior**

The zoom level increases/decreases in steps of 2.

**Environment**
- Leaflet version: I don't know how to detect that, sorry.
- Browser (with version): Firefox 97.0.1
- OS/Platform (with version): Windows 10 Version 21H1

**Additional context**

This issue is not present in Chrome.
This bug was first reported in https://github.com/openstreetmap/openstreetmap-website/issues/3463.
This bug seems to be related to #7403, but I my monitor's resolution is only 2560*1440.

**Comment by jonkoops** [comment] 2022-02-22 10:10
Duplicate of #7403

**Closed by jonkoops** 2022-02-22 10:10 UTC
