### ISSUE TITLE
Geolocation error (kCLError Domain 0) on iOS when no WiFi networks are in range

### ISSUE THREAD

**Issue by binghamchris** [Leaflet/Leaflet#9342] opened 2024-05-16 14:27 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

This issue occurs naturally only in places where no WiFi networks are in range of your device. To reproduce this issue in places where there are WiFi networks, use the following steps:
1. On an iOS device, completely disable WiFi in the Settings app.
2. (Optional) Check in a mapping app, such as Apple Maps or Google Maps, to see that the device is still able to return a geolocation without any detected WiFi networks.
3. Navigate to a site which uses Leaflet and offers geolocation. Either [OpenStreetMap](https://www.openstreetmap.org/) or my project [Paddel Buch](https://www.paddelbuch.ch) can serve as examples of this.
4. Click the geolocation button.
5. The following error message is displayed: `Geolocation error: The operation couldn't be completed. (kCLErrorDomain error O.).` 
 
Note that the map is zoomed to the correct location as the error message is displayed. The location marker is also very briefly displayed on the map as the error message comes up.

I've found that this error occurs with `enableHighAccuracy` set to either `true` or `false`, and with `watch` set to either `true` or `false`.

### Expected behavior

When geolocation is used on an iOS device in areas where there are no WiFi networks, Leaflet should use the location provided by the device and not display an error message.

I'm afraid I don't have an Android device to test with to see if this issue occurs on other platforms.

### Current behavior

Leaflet seems to be handling the geolocation returned by iOS when no WiFi networks are in range incorrectly. I base this on the fact that the map is zoomed to the correct bounds and the location maker is briefly displayed, indicating that Leaflet received a location and processed it correctly initially, and only after this throws an error.

I've tried to work out where in the code this is happening, without success I'm afraid.

For my project this is a very problematic issue as [Paddel Buch](https://www.paddelbuch.ch) is intended to support paddle sports participants on the Swiss lakes, and naturally you don't usually find WiFi networks in the middle of a lake!

### Environment

- Leaflet version: 1.9.3 and 1.9.4
- Browser (with version): iOS Safari 17.4 and 17.5
- OS/Platform (with version): iOS 17.4 and 17.5

**Comment by binghamchris** [comment] 2024-05-16 15:49
> Does the same error show up at https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API#examples ?

No, on this page the correct lat/lon coordinates are displayed with no error messages when WiFi is disabled.

**Comment by binghamchris** [comment] 2024-05-18 18:09
I've been able to get a quick test of this on a Samsung Android 14 device, and with WiFi switched off geolocation worked without an error message with Leaflet 1.9.4.

Seems like this issue might be limited to iOS devices.

**Comment by binghamchris** [comment] 2024-05-25 05:29
I notice the `needs more info` label is still attached to this issue.
Is there any more information I can try to get to help with this please?

**Comment by IvanSanchez** [comment] 2024-05-25 09:01
It's more like "need spare time and also an iPhone and an iMac which I don't have".

@binghamchris By any chance would you be able to provide an error stack? Attach a desktop Safari as a debugger (and the works) in order to put breakpoints in the javascript code.

The Leaflet geolocation code is pretty barebones and just calls the geolocation API a couple times. It's necessary to see how it runs compared to other geolocation examples.

**Comment by binghamchris** [comment] 2024-05-25 09:48
OK, I've had a go at this @IvanSanchez. Not being a JS developer I'm unsure if I've got the right info for you, so please let me know if there's more you need :) 

With WiFi switched off on the iPhone, I put a breakpoint on the `locate` function and stepped through until the error message came up in variables:
<img width="1792" alt="Safari Debug- Leaflet Geolocate Error" src="https://github.com/Leaflet/Leaflet/assets/3534465/b033bccf-ba18-48b5-ba82-d79c4ec398b9">

When this stage is reached, which is right before the error message is displayed to the user on the iPhone, there's two things I notice:

1. On the iPhone the map is zoomed to the correct area, with the location marker in the right place (my actual location) and the location accuracy circle showing a wide accuracy circle (roughly 1.5km diameter).
2. The `this._lastCenter` variable has the lat/lon coordinates of my actual location (redacted in the screenshot).

Does this help please?

**Comment by PaulWalks** [comment] 2024-06-17 08:38
So glad I found this as having the same issue and hadn't connected it to wifi.

The message comes up after the phone has gone to sleep, and is then woken up and first asks for location. All works fine if Wifi enabled (regardless of whether there are any wifi networks around), but the message comes up if wifi is disabled - though location is still available and found.

**Comment by Falke-Design** [comment] 2024-06-17 13:59
@binghamchris @PaulWalks can you please check if the error occurs on the following site too: https://florian-bischof.at/tests/location.html

It has the same location implementation as Leaflet but without Leaflet. 

In my eyes this is an error of IOS and nothing that we can capture.

**Comment by PaulWalks** [comment] 2024-06-17 14:20
I can't reproduce via that page. I think probably because it only asks location once - so after phone wakes up you have to reload the page to get it to try to geolocate. I think the error only happens when the phone wakes up on a page that is automatically updating location. I only get the error after waking the phone/screen from sleep with the locate page active.

**Comment by PaulWalks** [comment] 2024-06-17 14:20
The error message is thrown from Leaflet itself - it has the 'Geolocation error:' prefix from the leaflet code.

**Comment by Falke-Design** [comment] 2024-06-17 14:50
Leaflet just redirects the error, it is still thrown by the browser self:
https://github.com/Leaflet/Leaflet/blob/ed5778c319a0b5466e6f52b49004539ff8fff774/src/map/Map.js#L664-L683


@PaulWalks can you please try the page again. I added the `watch: true` attribute to keep requesting the location

**Comment by binghamchris** [comment] 2024-06-17 14:50
Same for me @Falke-Design: as with the Mozilla dev site, the test site displays a pop up with the same GPS coordinates in both cases, with Wi-Fi disabled (simulating not networks being present) or enabled.

Is there any more debugging I can do on iOS/macOS to help you narrow this down please?

**Comment by Falke-Design** [comment] 2024-06-17 14:53
I just updated the test page again, can you please test it?

**Comment by binghamchris** [comment] 2024-06-17 14:56
Tried again after you added `watch`, thanks @Falke-Design. Now I got 3 variations of the same outcome across 3 reloads of the page with WiFi switched off:

**Attempt 1**
1. Popup with correct coordinates
2. Popup with the error message `Code: 2 Msg: The operation couldn't be completed. (CLErrorDomain error O.)`
3. Popup with correct coordinates

**Attempt 2**
1. Popup with correct coordinates
2. Popup with correct coordinates
3. Popup with the error message `Code: 2 Msg: The operation couldn't be completed. (CLErrorDomain error O.)`

**Attempt 3**
1. Popup with correct coordinates
2. Popup with the error message `Code: 2 Msg: The operation couldn't be completed. (CLErrorDomain error O.)`

**Comment by Falke-Design** [comment] 2024-06-17 15:12
This confirms now, that it has nothing to do with Leaflet. As I expected the Browser has some issue.

The code:
```
		function onResponse(pos){
			var lat = pos.coords.latitude,
				lng = pos.coords.longitude;
			document.getElementById('wrapper').innerHTML += '<br>'+lat+','+lng
		}

		function onError(error){
			var code = error.code,
				message = error.message
			document.getElementById('wrapper').innerHTML += '<br> Error Code: '+code+' Msg: '+message
		}
		var options = {
			timeout: 10000,
			watch: true
		};
		// navigator.geolocation.getCurrentPosition(onResponse, onError, options);
		navigator.geolocation.watchPosition(onResponse, onError, options);
```

I wasn't able to find anything about this error in the internet. So I suggest you to create a bug report: https://www.apple.com/feedback/safari.html


As this is a Safari issue and not Leaflet issue, I will close this. Sorry that we can't help you more.

**Closed by Falke-Design** 2024-06-17 15:12 UTC
Labels: bug, needs more info, ios

**Comment by PaulWalks** [comment] 2024-06-17 15:15
Thanks for looking into this. Is there no chance of a workaround - perhaps ignoring the 'kCLError Domain 0' error on first instance and only triggering if it repeats on 2nd request?

**Comment by PaulWalks** [comment] 2024-06-17 15:28
Ah ok. We are using the official Leaflet.Locate plugin and the error is being thrown to the user. Does this mean you consider it a bug for Leaflet.Locate to deal with? Apologies for my ignorance btw.

**Comment by Falke-Design** [comment] 2024-06-17 15:33
Yes exactly because Leaflet.Locate is showing the error to the user: https://github.com/domoritz/leaflet-locatecontrol/blob/a2bbecc51de9add98a673847d9dbd2c1c0fea1ce/src/L.Control.Locate.js#L312

But it looks like you can override the error function with the option `onLocationError` .

> Apologies for my ignorance btw.

No need, everything is good 😄

**Comment by binghamchris** [comment] 2024-06-19 08:43
Thanks for looking into this @Falke-Design
