### ISSUE TITLE
popup opening downward if it's "overflowing" north maxBound would be great

### ISSUE THREAD

**Issue by remlev** [Leaflet/Leaflet#2896] opened 2014-09-11 11:15 UTC
First off all, thanks a LOT for all this amazing work!

On stable 0.7.3 I'm using map.setMaxBounds([[90, -180], [-90, 180]]), wich is great to prevent user from navigating through "copies" of the world. And I let the popup.otions.autoPan to default (true).

With this set up, there is one problem : Saying zoom level is very low and a marker is in top of the map (north of Groënland for example), The popup will open > autopan feature will allow for 1/2sec to view the popup (making the view go "over the world") > the setMaxBounds method will in the meantime prevent  this behaviour. Here you can see the problem : http://jsfiddle.net/9zyeyk0a/2/

I see 2 solutions to prevent this "yoyo" effect :
1.to have a setMaxBounds method which only works horizontally.
2.Better : to open the popup below the marker in this case.

I managed to go through the 2nde solution with some "dirty tricks" but it would be great to be something automatic (without these jQuery tricks). I did this :

*** I changed autoPan to false during binding Popups
*** I created a CSS custom class called 'reverse-popup' to have the tip at the top pointing upward :
.reverse-popup .leaflet-popup-tip-container {
position: absolute;
transform: rotate(180deg);
top: -20px;
left: 64px;
}
***And then in the page :
map.setMaxBounds([[90, -180], [-90, 180]]);
map.on('popupopen', function(e) {
if(!e.popup.options.oldOffset) e.popup.options.oldOffset = e.popup.options.offset; // saving old anchor point X Y
var px = map.project(e.popup._latlng);
var heightOpeningPopup = $('#map').find('.leaflet-popup-content').height(); // we calculate popup content height (jQuery)
var temp = px.y - heightOpeningPopup; var temp2 = heightOpeningPopup+42;
if(temp < 100){ // if it will go above the world, we prevent it to do so
e.popup.options.offset = new L.Point(0, temp2); // we make the popup go below the poi instead of above
$('#map').addClass("reverse-popup"); // we make the popup tip to be pointing upward (jQuery)
e.popup.update();
}
else{ // we allow auto pan if the popup can open in the normal upward way
e.popup.options.offset = e.popup.options.oldOffset;
e.popup.options.autoPan = true;
$('#map').removeClass("reverse-popup");
e.popup.update();
}
});

map.on('popupclose', function(e) {
e.popup.options.autoPan = false;
});

Here it is : http://jsfiddle.net/eopfrwdn/2/

Cheers et Bonsoir:)

**Comment by IvanSanchez** [comment] 2015-05-12 22:00
Duplicate of #2324

**Closed by IvanSanchez** 2015-05-12 22:00 UTC
