### ISSUE TITLE
"window is not defined" (server side rendering)

### ISSUE THREAD

**Issue by AmitMY** [Leaflet/Leaflet#8327] opened 2022-07-05 14:25 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Include a `leaflet` map in an angular app with prerendering
2. try to pre-render / server-side-render

### Expected behavior

`leaflet` should not call the `window` constant. It should use `globalThis` or check if `window` indeed exists, at least for code that is executed directly on import. 

It is OK if leaflet uses `window` after import, when executed, to allow for bundling it while allowing prerendering

### Current behavior

Error:
> ReferenceError: window is not defined

Coming from this line:
```js
export var requestFn = window.requestAnimationFrame || getPrefixed('RequestAnimationFrame') || timeoutDefer;
```

### Minimal example reproducing the issue

not really possible here using the leaflet editor

### Environment

- Leaflet version: 1.8.0
- Browser (with version): none, that's the issue :)
- OS/Platform (with version): MacOS, Github Actions (Ubuntu)

**Comment by IvanSanchez** [comment] 2022-07-05 16:39
Duplicate of https://github.com/Leaflet/Leaflet/issues/6331 , https://github.com/Leaflet/Leaflet/issues/3220 , https://github.com/Leaflet/Leaflet/issues/6552 .

**Closed by IvanSanchez** 2022-07-05 16:39 UTC
Labels: bug, needs triage
