### ISSUE TITLE
leaflet.css .leaflet-default-icon-path (Default icon URLs) breaks webpack import

### ISSUE THREAD

**Issue by iagafonov** [Leaflet/Leaflet#4985] opened 2016-09-30 11:34 UTC
leaflet.css:
`/* Default icon URLs */
.leaflet-default-icon-path {
	background-image: url(images/);
	}
`
`images/` - is not correct resource path. It can not be resolved in webpack module bundler and another dependency tracking utilities too, I suggess

**Comment by IvanSanchez** [comment] 2016-09-30 11:35
Duplicate of #4849

**Closed by IvanSanchez** 2016-09-30 11:35 UTC
