### ISSUE TITLE
Inertia drag triggers after pausing the drag

### ISSUE THREAD

**Issue by HarelM** [Leaflet/Leaflet#5711] opened 2017-08-13 22:08 UTC
## How to reproduce
- Leaflet version I'm using: 1.2
- Browser (with version) I'm using: Chrome Version 60.0.3112.90 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: windows 10 15063.540
1. Using the following example: http://leafletjs.com/examples/quick-start/example.html
2. Zoom in to maximum zoom level (18 in this case, but it even more visible in zoom 20).
3. Drag-move the map around, you'll notice that when you stop dragging the map moves a few pixels.

## What behaviour I'm expecting and which behaviour I'm seeing
Expected: the map will stay exactly where I left it.
Actual: The map moves a bit after I let go of the drag.

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

I thought this was a problem in my code until I managed to reproduce it with the leaflet example.
This is the issue I'm tracking on my site:
https://github.com/IsraelHikingMap/Site/issues/410
It also has a video there, I'm not 100% sure it's the same issue but the symptoms are very similar, the issue reported there was reproduced on FireFox.

**Comment by IvanSanchez** [comment] 2017-08-14 05:37
Can confirm, in multiple browsers. In order to reproduce, make a fast and abrupt drag, leave the mouse button pressed for a couple of seconds but not moving, then release the mouse button.

The problem seems to be related to the inertia drag functionality. In order to start debugging this, I suggest printing some debug information on the `_onDragEnd()` method of `/src/map/handler/Map.Drag.js`. Most likely the time of the last mouse/pointer event is not being taken into account for the inertia calculations.

**Comment by perliedman** [comment] 2017-08-14 06:30
Possibly related to #5690 that was included in 1.2.0, although I'm surprised by @IvanSanchez's description, since it sounds exactly like the behavior in <1.2.0 and #5690 should fix.

**Comment by IvanSanchez** [comment] 2017-08-14 06:43
I've made a playground for this at http://playground-leaflet.rhcloud.com/nusur/edit?html,output :

```js
    var h = new Hand({timing: 'frame'});
    var finger = h.growFinger('mouse', { pointerType: 'touch', pressure: 0.9 });
    
    finger.moveTo(20, 200, 500, {});
    finger.down(100);
    finger.moveBy(300, 0, 100);
    finger.wait(2500);
    finger.up(500);
```

**Comment by perliedman** [comment] 2017-08-14 07:01
@IvanSanchez that example fails for me, but it looks very similar to http://playground-leaflet.rhcloud.com/teba/1/edit?html,output

Sorry for the confusion - this bug (and #5652) _is_ present in 1.2.0, we didn't merge this fix until after the release. It should however be fixed in latest `master`: http://playground-leaflet.rhcloud.com/yune/edit?html,output

So, I'm closing this as fixed but not yet released!

**Closed by perliedman** 2017-08-14 07:01 UTC
Labels: needs solution, ux

**Comment by HarelM** [comment] 2017-08-14 07:24
@perliedman was this bug introduced in 1.1.0 or did it exists in previous versions?
In any case, it's probably better to update the release notes or even better - to release a new version with this fix :-)
Keep up the good work!

**Comment by perliedman** [comment] 2017-08-14 08:36
@HarelM hm, not sure what we should update the release notes with? I don't think we ever said this was fixed anywhere?

I wouldn't say this is a high priority issue (existed since 1.0.0, released 10 months ago or so, only two reports during that time), so I will not push out an immediate release for this, but it definitely will be in the next version, which hopefully isn't too far away.

**Comment by HarelM** [comment] 2017-08-14 08:57
Sorry, my bad, I was sure I read it in the change log...
While this is subtle in zoom levels up to 16-17 in deeper zoom levels (19-20) this is extremely annoying.
I'm working on a POI layer that there are many points on the map and you need deeper zoom levels to be able to see each POI separately - this issue can kill the usability of this feature completely...
Since I'm using npm and angular It will be hard to take the latest version, a pre-release in npm would be much appreciated...
