### ISSUE TITLE
Tabbing through leaflet markers breaks the map

### ISSUE THREAD

**Issue by MuellerMatthew** [Leaflet/Leaflet#3385] opened 2015-04-17 19:04 UTC
When using the 'tab' key to navigate leaflet maps, the selected options will cycle through all of the selectable markers, including the ones off the screen. When the map pans/refocuses on the marker that was previously off the screen(either below the bottom of the map or off the right edge of the map), all of the controls pan across the map.

I tested this bug on both Chrome and Firefox, and they both had this bug.

At first i thought this was an issue with just my maps, but I noticed the same issue on the leaflet example maps as well. http://leafletjs.com/examples/layers-control-example.html If any of markers are off the screen to the bottom, or right side when a user is tabbing the map breaks.

Additionally, if the tiles beneath the marker you have just panned-to by tabbing are not cached leaflet will not issue a call for new tiles, and instead it just displays the blank background.

I think a temporary workaround might be to set the tabindex of all the markers which are off the screen to -1, but I think that since this is an accessibility issues we still need to work towards improving the tabbing so that it tabs first to all the markers on the screen, and then tabs to the markers which are off the screen but without breaking the map.

**Comment by IvanSanchez** [comment] 2015-04-17 19:23
Duplicate of #3333, already fixed in master.

**Closed** 2015-04-17 19:30 UTC
