### ISSUE TITLE
touchZoom does not work in ipad Air

### ISSUE THREAD

**Issue by jasonzhang2022** [Leaflet/Leaflet#3138] opened 2015-01-14 17:44 UTC
My Environment: ipad Air, ios 8.1.2, cordova wrapped leaflet application, leaflet 0.7.3.

Zoom by control works.
DoubleClick Zoom works.
TouchZoom does not work under ios 8.1.2. Debugging shows that some fractional zoom level is used to request map tile.

It works for android most of time, but not all the time.
I traced it down this method.

```javascript
getScaleZoom: function (scale, fromZoom) {
		fromZoom = fromZoom === undefined ? this._zoom : fromZoom;
		return fromZoom + (Math.log(scale) / Math.LN2);
	},
```
This method is called by animationZoom to retrieve zoom level. If I change the return to 
> return Math.round(fromZoom + (Math.log(scale) / Math.LN2));

The touchZoom works, but is not smooth and the Path is only in correct position at the end of animation, not during the transition.

**Comment by danzel** [comment] 2015-01-14 19:17
Have you tried the master version?

**Comment by jasonzhang2022** [comment] 2015-01-14 22:25
Replace the 0.7.3 library with 0.8-dev. I do not even have map any more.

**Comment by mourner** [comment] 2015-05-11 10:44
@jasonzhang2022 question, do you see the same problem on www.leafletjs.com, or only in your setup? I can't reproduce this...

**Comment by mourner** [comment] 2015-06-05 05:18
No further response so closing.

**Closed by mourner** 2015-06-05 05:18 UTC
Labels: bug, mobile
