### ISSUE TITLE
A map shift or a projection failure?

### ISSUE THREAD

**Issue by DiamondSteel** [Leaflet/Leaflet#6159] opened 2018-05-10 05:32 UTC
There is one and the same map with polygons. The same data is used.
Map 1. Everything is displayed as intended.
http://mycology.su/wp-content/plugins/wp-ds-myco-geographical-habitat/index.html
Map 2. The WordPress environment does not display correctly.
http://mycology.su/cortinarius-caperatus.html
What can influence the map?
How can I fix it myself?

Leaflet version 1.3.1

**Comment by mourner** [comment] 2018-05-10 13:36
I see no issues on both urls — the map works. 

![image](https://user-images.githubusercontent.com/25395/39872283-2445b1cc-5470-11e8-8d2e-cf4df1e8786b.png)

Closing the issue. If you still experience a problem, please make sure to fill out the full issue template for us to be able to diagnose it.

**Closed by mourner** 2018-05-10 13:36 UTC

**Comment by perliedman** [comment] 2018-05-10 17:16
I agree with @tomchadwin, the polygons are shifted in the second link.

However, this falls under our policy of not debugging issues that only appear together with other frameworks, libraries, etc. In this case, it appears the Wordpress site does something that cause this.

I would look into CSS rules that potentially shift one element or another a couple of pixels.

Please provide information on how to reproduce if you believe this is actually an issue with Leaflet itself.

**Comment by tomchadwin** [comment] 2018-05-11 07:14
I don't think it's a projection issue. As far as I can see, the displacement remains the same in pixels regardless of zoom level. I'd your styles are the same in each version, then I'd guess @perliedman is right, and some non-map CSS is interfering.

**Comment by IvanSanchez** [comment] 2018-05-11 07:19
I cannot reproduce - the polygons fit the province boundaries in both cases here. (Using Firefox 59.0.2 and Chromium 66.0.3359)

**Comment by DiamondSteel** [comment] 2018-05-11 07:25
@perliedman
You gave me the right idea. Thanks.
Live interfered with redefined CSS style for the IMG tag (img{padding: 5px;}).
