### ISSUE TITLE
the zoomend event execute two times

### ISSUE THREAD

**Issue by cnroland** [Leaflet/Leaflet#4299] opened 2016-03-04 09:03 UTC
map.on("zoomend", zoomend);
function zoomend(evt){
    document.getElementById("test").innerHTML = map.getZoom() + ".zoomend<br>" + document.getElementById("test").innerHTML;
}

**Comment by IvanSanchez** [comment] 2016-03-04 09:05
Duplicate of #4023

Next time you report a bug, please take time to look for duplicates and follow the guidelines in [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md)

**Closed by IvanSanchez** 2016-03-04 09:05 UTC
