### ISSUE TITLE
VML objects lose their style after DOM manipulation in IE8

### ISSUE THREAD

**Issue by kerryarts** [Leaflet/Leaflet#3035] opened 2014-11-17 20:23 UTC
When using the VML fallback in IE8, VML objects lose their styling if they are re-added to the DOM after being removed.

For example, this occurs when re-adding a polyline layer to the map.

[Example jsfiddle](http://jsfiddle.net/7q3mw1nd/3/) - Clicking the black line twice causes the red line to revert to default styles (1px black stroke)

**Comment by danzel** [comment] 2015-01-09 20:44
We probably just need to re-add the stroke/fill properties when the line is added back to the map?
Would be worth checking this with polygons too, they should have the same error I expect.

**Comment by danzel** [comment] 2015-01-09 20:47
Duplicate of #3035 continue discussion there.

**Closed by danzel** 2015-01-09 20:47 UTC
