### ISSUE TITLE
"X" mark in popup is breaking applications by pointing to "#close"

### ISSUE THREAD

**Issue by hadson172** [Leaflet/Leaflet#8235] opened 2022-05-11 23:17 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Add popup to map (Screenshot from https://leafletjs.com/)
![image](https://user-images.githubusercontent.com/8881977/167962164-aa894bcc-e470-4822-846d-0e9e0998677d.png)

The "X" mark is a link, when click will redirect app to diffrent url (like this)
`https://leafletjs.com/#close
`

The button is rendered as `<a class="leaflet-popup-close-button" role="button" aria-label="Close popup" href="#close"><span aria-hidden="true">×</span></a>`

**Expected behavior**
Leaflet close popup button should not mess with routing inside application and create links pointing to sections.

**Current behavior**
In case of leaflet with frameworks like react and react-router this feature is breaking routing, enforcing to trigger hooks watching url changes and forcing to re-render whole map and page.

**Environment**
- Leaflet version: 1.8.0
- Browser (with version): Firefox
- OS/Platform (with version): Windows 

**Additional context**

**Minimal example reproducing the issue**

https://leafletjs.com/

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment] 2022-05-12 01:59
Duplicate of https://github.com/Leaflet/Leaflet/issues/8159

**Closed by IvanSanchez** 2022-05-12 01:59 UTC
