### ISSUE TITLE
Map fitBounds does not work sometimes

### ISSUE THREAD

**Issue by rkgh** [Leaflet/Leaflet#5759] opened 2017-09-05 09:58 UTC
## How to reproduce

- Leaflet version: 1.2.0
- create and add first circle to the map;
- fit map to the bounds of the first circle;
- create and add second circle to the map;
- fit map to the bounds of the second circle;

## What behaviour I'm expecting and which behaviour I'm seeing

**Actual**: map still fits to the bounds of the first circle
**Expected**: map has to be fit to the bounds of second circle

## Minimal example reproducing the issue

http://jsfiddle.net/ZkC5M/583/

**Comment by perliedman** [comment] 2017-09-05 10:19
Hi!

This looks like a duplicate of #3249, where moving the map while an animation is in progress does not always have the expected result.

As a side note: your fiddle uses Leaflet version 0.4.5, which is impressively old. Please ensure you're actually using the version you're reporting on.

**Closed by perliedman** 2017-09-05 10:19 UTC

**Comment by rkgh** [comment] 2017-09-05 10:57
@perliedman Thank you for your comments. The old Leaflet version was accidentally used. Please, have a look at another example:
http://jsfiddle.net/ZkC5M/606/
If you very fast and consequently enter the following radius 5000, then the issue is still reproduced.
Is there a workaround for this issue?

**Comment by perliedman** [comment] 2017-09-05 11:18
@rkgh yeah, the version comment was just a note. As mentioned above, we know #3249 is still active in the latest versions.

The only workaround I know is to avoid consecutive `fitBounds` calls right after each other, but of course it depends a bit on your application exactly how to do that.
