### ISSUE TITLE
Touch detection regression on leaflet 0.7.7 for IE 11.0.9600.16428 / Windows 7

### ISSUE THREAD

**Issue by paulgreg** [Leaflet/Leaflet#4186] opened 2016-02-02 09:54 UTC
Since leaflet 0.7.7, `L.Browser.touch` returns `true` for IE 11.0.9600.16428 / Windows 7 on **desktop** (no touch screen).

Result on Chrome and Firefox seems correct (no touch support).

Here’s a simple example file to reproduce :

    <!DOCTYPE html>
    <html>
    <head>
    	<title>Leaflet Touch</title>
    	<meta charset="utf-8" />
    </head>
    <body>
    
    
    
    
    
    
    
    
    
        
        
        
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.js"></script>
    	<script>
            alert('Touch support: ' + L.Browser.touch);
    	</script>
    </body>
    </html>

**Comment by IvanSanchez** [comment] 2016-02-02 10:11
Won't fix, duplicate of #3944.

**Closed by IvanSanchez** 2016-02-02 10:11 UTC

**Comment by paulgreg** [comment] 2016-02-02 10:29
Oops, sorry, I missed the #3944.

**Comment by IvanSanchez** [comment] 2016-02-02 10:33
@paulgreg Never mind, it's OK. We're near 4000 bugs and checking for duplicates is not trivial :-)

This is not 100% the same as #3944 (IE10 vs IE11) but the discussion there explains why `touch` detection is hard.
