### ISSUE TITLE
Clickable buffer on lines or points

### ISSUE THREAD

**Issue by tenshi04** [Leaflet/Leaflet#3239] opened 2015-02-18 17:19 UTC
Hi there,

Is there a way to add a buffer/border/invisible area surrounding a line or a point to increase the 'clickable' area of a line/point? It is difficult to actually precisely click on these items when they are thin, or dashed etc.

Any options?

**Comment by iH8** [comment] 2015-03-03 23:47
I've encounted and answered almost the exact same question on Stackoverflow. As far as i know (may TPTB correct me if i'm wrong) there is no functionality in Leaflet or SVG that would increase or decrease the eventtolerance. It's just the way SVG works, precise. The workaround is in your question. By adding that invisible area. So that boils down to drawing the feature twice, once how you would like it to appear and the second time larger (w/o dasharray) and hook the eventhandler on that. See:

http://stackoverflow.com/questions/28245832/mouseover-range-distance

After some searching i've come to find out that what i'm saying is correct, there is no option to change this in Leaflet and this issue is actually a duplicate. There is a solution in the works but it's in a future milestone past 1.0 See: https://github.com/Leaflet/Leaflet/issues/2689

**Comment by perliedman** [comment] 2015-03-04 07:53
Closing this as a dupe of #2689.

A workaround that has worked well for med is to use Makina Corpus' plugin AlmostOver: https://github.com/makinacorpus/Leaflet.AlmostOver

**Closed by perliedman** 2015-03-04 07:53 UTC
