### ISSUE TITLE
Overlapping tiles in old Webkit

### ISSUE THREAD

**Issue by robotnic** [Leaflet/Leaflet#3089] opened 2014-12-14 02:58 UTC
I made a small offline map example for android using mapsforge.
https://github.com/robotnic/mapsforge-cordova-plugin-example

The speed of the map is ok. Map tiles are usable.
But Leaflet does not work together with my setup.

L.control makes Tiles overlapping when clicked. 
This happens in 0.7.3 und in the dev version.
## before touching layer control

![screenshot_2014-12-14-04-36-07](https://cloud.githubusercontent.com/assets/219020/5426342/ecb5630a-834a-11e4-96dd-b645319057b5.jpg)
## after touching layer control

![screenshot_2014-12-14-04-36-22](https://cloud.githubusercontent.com/assets/219020/5426345/02e670ec-834b-11e4-95f2-ca408fae407c.jpg)
## Same bug in all layers

![screenshot_2014-12-14-03-54-09](https://cloud.githubusercontent.com/assets/219020/5426240/7acfa016-8345-11e4-927c-f5b957932472.jpg)

The example works fine in Chrome (2 Layers)
In Android Browser you see the overlapping tiles (2 Layers)
If you would like to see the offline map you have to compile with cordova. (3 Layers)

**Comment by mourner** [comment] 2015-05-11 10:40
Wow, Crosswalk looks super-awesome! I hate old Android WebView bugs so much, it's just too hard to debug, and fixing usually involves doing random things out of desperation in hope that it'll remove the bug trigger. I'd love to close this but maybe anyone has ideas how to fix this, so will keep open for a while...

**Comment by stromberger** [comment] 2017-04-10 08:25
This seems to be a duplicate of https://github.com/Leaflet/Leaflet/issues/161 ?

**Workaround (CSS)**
```
img.leaflet-tile {
    outline: 1px solid transparent;
}
```

**Comment by perliedman** [comment] 2017-04-10 11:52
@stromberger certainly looks that way, thanks for notifying. I'll close this off as a duplicate.

**Closed by perliedman** 2017-04-10 11:52 UTC
Labels: android, bug, help wanted, mobile, needs solution
