### ISSUE TITLE
vector layers on canvas disappears after first render

### ISSUE THREAD

**Issue by jfgodoy** [Leaflet/Leaflet#4763] opened 2016-07-29 16:08 UTC
If I configure the map to use `preferCanvas=true` and add a polygon, the first time it rendered correctly, but when I change the zoom or I move the map, it disappears.

See http://playground-leaflet.rhcloud.com/mahi/edit?html,output

Using `git bisect` I found the first commit that introduces the bug was `refactoring of events, it should be about 4 times faster now` 0210071dad5a1e4e73039c76c131b717b24511ed

**Comment by yohanboniface** [comment] 2016-07-29 17:27
I think it's a duplicate of #4743

**Closed by yohanboniface** 2016-07-29 17:27 UTC
