### ISSUE TITLE
circlemarker rendering issue on map.flyTo()

### ISSUE THREAD

**Issue by Wlavell2016** [Leaflet/Leaflet#6050] opened 2018-02-12 14:28 UTC
The issue is the when using the map.flyTo command with circle markers the circles dont animate correctly with the map.flyTo function.  They go from normal size to very large for 1-2 seconds and then back to the correct size at the correct zoom level.  I am assuming it is a rendering issue as part of the animation.  When I use regular markers this is not an issue.  It seems to be a bug?

var fwblayer = L.geoJSON(data3, {
    pointToLayer: function(feature, latlng) {

        if (feature.properties.PartnerID === 1) {
            // var circle = L.marker(latlng, {icon: greenIcon});

            var circle = L.circleMarker(latlng,  union);
            Union.addLayer(circle).addTo(map);

        } else {
            circle = L.circleMarker(latlng);
        }
            circle.on('click', function() {
                // console.log(marker.title)
                map.flyTo(latlng, 10)
                // $('#data .sidebar-header').text(feature.properties.Partner)

            })
            return circle.bindPopup(feature.properties.Name)
    },
    onEachFeature: function (feature, layer) {
       feature.layer = layer;
}
});
map.addLayer(fwblayer); I'm using:

**Comment by ghybs** [comment] 2018-02-14 09:36
Hi,

If I understand correctly, you initially have a map view at a low zoom (say around 0-5), then you perform a `map.flyTo(latlng, 10)`.
During this `flyTo`, your CircleMarker becomes very big, then is displayed as normal at the end of the zoom animation.

In that case, unfortunately this is the "expected" behaviour of all vector shapes in Leaflet, including Circle Markers, during any zoom change (not just `flyTo`).
This is due to how those vector shapes are implemented, and Leaflet does not try redisplaying them during a zoom animation to prevent too much computation in the animation process.
See https://github.com/Leaflet/Leaflet/issues/5403

This is most noticeable with Circle Markers, because you would not expect them to scale with zoom, but to maintain their size (like icon-based Markers, as you point out), whereas other features are _meant_ to scale with zoom.

A workaround is to stick with icon-based Markers.
Note that you can also use SVG icons for such Markers, e.g. using some [plugins](http://leafletjs.com/plugins.html#markers--renderers).

Therefore I am going to close this as "will not fix".
If your issue is different, please feel free to re-open or to create a new issue.
Please make sure to provide all the information requested in the issue template, so that people can easily understand your situation. Providing a live reproduction example greatly helps.

**Closed by ghybs** 2018-02-14 09:36 UTC
