### ISSUE TITLE
After upgrade to 1.9 smaller mouseover windows SOLVED

### ISSUE THREAD

**Issue by comprog-ux** [Leaflet/Leaflet#8862] opened 2023-02-23 16:08 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

```
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>
```
gives large popup windows.

```
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"></script>
```
gives smaller, hard to read windows.

### Expected behavior

![Skärmavbild 2023-02-23 kl  17 03 30](https://user-images.githubusercontent.com/72607670/220962869-814bf202-ce57-4165-859a-11b631838f76.png)
![Skärmavbild 2023-02-23 kl  17 21 53](https://user-images.githubusercontent.com/72607670/220967549-0f0adf6b-4592-44c6-a92c-179a63164767.png)

### Current behavior

![Skärmavbild 2023-02-23 kl  17 04 57](https://user-images.githubusercontent.com/72607670/220963225-f86a4c79-1453-4f3c-a271-6d4eda4d063d.png)

Also the Ukrainan flag and link text went smaller!

![Skärmavbild 2023-02-23 kl  17 20 17](https://user-images.githubusercontent.com/72607670/220967172-aee1b173-5ab6-4ef4-aabe-80cb6513ea0d.png)

### Environment

- Leaflet version: 1.0.3 / 1.9.3
- Browser (with version): Safari 16.3
- OS/Platform (with version): MacOS Big Sur 11.7.4

**Comment by IvanSanchez** [comment] 2023-02-23 16:26
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by IvanSanchez** [comment] 2023-02-23 16:26
Also, does this happen in any other OS/browser combination?

**Comment by Falke-Design** [comment] 2023-02-23 19:13
I think this is a duplicate of #8385 and since version 1.8.0

**Closed** 2023-02-23 20:24 UTC
Labels: bug, needs triage
