### ISSUE TITLE
Firefox reports excessive 'will-change' usage

### ISSUE THREAD

**Issue by araJamieson** [Leaflet/Leaflet#7375] opened 2020-12-09 16:44 UTC
- [x ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
Difficult: seems to happen fairly randomly.  I did see it on one occasion today when simply running the first couple of leaflet.js beginner's-guide examples.

On at least one occasion, with a not particularly complex map, after receiving a bunch of messages about will-change usage from Firefox, Firefox then reported some kind of corruption.  

From the web it looks as though this may have been a known issue at one point, and possibly one which may have been fixed in a previous release.  The proposed solution on the web (which seems to work for me) was to add 

   .leaflet-fade-anim .leaflet-tile,.leaflet-zoom-anim .leaflet-zoom-animated { will-change:auto !important; }

to my CSS.

**Expected behavior**

**Current behavior**

**Environment**
- Leaflet version: 1.7.1 (also in 1.6.0)
- Browser (with version): Firefox 83
- OS/Platform (with version): Win 10

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.  Not possible -- please see above.

- [x ] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment] 2020-12-09 17:10
Duplicate of https://github.com/Leaflet/Leaflet/issues/4686

**Closed by IvanSanchez** 2020-12-09 17:10 UTC
