### ISSUE TITLE
Problem using critical css

### ISSUE THREAD

**Issue by NielsHolt** [Leaflet/Leaflet#5406] opened 2017-03-23 08:29 UTC
Hi

Using critical css in an applications (see https://www.sitepoint.com/how-and-why-you-should-inline-your-critical-css/) gives problems in L.Icon.Default._detectIconPath (Leaflet 1.0.3) because the leaflet.css isn't loaded yet

**Comment by IvanSanchez** [comment] 2017-03-23 08:32
> Using critical css [...] gives problems [...]

Which problems, exactly?

**Comment by NielsHolt** [comment] 2017-03-23 10:09
Since leaflet-default-icon-path isn't part of the auto-detected critical css, it isn't loaded when  L.Icon.Default._detectIconPath try to use it to get background-image: url(images/marker-icon.png);
leaflet-default-icon-path is only used to set default imagePath so a solution could be to add  a default value to L.Icon.Default.options.imagePath: "images/marker-icon.png"

**Comment by IvanSanchez** [comment] 2017-03-23 10:28
I'm going to close this with the usual template of "we don't fix bugs caused by frameworks", because inlining Leaflet's CSS in a deferred manner is not within the realm of "vanilla" JS. Our docs tell users to include the whole CSS and JS before doing anything.

Besides, it's possible to customize the path of the default icon for these circumstances, as explained in http://leafletjs.com/reference-1.0.3.html#icon-default

And if you are inlining "critical" CSS and three missing lines of CSS break some of your JS code... well, you should consider those three lines to be critical too.

**Comment by IvanSanchez** [comment] 2017-03-23 10:28
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Closed by IvanSanchez** 2017-03-23 10:28 UTC
Labels: needs more info
