### ISSUE TITLE
maxBounds is buggy

### ISSUE THREAD

**Issue by OleLaursen** [Leaflet/Leaflet#4030] opened 2015-11-18 16:51 UTC
As far as I can tell, there's a bug in _getBoundsOffset. The code looks like this:

    var nwOffset = this.project(maxBounds.getNorthWest(), zoom).subtract(pxBounds.min),
           seOffset = this.project(maxBounds.getSouthEast(), zoom).subtract(pxBounds.max),

It subtracts the min of the pixel bounds to the projected north-west corner, vice versa for the max. But how do you know that north-west corner projected will contain the two min-values for the bound?

In fact, LatLngBounds ensures that the south-west corner will contain the two min-values. So the above only works in case the projection flips the direction of the y-axis.

I'm using a non-TMS tile source (just a tiled raster image) with a simple custom CRS, and indeed the above doesn't work. I think you need to project the two points, construct a new Bounds, and then do the subtraction, like this

            var projectedMaxBounds = L.bounds(
                    this.project(maxBounds.getNorthWest(), zoom),
                    this.project(maxBounds.getSouthEast(), zoom)
                ),
                minOffset = projectedMaxBounds.min.subtract(pxBounds.min),
                maxOffset = projectedMaxBounds.max.subtract(pxBounds.max),

                dx = this._rebound(minOffset.x, -maxOffset.x),
                dy = this._rebound(minOffset.y, -maxOffset.y);
            return new L.Point(dx, dy);

This works for my custom CRS.

(Thanks for a great library.)

**Comment by perliedman** [comment] 2015-11-27 17:39
Is this the only problem you've encountered when using a projection where y grows upwards?

If I remember correctly, there are many assumptions that y grows downwards (on screen) in Leaflet, and you're probably better off creating the CRS's transformation matrix so that y grows downwards.

If this doesn't work with your tile coordinates, you can enable the `tms` option, which flips how tile rows are calculated (default is rows grow downwards, with `tms: true`, they grow upwards).

**Comment by OleLaursen** [comment] 2015-11-30 08:54
Actually, I am on a projection where y grows downwards? I'm on 1.0.0-beta2, and everything else apart from the bounds seems to be working.

We initially had y growing upwards (on screen) because gdal2tiles.py produces the tiles in that direction. With the tms option to true, that seemed to work, although the included Simple CRS triggered a bug (I think because tms wants to subtract the max bounds, and the CRS pretends to be infinite). But due to application constraints, we'd rather have y pointing downwards, so I ended up flipping the generated files in the gdal2tiles.py output.

Is it a problem fixing this? If you could point me to where you'd put a test case for this, I think I could write an automated test for both a standard CRS and my custom one and supply a patch.

**Comment by OleLaursen** [comment] 2015-11-30 09:22
Eh, regarding y axis flipping, maybe I'm using the terms incorrectly, but what I meant was that _getBoundsOffset assumes that NW projected is (min, min). But NW itself in LatLng terms isn't (min, min), it's (min, max). SW is (min, min) - this is guaranteed by the LatLngBounds code. That's why I'm saying the assumptions of _getBoundsOffset can only work if the y axis is flipped. E.g., L.CRS.EPSG3857 has L.Transformation(scale, 0.5, -scale, 0.5), i.e. flipped y axis.

**Comment by OleLaursen** [comment] 2015-11-30 09:40
#2703 seems like the same problem.

**Comment by mourner** [comment] 2015-11-30 11:20
Yep, seems like a duplicate of #2703. Leaving it to @perliedman to judge if the fix looks like a right approach. If it is, let's get a PR :)

**Closed by mourner** 2015-11-30 11:20 UTC

**Comment by perliedman** [comment] 2015-12-09 12:57
Alright, this sounds very reasonable even if there would be other issues in the code when axis direction isn't the same is in for example EPSG:3857.

@OleLaursen do you want to make a PR, or should I extract the code you posted above?

**Comment by OleLaursen** [comment] 2015-12-09 13:50
I've sent a pull request.

**Comment by OleLaursen** [comment] 2015-12-09 13:57
... which is PR #4078.
