### ISSUE TITLE
When 404 returned for tile layer - mouse wheel not working

### ISSUE THREAD

**Issue by comdiv** [Leaflet/Leaflet#3105] opened 2014-12-27 05:08 UTC
Reproduce:
1) Setup base layer to ZXY what has max Q zoom (for example max zoom is 15)
2) Allow 17 zoom on layer
3) Open map with 10 zoom - all is well
4) Start to zoomin - at 16 level it will get multiple 404 erorr from ZXY server
5) Try to wheel down to return to valid zoom - map doesn't listen to wheel and doesn't zoomout

**Comment by juliensoret** [comment] 2015-02-16 13:35
Do you have an example of a tile provider which has a max zoom limit ?
In order to reproduce (and understand?) this issue.

**Comment by comdiv** [comment] 2015-11-25 16:19
It's hard to reproduce because 404 state is not caused by zoom limit - it can occure on any (Google, Yandex, OSM) when application works over bad conneciton with proxy or through 3G. We neve seen such behavior on good channel.
So to reproduce you have to create special ZXY server that randomly send 404 (or may be any other error state) may be some requests hangs. Anyway - if ZXY start to trash response we catch killing of map  reponsibility. 
Think it's minor bug while leaflet is not a component to use in the battle over anti-electronics noise. But if it's possible - may be good idea add some stress tests/environments where it can be checked.

**Comment by Falke-Design** [comment] 2021-11-30 19:02
404 response can easy forced by blocking the specific url in the developer tools of the browser. 
I close this issue, because I can't reproduce this issue and it was written in the time of Leaflet 0.X.

**Closed by Falke-Design** 2021-11-30 19:02 UTC
Labels: bug, needs investigation
