### ISSUE TITLE
npm package pollutes global namespace

### ISSUE THREAD

**Issue by Suppen** [Leaflet/Leaflet#7454] opened 2021-02-04 12:34 UTC
- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected (**Are bugs known for being documented and expected?**)
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Open a web application using Leaflet
- Open the browser console
- Type `L`
- L is Leaflet

**Expected behavior**
I expect npm packages to not touch the global namespace. Anything which will be used will also be imported or otherwise provided, not plucked from the global namespace

**Current behavior**
`L` is available over the entire application, without any `import` or `require` necessary

**Environment**
- Leaflet version: 1.6.0, 1.7.1
- Browser (with version): Any
- OS/Platform (with version): Any

**Additional context**
This behaviour is expected and even required when using leaflet in a `<script>` tag in browsers not supporting ES6 modules. It is, however, not necessary in the npm package.

Considering `L.noConflict()` sets `L` back to whatever it was before, and Leaflet still works as expected, Leaflet does in no way depend on `L` being global. It should therefore not be an issue to just not set it in the npm package.

**Minimal example reproducing the issue**
```
require("leaflet");
```
or
```
import "leaflet";
```

`L` is not being defined by me, and should therefore not be defined at all.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by johnd0e** [comment] 2021-02-04 12:43
> * (**Are bugs known for being documented and expected?**)

Well, it was designed in this way from the very beginning, long before before the package was created.
Workaround:
https://leafletjs.com/reference-1.7.1.html#noconflict

**Comment by johnd0e** [comment] 2021-02-04 20:39
See #2364

**Comment by Falke-Design** [comment] 2021-12-02 17:59
Is maybe one of the future plans of Leaflet V2: https://github.com/Leaflet/Leaflet/discussions/7729#discussioncomment-1577037

I close this because this will not be changed in Leaflet 1.X

**Closed by Falke-Design** 2021-12-02 17:59 UTC
