### ISSUE TITLE
bindPopup - not working on Safari 14.0.1

### ISSUE THREAD

**Issue by pl-samurai** [Leaflet/Leaflet#7356] opened 2020-12-01 20:15 UTC
Hi all.

I try tu use script and Safari browser 14.0.1 

	L.marker([39.74, -104.99]).bindPopup('This is Denver, CO.').addTo(cities),

after click on marker browser dont show pupup with text.

**Comment by pl-samurai** [comment] 2020-12-01 20:16
Checked on demo and on my server.
Demo not working: https://leafletjs.com/examples/layers-control/example.html

**Comment by johnd0e** [comment] 2020-12-02 07:39
Perhaps that is duplicate of #7255.

**Comment by IvanSanchez** [comment] 2020-12-02 09:00
Yeah, closing as a duplicate of #7255.

**Closed by IvanSanchez** 2020-12-02 09:00 UTC
