### ISSUE TITLE
feature request: show/hide marker

### ISSUE THREAD

**Issue by saturdaywalkers** [Leaflet/Leaflet#8955] opened 2023-05-12 22:41 UTC
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Display several thousands markers using the markercluster lib.
Want to show/hide groups of them (and then recluster), e.g. using checkboxes with on/off toggles
Only current solutions are
- remove markers from the map, and save them to possibly re-add later
- marker.setopacity(0) can hide a marker, but it is still included in the cluster counts
Simplest solution would be marker.show( true/false )
So I can loop thru the markers with  marker.show ( sym.match( /xxx/ )  ) to hide/re-show markers
Then the marker cluster can recluster

### Suggested solution

marker.show( true/false )

### Alternatives considered

Did find a very old closed ticket, but decided a fresh start might help

**Comment by jonkoops** [comment] 2023-05-14 11:58
> remove markers from the map, and save them to possibly re-add later

Is this not essentially what you want to accomplish though? I don't understand what this 'hidden' feature would do technically. Do we keep some special boolean property so that a plugin could use it? That seems like something that the plugin should do itself.

**Comment by saturdaywalkers** [comment] 2023-05-14 22:21
Technically, a boolean, yes.
e.g. a search box, type "abc", it filters the markers, backup, then type "def" instead. Rather than deleting and re-adding markers, just marker.show/hide them.
Plugins, e.g. markercluster, can use the same core show/hide boolean.

**Comment by jonkoops** [comment] 2023-05-15 14:30
I can see that this might be a useful feature, but I am not entirely convinced this should be in Leaflet itself rather than the specific plugin. I'd like to get a take of the other maintainers on this as well @Falke-Design @mourner @IvanSanchez WDTY?

**Comment by IvanSanchez** [comment] 2023-05-15 15:19
As @saturdaywalkers has pointed out, there's `addTo`/`remove` and `setOpacity` already. Adding a third way to hide/show markers will only cause confusion, IMO.

If the problem is adding/removing lots of markers from markercluster, then the approach is to create `LayerGroup`s, and ensure that markercluster can work with that.

**Comment by jonkoops** [comment] 2023-05-15 16:32
Thanks @IvanSanchez, I have to agree that adding this will only add more confusion. Closing this issue as I don't see a way this would be resolved in Leaflet itself.

**Closed by jonkoops** 2023-05-15 16:32 UTC
Labels: feature, needs triage
