### ISSUE TITLE
Issue with zooming in iOS

### ISSUE THREAD

**Issue by bmeine** [Leaflet/Leaflet#3993] opened 2015-11-08 19:21 UTC
I've only been able to try this on iOS9.1 and WP8.1 and the problem only seems to happen on the iOS9.1 phone (iphone 5) so I don't know how many platforms this will affect.

1.) Make sure there is a marker or polygon in view
2.) Start to pinch to zoom, but keep both fingers on the screen and rotate them around being sure to keep the marker/polygon in view

Eventually the marker/polygon will break loose from the map...the map will stop following your fingers, but the marker/polygon will continue to move with your fingers

The map will only update when you remove your fingers from the screen.

**Comment by IvanSanchez** [comment] 2015-11-09 08:49
@bmeine Which leaflet version are you using? We've had similar issues (e.g. #3798) with pinch interactions, and they are version-specific.

Please make sure the bug is reproducible in either 0.7.7 (`stable` branch) or in the `master` branch.

**Comment by bmeine** [comment] 2015-11-09 14:10
Sorry, didn't mention that I actually upgraded to 0.7.7 to try to fix the problem before I posted the issue. I was also able to reproduce it by visiting Leaflet's sample pages using Safari on my iPhone.

It can also be reproduced by rapidly zooming in and out (using pinch gesture)...keep repeating and the issue will eventually show up.

The other thing is that if you wait ~10 seconds or so the issue will vanish and the map will behave as expected again...almost like some queue got backed up or something.

**Comment by SupremumLimit** [comment] 2016-03-24 03:43
I observe the same effect with both a marker and a canvas layer using Leaflet 0.7.7.

**Comment by mourner** [comment] 2016-06-27 14:19
Spent a lot debugging this issue and looks like it's some really weird iOS Safari bug related to CSS transforms. Switching markers to use `top`/`left` properties for positioning fixes the issue. I have absolutely no idea what exactly triggers it and why it's not reproducible on 1.0.0.

The workaround is to include this patch once before adding any markers:

```js
L.Marker.prototype._setPos = function (pos) {
    L.DomUtil.setPosition(this._icon, pos, true);
    if (this._shadow) L.DomUtil.setPosition(this._shadow, pos, true);
    this._zIndex = pos.y + this.options.zIndexOffset;
    this._resetZIndex();
};
```

**Comment by mourner** [comment] 2016-06-27 14:21
Closing the issue for now because:

- This seems to be an obscure browser bug
- It's not critical to map usability
- There's a workaround above
- It's not reproducible in 1.0.0-rc.2

**Closed by mourner** 2016-06-27 14:21 UTC
Labels: bug, needs investigation, stable
