### ISSUE TITLE
marker.setIcon() causes changing popup position in 1.0

### ISSUE THREAD

**Issue by maxkuzmin** [Leaflet/Leaflet#4112] opened 2015-12-28 17:48 UTC
Hello. 

Please look at http://plnkr.co/edit/nJZnIfu0lmSVagNLcttU?p=preview . When you click button under the map it calls setIcon for marker and it causes changing popup position. This bug doesn't exists in stable version. This bug reproducible only in case when icon object has popupAnchor property.

Thanks.

**Comment by ghybs** [comment] 2015-12-28 18:45
Hi,

Not sure if this is the intended behaviour.

Updated example with Leaflet 1.0.0-beta.2: http://plnkr.co/edit/BR9I3gQfOZUbPU89EErR?p=preview

Note that this behaviour happens as soon as you re-bind a popup (which is done internally when calling `setIcon` on your marker).

**Comment by maxkuzmin** [comment] 2015-12-28 19:18
My case is a bit more complex - I have to toggle between 2 icons (via marker.setIcon()) - simple and selected. And I noticed that every call of setIcon method caused changing popup offset. I have found workaround for my case - I have 2 markers for every point and show one of them, but it is not cool.

**Comment by snkashis** [comment] 2016-01-02 16:57
@IvanSanchez , how connected do you think this is to https://github.com/Leaflet/Leaflet/issues/4026 ?

**Comment by IvanSanchez** [comment] 2016-01-06 14:58
Closing as duplicate of #4026 (thanks, @snkashis). @ghybs and @maxkuzmin: please move further discussion (if any) to #4026.

**Closed by IvanSanchez** 2016-01-06 14:58 UTC
