### ISSUE TITLE
race condition on setZoom with TiledLayer freezes the map

### ISSUE THREAD

**Issue by javisantana** [Leaflet/Leaflet#2021] opened 2013-09-10 09:13 UTC
If you call setZoom just after the map has been initialized the map freezes. It happens in current stable (0.6.4) and master with Chrome and FF (at least)

example: http://bl.ocks.org/javisantana/607cd01a8d12684a34ab

the interesting thing
```
var map = new L.Map('map', {
          zoomControl: false,
          center: [43, 0],
          zoom: 3
 });
 
 L.tileLayer('http://tile.stamen.com/toner/{z}/{x}/{y}.png', { attribution: 'Stamen' }).addTo(map);
 
 setTimeout(function() {
   //map.setZoom(2); // works
 }, 0);
 map.setZoom(2); //does not work
```

the problem is that transitionEnd event is not called on tiledlayer background div so _update is never called. That's because the '-webkit-transform' and '-webkit-transition' are applied in the same javascript tick to the same div.

A solution would be to add a setTimeout(function, 0) here https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.Anim.js#L12 but it does not look very elegant.

``` 
_animateZoom: function (e) {
        if (!this._animating) {
            this._animating = true;
            this._prepareBgBuffer();
        }
        var bg = this._bgBuffer;
        setTimeout(function() {
          var transform = L.DomUtil.TRANSFORM,
              initialTransform = e.delta ? L.DomUtil.getTranslateString(e.delta) : bg.style[transform],
              scaleStr = L.DomUtil.getScaleString(e.scale, e.origin);

          bg.style[transform] = e.backwards ?
                  scaleStr + ' ' + initialTransform :
                  initialTransform + ' ' + scaleStr;
        }, 0);
  },

```

**Comment by stephengoodwin** [comment] 2015-01-16 18:10
I also just experienced this same bug. Here's how I could reproduce it:

`var map = Leaflet.map('map').setView([30.442492, -97.606141], config.start.zoom);
       Leaflet.tileLayer('http://{s}.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={token}', {
           id: config.mapID,
           token: mapToken
       }).addTo(map);

       var marker = Leaflet.marker([30.442492, -97.606141]);
       marker.addTo(map);

       map.setZoom(14);`

**Comment by perliedman** [comment] 2015-01-17 21:37
Fiddle to reproduce: http://jsfiddle.net/nqr6m8wu/

**Comment by perliedman** [comment] 2015-01-18 11:22
Found another race condition, similar to the on fixed by #2636, that affects marker initialization. Putting `requestAnimFrame` around the marker's call to `_setPos` resolves this, and makes @stephengoodwin's code from https://github.com/Leaflet/Leaflet/issues/2021#issuecomment-70295665 work.

Note: I can't reproduce the discussed issue on master, just on the stable branch.

**Comment by perliedman** [comment] 2015-01-22 08:04
@stephengoodwin a fix for this is merged in the stable branch now (#3152). Would be great if you could try it out and verify that it works for you.

Closing this issue for now, and will reopen if you encounter more problems.

**Closed by perliedman** 2015-01-22 08:04 UTC
Labels: minor bug

**Comment by hawaiikaos** [comment] 2015-02-26 13:42
Is this merged into master yet? I'm having issues with this.

**Comment by perliedman** [comment] 2015-02-27 09:02
@hawaiikaos as mentioned in my comment above (https://github.com/Leaflet/Leaflet/issues/2021#issuecomment-70404411), this bug does not affect the master branch (upcoming 1.0 release). This issue affects 0.7.3 (and probably earlier versions), and is fixed in the current `stable` branch. So if you're using 0.7.3 and is affected by this, you might want to download latest stable and build it to see if that solves the issue.

**Comment by brunob** [comment] 2015-03-02 11:12
Hi @perliedman and thanks for the fix, maybe it's time to release a 0.7.4 in order to publish the two fixes available since latest release ? Any thought about it ?

**Comment by pke** [comment] 2016-06-07 20:26
This seems to be still an issue with `0.7.7`

**Comment by perliedman** [comment] 2016-06-08 06:14
@pke do you have an example that reproduces the issue?

I've taken the fiddle used to reproduce above and moved it to Leaflet Playground: http://playground-leaflet.rhcloud.com/yic/edit?html,output - the issue can't be reproduced with Leaflet 0.7.5, but can with 0.7.3.

I think you might be hitting another problem.
