### ISSUE TITLE
GeoJSON layer features not receiving dblclick event

### ISSUE THREAD

**Issue by linuskamb** [Leaflet/Leaflet#4684] opened 2016-06-28 17:00 UTC
Features added via GeoJSON layer are not receiving dblclick events.

I have tried binding the listener both via onEachFeature and pointToLayer (for point feature markers.)

In neither case do I get the dblclick event.  All other events (at least click, mouseover, contextmenu, etc) work as expected.

The map receives dblclick events, as do markers added directly to the map.

using 1.0.0 rc1

tested with
Chrome Version 46.0.2490.71 (64-bit) 
Safari Version 9.1.1 (11601.6.17)
Firefox Version 47.0.1
on
Mac OSX 10.11.5

**Comment by IvanSanchez** [comment] 2016-06-28 17:01
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by linuskamb** [comment] 2016-06-28 21:19
The simple case playground seems to work for all versions.

http://playground-leaflet.rhcloud.com/lit/1/edit?html,console,output

However, running my page from my local machine, and trying 1.0-Beta-2, 1.0-rc.1 from the cdn, and the latest snapshot from amazonws, only the latest snapshot works properly.  Below is console log output.  For the rc and beta versions, the dblclick event goes through to the map.

Not sure what to make of it, other than if it's working in the latest snapshot, I presume that will be in the final release.  I guess I'd close this unless you would like to investigate further.

> Navigated to http://localhost:8188/tcast/tws/pages/event/o46s80
1.0.0-rc.1+26df85e
retrieved IFs
mouseover:Ponce
leaflet.js:5 'webkitMovementX' is deprecated. Please use 'movementX' instead.
leaflet.js:5 'webkitMovementY' is deprecated. Please use 'movementY' instead.
1 click
2 click
marker dblclick Ponce
onFeature dblclick:Ponce
Navigated to http://localhost:8188/tcast/tws/pages/event/o46s80
1.0.0-rc.1
retrieved IFs
mouseover:Ponce
leaflet.js:5 'webkitMovementX' is deprecated. Please use 'movementX' instead.
leaflet.js:5 'webkitMovementY' is deprecated. Please use 'movementY' instead.
1 click
map dblclick
Navigated to http://localhost:8188/tcast/tws/pages/event/o46s80
1.0.0-beta.2
retrieved IFs
mouseover:Ponce
leaflet.js:5 'webkitMovementX' is deprecated. Please use 'movementX' instead.
leaflet.js:5 'webkitMovementY' is deprecated. Please use 'movementY' instead.
1 click
map dblclick

**Comment by yohanboniface** [comment] 2016-06-29 06:08
Unless we can reproduce it, I'll be tempted to think that something on your code is responsible for the issue you have.
I'm keeping the issue open for a while so you can investigate more and try to find a way to reproduce it in the playground.
But keep in mind we need that to start investigating ourselves.

**Comment by perliedman** [comment] 2017-08-09 08:38
Closing this for now, since I don't see that we have any information we can take action on.

Happy to re-open if we get information on how to reproduce this!

**Closed by perliedman** 2017-08-09 08:38 UTC
Labels: needs more info
