### ISSUE TITLE
Unknown (random) error when zooming on clusters

### ISSUE THREAD

**Issue by mahmoudmy** [Leaflet/Leaflet#4137] opened 2016-01-12 14:21 UTC
I'm using leaflet.markercluster plugin in my web application. Sometimes when I click on a cluster or zooming in map, the following error occurs and I can not pan the map and also the clustering doesn't work anymore!
```javascript
TypeError: this._map is undefined
	this._map._panes.markerPane.removeChild(this._icon);
```
**leaflet-src.js (line 3623, col3)**
	
 Any Idea?

**Comment by IvanSanchez** [comment] 2016-01-12 14:34
Duplicate of Leaflet/Leaflet.markercluster#620, will track progress there.

**Closed by IvanSanchez** 2016-01-12 14:34 UTC
