### ISSUE TITLE
marker.bindPopup() - version 1.7.1 only; on Mac Safari only - click event isn't recognized properly

### ISSUE THREAD

**Issue by Bibiko** [Leaflet/Leaflet#7331] opened 2020-11-06 15:39 UTC
An event added via `marker.bindpopup()` - version 1.7.1 only using a Mac Safari (version 14 and 13) browser only - will **only** be recognized if one makes a _long mouse-click_ of about 1s like a long tap event. If one adds such an event via `marker.on('click', function(e) {this.openPopup();});` it works properly.

**Comment by IvanSanchez** [comment] 2020-11-06 17:42
Possible duplicate of #7255 . The workaround of disabling the `tap` handler might help.

**Comment by NicoHood** [comment] 2020-12-10 10:47
What is the best workaround you can suggest? Downgrading to 1.7.0 or something else? Or will there be a release shortly?

**Comment by johnd0e** [comment] 2020-12-10 11:12
> What is the best workaround you can suggest?

Are you using `contextmenu` event to capture taphold? If you aren't then just specify map option `tap: false`.

Otherwise try unrelease version from `master`.

**Comment by NicoHood** [comment] 2020-12-10 12:19
I first noticed the issue on an Iphone. However I dont own any Iphone but someone told me that Midori on Linux has a similar browser engine. I could reproduce the bug on 1.7.0 and 1.7.1 with Midori. `tap: false` Does not fix the issue on Midori. 1.6.0 works great! The current master is not displaying a map at all, as there is no release in the dist folder currently and I dont know how to correctly integrate the current master.

**Comment by johnd0e** [comment] 2020-12-10 15:22
> `tap: false` Does not fix the issue on Midori.

Please show your exact code

**Comment by NicoHood** [comment] 2020-12-10 18:04
Here is the exact code I am using. I did not strip anything, but it should be short enough. Please keep in mind, that twig templates are used here of course:
https://gist.github.com/NicoHood/6081f242b85466c2722f2ac5bb219381

**Comment by johnd0e** [comment] 2020-12-11 08:14
> Here is the exact code I am using.

But I do not see where you set there map option `tap`.

**Comment by NicoHood** [comment] 2020-12-11 08:38
Oh right, I've removed it now. It was added at line 44
```
L.tileLayer(osmUrl, {attribution: osmAttr, detectRetina: true, tap: false}).addTo(mymap);
```

I confirmed it again, it does not work (with Midori)

**Comment by johnd0e** [comment] 2020-12-11 08:42
Read again: `tap` is Map option. Not TileLayer's.

**Comment by NicoHood** [comment] 2020-12-11 09:43
What a shame. Works now. Many thanks!

**Closed** 2021-01-27 19:53 UTC
Labels: bug, compatibility, needs investigation

**Comment by johnd0e** [comment] 2021-01-27 19:54
Duplicate of #7255

**Comment by Stephenlaye2** [comment] 2021-06-16 16:20
> An event added via `marker.bindpopup()` - version 1.7.1 only using a Mac Safari (version 14 and 13) browser only - will **only** be recognized if one makes a _long mouse-click_ of about 1s like a long tap event. If one adds such an event via `marker.on('click', function(e) {this.openPopup();});` it works properly.

This works for me. I wish there's a better way to do it though

**Comment by boxed** [comment] 2023-02-16 07:17
Probably duplicate of #7222 too
