### ISSUE TITLE
toGeoJSON with small exponent producing nan

### ISSUE THREAD

**Issue by hayden-t** [Leaflet/Leaflet#9172] opened 2023-11-19 05:37 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Poly created by voronoi calculation, tried passing false or 3 to the function but no difference

```
var poly = [
  {
    "lat": -117.2785881245743,
    "lng": 2.0301221021717147e-15
  },
  {
    "lat": -125.51698158552587,
    "lng": 14.848952851468814
  },
  {
    "lat": -124.59569838875832,
    "lng": 17.919304823001898
  },
  {
    "lat": -120.12646050811448,
    "lng": 18.355573753240016
  },
  {
    "lat": -112.62618933808815,
    "lng": 0
  }
]

var cellPoly = L.polygon(poly);
cellPoly.toGeoJSON();
```

outputs:
```

[
  [
    null,
    -117.279
  ],
  [
    14.849,
    -125.517
  ],
  [
    17.919,
    -124.596
  ],
  [
    18.356,
    -120.126
  ],
  [
    0,
    -112.626
  ],
  [
    null,
    -117.279
  ]
]
```

### Expected behavior

should not have null/nan

### Current behavior

has null/nan

### Environment

- Leaflet version: 
- Browser (with version): 
- OS/Platform (with version):

**Comment by Falke-Design** [comment] 2023-11-19 12:35
I can't reproduce this error. I think you are using an old version of Leaflet. Please make sure that you use the latest version (1.9.4) of Leaflet.

https://plnkr.co/edit/ovpguPdbK2MnuWxa

**Comment by jonkoops** [comment] 2023-11-21 11:36
Closing this issue as @Falke-Design mentioned this is likely an older version of Leaflet. If the problem persists in the latest Leaflet version let us know, and we will re-open this issue.

**Closed by jonkoops** 2023-11-21 11:36 UTC
Labels: bug, needs triage

**Comment by hayden-t** [comment] 2023-11-21 20:52
thankyou, i will try this and reply back

**Comment by hayden-t** [comment] 2023-11-22 10:15
yes this fixed it, thanks and sorry for not trying this first. i did search for past issues and didnt find any so thought it might still be a bug

**Comment by jonkoops** [comment] 2023-11-26 19:15
Thanks for getting back to us to confirm this 👍
