### ISSUE TITLE
Firefox blocks Mixed Content because leafletjs.com is not served via https

### ISSUE THREAD

**Issue by StefanBrand** [Leaflet/Leaflet#5242] opened 2017-01-10 22:41 UTC
- [x] I'm reporting a bug, not asking for help
- [x] I've searched through the issues to make sure it's not yet reported
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected --> **leafletjs.com/reference-1.0.2.html#control-attribution-prefix is not explicit about the link that is created**

----

## How to reproduce

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Firefox 50.1
- OS/Platform (with version) I'm using: Windows 10

1. Open browser console
2. Go to this iframe-embedded Leaflet map: https://forum.fairphone.com/t/testing-iframe-of-fairphone-community-map/25162?u=stefan
3.  Click on LEAFLET prefix in the attributions control
4.  Nothing happens: [Mixed Content ](https://developer.mozilla.org/de/docs/Sicherheit/MixedContent?utm_campaign=default&utm_medium=firefox-console-errors&utm_source=mozilla) warning in the console because leafletjs.com is served via http.

## What behaviour I'm expecting and which behaviour I'm seeing
I'm expecting that the link opens leafletjs.com in a new browser tab / that leafletjs.com is served via https.

**Comment by IvanSanchez** [comment] 2017-01-11 09:36
This is a duplicate of https://github.com/Leaflet/Leaflet/issues/3748 which, unfortunately, has no good solution in sight due to https://github.com/isaacs/github/issues/156 :-(

**Closed by IvanSanchez** 2017-01-11 09:36 UTC

**Comment by StefanBrand** [comment] 2017-01-11 12:58
Thank's, I didn't find it when I [searched the issues for leafletjs.com](https://github.com/Leaflet/Leaflet/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20leafletjs.com)...
