### ISSUE TITLE
Issue with bindpopup in Leaflet 1.7.1 - Popup opens, and immediately closes

### ISSUE THREAD

**Issue by thomaslian** [Leaflet/Leaflet#7330] opened 2020-11-04 17:34 UTC
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Create an Ionic project with Leaflet 1.7.1.
- Create a marker with bindpopup.
- Create a marker cluster and add marker to cluster. (this might be optional? I used this in my code)
- Add cluster to map.
- Build for browser with Cordova.
- Open Safari on an iPhone, and try to click a location.

**Expected behavior**
I expect the popup to stay open when i click a location icon

**Current behavior**
Popup closes immediately after i open it.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Safari 14
- OS/Platform (with version): iOS 14.1 (iPhone)

**Additional context**

**Minimal example reproducing the issue**
https://plnkr.co/edit/ScNPNUyq4p4QCQlj
Tried opening this with my iPhone and it is the same issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by johnd0e** [comment] 2020-11-04 19:05
Duplicate of #7255.
Caused by legacy `tap` handler.

**Closed** 2020-11-04 19:05 UTC
