### ISSUE TITLE
when hovering the mouse over the leaflet-control disappears

### ISSUE THREAD

**Issue by satrock1** [Leaflet/Leaflet#8361] opened 2022-08-01 06:27 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [x] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Expected behavior

stable operation, displaying the requested layers and nothing disappears

### Current behavior

I have more than 600,000 WMS objects in the database that should be displayed on the map, when I activate the layers on the leaflet-control, when there are a lot of objects, the leaflet control starts to disappear on hover.
On the first photo, the initial state, on the second, the checkboxes disappeared when hovering the mouse, and on the third, the entire leaflet control disappeared
![map1](https://user-images.githubusercontent.com/46323793/182084659-8b63e382-f7d8-45e1-9086-b16ce8e1e688.png)
![map2](https://user-images.githubusercontent.com/46323793/182084804-74138844-0a95-4bbc-a70e-0020869515bf.png)
![map3](https://user-images.githubusercontent.com/46323793/182084860-fd5f5096-5795-4ca4-9fb4-d6d46fce29cb.png)

### Environment

- Leaflet version: 1.6.0
- Browser (with version):  Chrome 103.0.5060.134
- OS/Platform (with version): Windows 10

**Comment by IvanSanchez** [comment] 2022-08-01 06:52
Please provide a reproducible example. Right now it's impossible to know what's going on.

Does the bug reproduce in other browsers?

**Comment by Malvoz** [comment] 2022-08-01 10:34
Looks similar to / possibly duplicate of https://github.com/Leaflet/Leaflet/issues/5931.

@satrock1 It would indeed be very helpful if you could provide a reproducible example.

**Comment by satrock1** [comment] 2022-08-02 03:56
I can’t provide my code due to the specifics of confidentiality, but the problem can be reproduced using a plugin like mine (`Leaflet.Control.Layers.Tree`), use 210 layers (`L.tileLayer.wms`) and output them using (`L.control. layers.tree`). The total number of objects should be more than 600,000, and the styles in the geoserver should be as follows:
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<StyledLayerDescriptor version="1.0.0"
  xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd"
  xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <NamedLayer>
    <Name>crane</Name>
    <UserStyle>
      <Title>orange square point style</Title>
      <FeatureTypeStyle>
        <Rule>
                    <Title>08970150-8c69-4c99-98d3-c2bd86035ac6</Title>
          <MinScaleDenominator>20000</MinScaleDenominator>
          <ogc:Filter>
       <ogc:PropertyIsEqualTo>
             <ogc:PropertyName>nazn_id</ogc:PropertyName>
          <ogc:Literal>2</ogc:Literal>
       </ogc:PropertyIsEqualTo>
    </ogc:Filter>
          <PointSymbolizer>
                        <graphic>
                            <ExternalGraphics>
                                <OnlineResource xlink:type="simple" xlink:href="./img/227.png" />
                                <Format>image/png</Format>
                            </ExternalGraphics>
                          <Size>5</Size>
                        </Graphic>
                    </PointSymbolizer>
                </Rule>
        <Rule>
                    <Title>08970150-8c69-4c99-98d3-c2bd86035ac6</Title>
          <MaxScaleDenominator>20000</MaxScaleDenominator>
          <MinScaleDenominator>10000</MinScaleDenominator>
                    <PointSymbolizer>
                        <graphic>
                            <ExternalGraphics>
                                <OnlineResource xlink:type="simple" xlink:href="./img/227.png" />
                                <Format>image/png</Format>
                            </ExternalGraphics>
                            <Size>
                               <ogc:Function name="env">
          <ogc:Literal>size</ogc:Literal>
          <ogc:Literal>9</ogc:Literal>
       </ogc:Function>
                            </Size>
                        </Graphic>
                    </PointSymbolizer>
                </Rule>
        <Rule>
                    <Title>08970150-8c69-4c99-98d3-c2bd86035ac6</Title>
          <MaxScaleDenominator>10000</MaxScaleDenominator>
          <MinScaleDenominator>5000</MinScaleDenominator>
                    <PointSymbolizer>
                        <graphic>
                            <ExternalGraphics>
                                <OnlineResource xlink:type="simple" xlink:href="./img/227.png" />
                                <Format>image/png</Format>
                            </ExternalGraphics>
                            <Size>
                               <ogc:Function name="env">
          <ogc:Literal>size</ogc:Literal>
          <ogc:Literal>11</ogc:Literal>
       </ogc:Function>
                            </Size>
                        </Graphic>
                    </PointSymbolizer>
                </Rule>
        <Rule>
                    <Title>08970150-8c69-4c99-98d3-c2bd86035ac6</Title>
          <MaxScaleDenominator>5000</MaxScaleDenominator>
          <MinScaleDenominator>3000</MinScaleDenominator>
                    <PointSymbolizer>
                        <graphic>
                            <ExternalGraphics>
                                <OnlineResource xlink:type="simple" xlink:href="./img/227.png" />
                                <Format>image/png</Format>
                            </ExternalGraphics>
                            <Size>
                               <ogc:Function name="env">
          <ogc:Literal>size</ogc:Literal>
          <ogc:Literal>13</ogc:Literal>
       </ogc:Function>
                            </Size>
                        </Graphic>
                    </PointSymbolizer>
                </Rule>
<Rule>
                    <Title>08970150-8c69-4c99-98d3-c2bd86035ac6</Title>
          <MaxScaleDenominator>3000</MaxScaleDenominator>
  <MinScaleDenominator>1000</MinScaleDenominator>
                    <PointSymbolizer>
                        <graphic>
                            <ExternalGraphics>
                                <OnlineResource xlink:type="simple" xlink:href="./img/227.png" />
                                <Format>image/png</Format>
                            </ExternalGraphics>
                            <Size>
                               <ogc:Function name="env">
          <ogc:Literal>size</ogc:Literal>
          <ogc:Literal>17</ogc:Literal>
       </ogc:Function>
                            </Size>
                        </Graphic>
```

**Comment by satrock1** [comment] 2022-08-02 05:17
I saw the L.tileLayer.canvas plugin but I don't understand how to implement it instead:
```
var layerWMS= L.tileLayer.wms(url, {
		layers: 'layer1',
		format: 'image/png',
                transparent: true,version: '1.1.1',
		maxZoom: 24,
		opacity: 1
	});
```

**Comment by Malvoz** [comment] 2022-09-26 08:33
@satrock1 Thanks for reporting the bug. Let's merge this into https://github.com/Leaflet/Leaflet/issues/5931.

**Closed by Malvoz** 2022-09-26 08:33 UTC
Labels: bug, needs more info
