### ISSUE TITLE
L.Hash plugin does not work

### ISSUE THREAD

**Issue by obama** [Leaflet/Leaflet#5838] opened 2017-10-13 11:25 UTC
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome 61
- OS/Platform (with version) I'm using: Windows 10
- step 1 try to use the Hash plugin

## What behaviour I'm expecting and which behaviour I'm seeing
exptected: it works
seen: it doesnt

THE PLUGIN IS NOT MAINTAINED ANYMORE SO PLEASE REMOVE IT FROM THE PLUGIN LIST / FIND A WORKING FORK

**Comment by IvanSanchez** [comment] 2017-10-13 11:29
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.

Also: "It doesn't work" is not a bug report.

Also (2): don't write in all caps. It looks like you're yelling at us, and that's rude.

Also (3): If you want the L.Hash plugin to be removed, title the issue "Remove L.hash plugin", or better yet, send a pull request with the required changes in the `docs/plugins.html` file.

**Closed by IvanSanchez** 2017-10-13 11:29 UTC

**Comment by obama** [comment] 2017-10-13 11:44
pls merge https://github.com/Leaflet/Leaflet/pull/5839

**Comment by PowerPan** [comment] 2017-10-16 11:45
is this still a "problem"
i have done additional work based on the L.Hash plugin

https://github.com/PowerPan/leaflet-hash
