### ISSUE TITLE
Chrome >=72 hiding controls when scrolling a sticky map

### ISSUE THREAD

**Issue by rmader** [Leaflet/Leaflet#6513] opened 2019-02-13 13:30 UTC
Starting with the most recent Chrome version, 72, when scrolling down on a page with a sticky map, controls like the zoom buttons or search bars disappear. They do reappear when scrolling up again

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
  - pretty sure it's not
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
  - might be a Chrome issue
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- open chrome >= 72
- go to https://mein.berlin.de/projekte/ or https://fragdenstaat.de/kampagnen/lebensmittelkontrolle/app/
- scroll down next to the map

**Expected behavior**
Controls stay visible, as they do with other/earlier browsers

**Current behavior**
Controls like zoom control disappear when scrolling down/reappear when scrolling up again

**Environment**
- Leaflet version: 1.3.4, 1.4.0
- Browser (with version): Chrome >= 72
- OS/Platform (with version): MacOS / Ubuntu 18.04 / Fedora 29

**Comment by IvanSanchez** [comment] 2019-02-13 20:53
By "sticky map" I presume you mean "a map container with a `position: sticky` CSS rule".

Can confirm. It seems that Chrome ignores the `z-index` of the control containers when `sticky` is in play.

Still, I must ask for a **minimal** reproducible example of this, specifically **without** vue2leaflet. In the two webpages linked, I can see extraneous HTML elements added inside the map container. In order to really confirm this, I'll need to see this happening with just vanilla Leaflet.

**Comment by treba123** [comment] 2019-02-14 10:13
Thanks for the fast reply! Here's a minimal example: https://leaflet.liqd.net/

cc: @MagdaN

**Comment by IvanSanchez** [comment] 2019-02-14 10:58
@treba123 Thanks to that, I've been able to reproduce the bug without Leaflet, creating an even smaller failing example:

```html
    <div id="sticky-container" style="position:sticky; top:0; height: 300px;"> 
      <div id="map" style="position:relative; height: 300px; width: 100vw; overflow: hidden">
	
		<div id="tile" style="transform: translate3D(0, 0, 0); width: 1024px; height: 1024px; background: gray; z-index: 0; opacity: 0.9">
		</div>
		
		<div id="top-controls" style="position:absolute; top: 0; left: 0; width: 30px; height: 60px; background: red; z-index: 1000">
		+ <br/> -
		</div>
		
		<div id="bottom-controls" style="position:absolute; bottom: 0; right: 0; height: 30px; background: red; z-index: 1000">
		(Map attribution goes here)
		</div>
      </div>
    </div>
```

The `z-index`es of the innermost elements are ignored, but AFAIK the bug still needs a sticky top-level container and a `overflow:hidden` container and some tiles with a `translate` transform; definitely an upstream bug.

**Comment by treba123** [comment] 2019-02-14 11:14
@IvanSanchez thanks a lot for looking into it. Will you create an upstream issue or should I? :)

**Comment by IvanSanchez** [comment] 2019-02-14 11:19
I already created an upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=932068

Nothing to do here on the Leaflet side of things but wait. :neutral_face:

**Comment by Malvoz** [comment] 2022-02-05 10:33
It seems this was deemed a browser bug, unfortunately the Chromium bug is unavailable to those without permission. I can't reproduce this in Chrome 98.0.4758.82.

Can this be closed?

**Comment by Falke-Design** [comment] 2022-02-05 10:44
I can't reproduce it too so let us close it.

**Closed by Falke-Design** 2022-02-05 10:44 UTC
Labels: needs solution, compatibility
