### ISSUE TITLE
"contextmenu" event is not fired on "touchstart"

### ISSUE THREAD

**Issue by putchi** [Leaflet/Leaflet#6349] opened 2018-09-27 06:32 UTC
## How to reproduce

- Leaflet version I'm using: 1.3.4
- Browser (with version) I'm using: chrome (latest), Safari, and all others, not browser related issue!
- OS/Platform (with version) I'm using: macOS High Sierra 10.13.6

**on mobile devices**,

`L.map('mapId', {
                scrollWheelZoom: false,
                tap: false,
                dragging: false,
                zoomControl: false,
                zoom: 8,
                minZoom: 3,
                maxZoom: 18
})`

* if disabling "tap" (like in the code example above) in order to enable the user to move the page even when the user taps over the map then the "contextmenu" event is not fired on touchstart.
* this event is important to be fired every time on touchstart with the default delay of 1 sec. Regardless if tap is disabled or enabled.

## What behaviour I'm expecting and which behaviour I'm seeing
* for example: an issue that when you try to listen to the contextmenu event and let the user know that dragging the map is possible with two fingers.

## Minimal example reproducing the issue

- [ ] create new Map instance, disable "tap". on mobile device (or browser's mobile/tablet mode, better a real device).
- [ ] try tapping the map and scrolling the page (even long tap), you'll see that the contextmenu event will not be fired because it is related to the touchstart event that depends on the "tap" option to be enabled.  

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by putchi** [comment] 2018-10-02 08:31
* In addition, if "tap" is disabled user cannot scroll the page if he taped the map!

**Comment by johnd0e** [comment] 2020-04-14 07:21
Unable to reproduce. Please provide sample jsfiddle.

Note that `contextmenu` should be fired only if there is no following `touchmove`. 

Closing for now.

**Closed by johnd0e** 2020-04-14 07:21 UTC
