### ISSUE TITLE
Problems with _pruneTiles

### ISSUE THREAD

**Issue by OriginalSin** [Leaflet/Leaflet#4190] opened 2016-02-03 14:18 UTC
We wanted to test the asynchronous rendering canvas tiles.
Wrote a short example in which we want call "done" function on all active tiles in one tick.
However we saw that Leaflet don't pruneTiles in this case.
Look example and click on button in
https://github.com/OriginalSin/Leaflet1.0.0-beta.2_test

**Comment by OriginalSin** [comment] 2016-02-03 14:37
In the next example "L.GridLayerAsync_test.html" we want to create tile Dom node  asynchronously or not to create.
For this we have to extend L.GridLayer  with "_updateOpacity", "_removeTile", "_tileReady"  and correct 4 lines depended from tile nodes.

**Comment by IvanSanchez** [comment] 2016-02-03 14:40
I'm gonna say this is a duplicate of #3765.

**Comment by OriginalSin** [comment] 2016-02-03 14:48
Yes this is the same problem.
This test http://originalsin.github.io/Leaflet1.0.0-beta.2_test/examples/L.GridLayerTest.html stable produce this bug.

**Comment by IvanSanchez** [comment] 2016-02-03 14:49
> Yes this is the same problem.

Closing as duplicate then.

**Closed by IvanSanchez** 2016-02-03 14:49 UTC
Labels: needs investigation
