### ISSUE TITLE
Leaflet playground is not working

### ISSUE THREAD

**Issue by Kamilius** [Leaflet/Leaflet#5317] opened 2017-02-08 08:06 UTC
Wanted to try to reproduce my issue using leaflet playground from "guidelines for contributing" (http://playground-leaflet.rhcloud.com/?html,output), but it appeared as not working. Error I'm seeing in console: `Uncaught ReferenceError: L is not defined`

**Comment by IvanSanchez** [comment] 2017-02-08 08:07
Click on "add library", then select a Leaflet version.

Not a bug, closing.

**Closed by IvanSanchez** 2017-02-08 08:07 UTC
