### ISSUE TITLE
Map freezes after touch zoom if no marker is present on the map

### ISSUE THREAD

**Issue by mlegenhausen** [Leaflet/Leaflet#2873] opened 2014-08-26 17:41 UTC
Following example:

``` html

<!DOCTYPE html>
<html>
<head>
    <title>Leaflet mobile example</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <link rel="stylesheet" href="./vendor/leaflet/leaflet.css" />

    <script src="./vendor/leaflet/leaflet.js"></script>

    <style>
        body {
            padding: 0;
            margin: 0;
        }
        html, body, #map {
            height: 100%;
        }
    </style>
</head>
<body>
    <div id="map"></div>

    <script>
        var map = L.map('map');

        L.tileLayer('https://{s}.tiles.mapbox.com/v3/{id}/{z}/{x}/{y}.png', {
            maxZoom: 16,
            id: 'examples.map-i86knfo3'
        }).addTo(map);

        function onLocationFound(e) {
            var radius = e.accuracy / 2;

            L.marker(e.latlng).addTo(map);

            L.circle(e.latlng, radius).addTo(map);
        }

        function onLocationError(e) {
            alert(e.message);
        }

        map.on('locationfound', onLocationFound);
        map.on('locationerror', onLocationError);

        map.locate({setView: true, maxZoom: 16});
    </script>
</body>
</html>

```

Tested with actual master version. Open this example in ios simulator and start zooming in by pressing `alt`. Everything is working fine. But when removing `L.marker(e.latlng).addTo(map);` from the code and start zooming in again as before the map completely freezes. I don't know excatly if this is related to #2693.

**Comment by yohanboniface** [comment] 2015-10-07 12:23
If the issue is still in latest master, a minimal jsfiddle would help: http://playground-leaflet.rhcloud.com/

**Comment by nmccready** [comment] 2016-06-20 16:53
Does this problem exist on 1.X at all?

**Comment by perliedman** [comment] 2017-08-09 08:27
Hi! I'm closing this since it doesn't seem to have been reproduced in a couple of years. If you still experience this issue, add an example and I'll re-open!

**Closed by perliedman** 2017-08-09 08:27 UTC
Labels: bug, mobile, needs more info
