### ISSUE TITLE
z-index number of .leaflet-top, .leaflet-bottom should be lower

### ISSUE THREAD

**Issue by darkclip** [Leaflet/Leaflet#6555] opened 2019-03-12 20:50 UTC
.leaflet-top, .leaflet-bottom now have z-index number of 1000, sometimes it interfere with other elements in the page, like dropdown menu etc., it would be nice to lower it a bit, say 900, still big enough and i don't have to meddle with default css every time.

**Comment by IvanSanchez** [comment] 2019-03-12 21:55
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by darkclip** [comment] 2019-03-13 01:28
@IvanSanchez 

here is link:
[https://jsfiddle.net/n7t1xkeb/](url)

click on upper right -> user, see how the dropdown menu been covered by zoom control

**Comment by IvanSanchez** [comment] 2019-03-13 09:27
Ensure that the map container spawns a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) by e.g. specifying a `z-index` for it (`<div id="map" style="width:100%;height:400px;z-index: 0"> </div>`).

Duplicate of https://github.com/Leaflet/Leaflet/issues/3690

**Closed by IvanSanchez** 2019-03-13 09:27 UTC

**Comment by darkclip** [comment] 2019-03-13 16:44
@IvanSanchez 
thanks for the tip, but wouldn't it be nice that users don't have to do that?
that's why i think this is a suggestion rather than a bug report.

**Comment by JorisDebonnet** [comment] 2019-09-05 14:29
I absolutely agree! I'm not sure why the z-indices need to be so extremely high? I also encountered this issue today (a hovering menu in my case) and had to look around quite a while to find a solution. 

But there's a super simple fix. Just add `.leaflet-container {z-index:0}` in the `leaflet.css` stylesheet. Then the workaround is embedded in the default stylesheet, and users won't encounter this issue anymore. Right?
