### ISSUE TITLE
IE11 regression in 0.7.7

### ISSUE THREAD

**Issue by jmullo** [Leaflet/Leaflet#4061] opened 2015-12-01 15:42 UTC
Something leaks or loops when clearing & adding markers derived from L.Path to L.LayerGroup while panning the map. UI becomes slower and slower until starts to freeze totally.

Works fine in 0.7.5.

**Comment by IvanSanchez** [comment] 2015-12-01 16:12
I'm gonna guess this is directly related to #4041

**Comment by jmullo** [comment] 2015-12-02 08:37
Yep, I also see those addEventListener() calls taking time when profiling.

**Comment by davojta** [comment] 2015-12-03 16:50
Seems that [that commit] (https://github.com/danzel/Leaflet/commit/4b289ab8071e480c182bb5df76bbfe0cac2a54e0)  broke IE11 in stable

**Comment by davojta** [comment] 2015-12-03 16:51
I will try figure out more about cause of the bug and prepare a new release with fix )

**Comment by mourner** [comment] 2015-12-03 16:55
@danzel hmm I think I remember seeing some discussions of perf problems with pointer detection, want to take a look?

**Comment by danzel** [comment] 2015-12-08 00:42
It's probably related to this one:
https://github.com/Leaflet/Leaflet/issues/3972#issuecomment-152373252

@jmullo do you have a prepared test so I can reproduce this easily?

**Comment by jmullo** [comment] 2015-12-08 11:18
Nope, pretty hard to detach from our code...

"Only affects repeatedly adding and removing markers on IE(11/10) with a touch device."

Not a touch device in my case.

**Comment by Monduiz** [comment] 2015-12-14 16:17
I have the same issue. I had to revert to version 0.7.5 so the applications I am developing can work on IE 11.

**Comment by mourner** [comment] 2016-03-31 22:28
Closing as duplicate of #4357

**Closed by mourner** 2016-03-31 22:28 UTC
Labels: bug, needs investigation, stable
