### ISSUE TITLE
Getting a distorted map near China region from the leaflet library

### ISSUE THREAD

**Issue by recursivecurse** [Leaflet/Leaflet#8785] opened 2023-01-09 11:23 UTC
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

https://ecn.t3.tiles.virtualearth.net/tiles/r132211.jpeg?g=13219&mkt=en-US&shading=hill

https://ecn.t1.tiles.virtualearth.net/tiles/r132302.jpeg?g=13219&mkt=en-US&shading=hill

https://ecn.t0.tiles.virtualearth.net/tiles/r132300.jpeg?g=13219&mkt=en-US&shading=hill

 

The above links provide the tiles which combines together to form the map.

### Expected behavior

Expected behavior is to get a a clear map.

### Current behavior

Receiving distorted map near China region.

### Environment

- Leaflet version: **"1.0.0-rc.2+e02b5c9"** 
- Browser (with version):  Mozilla Firefox
- OS/Platform (with version):   **Windows 10 Enterprise**

**Comment by Falke-Design** [comment] 2023-01-09 12:05
Please try again with the **newest** Leaflet version. `1.9.3`

**Comment by IvanSanchez** [comment] 2023-01-09 12:49
Those URLs are from Bing maps - and a quick test at https://plnkr.co/edit/IDPDujiiCzKdQLoI using https://github.com/digidem/leaflet-bing-layer tells me that there's no significant offset between Bing and OSM tiles.

I recall problems regarding the CRS used in South Korea (EPSG:5179), which is similar but not equal to EPSG:3857 - there's notes at https://github.com/tontita/Leaflet.KoreanTmsProviders . I don't think that's the case here.

Unless the problem is clarified, this is likely a duplicate of #5056 AKA "Leaflet is a display library, if you've got problems with your tile provider then that's not Leaflet's problem".

**Comment by Falke-Design** [comment] 2023-01-18 17:26
Cloing because of no response

**Closed by Falke-Design** 2023-01-18 17:26 UTC
Labels: bug, needs more info, needs triage
