### ISSUE TITLE
Error on clearLayers - this._icon is undefined

### ISSUE THREAD

**Issue by luizalexandrew** [Leaflet/Leaflet#7429] opened 2021-01-23 14:28 UTC
I'm having a problem when I call the Leaflet's **clearLayers** function. In 99% of the use of the application this function is executed correctly, but in some moments an exception is launched from the clearLayers function

Call that triggers the error
![image](https://user-images.githubusercontent.com/10445220/105580900-f1886b80-5d6d-11eb-859a-d466c1611aba.png)

getMapLayersLeaflet is just a function that searches for layers or creates if it doesn't exist (singleton idea)
![image](https://user-images.githubusercontent.com/10445220/105580824-74f58d00-5d6d-11eb-825d-3bcb7cc7ac77.png)

**Error**
![image](https://user-images.githubusercontent.com/10445220/105580021-a750bb80-5d68-11eb-9076-3efbdb027c7f.png)

Original Code: **leaflet-src.js** in function **_removeIcon**. The error is coming from the call  **remove(this._icon)**, because it's coming in this function **this._icon** with **undefined**

![image](https://user-images.githubusercontent.com/10445220/105580051-d0714c00-5d68-11eb-8b3e-1bf760018279.png)

**Debug Code**: Showing that it is coming undefined in the _removeIcon function

![image](https://user-images.githubusercontent.com/10445220/105580115-3eb60e80-5d69-11eb-9850-fefbe56895d7.png)

**Result 1**

![image](https://user-images.githubusercontent.com/10445220/105580136-6016fa80-5d69-11eb-9674-897aad15ef80.png)

**Result 2**

![image](https://user-images.githubusercontent.com/10445220/105580208-c734af00-5d69-11eb-8566-20d5a583f44f.png)

I believe that a race condition is occurring, at some point that it has 2 expenses at the same time, this is an assumption

**Initial Solution**:  The solution was to check if this._icon exist on **leaflet-src.js** in function **_removeIcon**.
![image](https://user-images.githubusercontent.com/10445220/105580249-0400a600-5d6a-11eb-9441-9b1f68449344.png)
I don't know if this solution was correct

I'm running the latest version of Leaflet v1.7.1, the error also occurs in previous versions
The browser that is running the code is the Google Chrome Version 81.0.4044.92 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/10445220/105580523-a1100e80-5d6b-11eb-877f-ca20655c2a58.png)

**Comment by johnd0e** [comment] 2021-01-30 14:53
We need to know how to reproduce the issue, otherwise it's hard to choose where it should be fixed.

**Comment by akselaase** [comment] 2021-08-20 09:34
I have the same issue. `layer.clearLayers();` works most of the time, but will sometimes throw an exception because `this._icon` is undefined. Some further info: I have a WebSocket that receives GPS coordinates from an external source (at ~10Hz), and in the `onmessage` callback of the WebSocket, I call `layer.clearLayers(); L.marker(message.position, {icon}).addTo(layer);` (`icon` is  defined earlier).

Call stack:
```
ri (http://localhost:8080/static/dist/leaflet@1.7.1.js#5)
_removeIcon (http://localhost:8080/static/dist/leaflet@1.7.1.js#5)
onRemove (http://localhost:8080/static/dist/leaflet@1.7.1.js#5)
removeLayer (http://localhost:8080/static/dist/leaflet@1.7.1.js#5)
removeLayer (http://localhost:8080/static/dist/leaflet@1.7.1.js#5)
removeLayer (http://localhost:8080/static/dist/leaflet@1.7.1.js#5)
eachLayer (http://localhost:8080/static/dist/leaflet@1.7.1.js#5)
clearLayers (http://localhost:8080/static/dist/leaflet@1.7.1.js#5)
make_listener (http://localhost:8080/static/js/app/map.js#70)
dispatch_message (http://localhost:8080/static/js/app/api.js#84)
onmessage (http://localhost:8080/static/js/app/api.js#25)
...
```

**Comment by Falke-Design** [comment] 2022-10-04 16:50
I close this issue until we have a reproduceable example

**Closed by Falke-Design** 2022-10-04 16:50 UTC
Labels: needs more info
