### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by reiniermujica** [Leaflet/Leaflet#6859] opened 2019-10-11 09:58 UTC
Im using Leaflet with React, basically i wrote a wrapper of the library. When the React Wrapper is unmount I execute the following code:

```
  this.map.eachLayer(function(layer) {
          layer.remove();
   });
  this.map.remove();
```
Then the following error is thrown:
**Uncaught TypeError: Cannot read property 'classList' of undefined**

The problem is in this function in leaflet-src.js:2336

```
function removeClass(el, name) {
	if (el.classList !== undefined) {
		el.classList.remove(name);
	} else {
		setClass(el, trim((' ' + getClass(el) + ' ').replace(' ' + name + ' ', ' ')));
	}
}
```
It seems that the el parameter is null.

**Expected behavior**
Component Unmount and no error is trigger

**Current behavior**
The component unmount successfully but some kind of error is trigged:

**Uncaught TypeError: Cannot read property 'classList' of undefined**

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Chrome 71
- OS/Platform (with version): Linux Mint 19.2

**Comment by johnd0e** [comment] 2020-03-20 15:41
You do not provide any sample to test.
Wild guess: some layers are `LayerGroup`s, and on remove they also try to remove their layers.

Are you sure that you ever need to remove layers one-by-one?
How about `map.remove();`?

**Comment by leroydev** [comment] 2022-06-22 13:42
@reiniermujica Did you find a workaround for this issue by any chance? I'm running into the same issue when using leaflet through `react-leaflet`

**Comment by Falke-Design** [comment] 2022-06-22 13:48
@leroydev can you please share a stacktrace of the error?

**Comment by Falke-Design** [comment] 2022-06-22 13:52
It is pretty the same as #8287. The problem is always that React already removed the DOM element of the layer before `layer.remove()` is called.

I will take care of this. We already solved other issues like that for react too. (#8288)

**Comment by jonkoops** [comment] 2022-07-17 16:50
Not sure what to do about this issue if we do not have a reliable and reproducible test case. I say we close this issue until someone finds a way to reproduce this.

@Falke-Design WDYT?

**Comment by Falke-Design** [comment] 2022-07-17 18:53
I tried to reproduce this error but I found no way how this can happens. `map._mapPane` is only "deleted" in the `map.remove()` function but this also stops the animation. So it is not possible that `_mapPane` is `undefined` with only the Leaflet-Core code.

I never worked with react, so my knowledge is very small but I tested it and I get no errors: https://codesandbox.io/s/leaflet-with-react-forked-dohc5d it is an older React version but it worked ... Maybe because it is using `react-leaflet`?

Until we find a reproducable example with vanilla Leaflet, we will close this.

**Closed by Falke-Design** 2022-07-17 18:53 UTC
Labels: bug

**Comment by Pynbiangborlang** [comment] 2023-03-28 12:24
I got this error and i dont know how to work around this issue. Can anyone help explain this?
Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at removeClass (leaflet-src.js:2446:11)
    at NewClass._onPanTransitionEnd (leaflet-src.js:4711:5)
    at NewClass.fire (leaflet-src.js:605:11)
    at NewClass._complete (leaflet-src.js:3117:10)
    at NewClass._step (leaflet-src.js:3095:11)
    at NewClass._animate (leaflet-src.js:3084:10)

  // @function removeClass(el: HTMLElement, name: String)
  // Removes `name` from the element's class attribute.
  function removeClass(el, name) {
  	if (el.classList !== undefined) {
  		el.classList.remove(name);
  	} else {
  		setClass(el, trim((' ' + getClass(el) + ' ').replace(' ' + name + ' ', ' ')));
  	}
  }

**Comment by Falke-Design** [comment] 2023-03-28 17:48
@Pynbiangborlang can you please describe the error, adding a video and maybe creating a demo to reproduce this error?

**Comment by rrsouzza** [comment] 2023-09-29 14:39
![image](https://github.com/Leaflet/Leaflet/assets/66682713/9a56aeea-20d1-474c-976a-4491640a63a2)

I'm using the ``geoman-io`` library with an Angular project, and I was having a similar (if not the same) issue.
In my case, I'm using the map in a Modal component, and this error was being triggered after a "Save" button was clicked, which would emit an event to the parent component, thus destroying the Modal component where the map was being rendered.

> It is pretty the same as #8287. The problem is always that React already removed the DOM element of the layer before `layer.remove()` is called.

Like @Falke-Design said, I assumed either ``leaflet`` or ``geoman-io`` was trying to remove the layers from the map **after** the component had been destroyed (since it was being triggered by ngOnDestroy, as seen in the image above).

I solved it by just manually going through every layer on the map and calling both ``remove()``and ``clearAllEventListeners()`` on each one **before** emitting the event to the parent component.

**Comment by iqbalhassan-7654** [comment] 2024-05-20 06:46
![image](https://github.com/Leaflet/Leaflet/assets/170302501/2fee1020-cbbf-4b37-aa9a-fe88b6b86365)
i have same issue @Falke-Design can you tell what can i do or how can i resolve him now . ?
