### ISSUE TITLE
Figure out what triggered an event like moveend

### ISSUE THREAD

**Issue by mbrucher** [Leaflet/Leaflet#6733] opened 2019-07-18 10:10 UTC
**Is your feature request related to a problem? Please describe.**

I currently use leaflet for a webapp. When a move is triggered, I use `moveend` to save the new location of the map center, which in turn is used to set `center`.
The problem then arises when I use a marker with a popup and move the popup out of the visible viewport. This triggers an infinite recursion of `moveend`.

**Describe the solution you'd like**

If there was a way of saying that the event is triggered by the user interaction or if it was triggered through internal mechanics (recentering the popup, zoom in/out), then these issues could be avoided.

**Describe alternatives you've considered**

I tried not triggering a `center` update, but this doesn't work, and there is still this infinite recursion.

**Additional context**
This is actually a request for the solution to #1686 to be implemented.

**Comment by IvanSanchez** [comment] 2019-07-18 10:49
Duplicate of #2934

**Closed by IvanSanchez** 2019-07-18 10:49 UTC
