### ISSUE TITLE
Examples on http://leafletjs.com/examples/wms/wms.html are not working anymore

### ISSUE THREAD

**Issue by astridx** [Leaflet/Leaflet#5671] opened 2017-07-30 11:06 UTC
The wms examples on the site
http://leafletjs.com/examples/wms/wms.html
are not working anymore. 

I hope this is the right place to communicate this issue.

**Comment by perliedman** [comment] 2017-07-30 18:32
Hi! Thanks for reporting, this is indeed the right place to do so.

However, this is a duplicate of #5540, so I'm closing this now!

**Closed by perliedman** 2017-07-30 18:32 UTC
