### ISSUE TITLE
Problem with detection of L.Browser.touch in some desktop browsers

### ISSUE THREAD

**Issue by NielsHolt** [Leaflet/Leaflet#5407] opened 2017-03-23 10:23 UTC
It seems that the detection of browser support for touch-event isn't consistent on some desktop browser
On IE11 and Chrome it get set to true while on Firefox it is set to false

```
Monernizr (https://modernizr.com) use another methods to detect the presents of touch-event and it returns false for all tree browsers:
function() {
    var bool;
    if (('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch) {
      bool = true;
    } else {
      // include the 'heartz' as a way to have a non matching MQ to help terminate the join
      // https://git.io/vznFH
      var query = ['@media (', prefixes.join('touch-enabled),('), 'heartz', ')', '{#modernizr{top:9px;position:absolute}}'].join('');
      testStyles(query, function(node) {
        bool = node.offsetTop === 9;
      });
    }
    return bool;
  });
```

**Comment by IvanSanchez** [comment] 2017-03-23 10:30
Duplicate of https://github.com/Leaflet/Leaflet/issues/5266, https://github.com/Leaflet/Leaflet/issues/3944 and others.

Not going to take action on this due to the recent work done in the `pointerify` branch, because worrying about `PointerEvent`s is way more promising than worrying about `TouchEvent`s

**Closed by IvanSanchez** 2017-03-23 10:30 UTC
