### ISSUE TITLE
[ie11/edge] The more L.Marker you create, the more time it takes

### ISSUE THREAD

**Issue by flemenach** [Leaflet/Leaflet#4874] opened 2016-09-01 12:06 UTC
Hi,

here is a jsfiddle to illustrate the issue:
https://jsfiddle.net/bds4u3z4/
Each time you click on the "update markers" link, it adds 100 markers to the map (and remove the previous ones) and displays the time it took to process.

If you click multiple times on the link, the update time is stable in chrome/FF but increases more and more in ie11 and edge
It seems all the process time is used by DomEvent.addDoubleTapListener method

This issue is already fixed in leaflet 1.0.0-rc3

**Comment by IvanSanchez** [comment] 2016-09-01 12:44
Duplicate of #4357

**Closed by IvanSanchez** 2016-09-01 12:44 UTC
